### ISSUE TITLE
App deployment for a custom nodejs runtime fails after latest SDK update

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#101]
```
1. Configure an AppeEngine app with a custom runtime. Dockerfile contents are:

FROM google/nodejs-runtime



2. Attempt to deploy it via:

gcloud preview app deploy .

I get a stack trace:

...
  File "/home/bartek_bargiel_gmail_com/moneypenny/../google-cloud-sdk/./lib/googlecloudsdk/appengine/lib/images/pus
h.py", line 141, in BuildAndPushDockerImage
    creds.Start()
  File "/home/bartek_bargiel_gmail_com/moneypenny/../google-cloud-sdk/./lib/googlecloudsdk/appengine/lib/images/cre
dentials.py", line 95, in Start
    name=containers.CleanableContainerName(




What is the output of 'gcloud info'?

Google Cloud SDK [0.9.42]
Platform: [Linux, x86_64]
Python Version: [2.7.6 (default, Mar 22 2014, 22:59:56)  [GCC 4.8.2]]
Site Packages: [Disabled]
Installation Root: [/home/bartek_bargiel_gmail_com/google-cloud-sdk]
Installed Components:
  core: [2015.01.06]
  app-engine-python: [1.9.17]
  app-engine-managed-vms: [2014.11.03]
  compute: [2015.01.06]
  app-engine-go-linux-x86_64: [1.9.17]
  app: [2015.01.06]
  gsutil-nix: [4.6]
  preview-extensions-linux-x86_64: [0.7.0]
  core-nix: [2014.10.20]
  gsutil: [4.7]
  bq: [2.0.18]
  dns: [2015.01.06]
  sql: [2015.01.06]
  gcutil: [1.16.5]
  preview: [2015.01.06]
  app-engine-java: [1.9.17]
  gcutil-nix: [1.16.5]
  bq-nix: [2.0.18]
System PATH: [/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin]
Cloud SDK on PATH: [True]

Installation Properties: 
[/home/bartek_bargiel_gmail_com/google-cloud-sdk/properties]
User Config Directory: [/home/bartek_bargiel_gmail_com/.config/gcloud]
User Properties: [/home/bartek_bargiel_gmail_com/.config/gcloud/properties]
Current Workspace: [None]
Workspace Config Directory: [None]
Workspace Properties: [None]
Account: [bartek.bargiel@gmail.com]
Project: [symbolic-object-815]
Current Properties:
  [core]
    project: [symbolic-object-815]
    account: [bartek.bargiel@gmail.com]
    disable_usage_reporting: [False]
    user_output_enabled: [True]
Logs Directory: [/home/bartek_bargiel_gmail_com/.config/gcloud/logs]
Last Log File: 
[/home/bartek_bargiel_gmail_com/.config/gcloud/logs/2015.01.09/08.14.03.678822.l
og]

```

Original issue reported on code.google.com by `bartek.b...@gmail.com` on 9 Jan 2015 at 8:31

**Comment by GoogleCodeExporter** [comment]
```
Could you please copy in the entire stack trace, including the eventual 
exception?
```

Original comment by `jasm...@google.com` on 12 Jan 2015 at 7:10
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
There we go:

Traceback (most recent call last):
  File "../google-cloud-sdk/./lib/googlecloudsdk/gcloud/gcloud.py", line 177, in <module> 
   main()
  File "../google-cloud-sdk/./lib/googlecloudsdk/gcloud/gcloud.py", line 173, in main
    _cli.Execute()
  File "../google-cloud-sdk/./lib/googlecloudsdk/calliope/cli.py", line 409, in Execute
    post_run_hooks=self.__post_run_hooks, kwargs=kwargs)
  File "../google-cloud-sdk/./lib/googlecloudsdk/calliope/frontend.py", line 274, in _Execute
    pre_run_hooks=pre_run_hooks, post_run_hooks=post_run_hooks)
  File "../google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 928, in Run
    result = command_instance.Run(args)
  File "../google-cloud-sdk/./lib/googlecloudsdk/calliope/exceptions.py", line 78, in TryFunc
    return func(*args, **kwargs)
  File "../google-cloud-sdk/lib/googlecloudsdk/appengine/app_commands/deploy.py", line 158, in Run
    self.__Run(args, project, deployables)
  File "../google-cloud-sdk/lib/googlecloudsdk/appengine/app_commands/deploy.py", line 211, in __Run
    args.remote)
  File "../google-cloud-sdk/./lib/googlecloudsdk/appengine/lib/images/push.py", line 141, in BuildAndPushDockerImage
    creds.Start()
  File "../google-cloud-sdk/./lib/googlecloudsdk/appengine/lib/images/credentials.py", line 95, in Start
    name=containers.CleanableContainerName(
AttributeError: 'module' object has no attribute 'CleanableContainerName'

```

Original comment by `bartek.b...@gmail.com` on 14 Jan 2015 at 7:48

**Comment by GoogleCodeExporter** [comment]
```
Looks like there may have been an issue in 0.9.42. If you do a 'gcloud 
components update', you'll be brought to 0.9.43. The offending line does not 
exist in the new version. Feel free to reopen if the issue persists!
```

Original comment by `jasm...@google.com` on 14 Jan 2015 at 3:18
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Wow. The new tool is great - it works and it finally outputs a lot of data 
about what's going on during the deployment. Thanks guys.
```

Original comment by `bartek.b...@gmail.com` on 14 Jan 2015 at 6:57
