### ISSUE TITLE
Breaking change to command-line tools since 07/01/15

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#103]
```
What steps will reproduce the problem?

    "gcloud components update" followed by just about any command, e.g. "gsutil ls"

What is the expected output? What do you see instead?

    gsutil ls should list the contents of my google cloud storage, instead, I get the following;

$ google-cloud-sdk/bin/gsutil ls
Traceback (most recent call last):
  File "/home/david/google-cloud-sdk/bin/bootstrapping/gsutil.py", line 72, in <module>
    main()
  File "/home/david/google-cloud-sdk/bin/bootstrapping/gsutil.py", line 20, in main
    project, account = bootstrapping.GetActiveProjectAndAccount()
  File "/home/david/google-cloud-sdk/bin/bootstrapping/bootstrapping.py", line 217, in GetActiveProjectAndAccount
    project_name = properties.VALUES.core.project.Get()
  File "/home/david/google-cloud-sdk/bin/bootstrapping/../../lib/googlecloudsdk/core/properties.py", line 449, in Get
    self.Validate(value)
  File "/home/david/google-cloud-sdk/bin/bootstrapping/../../lib/googlecloudsdk/core/properties.py", line 463, in Validate
    self.__validator(value)
  File "/home/david/google-cloud-sdk/bin/bootstrapping/../../lib/googlecloudsdk/core/properties.py", line 322, in ProjectValidator
    'project must be the project ID, not the project number')
googlecloudsdk.core.properties.InvalidValueError: project must be the project 
ID, not the project number

What is the output of 'gcloud info'?

$ google-cloud-sdk/bin/gcloud info
ERROR: (gcloud.info) project must be the project ID, not the project number

Please provide any additional information below.

Reverting the contents of the google-cloud-sdk directory to a version from 3 
days ago makes it all work again.
```

Original issue reported on code.google.com by `da...@digitalronin.com` on 10 Jan 2015 at 11:21

**Comment by GoogleCodeExporter** [comment]
```
It turns out this comes from a validation change which requires users to use a 
project ID string, rather than a project number.

Running; 

    gcloud config set project [project-ID]

...fixes this.

```

Original comment by `da...@digitalronin.com` on 12 Jan 2015 at 6:49

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the follow-up. In next week's release of the Cloud SDK, the error 
message will be nicer, and 'gcloud info' will work properly.
```

Original comment by `jasm...@google.com` on 12 Jan 2015 at 7:08
- Changed state: **Fixed**
