### ISSUE TITLE
Problem loading gcloud.preview.app

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#106]
```
What steps will reproduce the problem?
Install gcloud tool using:
"curl https://sdk.cloud.google.com | bash"
on CentOS 6.5 x64, login using "gcloud auth login" and then update "app" 
component:
"gcloud components update app" and try to setup managedVMS
"gcloud preview app setup-managed-vms" or "gcloud preview app deploy ."

What is the expected output? What do you see instead?

Output:
[root@aq-repository-01 user-server]# gcloud preview app setup-managed-vms
Traceback (most recent call last):
  File "/opt/google-cloud-sdk/./lib/googlecloudsdk/gcloud/gcloud.py", line 181, in <module>
    main()
  File "/opt/google-cloud-sdk/./lib/googlecloudsdk/gcloud/gcloud.py", line 177, in main
    _cli.Execute()
  File "/opt/google-cloud-sdk/./lib/googlecloudsdk/calliope/cli.py", line 470, in Execute
    args = self.__parser.parse_args(args)
  File "/opt/google-cloud-sdk/./lib/argparse/__init__.py", line 1703, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/opt/google-cloud-sdk/./lib/argparse/__init__.py", line 1735, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/opt/google-cloud-sdk/./lib/argparse/__init__.py", line 1944, in _parse_known_args
    stop_index = consume_positionals(start_index)
  File "/opt/google-cloud-sdk/./lib/argparse/__init__.py", line 1900, in consume_positionals
    take_action(action, args)
  File "/opt/google-cloud-sdk/./lib/argparse/__init__.py", line 1809, in take_action
    action(self, namespace, argument_values, option_string)
  File "/opt/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 229, in __call__
    parser, namespace, values, option_string=option_string)
  File "/opt/google-cloud-sdk/./lib/argparse/__init__.py", line 1111, in __call__
    namespace, arg_strings = parser.parse_known_args(arg_strings, namespace)
  File "/opt/google-cloud-sdk/./lib/argparse/__init__.py", line 1735, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/opt/google-cloud-sdk/./lib/argparse/__init__.py", line 1944, in _parse_known_args
    stop_index = consume_positionals(start_index)
  File "/opt/google-cloud-sdk/./lib/argparse/__init__.py", line 1900, in consume_positionals
  File "/opt/google-cloud-sdk/./lib/argparse/__init__.py", line 1809, in take_action
    take_action(action, args)
  File "/opt/google-cloud-sdk/./lib/argparse/__init__.py", line 1809, in take_action
    action(self, namespace, argument_values, option_string)
  File "/opt/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 229, in __call__
    parser, namespace, values, option_string=option_string)
  File "/opt/google-cloud-sdk/./lib/argparse/__init__.py", line 1111, in __call__
    namespace, arg_strings = parser.parse_known_args(arg_strings, namespace)
  File "/opt/google-cloud-sdk/./lib/argparse/__init__.py", line 1735, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/opt/google-cloud-sdk/./lib/argparse/__init__.py", line 1944, in _parse_known_args
    stop_index = consume_positionals(start_index)
  File "/opt/google-cloud-sdk/./lib/argparse/__init__.py", line 1900, in consume_positionals
    take_action(action, args)
  File "/opt/google-cloud-sdk/./lib/argparse/__init__.py", line 1809, in take_action
    action(self, namespace, argument_values, option_string)
  File "/opt/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 227, in __call__
    self._calliope_command.LoadSubElement(parser_name)
  File "/opt/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 824, in LoadSubElement
    self._help_func, parent_group=self)
  File "/opt/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 940, in __init__
    parent_group=parent_group)
  File "/opt/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 463, in __init__
    construction_id)
  File "/opt/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 635, in _GetModuleFromPath
    module = imp.load_module(name, f, file_path, items)
  File "/opt/google-cloud-sdk/lib/googlecloudsdk/appengine/app_commands/setup_managed_vms.py", line 7, in <module>
    from googlecloudsdk.appengine.lib.images import pull
  File "/opt/google-cloud-sdk/./lib/googlecloudsdk/appengine/lib/images/pull.py", line 11, in <module>
    from googlecloudsdk.appengine.lib.images import util
googlecloudsdk.calliope.backend.CommandLoadFailure: Problem loading 
gcloud.preview.app.setup_managed_vms: invalid syntax (util.py, line 220).

Instead of running the installation.

What is the output of 'gcloud info'?
Google Cloud SDK [0.9.44]
Platform: [Linux, x86_64]
Python Version: [2.6.6 (r266:84292, Jan 22 2014, 09:42:36)  [GCC 4.4.7 20120313 
(Red Hat 4.4.7-4)]]
Site Packages: [Disabled]
Installation Root: [/opt/google-cloud-sdk]
Installed Components:
  core: [2015.01.15]
  app-engine-python: [1.9.17]
  app-engine-managed-vms: [2014.11.03]
  compute: [2015.01.12]
  app-engine-go-linux-x86_64: [1.9.17]
  app: [2015.01.15]
  gsutil-nix: [4.6]
  preview: [2015.01.15]
  core-nix: [2014.10.20]
  gsutil: [4.7]
  bq: [2.0.18]
  dns: [2015.01.15]
  sql: [2015.01.15]
  gcutil: [1.16.5]
  preview-extensions-linux-x86_64: [0.7.0]
  app-engine-java: [1.9.17]
  gcutil-nix: [1.16.5]
  bq-nix: [2.0.18]
System PATH: 
[/opt/google-cloud-sdk/bin:/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/root/b
in]
Cloud SDK on PATH: [True]
Installation Properties: [/opt/google-cloud-sdk/properties]
User Config Directory: [/root/.config/gcloud]
User Properties: [/root/.config/gcloud/properties]
Current Workspace: [None]
Workspace Config Directory: [None]
Workspace Properties: [None]
Account: [EMAIL]
Project: [PRIVATE]
Current Properties:
  [core]
    project: [PRIVATE]
    account: [EMAIL]
    disable_usage_reporting: [True]
    user_output_enabled: [True]
Logs Directory: [/root/.config/gcloud/logs]
Last Log File: [/root/.config/gcloud/logs/2015.01.23/16.51.34.278955.log]


```

Original issue reported on code.google.com by `eric.sch...@touchfactor.com` on 23 Jan 2015 at 5:03

**Comment by GoogleCodeExporter** [comment]
```
The gcloud app set of commands are currently not compatible with Python 2.6.  
We are working on making them compatible but in the mean time, pleas use Python 
2.7 to run gcloud.
```

Original comment by `markp...@google.com` on 23 Jan 2015 at 9:14
- Changed state: **Accepted**
