### ISSUE TITLE
gcloud no longer working under windows

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#107]
```
What steps will reproduce the problem?
Any invocation of gcloud results in python error:
Traceback (most recent call last):
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\gcloud\gcloud.py", line 169, in <module>
    _cli = CreateCLI()
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\gcloud\gcloud.py", line 123, in CreateCLI
    cli.GoogleCloudSDKPackageRoot(),
AttributeError: 'module' object has no attribute 'GoogleCloudSDKPackageRoot'

What is the output of 'gcloud info'?
Traceback (most recent call last):
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\gcloud\gcloud.py", line 169, in <module>
    _cli = CreateCLI()
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\gcloud\gcloud.py", line 123, in CreateCLI
    cli.GoogleCloudSDKPackageRoot(),
AttributeError: 'module' object has no attribute 'GoogleCloudSDKPackageRoot'

Please provide any additional information below.
Python version 2.7.8, updated to 2.7.9, problem persists
Google Cloud SDK was uninstalled and installed again, system rebooted, problem 
persists
```

Original issue reported on code.google.com by `Shadow.G...@gmail.com` on 24 Jan 2015 at 6:04

**Comment by GoogleCodeExporter** [comment]
```
When uninstalling the Cloud SDK, how did you uninstall it? I'm assuming you 
deleted c:\program files\Google\Cloud SDK\*.

When you first installed the Cloud SDK, did you also install Python as 
suggested by the Cloud SDK installer, or did you have Python installed already?

Could you list your SYSTEM and USER paths?
```

Original comment by `rdayal@google.com` on 26 Jan 2015 at 1:06

**Comment by GoogleCodeExporter** [comment]
```
As gcloud sdk is not listed in "Programs and Features" and there's no uninstall 
executable, I've deleted sdk folder and cleaned up path.

Python was installed prior to Cloud SDK installation.

SystemDrive=C:
SystemRoot=C:\Windows
USERPROFILE=C:\Users\Garrett

```

Original comment by `Shadow.G...@gmail.com` on 26 Jan 2015 at 1:36

**Comment by GoogleCodeExporter** [comment]
```
What is the value of the PATH environment variable?

Where do you have Python installed?
```

Original comment by `rdayal@google.com` on 26 Jan 2015 at 1:40

**Comment by GoogleCodeExporter** [comment]
```
Value of path:
%SystemRoot%\system32;
%SystemRoot%;
%SystemRoot%\System32\Wbem;
%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;
C:\Dev\Python27\;
C:\Dev\Python27\Scripts;
C:\Perl64\bin;
C:\Perl64\site\bin;
C:\Dev\Ruby200-x64\bin;
C:\Program Files\Microsoft\Web Platform Installer\;
C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;
C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;
C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;
C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin;
C:\Program Files (x86)\Google\google_appengine\

Python is installed at C:\Dev\Python27
```

Original comment by `Shadow.G...@gmail.com` on 26 Jan 2015 at 1:44

**Comment by GoogleCodeExporter** [comment]
```
Ok. Here's what I'd recommend:

-uninstall the Google App Engine SDK. I think you may have it installed here 
(C:\Program Files (x86)\Google\google_appengine\). There should be an entry in 
Add/Remove programs for this, so try and uninstall it that way
-clean up your system path so that there are no references to the Cloud SDK or 
Google App Engine
-delete all of the files under c:\program files\google\cloud sdk
-delete the directory c:\users\<your username>\appdata\<local or roaming>\gcloud
-delete any shortcuts to the cloud sdk on your desktop, or under the start menu 

Try installing the Cloud SDK again using the Windows installer and see what 
happens. It shouldn't prompt you to install Python.

Also, you're using Python 2.7.9, correct? Where did you grab the installer from 
(for Python 2.7.9)?  
```

Original comment by `rdayal@google.com` on 26 Jan 2015 at 2:32

**Comment by GoogleCodeExporter** [comment]
```
I've done all steps and it is working correctly now!
There was gcloud in Roaming profile, Local only have google with chrome.

Python installer from python.org
```

Original comment by `Shadow.G...@gmail.com` on 26 Jan 2015 at 9:27

**Comment by GoogleCodeExporter** [comment]
```
Glad it's working. I'll close this out for now. I think issues like this will 
be mitigated with the updated Windows installer. 
```

Original comment by `rdayal@google.com` on 26 Jan 2015 at 11:40
- Changed state: **WorkingAsIntended**

**Comment by GoogleCodeExporter** [comment]
```
Thank you for your support, proper windows installer would be great, and 
uninstall with option to delete all related files too :3
```

Original comment by `Shadow.G...@gmail.com` on 26 Jan 2015 at 11:42
