### ISSUE TITLE
gcloud auth login fail

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#11]
```
What steps will reproduce the problem?
1. gcloud auth login fails with or without the --no-launch -browser flag.

using gcloud auth login fails to open a browser window

using gcloud auth login --no-launch-browser works as putting url into browser, 
accepting all security permissions, then getting a verification code. 

when entering the code back into terminal, see attached stack trace file, 
"trace.txt"

Then verified on https://security.google.com/settings/security/permissions?pli=1
that no Google Cloud entries exist on account permissions.   


What is the expected output? What do you see instead?
expect cloud SDK to have account access, see attached trace

What version of the product are you using? On what operating system?
0.9.13.1 - windows7 - Cygwin 2.831 32 bit

Please provide any additional information below.


```

Original issue reported on code.google.com by `mmcdo...@gmail.com` on 4 Dec 2013 at 6:35

Attachments:
- [Trace.txt](https://storage.googleapis.com/google-code-attachments/google-cloud-sdk/issue-11/comment-0/Trace.txt)

**Comment by GoogleCodeExporter** [comment]
```
Looks like you are behind a proxy but the socks module is missing.  We will 
push out an update soon to fix this issue.

Thanks for the report
```

Original comment by `markp...@google.com` on 4 Dec 2013 at 7:22

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the quick response Mark. 

Yes, at office behind proxy. Added proxy settings to curl and profile, able to 
update all components - only gcloud auth fails thus far.

```

Original comment by `mmcdo...@gmail.com` on 4 Dec 2013 at 7:30

**Comment by GoogleCodeExporter** [comment]
```
We just pushed an update that adds the socks module to the installation.  
Please run:

gcloud components update

to get the latest version, and see if that solves your problem.
```

Original comment by `markp...@google.com` on 4 Dec 2013 at 8:26

**Comment by GoogleCodeExporter** [comment]
```
Issue 12 has been merged into this issue.
```

Original comment by `jasm...@google.com` on 4 Dec 2013 at 9:10

**Comment by GoogleCodeExporter** [comment]
```
Issue 12 has been merged into this issue.
```

Original comment by `markp...@google.com` on 4 Dec 2013 at 10:47

**Comment by GoogleCodeExporter** [comment]
```
i also ran into this, and the update seems to have resolved it.
```

Original comment by `kapil.th...@canonical.com` on 4 Dec 2013 at 11:12

**Comment by GoogleCodeExporter** [comment]
Original comment by `jasm...@google.com` on 4 Dec 2013 at 11:14
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
i get a new trace message back now for gcloud auth login. Tried reinstalling 
cloud sdk and still cannot authenticate using same information as initial 
report.


Traceback (most recent call last):
  File "/home/c2485/google-cloud-sdk/bin/../lib/google/cloud/sdk/gcloud/gcloud.py", line 78, in <module>
    main()
  File "/home/c2485/google-cloud-sdk/bin/../lib/google/cloud/sdk/gcloud/gcloud.py", line 75, in main
    _loader.Execute()
  File "/home/c2485/google-cloud-sdk/bin/../lib/google/cloud/sdk/calliope/__init__.py", line 1270, in Execute
    cur._Execute(cli_mode=True, kwargs=kwargs)
  File "/home/c2485/google-cloud-sdk/bin/../lib/google/cloud/sdk/calliope/__init__.py", line 933, in _Execute
    cli_mode=cli_mode)
  File "/home/c2485/google-cloud-sdk/bin/../lib/google/cloud/sdk/calliope/__init__.py", line 665, in Run
    result = command_instance.Run(args)
  File "/home/c2485/google-cloud-sdk/bin/../lib/google/cloud/sdk/calliope/exceptions.py", line 84, in TryFunc
    return func(*args, **kwargs)
  File "/home/c2485/google-cloud-sdk/bin/../lib/google/cloud/sdk/gcloud/sdktools/auth/login.py", line 46, in Run
    launch_browser=args.launch_browser and not c_gce.IsOnGCE())
  File "/home/c2485/google-cloud-sdk/bin/../lib/google/cloud/sdk/core/credentials/__init__.py", line 290, in AcquireFromWebFlow
    cred = flow.Run(webflow, launch_browser=launch_browser)
  File "/home/c2485/google-cloud-sdk/bin/../lib/google/cloud/sdk/core/credentials/flow.py", line 152, in Run
    credential = flow.step2_exchange(code, http=http)
  File "/home/c2485/google-cloud-sdk/bin/../lib/oauth2client/util.py", line 132, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/c2485/google-cloud-sdk/bin/../lib/oauth2client/client.py", line 1283, in step2_exchange
    headers=headers)
  File "/home/c2485/google-cloud-sdk/bin/../lib/httplib2/__init__.py", line 1586, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/home/c2485/google-cloud-sdk/bin/../lib/httplib2/__init__.py", line 1333, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/home/c2485/google-cloud-sdk/bin/../lib/httplib2/__init__.py", line 1289, in _conn_request
    response = conn.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1018, in getresponse
    raise ResponseNotReady()
httplib.ResponseNotReady

```

Original comment by `mmcdo...@gmail.com` on 5 Dec 2013 at 6:00
