### ISSUE TITLE
AttributeError: 'module' object has no attribute 'HTTPSConnection'

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#110]
```
What steps will reproduce the problem?
run the installer

What is the expected output? What do you see instead?
the software to be installed correctly

What is the output of 'gcloud info'?
i can't get gcloud installed in order to run this command

Please provide any additional information below.

$ google-cloud-sdk/install.sh
Welcome to the Google Cloud SDK!
Traceback (most recent call last):
  File "/Users/nateaune/google-cloud-sdk/bin/bootstrapping/install.py", line 8, in <module>
    import bootstrapping
  File "/Users/nateaune/google-cloud-sdk/bin/bootstrapping/bootstrapping.py", line 17, in <module>
    import oauth2client.gce as gce
  File "/Users/nateaune/google-cloud-sdk/bin/bootstrapping/../../lib/oauth2client/gce.py", line 27, in <module>
    from oauth2client.client import AccessTokenRefreshError
  File "/Users/nateaune/google-cloud-sdk/bin/bootstrapping/../../lib/oauth2client/client.py", line 34, in <module>
    import httplib2
  File "/Users/nateaune/google-cloud-sdk/bin/bootstrapping/../../lib/httplib2/__init__.py", line 930, in <module>
    class HTTPSConnectionWithTimeout(httplib.HTTPSConnection):
AttributeError: 'module' object has no attribute 'HTTPSConnection'

```

Original issue reported on code.google.com by `n...@noderabbit.com` on 9 Feb 2015 at 6:33

**Comment by GoogleCodeExporter** [comment]
```
What OS/architecture/python version are you using?
Can you attach the result of the following command:
  python -c 'import httplib; print httplib.__file__'
```

Original comment by `markp...@google.com` on 9 Feb 2015 at 10:57
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
I'm on MacOSX and Python 2.7.8.

$ python -c 'import httplib; print httplib.__file__'
/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/py
thon2.7/httplib.pyc
```

Original comment by `n...@noderabbit.com` on 10 Feb 2015 at 3:27

**Comment by GoogleCodeExporter** [comment]
```
Strangely, httplib2 is coming from a different place:
$ python -c 'import httplib2; print httplib2.__file__'
/usr/local/lib/python2.7/site-packages/httplib2/__init__.pyc
```

Original comment by `n...@noderabbit.com` on 10 Feb 2015 at 3:29

**Comment by GoogleCodeExporter** [comment]
```
I received this error as well on OSX 10.10 and homebrewed python. Upgrading 
python via homebrew resolved the issue for me.

$ brew update && brew upgrade python
```

Original comment by `c...@dubberly.com` on 8 Apr 2015 at 11:14
