### ISSUE TITLE
ERROR: (gcloud.preview.projects.list) You do not have permission to access project [projects].

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#113]
```
What steps will reproduce the problem?

Using https://cloud.google.com/tools/repo/push-to-deploy instructions, then ssh 
to the machine and execute 

gcloud preview projects list

What is the expected output? What do you see instead?

root@bitnami-jenkins:/home/Josh# gcloud auth list
Credentialed accounts:
 - 86709905025-compute@developer.gserviceaccount.com (active)

To set the active account, run:
  $ gcloud config set account ``ACCOUNT''

root@bitnami-jenkins:/home/Josh# gcloud config set project kapx-site-demo
root@bitnami-jenkins:/home/Josh# gcloud preview projects list
ERROR: (gcloud.preview.projects.list) You do not have permission to access 
project [projects].


What is the output of 'gcloud info'?

root@bitnami-jenkins:/home/Josh# gcloud info
Google Cloud SDK [0.9.46]

Platform: [Linux, x86_64]
Python Version: [2.7.3 (default, Mar 13 2014, 11:03:55)  [GCC 4.7.2]]
Site Packages: [Disabled]

Installation Root: [/usr/local/share/google/google-cloud-sdk]
Installed Components:
  core: [2015.02.05]
  app-engine-python: [1.9.17]
  app-engine-managed-vms: [2015.01.22]
  gcutil: [1.16.5]
  app-engine-go-linux-x86_64: [1.9.17]
  gae-python: [2014.05.06]
  app: [2015.01.31]
  gsutil-nix: [4.7]
  bq-nix: [2.0.18]
  app-engine-python-extras: [1.9.6]
  core-nix: [2015.01.08]
  gsutil: [4.8]
  bq: [2.0.18]
  dns: [2015.01.15]
  sql: [2015.01.31]
  compute: [2015.01.22]
  preview: [2015.01.31]
  app-engine-java: [1.9.17]
  gcutil-nix: [1.16.5]
  preview-extensions-linux-x86_64: [0.9.1]
System PATH: 
[/opt/bitnami/gradle/bin:/opt/bitnami/git/bin:/opt/bitnami/java/bin:/opt/bitnami
/sqlite/bin:/opt/bitnami/apache2/bin:/opt/bitnami/common/bin:/usr/local/sbin:/us
r/local/bin:/usr/sbin:/usr/bin:/sbin:/bin]
Cloud SDK on PATH: [False]

Installation Properties: [/usr/local/share/google/google-cloud-sdk/properties]
User Config Directory: [/root/.config/gcloud]
User Properties: [/root/.config/gcloud/properties]
Current Workspace: [None]
Workspace Config Directory: [None]
Workspace Properties: [None]

Account: [86709905025-compute@developer.gserviceaccount.com]
Project: [kapx-site-demo]

Current Properties:
  [core]
    project: [kapx-site-demo]
    account: [86709905025-compute@developer.gserviceaccount.com]
    user_output_enabled: [True]

Logs Directory: [/root/.config/gcloud/logs]
Last Log File: [/root/.config/gcloud/logs/2015.02.11/14.17.48.429081.log]

Please provide any additional information below.

root@bitnami-jenkins:/home/Josh# cat 
/root/.config/gcloud/logs/2015.02.11/14.17.48.429081.log
2015-02-11 14:17:48,433 DEBUG    root            Metrics collector 
initialized...
2015-02-11 14:17:48,434 DEBUG    root            Loaded Command Group: 
['gcloud', 'preview', 'projects']
2015-02-11 14:17:48,436 DEBUG    root            Loaded Command Group: 
['gcloud', 'preview', 'projects', 'list']
2015-02-11 14:17:48,447 DEBUG    root            Running 
gcloud.preview.projects.list with Namespace(cmd_func=<bound method Command.Run 
of <googlecloudsdk.calliope.backend.Command object at 0x2e73bd0>>, 
command_path=['gcloud', 'preview', 'projects', 'list'], format=None, h=None, 
help=None, limit=None, markdown=None, project=None, quiet=None, 
trace_token=None, user_output_enabled=None, verbosity=None, version=None).
2015-02-11 14:17:48,481 DEBUG    root            (gcloud.preview.projects.list) 
You do not have permission to access project [projects].
Traceback (most recent call last):
  File "/usr/local/bin/../share/google/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 1018, in Run
    output_formatter(result)
  File "/usr/local/bin/../share/google/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 1004, in OutputFormatter
    command_instance.Display(args, obj)
  File "/usr/local/share/google/google-cloud-sdk/lib/googlecloudsdk/projects/commands/list.py", line 56, in Display
    list_printer.PrintResourceList('developerprojects.projects', result)
  File "/usr/local/bin/../share/google/google-cloud-sdk/./lib/googlecloudsdk/core/util/list_printer.py", line 45, in PrintResourceList
    console_io.PrintExtendedList(items, COLLECTION_COLUMNS[collection])
  File "/usr/local/bin/../share/google/google-cloud-sdk/./lib/googlecloudsdk/core/util/console_io.py", line 405, in PrintExtendedList
    for item in items:
  File "/usr/local/share/google/google-cloud-sdk/lib/googlecloudsdk/projects/commands/list.py", line 53, in Run
    raise util.GetError(error)
ProjectAccessError: You do not have permission to access project [projects].
2015-02-11 14:17:48,482 ERROR    root            (gcloud.preview.projects.list) 
You do not have permission to access project [projects].
2015-02-11 14:17:48,485 DEBUG    root            Metrics reporting process 
started...

Verified that service account can edit project from 
https://console.developers.google.com/project/kapx-site-demo/permissions. See 
screenshot

```

Original issue reported on code.google.com by `jojohns...@kaplan.edu` on 11 Feb 2015 at 2:21

Attachments:
- [service-account.png](https://storage.googleapis.com/google-code-attachments/google-cloud-sdk/issue-113/comment-0/service-account.png)

**Comment by GoogleCodeExporter** [comment]
```
The projects API is currently a whitelist only API which is why you are getting 
a permission denied error.  We will announce when this API is available for 
general use.
```

Original comment by `markp...@google.com` on 11 Feb 2015 at 5:50
- Changed state: **WorkingAsIntended**

**Comment by GoogleCodeExporter** [comment]
```
I used that as an example to illustrate my issue. I have the same problem
trying to deploy an app engine project using utility. I get an auth error
even though my service account is correct.
```

Original comment by `johnston...@gmail.com` on 11 Feb 2015 at 5:52
