### ISSUE TITLE
[URGENT ]OrderedDict DOES NOT EXIST IN PYTHON 2.6.1

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#119]
```
I am using gcloud in Mac OSX 10.6.8 "Terminal"
Installed SDK as stated in instructions and authenticated project. but compute 
zones list is not working properly. I need nameservers to europe zone urgently 
as production website is down.

Installed --> backports-debian-7-wheezy-v20150309 


What steps will reproduce the problem?
$ gcloud compute zones list


What do you see in output?
NAME REGION STATUS NEXT_MAINTENANCE TURNDOWN_DATE
Traceback (most recent call last):
  File "/Users/BBB/Google_Cloud/google-cloud-sdk/./lib/googlecloudsdk/gcloud/gcloud.py", line 204, in <module>
    main()
  File "/Users/BBB/Google_Cloud/google-cloud-sdk/./lib/googlecloudsdk/gcloud/gcloud.py", line 200, in main
    _cli.Execute()
  File "/Users/BBB/Google_Cloud/google-cloud-sdk/bin/bootstrapping/../../lib/googlecloudsdk/calliope/cli.py", line 558, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "/Users/BBB/Google_Cloud/google-cloud-sdk/bin/bootstrapping/../../lib/googlecloudsdk/calliope/backend.py", line 1022, in Run
    output_formatter(result)
  File "/Users/BBB/Google_Cloud/google-cloud-sdk/bin/bootstrapping/../../lib/googlecloudsdk/calliope/backend.py", line 1016, in <lambda>
    output_formatter = lambda obj: command_instance.Display(args, obj)
  File "/Users/BBB/Google_Cloud/google-cloud-sdk/./lib/googlecloudsdk/compute/lib/base_classes.py", line 296, in Display
    PrintTable(resources, self._resource_spec.table_cols)
  File "/Users/BBB/Google_Cloud/google-cloud-sdk/./lib/googlecloudsdk/compute/lib/base_classes.py", line 49, in PrintTable
    for resource in resources:
  File "/Users/BBB/Google_Cloud/google-cloud-sdk/./lib/googlecloudsdk/compute/lib/base_classes.py", line 281, in Run
    for item in items:
  File "/Users/BBB/Google_Cloud/google-cloud-sdk/./lib/googlecloudsdk/compute/lib/lister.py", line 29, in ProcessResults
    yield field_selector.Apply(resource)
  File "/Users/BBB/Google_Cloud/google-cloud-sdk/./lib/googlecloudsdk/compute/lib/property_selector.py", line 355, in Apply
    res = _DictToOrderedDict(obj)
  File "/Users/BBB/Google_Cloud/google-cloud-sdk/./lib/googlecloudsdk/compute/lib/property_selector.py", line 177, in _DictToOrderedDict
    new_obj = collections.OrderedDict(sorted(obj.items()))
AttributeError: 'module' object has no attribute 'OrderedDict'


What is the output of 'gcloud info'?
Google Cloud SDK [0.9.51]

Platform: [Mac OS X, x86]
Python Version: [2.6.1 (r261:67515, Jun 24 2010, 21:47:49)  [GCC 4.2.1 (Apple 
Inc. build 5646)]]
Site Packages: [Disabled]

Installation Root: [/Users/BBB/Google_Cloud/google-cloud-sdk]
Installed Components:
  core: [2015.03.10]
  core-nix: [2014.10.20]
  compute: [2015.03.10]
  gsutil-nix: [4.6]
  gsutil: [4.10]
  bq: [2.0.18]
  dns: [2015.03.10]
  sql: [2015.03.10]
  gcutil: [1.16.5]
  gcutil-nix: [1.16.5]
  bq-nix: [2.0.18]
System PATH: 
[/Users/BBB/Google_Cloud/google-cloud-sdk/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr
/local/bin:/usr/X11/bin]
Cloud SDK on PATH: [True]

Installation Properties: [/Users/BBB/Google_Cloud/google-cloud-sdk/properties]
User Config Directory: [/Users/BBB/.config/gcloud]
User Properties: [/Users/BBB/.config/gcloud/properties]
Current Workspace: [None]
Workspace Config Directory: [None]
Workspace Properties: [None]

Account: [mrdino786@gmail.com]
Project: [x-landing-87920]

Current Properties:
  [core]
    project: [x-landing-87920]
    account: [mr_ _@gmail.com]
    disable_usage_reporting: [True]

Logs Directory: [/Users/BBB/.config/gcloud/logs]
Last Log File: [/Users/BBB/.config/gcloud/logs/2015.03.15/11.13.24.593914.log]


```

Original issue reported on code.google.com by `mrdino...@gmail.com` on 15 Mar 2015 at 11:25

**Comment by GoogleCodeExporter** [comment]
```
$ gcloud compute images list

NAME PROJECT ALIAS DEPRECATED STATUS
Traceback (most recent call last):
  File "/Users/BBB/Google_Cloud/google-cloud-sdk/./lib/googlecloudsdk/gcloud/gcloud.py", line 204, in <module>
    main()
  File "/Users/BBB/Google_Cloud/google-cloud-sdk/./lib/googlecloudsdk/gcloud/gcloud.py", line 200, in main
    _cli.Execute()
  File "/Users/BBB/Google_Cloud/google-cloud-sdk/bin/bootstrapping/../../lib/googlecloudsdk/calliope/cli.py", line 558, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "/Users/BBB/Google_Cloud/google-cloud-sdk/bin/bootstrapping/../../lib/googlecloudsdk/calliope/backend.py", line 1022, in Run
    output_formatter(result)
  File "/Users/BBB/Google_Cloud/google-cloud-sdk/bin/bootstrapping/../../lib/googlecloudsdk/calliope/backend.py", line 1016, in <lambda>
    output_formatter = lambda obj: command_instance.Display(args, obj)
  File "/Users/BBB/Google_Cloud/google-cloud-sdk/./lib/googlecloudsdk/compute/lib/base_classes.py", line 296, in Display
    PrintTable(resources, self._resource_spec.table_cols)
  File "/Users/BBB/Google_Cloud/google-cloud-sdk/./lib/googlecloudsdk/compute/lib/base_classes.py", line 49, in PrintTable
    for resource in resources:
  File "/Users/BBB/Google_Cloud/google-cloud-sdk/./lib/googlecloudsdk/compute/lib/base_classes.py", line 281, in Run
    for item in items:
  File "/Users/BBB/Google_Cloud/google-cloud-sdk/./lib/googlecloudsdk/compute/lib/lister.py", line 29, in ProcessResults
    yield field_selector.Apply(resource)
  File "/Users/BBB/Google_Cloud/google-cloud-sdk/./lib/googlecloudsdk/compute/lib/property_selector.py", line 355, in Apply
    res = _DictToOrderedDict(obj)
  File "/Users/BBB/Google_Cloud/google-cloud-sdk/./lib/googlecloudsdk/compute/lib/property_selector.py", line 177, in _DictToOrderedDict
    new_obj = collections.OrderedDict(sorted(obj.items()))
AttributeError: 'module' object has no attribute 'OrderedDict'

```

Original comment by `mrdino...@gmail.com` on 15 Mar 2015 at 11:32

**Comment by GoogleCodeExporter** [comment]
```
I can't believe Google cloud blocks administrator's root access. If I go super 
user it asks for a password that is never provided to us. How on earth is this 
possible ?
```

Original comment by `mrdino...@gmail.com` on 15 Mar 2015 at 11:33

**Comment by GoogleCodeExporter** [comment]
```
Please refer https://code.google.com/p/google-cloud-sdk/issues/detail?id=33

Problem might be related to rc or bash || Phython's Order Direct.

Please help us, we will really appreciate a prompt reply to resolve this issue 
as my director is planning to move website to Amazon web services but I like 
Google cloud hosting so looking for an effective solution.

It is affecting our ranks due to website being offline.
```

Original comment by `mrdino...@gmail.com` on 15 Mar 2015 at 12:14

**Comment by GoogleCodeExporter** [comment]
```
The ORDERED_DICT issue is a known problem that we're fixing.  As a work around, 
please run in an environment with python 2.7.

With respect to root access, you need to run
  $ sudo -s
to get root shell.  As far as I know there's not a common and robust way to get 
`sudo root` to work withouth prompting for a password.
```

Original comment by `jeffvaughan@google.com` on 15 Mar 2015 at 7:17

**Comment by GoogleCodeExporter** [comment]
```
Marking as accepted for the OrderedDict issue.  Please open a new issue thread 
if you're continuing to have problems getting root access.
```

Original comment by `jeffvaughan@google.com` on 15 Mar 2015 at 7:19
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
From https://cloud.google.com/sdk/
System Requirements: Google Cloud SDK runs on Windows, Mac OS X and Linux, and 
requires Python 2.7.x. Some of the individual tools bundled with Cloud SDK have 
more stringent requirements: using App Engine tools for Java development 
requires Java 1.7+.

Google Cloud SDK requires Python 2.7.x. Even if we fix this specific problem, 
there are likely other areas where you will encounter problems running gcloud 
with python 2.6
```

Original comment by `svalen...@google.com` on 25 Mar 2015 at 6:07

**Comment by GoogleCodeExporter** [comment]
```
Please reopen if python 2.6 support is a must have for you.

```

Original comment by `che...@google.com` on 8 Sep 2015 at 3:40
- Changed state: **Obsolete**
