### ISSUE TITLE
gcloud app preview run - unable to launch offline

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#124]
```
What steps will reproduce the problem?

OSX 10.10.2, attempt to run Dart App Engine app, without internet connection on 
host machine.

gcloud --verbosity=debug preview app run app.yaml 

What is the expected output? What do you see instead?

expected:
app to run locally, (I'm pretty sure this used to work in previous iterations 
with the host machine offline).

instead:

DEBUG: Found Cloud SDK root: /Users/user/google-cloud-sdk
Module [default] found in file [/Users/user/dart/app/app.yaml]
INFO: Refreshing access_token
DEBUG: (gcloud.preview.app.run) Unable to find the server at accounts.google.com
Traceback (most recent call last):
  File "/Users/user/google-cloud-sdk/./lib/googlecloudsdk/calliope/cli.py", line 559, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "/Users/user/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 1020, in Run
    result = command_instance.Run(args)
  File "/Users/user/google-cloud-sdk/./lib/googlecloudsdk/calliope/exceptions.py", line 86, in TryFunc
    return func(*args, **kwargs)
  File "/Users/user/google-cloud-sdk/lib/googlecloudsdk/appengine/app_commands/run.py", line 307, in Run
    docker.UpdateDockerCredentials(constants.DEFAULT_REGISTRY)
  File "/Users/user/google-cloud-sdk/./lib/googlecloudsdk/core/util/docker.py", line 79, in UpdateDockerCredentials
    cred = store.Load()
  File "/Users/markharrison/google-cloud-sdk/./lib/googlecloudsdk/core/credentials/store.py", line 259, in Load
    Refresh(cred)
  File "/Users/markharrison/google-cloud-sdk/./lib/googlecloudsdk/core/credentials/store.py", line 279, in Refresh
    raise RefreshError(e)
RefreshError: Unable to find the server at accounts.google.com
ERROR: (gcloud.preview.app.run) Unable to find the server at accounts.google.com

What is the output of 'gcloud info'?

>gcloud --version

Google Cloud SDK 0.9.53

app 2015.03.23
app-engine-go-darwin-x86_64 1.9.18
app-engine-java 1.9.18
app-engine-managed-vms 2015.03.23
app-engine-python 1.9.18
bq 2.0.18
bq-nix 2.0.18
compute 2015.03.23
core 2015.03.23
core-nix 2014.10.20
dns 2015.03.23
gcutil 1.16.5
gcutil-nix 1.16.5
gsutil 4.11
gsutil-nix 4.6
preview 2015.03.23
preview-extensions-darwin-x86_64 0.13.1
sql 2015.03.23

Please provide any additional information below.




```

Original issue reported on code.google.com by `markh.ne...@gmail.com` on 1 Apr 2015 at 1:10

**Comment by GoogleCodeExporter** [comment]
```
Yep, I've just encountered this too.
```

Original comment by `jaffathe...@gmail.com` on 22 Apr 2015 at 4:48

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the report. I'll get this fixed for the next release. For now you 
can just delete line 307 in this file, it's no longer necessary. The line 
should be:
docker.UpdateDockerCredentials(constants.DEFAULT_REGISTRY)

/Users/user/google-cloud-sdk/lib/googlecloudsdk/appengine/app_commands/run.py
```

Original comment by `dlor...@google.com` on 22 Apr 2015 at 5:45

**Comment by GoogleCodeExporter** [comment]
```
Please re-open if this is still and issue; I believe that it's obsolete now.
```

Original comment by `z...@google.com` on 27 Aug 2015 at 11:12
- Changed state: **Obsolete**

**Comment by GoogleCodeExporter** [comment]
```
s/and issue/an issue/
```

Original comment by `z...@google.com` on 27 Aug 2015 at 11:12
