### ISSUE TITLE
gcloud SDK failed after reinstallation

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#132]
```
What steps will reproduce the problem?

I had a working gcloud, yesterday I wanted to try out the alpha https load 
balancer, reinstalled by running these commands:

curl https://sdk.cloud.google.com | bash

**restart terminal**

gcloud auth login

gcloud components repositories add 
https://storage.googleapis.com/gcp­https­lb­alpha­gcloud/components
­2.json

gcloud components update --­­quiet

----------------------
now my glcoud is not working. no matter what command I try to run, I get these 
follow error:

Ken$ gcloud compute -h
Traceback (most recent call last):
  File "/Users/Ken/google-cloud-sdk/./lib/googlecloudsdk/gcloud/gcloud.py", line 191, in <module>
    _cli = CreateCLI()
  File "/Users/Ken/google-cloud-sdk/./lib/googlecloudsdk/gcloud/gcloud.py", line 189, in CreateCLI
    return loader.Generate()
  File "/Users/Ken/google-cloud-sdk/./lib/googlecloudsdk/calliope/cli.py", line 311, in Generate
    exception_if_present=exception_if_present)
  File "/Users/Ken/google-cloud-sdk/./lib/googlecloudsdk/calliope/cli.py", line 389, in __GetGroupInfo
    raise exception_if_present
googlecloudsdk.calliope.backend.LayoutException: Root [preview] for command 
group [container] does not exist.

What is the expected output? What do you see instead?

What is the output of 'gcloud info'?

Traceback (most recent call last):
  File "/Users/Ken/google-cloud-sdk/./lib/googlecloudsdk/gcloud/gcloud.py", line 191, in <module>
    _cli = CreateCLI()
  File "/Users/Ken/google-cloud-sdk/./lib/googlecloudsdk/gcloud/gcloud.py", line 189, in CreateCLI
    return loader.Generate()
  File "/Users/Ken/google-cloud-sdk/./lib/googlecloudsdk/calliope/cli.py", line 311, in Generate
    exception_if_present=exception_if_present)
  File "/Users/Ken/google-cloud-sdk/./lib/googlecloudsdk/calliope/cli.py", line 389, in __GetGroupInfo
    raise exception_if_present
googlecloudsdk.calliope.backend.LayoutException: Root [preview] for command 
group [container] does not exist.


Please provide any additional information below.


```

Original issue reported on code.google.com by `Ken....@cru.org` on 20 Apr 2015 at 10:43

**Comment by GoogleCodeExporter** [comment]
```
Thanks for reporting.  This is a bug and I'm working on a fix right now.
```

Original comment by `jeffvaughan@google.com` on 8 May 2015 at 5:55

**Comment by GoogleCodeExporter** [comment]
```
Hey Ken,

A fix should be live.  Please try reinstalling.  It would be very helpful if 
you could comment on this issue an confirm that it works for you.  Bonus 
points: also change bug status to "Verified" or "New":)

Cheers,
Jeff
```

Original comment by `jeffvaughan@google.com` on 8 May 2015 at 6:32
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
it is fixed, thank you!
```

Original comment by `Ken....@cru.org` on 9 May 2015 at 12:54
