### ISSUE TITLE
gcloud auth login Exception

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#135]
```
What steps will reproduce the problem?
gcloud auth login


What is the expected output? What do you see instead?
what is see:
2015-04-23 14:59:05,032 DEBUG    root            Metrics collector 
initialized...
2015-04-23 14:59:05,173 DEBUG    root            Loaded Command Group: 
['gcloud', 'auth']
2015-04-23 14:59:05,173 DEBUG    root            Loaded Command Group: 
['gcloud', 'auth', 'login']
2015-04-23 14:59:05,187 DEBUG    root            Running gcloud.auth.login with 
Namespace(account=None, cmd_func=<bound method Command.Run of 
<googlecloudsdk.calliope.backend.Command object at 0x03084110>>, 
command_path=['gcloud', 'auth', 'login'], do_not_activate=False, force=False, 
format=None, h=None, help=None, http_timeout=None, launch_browser=True, 
log_http=None, markdown=None, project=None, quiet=None, trace_token=None, 
user_output_enabled=None, verbosity=None, version=None).
2015-04-23 14:59:05,203 INFO     ___FILE_ONLY___ Your browser has been opened 
to visit:

    https://accounts.google.com/o/oauth2/auth?redirect_uri=http%3A%2F%2Flocalhost%3A8085%2F&prompt=select_account&response_type=code&client_id=32555940559.apps.googleusercontent.com&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fappengine.admin+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcompute&access_type=offline



2015-04-23 14:59:38,882 DEBUG    ___FILE_ONLY___ 
Traceback (most recent call last):
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\cli.py", line 621, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\backend.py", line 1088, in Run
    result = command_instance.Run(args)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\exceptions.py", line 86, in TryFunc
    return func(*args, **kwargs)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\lib\googlecloudsdk\gcloud\sdktools\auth\login.py", line 83, in Run
    creds = self.DoWebFlow(args.launch_browser)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\lib\googlecloudsdk\gcloud\sdktools\auth\login.py", line 141, in DoWebFlow
    return c_store.AcquireFromWebFlow(launch_browser=launch_browser)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\core\credentials\store.py", line 394, in AcquireFromWebFlow
    http=_Http())
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\core\credentials\flow.py", line 160, in Run
    credential = flow.step2_exchange(code, http=http)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\oauth2client\util.py", line 129, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\oauth2client\client.py", line 1825, in step2_exchange
    headers=headers)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\httplib2\__init__.py", line 1608, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\httplib2\__init__.py", line 1350, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\httplib2\__init__.py", line 1306, in _conn_request
    response = conn.getresponse()
  File "C:\python27_x64\lib\httplib.py", line 1033, in getresponse
    raise ResponseNotReady()
ResponseNotReady
2015-04-23 14:59:38,946 DEBUG    root            Metrics reporting process 
started...


What is the output of 'gcloud info'?
Google Cloud SDK [0.9.57]

Platform: [Windows, x86]
Python Version: [2.7.6 (default, Nov 10 2013, 19:24:18) [MSC v.1500 32 bit 
(Intel)]]
Site Packages: [Disabled]

Installation Root: [C:\Program Files\Google\Cloud SDK\google-cloud-sdk]
Installed Components:
  core: [2015.04.21]
  app-engine-python: [1.9.18]
  gsutil-win: [4.11]
  compute: [2015.04.21]
  gcutil-win: [1.16.5]
  gae-python: [2014.05.06]
  gae-java-win: [1.9.18]
  core-win: [2015.04.14]
  gcloud: [2015.04.21]
  windows-ssh-tools: [2015.04.14]
  gae-java: [1.9.18]
  app-engine-python-extras: [1.9.18]
  gae-python-launcher-win: [1.9.18]
  gsutil: [4.11]
  bq: [2.0.18]
  dns: [2015.04.21]
  sql: [2015.04.09]
  gcutil: [1.16.5]
  preview: [2015.04.21]
  bq-win: [2.0.18]
System PATH: [C:\Program Files\Google\Cloud 
SDK\google-cloud-sdk\bin\..\bin\sdk;C:\python27_x64\;C:\Program 
Files\Google\Cloud 
SDK\google-cloud-sdk\bin;D:\apache-tomcat-8.0.21\bin;C:\apache-maven-3.2.3\bin;C
:\oraclexe\app\oracle\product\11.2.0\server\bin;C:\ProgramData\Oracle\Java\javap
ath;C:\Program Files\NVIDIA 
Corporation\PhysX\Common;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem
;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program 
Files\WinMerge;C:\totalcmd;C:\mplayer-svn-37380;C:\Program 
Files\TortoiseSVN\bin;C:\Program Files\jEdit;C:\Program Files\Google\Cloud 
SDK\google-cloud-sdk\bin;]
Cloud SDK on PATH: [True]

Installation Properties: [C:\Program Files\Google\Cloud 
SDK\google-cloud-sdk\properties]
User Config Directory: [C:\Users\rhoddesiax\AppData\Roaming\gcloud]
User Properties: [C:\Users\rhoddesiax\AppData\Roaming\gcloud\properties]
Current Workspace: [None]
Workspace Config Directory: [None]
Workspace Properties: [None]

Account: [rhodesiax.lo@gmail.com]
Project: [None]

Current Properties:
  [core]
    account: [rhodesiax.lo@gmail.com]
    disable_usage_reporting: [False]

Logs Directory: [C:\Users\rhoddesiax\AppData\Roaming\gcloud\logs]
Last Log File: 
[C:\Users\rhoddesiax\AppData\Roaming\gcloud\logs\2015.04.23\15.20.25.552000.log]


Please provide any additional information below.
first of all,i am from mainland china,normally google services are blocked here 
, but i manage to do it with proxy , i also setup http_proxy env varialbe the 
way i set my IE browser,so think proxy may not the issue here.
second ,before make this post ,i have search the internet for solution,such as 
reinstall gcloud SDK,gcloud component update,ect.none of them works.
here is my pc information:
Host Name:                 RHODDESIAX-PC
OS Name:                   Microsoft Windows 7 Ultimate 
OS Version:                6.1.7601 Service Pack 1 Build 7601
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          rhoddesiax
Registered Organization:   
Product ID:                00426-OEM-8992662-00015
Original Install Date:     3/14/2015, 2:26:49 PM
System Boot Time:          4/23/2015, 12:19:07 PM
System Manufacturer:       ASUSTeK Computer Inc.        
System Model:              N82JV
System Type:               X86-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: x64 Family 6 Model 37 Stepping 5 GenuineIntel ~2373 Mhz
BIOS Version:              American Megatrends Inc. N82JV.212, 1/24/2011
Windows Directory:         C:\Windows
System Directory:          C:\Windows\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             zh-cn;Chinese (China)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi
Total Physical Memory:     2,732 MB
Available Physical Memory: 612 MB
Virtual Memory: Max Size:  5,463 MB
Virtual Memory: Available: 2,066 MB
Virtual Memory: In Use:    3,397 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\RHODDESIAX-PC
Hotfix(s):                 190 Hotfix(s) Installed.


```

Original issue reported on code.google.com by `Rhodesia...@gmail.com` on 23 Apr 2015 at 7:33
- Merged into: #14

**Comment by GoogleCodeExporter** [comment]
```
Would setting proxy as described here would work for you:
  http://docs.cloudfoundry.org/devguide/installcf/http-proxy.html

```

Original comment by `che...@google.com` on 23 Apr 2015 at 6:33

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
 As a matter of fact ,i can successfuly login my google account ,i can visit youtube,facebook and twitter,Doesn't it  mean that proxy configuration i have set is just right,but if it is ,why i still not get credentials from google cloud ,is there any issues i have missed ?
```

Original comment by `Rhodesia...@gmail.com` on 24 Apr 2015 at 4:05

**Comment by GoogleCodeExporter** [comment]
```
this is the proxy i used
http://121.40.169.8:1234/c38vpags

echo %http_proxy%
output:http://121.40.169.8:1234/c38vpags

```

Original comment by `Rhodesia...@gmail.com` on 24 Apr 2015 at 4:23

Attachments:
- [dsk.jpg](https://storage.googleapis.com/google-code-attachments/google-cloud-sdk/issue-135/comment-4/dsk.jpg)

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 13 Oct 2015 at 3:07
- Changed state: **Duplicate**
