### ISSUE TITLE
gcloud installation issue on Ubuntu 12.04

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#156]
```
What steps will reproduce the problem?

I have installed php app engine sdk first.

After I installed Google cloud SDK, using 
sudo curl https://sdk.cloud.google.com | bash

But, its showing error while installing

I  can't access gcloud from my terminal.

What is the expected output? What do you see instead?

got welcome message, but after showing an error

/home/nikhil/google-cloud-sdk/install.sh
Welcome to the Google Cloud SDK!
Traceback (most recent call last):
  File "/home/nikhil/google-cloud-sdk/bin/bootstrapping/install.py", line 20, in <module>
    from googlecloudsdk.gcloud import gcloud
  File "/home/nikhil/google-cloud-sdk/bin/bootstrapping/../../lib/googlecloudsdk/gcloud/gcloud.py", line 190, in <module>
    _cli = CreateCLI()
  File "/home/nikhil/google-cloud-sdk/bin/bootstrapping/../../lib/googlecloudsdk/gcloud/gcloud.py", line 188, in CreateCLI
    return loader.Generate()
  File "/home/nikhil/google-cloud-sdk/bin/bootstrapping/../../lib/googlecloudsdk/calliope/cli.py", line 304, in Generate
    cli = self.__MakeCLI(top_group)
  File "/home/nikhil/google-cloud-sdk/bin/bootstrapping/../../lib/googlecloudsdk/calliope/cli.py", line 467, in __MakeCLI
    log.AddFileLogging(self.__logs_dir)
  File "/home/nikhil/google-cloud-sdk/bin/bootstrapping/../../lib/googlecloudsdk/core/log.py", line 547, in AddFileLogging
    _log_manager.AddLogsDir(logs_dir=logs_dir)
  File "/home/nikhil/google-cloud-sdk/bin/bootstrapping/../../lib/googlecloudsdk/core/log.py", line 331, in AddLogsDir
    log_file = self._SetupLogsDir(logs_dir)
  File "/home/nikhil/google-cloud-sdk/bin/bootstrapping/../../lib/googlecloudsdk/core/log.py", line 408, in _SetupLogsDir
    os.makedirs(day_dir_path)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: 
'/home/nikhil/.config/gcloud/logs/2015.07.03'



What is the output of 'gcloud info'?

gcloud: command not found


Please provide any additional information below.


```

Original issue reported on code.google.com by `nikhilki...@gmail.com` on 3 Jul 2015 at 1:44

**Comment by GoogleCodeExporter** [comment]
```
i have installed Google cloud sdk from zip file.

after gcloud info showing result:

nikhil@nikhil-Aspire-S3-391:~$ gcloud info
Traceback (most recent call last):
  File "/home/nikhil/google-cloud-sdk/./lib/googlecloudsdk/gcloud/gcloud.py", line 190, in <module>
    _cli = CreateCLI()
  File "/home/nikhil/google-cloud-sdk/./lib/googlecloudsdk/gcloud/gcloud.py", line 188, in CreateCLI
    return loader.Generate()
  File "/home/nikhil/google-cloud-sdk/./lib/googlecloudsdk/calliope/cli.py", line 304, in Generate
    cli = self.__MakeCLI(top_group)
  File "/home/nikhil/google-cloud-sdk/./lib/googlecloudsdk/calliope/cli.py", line 467, in __MakeCLI
    log.AddFileLogging(self.__logs_dir)
  File "/home/nikhil/google-cloud-sdk/./lib/googlecloudsdk/core/log.py", line 547, in AddFileLogging
    _log_manager.AddLogsDir(logs_dir=logs_dir)
  File "/home/nikhil/google-cloud-sdk/./lib/googlecloudsdk/core/log.py", line 333, in AddLogsDir
    file_handler = logging.FileHandler(log_file)
  File "/usr/lib/python2.7/logging/__init__.py", line 897, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 916, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 13] Permission denied: 
'/home/nikhil/.config/gcloud/logs/2015.07.03/20.50.04.771292.log'

```

Original comment by `nikhilki...@gmail.com` on 3 Jul 2015 at 3:22

**Comment by GoogleCodeExporter** [comment]
```
This looks like another instance of the issue resolved here:

http://stackoverflow.com/questions/31220077/gcloud-ubuntu-12-04-installation-per
mission-issue/31247129#31247129

Closing this for now.  Please reopen if we can provide additional help 
troubleshooting.
```

Original comment by `jeffvaughan@google.com` on 6 Jul 2015 at 2:54
- Changed state: **WontFix**
