### ISSUE TITLE
import traceback > No module named traceback

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#159]
```
What steps will reproduce the problem?
Installed on windows 8.1 with GoogleCloudSDKINstaller.exe
Open google cloud shell and execute gcloud -h

What is the expected output? What do you see instead?


What is the output of 'gcloud info'?
Welcome to Google Cloud SDK! Run "gcloud -h" to get the list of available comma
ds.

---
C:\Program Files\Google\Cloud SDK>gcloud -h
Traceback (most recent call last):
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecoudsdk\gcloud\gcloud.py", line 13, in <module>
    import traceback
ImportError: No module named traceback



Please provide any additional information below.
Have python27 and google appengine installed.
Was following google setup instructions on google-cloud-sdk and google 
appengine.
Looked into python27 lib and there is traceback.py file there.
made a python file with only import traceback and got no error from python.


```

Original issue reported on code.google.com by `sjepju...@gmail.com` on 13 Jul 2015 at 12:11

**Comment by GoogleCodeExporter** [comment]
```
Hi sjepjusis,

Thanks for reporting this! It looks to be some kind of strange install/Python 
configuration problem.

We'll try to reproduce and let you know what we find.

As it looks like you already know, `traceback` is a built-in Python module, so 
if Python cannot find it, it indicates problems with the Python setup that 
gcloud uses (gcloud creates some changes to the normal Python path).

In the meantime, do you mind reporting the output of (please sanitize any 
personal information in the paths(:
* python.exe -V
* echo %PATH%
* echo %PYTHONPATH%
in the Google Cloud Shell?
```

Original comment by `z...@google.com` on 13 Jul 2015 at 12:26
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
In particular, I'm looking for spaces in paths (a common culprit in creating 
issues like this) or any other anomalies that would indicate a bug on our end.
```

Original comment by `z...@google.com` on 13 Jul 2015 at 12:28

**Comment by GoogleCodeExporter** [comment]
```
Always in google shell or in windows power shell after running the cloud_env.bat
This is all from the google shell

C:\Program Files\Google\Cloud SDK>python -V
Python 2.7.10

echo %pythonpath%
%pythonpath%

C:\vinna\Google\Cloud SDK>echo %path% > mypath.txt
TRUE;C:\vinna\Google\Cloud 
SDK\google-cloud-sdk\bin;C:\vinna\Python27\Scripts;C:\ProgramData\Oracle\Java\ja
vapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS 
Client\;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\Syste
m32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine 
Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine 
Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine 
Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine 
Components\IPT;C:\Program Files\Lenovo\Fingerprint Manager Pro\;C:\Program 
Files (x86)\Common 
Files\lenovo\easyplussdk\bin;C:\ProgramData\Lenovo\ReadyApps;C:\Program 
Files\Intel\WiFi\bin\;C:\Program Files\Common 
Files\Intel\WirelessCommon\;C:\Users\sigurdur\.dnx\bin;C:\Program 
Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Windows Kits\8.1\Windows 
Performance Toolkit\;C:\Program Files\Microsoft SQL 
Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL 
Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft 
SDKs\TypeScript\1.0\;C:\vinna\Google\Cloud SDK\google-cloud-sdk\bin;C:\Program 
Files\Google\Cloud 
SDK\google-cloud-sdk\bin;C:\vinna\.virtualenvs\wagenv/Scripts;C:\vinna\Python27\
;C:\vinna\Python27\Scripts;C:\ProgramData\Oracle\Java\javapath;C:\Program Files 
(x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS 
Client\;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\Syste
m32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine 
Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine 
Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine 
Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine 
Components\IPT;C:\Program Files\Lenovo\Fingerprint Manager Pro\;C:\Program 
Files (x86)\Common 
Files\lenovo\easyplussdk\bin;C:\ProgramData\Lenovo\ReadyApps;C:\Program 
Files\Intel\WiFi\bin\;C:\Program Files\Common 
Files\Intel\WirelessCommon\;C:\windows\system32\config\systemprofile\.dnx\bin;C:
\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Windows 
Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL 
Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL 
Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft 
SDKs\TypeScript\1.0\;C:\Vinna\Postgres\v9.4.4\bin;C:\Vinna\Postgres\v9.4.4\bin;C
:\Vinna\Google\google_appengine\; 


I treid reinstall  GoogleCloudSDKInstaller.exe but still the same

If I set the PythonPathh to this
c:\vinna\Python27\Lib
I get this error:

PS C:\vinna\google\Cloud SDK> gcloud -h
Traceback (most recent call last):
  File "C:\Vinna\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\gcloud\gcloud.py", line 85, in <module>
    from googlecloudsdk.calliope import base
  File "C:\Vinna\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\base.py", line 8, in <module>
    from googlecloudsdk.calliope import usage_text
  File "C:\Vinna\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\usage_text.py", line 12, in <mod
ule>
    from googlecloudsdk.calliope import arg_parsers
  File "C:\Vinna\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\arg_parsers.py", line 43, in <mo
dule>
    from googlecloudsdk.core import log
  File "C:\Vinna\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\core\log.py", line 14, in <module>
    from googlecloudsdk.core import properties
  File "C:\Vinna\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\core\properties.py", line 13, in <module>

    from googlecloudsdk.core.credentials import devshell as c_devshell
  File "C:\Vinna\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\core\credentials\devshell.py", line 9, in
 <module>
    from oauth2client import client
  File "C:\Vinna\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\oauth2client\client.py", line 29, in <module>
    import socket
  File "c:\vinna\Python27\Lib\socket.py", line 47, in <module>
    import _socket
ImportError: No module named _socket
PS C:\vinna\google\Cloud SDK>

```

Original comment by `sjepju...@gmail.com` on 13 Jul 2015 at 1:32

**Comment by GoogleCodeExporter** [comment]
```
I notice that c:\vinna\python27\scripts is twice in the path but that happens 
only in the google shell or after you run the cloud-env.bat

Was wondering if it would matter to have the python path first, before the 
cloud path?
```

Original comment by `sjepju...@gmail.com` on 13 Jul 2015 at 1:42

**Comment by GoogleCodeExporter** [comment]
```
Neither of those things *should* matter (i.e. two occurrences of 
'c:\vinna\python27\scripts' or Python path being before/after the cloud path.

Is there anything unusual about this Python installation? Did it come from an 
installer on http://python.org ? Or the automatic Python installation through 
the Cloud SDK installer?
```

Original comment by `z...@google.com` on 13 Jul 2015 at 1:47

**Comment by GoogleCodeExporter** [comment]
```
I had python installed before I started trying the google cloud.
```

Original comment by `sjepju...@gmail.com` on 13 Jul 2015 at 1:58

**Comment by GoogleCodeExporter** [comment]
```
Been going through the appengine examples and they all run fine with the google 
appengine launcher. Also django demos run fine. Only thing I have had problems 
with is google cloud environment.  
```

Original comment by `sjepju...@gmail.com` on 13 Jul 2015 at 2:02

**Comment by GoogleCodeExporter** [comment]
```
I'm not sure why but i'm kind of new to python, google cloud and virtualenv.

If I run this though power shell, change virtual enviroment with WORKON command 
to my enviroment, run the cloud-env.bat then i work OK

gcloud -h gives me now the help screen.
```

Original comment by `sjepju...@gmail.com` on 13 Jul 2015 at 2:08

**Comment by GoogleCodeExporter** [comment]
```
I set up the virtual env using this page:
http://www.tylerbutler.com/2012/05/how-to-install-python-pip-and-virtualenv-on-w
indows-with-powershell/

Don't know why this only work after I chagne to the virtualenv, I thought it 
should work with out it.

Thanks for the help - it got me on the right track again.
```

Original comment by `sjepju...@gmail.com` on 13 Jul 2015 at 2:21

**Comment by GoogleCodeExporter** [comment]
```
I didn't realize earlier that you were using a virtualenv. virtualenvs and the 
Cloud SDK don't play particularly nice together, historically. This is a bug 
that we're tracking.

I think that information should enable us to make a good attempt at 
reproducing. Thank you.

We're glad that you got everything working after all! Hopefully we'll fix this 
up so it either (a) works out of the box, or (b) is more obvious what the issue 
is. 
```

Original comment by `z...@google.com` on 13 Jul 2015 at 2:23

**Comment by GoogleCodeExporter** [comment]
```
Yes, the problem was that I was not using it since I installed it.
Plz, put a replay to this post if you find a solution to this.

Until then I'll just remember to use my virtualenv.
```

Original comment by `sjepju...@gmail.com` on 13 Jul 2015 at 2:43

**Comment by GoogleCodeExporter** [comment]
```
After looking into this a little more, it looks like the problem is just that 
your virtualenv was misconfigured, and that you were attempting to use the 
virtualenv Python install *outside* of the virtualenv. Since this causes 
everything in Python to break, we can't do a whole lot about that from our end, 
unfortunately.

Gald you were able to figure it out.
```

Original comment by `z...@google.com` on 14 Jul 2015 at 3:43
- Changed state: **Invalid**
