### ISSUE TITLE
docker 1.7.1 breaks managed VMs deployment

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#163]
```
Please note that this is on a project not configured for managed VMs (or 
rather, I deleted the containers and configs buckets from GCS to have a fresh 
start, as I have done before).

Beginning deployment...
Verifying that Managed VMs are enabled and ready.
If this is your first deployment, this may take a while...done.

Traceback (most recent call last):
  File "/home/user/appengine/google-cloud-sdk/./lib/googlecloudsdk/gcloud/gcloud.py", line 200, in main
    _cli.Execute()
  File "/home/user/appengine/google-cloud-sdk/./lib/googlecloudsdk/calliope/cli.py", line 538, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "/home/user/appengine/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 1124, in Run
    result = command_instance.Run(args)
  File "/home/user/appengine/google-cloud-sdk/lib/googlecloudsdk/appengine/app_commands/deploy.py", line 162, in Run
    args.remote)
  File "/home/user/appengine/google-cloud-sdk/./lib/googlecloudsdk/appengine/lib/deploy_command_util.py", line 59, in BuildAndPushDockerImages
    remote) as docker_client:
  File "/home/user/appengine/google-cloud-sdk/./lib/googlecloudsdk/appengine/lib/images/remote_docker.py", line 207, in __enter__
    return containers.NewDockerClient(**kwargs)
  File "/home/user/appengine/google-cloud-sdk/./lib/googlecloudsdk/appengine/lib/docker/containers.py", line 294, in NewDockerClient
    client.ping()
  File "/home/user/appengine/google-cloud-sdk/./lib/docker/docker/client.py", line 847, in ping
    return self._result(self._get(self._url('/_ping')))
  File "/home/user/appengine/google-cloud-sdk/./lib/docker/docker/client.py", line 126, in _result
    self._raise_for_status(response)
  File "/home/user/appengine/google-cloud-sdk/./lib/docker/docker/client.py", line 122, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
APIError: 400 Client Error: Bad Request ("client is too old, minimum supported 
API version is 1.12, please upgrade your client to a newer version")

Then gcloud just hangs. I cannot Ctrl-C it either. It worked again after I 
downgraded to the previous docker version. (I deleted config and containers 
from GCS again before I tried again, to exclude that as a problem.)
```

Original issue reported on code.google.com by `pdknsk` on 15 Jul 2015 at 4:57

**Comment by GoogleCodeExporter** [comment]
```
Hi pdknsk,

Thanks for reporting this. We're working on it.

In the meantime, I'm glad you were able to work around this issue by 
downgrading Docker. Of course, this isn't a great long-term solution; we hope 
to have a fix out soon that allows the Cloud SDK to work with newer versions of 
Docker.
```

Original comment by `z...@google.com` on 15 Jul 2015 at 6:02
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
To clarify: Is this caused by Docker 1.7.1 or is it a problem on the Cloud SDK 
side?

I am wondering if the Cloud SDK / Managed VM documentation should mention the 
most recent version of docker that is known to work with the Cloud SDK.

Thanks,
Ingo
```

Original comment by `ingo.jae...@gmail.com` on 15 Jul 2015 at 9:47

**Comment by GoogleCodeExporter** [comment]
```
This is a problem with the Cloud SDK: the Cloud SDK sets the Docker API version 
used.

Adding that notice or a warning in the appropriate documentation is a great 
idea. I'll update this once we get the docs fix out.
```

Original comment by `z...@google.com` on 15 Jul 2015 at 9:52

**Comment by GoogleCodeExporter** [comment]
```
Documentation change is out: 
https://cloud.google.com/appengine/docs/managed-vms/getting-started#check_your_d
ocker_versions

We're still working on a fix for the underlying issue and will update when it 
is fixed.
```

Original comment by `z...@google.com` on 16 Jul 2015 at 2:43

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Expect a fix in Cloud SDK version 0.9.71 (to be released in about a week).
```

Original comment by `z...@google.com` on 21 Jul 2015 at 3:21

**Comment by GoogleCodeExporter** [comment]
```
The fix suggested to have 1.7.0 instead worked for my nodejs custom app engine 
VM.
Though after download, executing "boot2docker version" kept sayinh "1.7.1" 
where the ISO was indeed 1.7.0 -- just saying in case that can throw ppl off
```

Original comment by `camilo.s...@citrix.com` on 21 Jul 2015 at 10:29

**Comment by GoogleCodeExporter** [comment]
```
Issue 177 has been merged into this issue.
```

Original comment by `z...@google.com` on 29 Jul 2015 at 3:42

**Comment by GoogleCodeExporter** [comment]
```
Confirmed! New release works, even when the release notes don't
mention it. Also really like the new dockerless local development that
was apparently available for a while now, but I wasn't aware. You
still need docker for deployment obviously, but no more boot2docker
(on Linux at least)!
```

Original comment by `pdknsk` on 30 Jul 2015 at 2:56

**Comment by GoogleCodeExporter** [comment]
```
Thanks for confirming!

Dockerless development was in sort-of a trial mode and we flipped it on by 
default in this release. That's why we didn't publicize it before.

We always appreciate the feedback (good or bad :) ).
```

Original comment by `z...@google.com` on 30 Jul 2015 at 3:10
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Hey pdknsk,

Thanks for the feedback and confirming. We're working on something very similar 
for deployments, and it will soon become the default :) You can try it today 
just by passing "--remote" to gcloud preview app deploy. There are a few minor 
issues, but we'll be flipping this on very soon.
```

Original comment by `dlor...@google.com` on 30 Jul 2015 at 3:19

**Comment by GoogleCodeExporter** [comment]
```
Well you still need docker, to build images. Or so I thought! Untill I
tried and read this.

That's great! I don't really mind having docker installed, but it's
quite invasive IMO when you only need it to build images (rather than
run containers).

And it significantly cuts first deployment time, I imagine, especially
when you're on a slow upload connection. Deployment with no changes is
about +30 seconds when I tried, but that's a very good trade-off.
```

Original comment by `pdknsk` on 30 Jul 2015 at 3:36

**Comment by GoogleCodeExporter** [comment]
```
The bug tracker ate this line.

-- Provisioning remote build service.
```

Original comment by `pdknsk` on 30 Jul 2015 at 3:37

**Comment by GoogleCodeExporter** [comment]
```
Hello guys, thanks for this information but I still can't get the nodejs 
environment working in any shape or form.

I'm trying to run on preview and deploy the tutorial example from here:
https://github.com/GoogleCloudPlatform/nodejs-getting-started/tree/1-hello-world
Note that app.yaml from this example has "nodejs" set as runtime.

After running:
gcloud preview app run --host localhost:8080 app.yaml
I get:
RuntimeError: Unknown runtime 'nodejs'; supported runtimes are 'custom', 'go', 
'java', 'java7', 'php', 'php55', 'python, 'python27', 'vm'.

If I put "vm" for runtime it wants to use docker, which doesn't work for me 
either. So this dockerless option felt very heartwarming.

If I put "custom" for runtime in yaml file I get:
ValueError: The --custom_entrypoint flag must be set for custom runtimes

Example given in the help output for this switch is the following:
--custom_entrypoint="gunicorn -b localhost:{port} mymodule:application"

I tried with this, best guess:
gcloud preview app run --custom_entrypoint="nodejs -b localhost:{8080} 
mymodule:application" app.yaml
and got this:
ERROR: Argument [--custom_entrypoint=nodejs -b localhost:{8080} 
mymodule:application] is not a valid deployable file.
ERROR: (gcloud.preview.app.run) Errors occurred while parsing the App Engine 
app configuration.

You have my sincere apologies if this isn't a proper venue for this type of 
post, but all this jak shaving makes me a bit dimwitted.
```

Original comment by `marko.kn...@gmail.com` on 30 Jul 2015 at 7:37

**Comment by GoogleCodeExporter** [comment]
```
http://stackoverflow.com/questions/tagged/gcloud might be a better place for 
this question.

If you post there, I can loop in some of the folks who worked on the nodejs 
tutorial.
```

Original comment by `z...@google.com` on 30 Jul 2015 at 8:17

**Comment by GoogleCodeExporter** [comment]
```
OK thanks, will do. I though I'll get a notification, sorry about the delayed 
reply.
```

Original comment by `marko.kn...@gmail.com` on 2 Aug 2015 at 9:45

**Comment by GoogleCodeExporter** [comment]
```
This still doesn't work for me when running in Docker mode 
(GAE_LOCAL_VM_RUNTIME=0).

I'm on Cloud SDK version 0.9.71 and Docker 1.7.1. When I run gcloud run_start I 
receive the same error message as the first post: "APIError: 400 Client Error: 
Bad Request ("client is too old, minimum supported API version is 1.12, please 
upgrade your client to a newer version")"

Running in Dockerless mode allows the development server to start up without 
error.
```

Original comment by `YDRadcli...@gmail.com` on 3 Aug 2015 at 5:34

**Comment by GoogleCodeExporter** [comment]
```
#17: This is fixed, but the version `gcloud preview app run` lags behind 
`gcloud preview app deploy` (we have to wait for the Google App Engine SDK 
release to go out, which happens on a much slower schedule than the Cloud SDK 
release). For now, please continue to use Docker 1.7.0, or use Dockerless local 
development.
```

Original comment by `z...@google.com` on 4 Aug 2015 at 9:16

**Comment by GoogleCodeExporter** [comment]
```
I have a feature request to decrease deployment time for remote
builds. Make it possible to provision a permanent instance just for
that purpose, rather than spin an instance up and down for every
deployment. A micro-f instance is just $4 per month. When you consider
10 minute penalty for each instance start (or deployment), the
difference is even smaller.
```

Original comment by `pdknsk` on 14 Aug 2015 at 3:59

**Comment by GoogleCodeExporter** [comment]
```
I meant f1-micro instance.
```

Original comment by `pdknsk` on 14 Aug 2015 at 4:03

**Comment by GoogleCodeExporter** [comment]
```
pdknsk: Thank you for the suggestion. We're aware that deployment time for 
remote builds is long, and have several strategies cooking which we'd like to 
implement to make it faster by default.

Note also that what you described is currently possible to do manually (if you 
install Docker yourself), though we still would call it a "local" build.
```

Original comment by `z...@google.com` on 14 Aug 2015 at 3:33

**Comment by GoogleCodeExporter** [comment]
```
I notice the builder uses n1-standard-1 instances. That's $0.0084 per 
deployment (unless it takes more than 10 minutes, which seems unlikely).

By the way, I noticed that docker-less deployments still make a .dockercfg file 
in the home directory. I'm not sure what the purpose is, but it seems 
unnecessary to me.
```

Original comment by `pdknsk` on 15 Aug 2015 at 7:19

**Comment by GoogleCodeExporter** [comment]
```
The .dockercfg holds authentication for gcr.io (the Google Container Registry). 
In this case, it is necessary, since the built image gets pushed to GCR so that 
the deployed application instance can access it.
```

Original comment by `z...@google.com` on 17 Aug 2015 at 5:48

**Comment by GoogleCodeExporter** [comment]
```
For some reason, even though I'm running version 0.9.74 of the Google Cloud 
SDK, and version 1.7.0 of docker, I will get the error when running my app 
locally in docker mode. Is anyone else seeing this? Am I doing something wrong?

WARNING: The [application] field is specified in file 
[/Users/kwasi/dev/goodwater/ocean/app.yaml].  This field is not used by gcloud 
and should be removed.
Module [default] found in file [/Users/kwasi/dev/goodwater/ocean/app.yaml]
INFO: Looking for the Dockerfile in /Users/kwasi/dev/goodwater/ocean
INFO: Using Dockerfile found in /Users/kwasi/dev/goodwater/ocean
INFO     2015-08-25 21:37:20,412 devappserver2.py:763] Skipping SDK update 
check.
INFO     2015-08-25 21:37:20,440 api_server.py:205] Starting API server at: 
http://localhost:49411
INFO     2015-08-25 21:37:20,466 api_server.py:648] Applying all pending 
transactions and saving the datastore
INFO     2015-08-25 21:37:20,466 api_server.py:651] Saving search indexes
Traceback (most recent call last):
  File "/Users/kwasi/google-cloud-sdk/platform/google_appengine/dev_appserver.py", line 83, in <module>
    _run_file(__file__, globals())
  File "/Users/kwasi/google-cloud-sdk/platform/google_appengine/dev_appserver.py", line 79, in _run_file
    execfile(_PATHS.script_file(script_name), globals_)
  File "/Users/kwasi/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 1033, in <module>
    main()
  File "/Users/kwasi/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 1026, in main
    dev_server.start(options)
  File "/Users/kwasi/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 818, in start
    self._dispatcher.start(options.api_host, apis.port, request_data)
  File "/Users/kwasi/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/dispatcher.py", line 193, in start
    _module, port = self._create_module(module_configuration, port)
  File "/Users/kwasi/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/dispatcher.py", line 278, in _create_module
    threadsafe_override=threadsafe_override)
  File "/Users/kwasi/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/module.py", line 1535, in __init__
    super(ManualScalingModule, self).__init__(**kwargs)
  File "/Users/kwasi/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/module.py", line 554, in __init__
    self._module_configuration)
  File "/Users/kwasi/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/module.py", line 255, in _create_instance_factory
    module_configuration=module_configuration)
  File "/Users/kwasi/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/vm_runtime_factory.py", line 76, in __init__
    timeout=self.DOCKER_D_REQUEST_TIMEOUT_SECS)
  File "/Users/kwasi/google-cloud-sdk/platform/google_appengine/google/appengine/tools/docker/containers.py", line 742, in NewDockerClient
    client.ping()
  File "/Users/kwasi/google-cloud-sdk/lib/docker/docker/client.py", line 847, in ping
    return self._result(self._get(self._url('/_ping')))
  File "/Users/kwasi/google-cloud-sdk/lib/docker/docker/client.py", line 126, in _result
    self._raise_for_status(response)
  File "/Users/kwasi/google-cloud-sdk/lib/docker/docker/client.py", line 122, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
docker.docker.errors.APIError: 400 Client Error: Bad Request ("client is too 
old, minimum supported API version is 1.12, please upgrade your client to a 
newer version")
ERROR: (gcloud.preview.app.run) DevAppSever failed with error code [1]
```

Original comment by `kohene...@goodwatercap.com` on 25 Aug 2015 at 9:40

**Comment by GoogleCodeExporter** [comment]
```
HOnestly, I gave up on running my app in docker mode at the moment.
I simply test locally normally and then deploy (in only do this since it is 
easy enough).

What's even weirder is that I was able to test on docker mode before the Aug 
19th release/upgrade of gcloud.

I'm using NodeJS managed VM.
docker and boot2docker v1.5.0

Regards,
CAS
```

Original comment by `camilo.s...@citrix.com` on 26 Aug 2015 at 4:14

**Comment by GoogleCodeExporter** [comment]
```
Hey CAS,

It turns out that my docker server was running a version higher than 1.7.0 even 
though my docker client was in fact running 1.7.0. I was having trouble 
downgrading the version of the docker daemon in docker-machine on my Mac, so in 
my frustration yesterday, I went ahead and made a minor tweak to the code in 
google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/
vm_runtime_factory.py.

I switched version='1.9' on line 75 to version='1.12'.

That did the trick. Now I can test in both docker and docker-less mode. As I 
suspected, I've already caught a number of edge case bugs triggered by my code 
that don't show up when I'm running in docker-less mode. So it's been extremely 
useful for me to be able to test in docker mode locally.

Cheers,
Kwasi
```

Original comment by `kohene...@goodwatercap.com` on 26 Aug 2015 at 4:29

**Comment by GoogleCodeExporter** [comment]
```
This is fixed in the latest version of the AppEngine SDK (1.9.26), which is not
released yet. For now, please downgrade to Docker version 1.6.2 as a
work-around.

However, we're removing support for local Docker in the dev_appserver in the 
following version. If you'd like to keep this workflow, do not upgrade from 
AppEngine 1.9.26. In
general, we encourage local development using language-specific tools as much
as possible. A longer-term (but not officially supported) solution might be
AppStart (https://github.com/GoogleCloudPlatform/appstart), which aims to
simulate the deployed environment for Managed VMs for local development.

```

Original comment by `z...@google.com` on 26 Aug 2015 at 6:11

**Comment by GoogleCodeExporter** [comment]
```
Just looked at the appstart readme in github.
Do you know if the authors have tested this on a managed vm running Node?

I am tempted to clone, install it and see if it works (I have both boo2docker 
and docker v1.5.0 so Im fulfilling the basic reqs)

Thanks,
Camilo
```

Original comment by `camilo.s...@citrix.com` on 26 Aug 2015 at 6:51

**Comment by GoogleCodeExporter** [comment]
```
The Cloud SDK team does not manage AppStart, so I'd recommend reaching out to 
them directly.
```

Original comment by `z...@google.com` on 26 Aug 2015 at 6:52

**Comment by GoogleCodeExporter** [comment]
```
Hi Kwasi,

Just wanted to follow up.
As an alternative to the solution that you posted,
I found that forcing gcloud to run on version 0.9.66 also does the trick.
With that version, I can run my nodeJS app in docker locally using gcloud and 
it works.
I'm using both boot2docker and docker v1.5.0.

```

Original comment by `camilo.s...@citrix.com` on 31 Aug 2015 at 2:03

**Comment by GoogleCodeExporter** [comment]
```
Hello Camilo,

Thanks for the pointers. I'm not quite sure I agree with removing support for 
local docker mode in later versions of the app engine SDK. From the little time 
I've spent with managed VMs, it's very important to be able to verify that 
docker containers are constructed properly in local development to eliminate 
any surprises when publishing to production. I think the AppStart project is a 
great idea.
```

Original comment by `kohene...@goodwatercap.com` on 18 Sep 2015 at 5:19

**Comment by GoogleCodeExporter** [comment]
```
I made a topic on the forum to discuss where this is going.

https://groups.google.com/forum/#!topic/google-cloud-sdk/JSn8MNICOmQ
```

Original comment by `pdknsk` on 3 Oct 2015 at 12:41

**Comment by GoogleCodeExporter** [comment]
```
when does this issue could be fixed? it still happen on latest version of SDK
```

Original comment by `bilig...@gmail.com` on 25 Oct 2015 at 8:18

**Comment by GoogleCodeExporter** [comment]
```
#33: do you mind making a new issue? This one has been used for a couple of 
different issues, and it'd be easier to focus on just one.
```

Original comment by `z...@google.com` on 26 Oct 2015 at 4:01
