### ISSUE TITLE
gcloud auth login not working

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#168]
```
What steps will reproduce the problem?
After installing gcloud on OS X Yosemite, restarting the shell, I run `gcloud 
auth login`

What is the expected output? What do you see instead?
After allowing access through the browser window, the following output is given:
>>>>
Traceback (most recent call last):
  File "/Users/josesho/gcloud/google-cloud-sdk/./lib/googlecloudsdk/gcloud/gcloud.py", line 194, in main
    _cli.Execute()
  File "/Users/josesho/gcloud/google-cloud-sdk/./lib/googlecloudsdk/calliope/cli.py", line 548, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "/Users/josesho/gcloud/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 1124, in Run
    result = command_instance.Run(args)
  File "/Users/josesho/gcloud/google-cloud-sdk/./lib/googlecloudsdk/calliope/exceptions.py", line 86, in TryFunc
    return func(*args, **kwargs)
  File "/Users/josesho/gcloud/google-cloud-sdk/lib/googlecloudsdk/gcloud/sdktools/auth/login.py", line 95, in Run
    creds = self.DoWebFlow(args.launch_browser)
  File "/Users/josesho/gcloud/google-cloud-sdk/lib/googlecloudsdk/gcloud/sdktools/auth/login.py", line 153, in DoWebFlow
    return c_store.AcquireFromWebFlow(launch_browser=launch_browser)
  File "/Users/josesho/gcloud/google-cloud-sdk/./lib/googlecloudsdk/core/credentials/store.py", line 384, in AcquireFromWebFlow
    http=_Http())
  File "/Users/josesho/gcloud/google-cloud-sdk/./lib/googlecloudsdk/core/credentials/flow.py", line 156, in Run
    credential = flow.step2_exchange(code, http=http)
  File "/Users/josesho/gcloud/google-cloud-sdk/./lib/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/josesho/gcloud/google-cloud-sdk/./lib/oauth2client/client.py", line 1993, in step2_exchange
    headers=headers)
  File "/Users/josesho/gcloud/google-cloud-sdk/./lib/httplib2/__init__.py", line 1608, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/Users/josesho/gcloud/google-cloud-sdk/./lib/httplib2/__init__.py", line 1350, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/Users/josesho/gcloud/google-cloud-sdk/./lib/httplib2/__init__.py", line 1272, in _conn_request
    conn.connect()
  File "/Users/josesho/gcloud/google-cloud-sdk/./lib/httplib2/__init__.py", line 1059, in connect
    raise SSLHandshakeError(e)
SSLHandshakeError: [Errno 1] _ssl.c:503: error:14090086:SSL 
routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
>>>>


What is the output of 'gcloud info'?
Google Cloud SDK [0.9.69]

Platform: [Mac OS X, x86_64]
Python Version: [2.7.2 (v2.7.2:8527427914a2, Jun 11 2011, 14:13:39)  [GCC 4.0.1 
(Apple Inc. build 5493)]]
Site Packages: [Disabled]

Installation Root: [/Users/josesho/gcloud/google-cloud-sdk]
Installed Components:
  core: [2015.07.10]
  core-nix: [2015.06.02]
  gcutil-msg: [2015.07.02]
  gcloud: [2015.07.10]
  gsutil-nix: [4.12]
  gsutil: [4.13]
  bq: [2.0.18]
  bq-nix: [2.0.18]
System PATH: 
[/Users/josesho/gcloud/google-cloud-sdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sb
in:/sbin:/opt/X11/bin:/usr/local/git/bin:/usr/texbin:/Users/josesho/gcloud/googl
e-cloud-sdk/bin]
Cloud SDK on PATH: [True]

Installation Properties: [/Users/josesho/gcloud/google-cloud-sdk/properties]
User Config Directory: [/Users/josesho/.config/gcloud]
User Properties: [/Users/josesho/.config/gcloud/properties]
Current Workspace: [None]
Workspace Config Directory: [None]
Workspace Properties: [None]

Account: [joseshowh]
Project: [None]

Current Properties:
  [core]
    account: [joseshowh]
    disable_usage_reporting: [False]

Logs Directory: [/Users/josesho/.config/gcloud/logs]
Last Log File: 
[/Users/josesho/.config/gcloud/logs/2015.07.22/17.04.58.759588.log]


Please provide any additional information below.

```

Original issue reported on code.google.com by `josesh...@gmail.com` on 22 Jul 2015 at 9:13
- Merged into: #14

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 13 Oct 2015 at 3:08
- Changed state: **Duplicate**
