### ISSUE TITLE
glcoud preview app deploy fails

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#169]
```
What steps will reproduce the problem?
cd into the app directory then run 
gcloud preview app deploy ./app.yaml —set-default

What is the expected output? What do you see instead?
that the app deployed to GCP 

lynnlangits-MacBook-Air:TKPTimer lynnlangit$ gcloud preview app deploy 
./app.yaml —set-default
Traceback (most recent call last):
  File "/Users/lynnlangit/google-cloud-sdk/./lib/googlecloudsdk/gcloud/gcloud.py", line 195, in main
    _cli.Execute()
  File "/Users/lynnlangit/google-cloud-sdk/./lib/googlecloudsdk/calliope/cli.py", line 527, in Execute
    raise exceptions.InvalidStringException(s)
  File "/Users/lynnlangit/google-cloud-sdk/./lib/googlecloudsdk/calliope/exceptions.py", line 117, in __init__
    self.invalid_arg))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal 
not in range(128)

Please provide any additional information below.


The output of 'gcloud info':

Google Cloud SDK [0.9.70]

Platform: [Mac OS X, x86_64]
Python Version: [2.7.9 |Anaconda 2.2.0 (x86_64)| (default, Dec 15 2014, 
10:37:34)  [GCC 4.2.1 (Apple Inc. build 5577)]]
Site Packages: [Disabled]

Installation Root: [/Users/lynnlangit/google-cloud-sdk]
Installed Components:
  core: [2015.07.16]
  app-engine-python: [1.9.23]
  core-nix: [2015.06.02]
  kubectl: []
  app: [2015.07.16]
  gcloud: [2015.07.16]
  gsutil-nix: [4.12]
  bq-nix: [2.0.18]
  app-engine-python-extras: [1.9.21]
  gsutil: [4.13]
  bq: [2.0.18]
  preview: [2015.07.16]
  kubectl-darwin-x86_64: [1.0.0]
System PATH: 
[/Users/lynnlangit/google-cloud-sdk/bin:/Users/lynnlangit/anaconda/bin:/Users/ly
nnlangit/bin:/Users/lynnlangit/.rvm/gems/ruby-1.9.3-p327/bin:/Users/lynnlangit/.
rvm/gems/ruby-1.9.3-p327@global/bin:/Users/lynnlangit/.rvm/rubies/ruby-1.9.3-p32
7/bin:/Users/lynnlangit/.rvm/bin:/Users/lynnlangit/cli/assembly/target/codenvy-c
li-2.5.0-SNAPSHOT/codenvy-cli-2.5.0-SNAPSHOT/bin:/usr/local/bin:/usr/bin:/bin:/u
sr/sbin:/sbin:/opt/X11/bin:/Applications/domino:/usr/local/go/bin:/usr/local/Mac
GPG2/bin:/Users/lynnlangit/gcutil-1.5.0]
Cloud SDK on PATH: [True]



```

Original issue reported on code.google.com by `lynnlan...@gmail.com` on 24 Jul 2015 at 4:14

**Comment by GoogleCodeExporter** [comment]
```
Hi there,

It looks like you're using an en-dash (—) rather than two hyphens (--) to 
pass the --set-default argument.

Do you mind trying again with the following command line invocation?

    gcloud preview app deploy ./app.yaml --set-default

If you copy-pasted your original command from a Google website, please let us 
know where and we'll fix it.
```

Original comment by `z...@google.com` on 24 Jul 2015 at 2:41
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
thanks that worked - I honestly don't remember where I got the original
code from, I check your docs at
https://cloud.google.com/sdk/gcloud/reference/preview/app/deploy and they
look ok

I do wish the error message returned by GCloud weren't so cryptic though.

thank again

Lynn Langit
```

Original comment by `lynnlan...@gmail.com` on 24 Jul 2015 at 4:12

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the report and feedback. We have created an internal issue to 
improve the error message.
```

Original comment by `vil...@google.com` on 24 Jul 2015 at 5:28

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 13 Oct 2015 at 3:09
- Changed state: **Obsolete**
