### ISSUE TITLE
gcloud auth login ­-no-launch-browser command in cygwin fails with exception

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#170]
```
What steps will reproduce the problem?

Install the Google Cloud SDK through cygwin by giving "curl  
https://sdk.cloud.google.com  | bash " command in cygwin command prompt. after 
successfully installing sdk, exit the cygwin command prompt and enter "gcloud 
auth login ­-no-launch-browser"
What is the expected output? What do you see instead?
A url 

What is the output of 'gcloud info'?

The command will generate a link and wait for me to enter verification code
Please provide any additional information below.
below is the error message im getting.

479634@01HW197792 ~
$ gcloud auth login ­-no-launch-browser
Traceback (most recent call last):
  File "/home/479634/google-cloud-sdk/./lib/googlecloudsdk/gcloud/gcloud.py", line 195, in main
    _cli.Execute()
  File "/home/479634/google-cloud-sdk/./lib/googlecloudsdk/calliope/cli.py", line 527, in Execute
    raise exceptions.InvalidStringException(s)
  File "/home/479634/google-cloud-sdk/./lib/googlecloudsdk/calliope/exceptions.py", line 117, in __init__
    self.invalid_arg))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 0: ordinal 
not in range(128)

If you would like to report this issue, please run the following command:
  gcloud feedback





```

Original issue reported on code.google.com by `mailusuresh@gmail.com` on 24 Jul 2015 at 7:39

Attachments:
- [12.22.23.503265.log](https://storage.googleapis.com/google-code-attachments/google-cloud-sdk/issue-170/comment-0/12.22.23.503265.log)
- [12.27.03.907265.log](https://storage.googleapis.com/google-code-attachments/google-cloud-sdk/issue-170/comment-0/12.27.03.907265.log)
- [12.30.40.742265.log](https://storage.googleapis.com/google-code-attachments/google-cloud-sdk/issue-170/comment-0/12.30.40.742265.log)

**Comment by GoogleCodeExporter** [comment]
```
It appears in your command you have some non ascii characters (likely copy 
pasted from somewhere) like  double -- becomes - in some browsers.
  gcloud auth login ­-no-launch-browser

Flags have two dashes in from on of them:
  gcloud auth login ­--no-launch-browser
```

Original comment by `che...@google.com` on 24 Jul 2015 at 12:48

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 13 Oct 2015 at 3:13
- Changed state: **WorkingAsIntended**
