### ISSUE TITLE
gcloud components update is up to date, yet can't deploy to appengine

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#177]
```
What steps will reproduce the problem?

Unknown exactly.

Use glcoud one week, wait a few weeks, and it can no longer deploy.


What is the expected output? What do you see instead?

I would have expected the following to be able to successfully deploy:

~ccce-raggi/src/sserb * gcloud components update

All components are up to date.
~ccce-raggi/src/sserb % gcloud preview app deploy sserb.yaml --set-default
You are about to deploy the following modules:
 - ccce-raggi/sserb (from [/Users/raggi/src/source.developers.google.com/p/ccce-raggi/r/default/src/sserb/sserb.yaml])
     Deployed URL: [https://sserb-dot-ccce-raggi.appspot.com]

Do you want to continue (Y/n)?  y

Beginning deployment...
Verifying that Managed VMs are enabled and ready.

Traceback (most recent call last):
  File "/Users/raggi/usr/google-cloud-sdk/./lib/googlecloudsdk/gcloud/gcloud.py", line 195, in main
    _cli.Execute()
  File "/Users/raggi/usr/google-cloud-sdk/./lib/googlecloudsdk/calliope/cli.py", line 548, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "/Users/raggi/usr/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 1102, in Run
    result = command_instance.Run(args)
  File "/Users/raggi/usr/google-cloud-sdk/lib/googlecloudsdk/appengine/app_commands/deploy.py", line 192, in Run
    args.remote)
  File "/Users/raggi/usr/google-cloud-sdk/./lib/googlecloudsdk/appengine/lib/deploy_command_util.py", line 59, in BuildAndPushDockerImages
    remote) as docker_client:
  File "/Users/raggi/usr/google-cloud-sdk/./lib/googlecloudsdk/appengine/lib/images/remote_docker.py", line 208, in __enter__
    return containers.NewDockerClient(**kwargs)
  File "/Users/raggi/usr/google-cloud-sdk/./lib/googlecloudsdk/appengine/lib/docker/containers.py", line 294, in NewDockerClient
    client.ping()
  File "/Users/raggi/usr/google-cloud-sdk/./lib/docker/docker/client.py", line 847, in ping
    return self._result(self._get(self._url('/_ping')))
  File "/Users/raggi/usr/google-cloud-sdk/./lib/docker/docker/client.py", line 126, in _result
    self._raise_for_status(response)
  File "/Users/raggi/usr/google-cloud-sdk/./lib/docker/docker/client.py", line 122, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
APIError: 400 Client Error: Bad Request ("client is too old, minimum supported 
API version is 1.12, please upgrade your client to a newer version")

If you would like to report this issue, please run the following command:
  gcloud feedback


We should never leave users with this kind of client error while gcloud 
components update claims to be up to date.

Please provide any additional information below.


The output of 'gcloud info':

Google Cloud SDK [0.9.70]

Platform: [Mac OS X, x86_64]
Python Version: [2.7.6 (default, Sep  9 2014, 15:04:36)  [GCC 4.2.1 Compatible 
Apple LLVM 6.0 (clang-600.0.39)]]
Site Packages: [Disabled]

Installation Root: [/Users/raggi/usr/google-cloud-sdk]
Installed Components:
  core: [2015.07.16]
  app-engine-python: [1.9.23]
  core-nix: [2015.06.02]
  kubectl: []
  app-engine-java: [1.9.23]
  gcloud: [2015.07.16]
  gsutil-nix: [4.12]
  bq-nix: [2.0.18]
  gsutil: [4.13]
  bq: [2.0.18]
  alpha: [2015.06.30]
  preview: [2015.07.16]
  app: [2015.07.16]
  kubectl-darwin-x86_64: [1.0.0]
System PATH: 
[/Users/raggi/usr/google-cloud-sdk/bin:/Users/raggi/usr/google-cloud-sdk/bin:/Us
ers/raggi/bin:/Users/raggi/usr/local/bin:/usr/local/bin:/usr/local/sbin:/usr/bin
:/usr/sbin:/bin:/sbin:/usr/local/git/current/bin:/opt/X11/bin:/Users/raggi/usr/g
oogle-cloud-sdk/bin]
Cloud SDK on PATH: [True]

Installation Properties: [/Users/raggi/usr/google-cloud-sdk/properties]
User Config Directory: [/Users/raggi/.config/gcloud]
User Properties: [/Users/raggi/.config/gcloud/properties]
Current Workspace: [None]
Workspace Config Directory: [None]
Workspace Properties: [None]

Account: [raggi@google.com]
Project: [ccce-raggi]

Current Properties:
  [core]
    project: [ccce-raggi]
    account: [raggi@google.com]
    disable_usage_reporting: [False]

[output truncated]

```

Original issue reported on code.google.com by `ra...@google.com` on 28 Jul 2015 at 6:33
- Merged into: #163

**Comment by GoogleCodeExporter** [comment]
```
docker 1.7.1 issue. dup.
```

Original comment by `ra...@google.com` on 28 Jul 2015 at 8:17

**Comment by GoogleCodeExporter** [comment]
```
Thanks for reporting this. We have a fix that should be coming out in Cloud SDK 
0.9.71. Please try again when that is released (should be sometime this week).
```

Original comment by `z...@google.com` on 29 Jul 2015 at 3:42
- Changed state: **Duplicate**
