### ISSUE TITLE
gcloud CommandLoadFailure: Problem loading gcloud.projects: No module named developerprojects

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#178]
```
1. What steps will reproduce the problem?

I run `gcloud` on a node of our "development-blue" cluster and I get an error.

2. What is the expected output? What do you see instead?
3. What is the output of 'gcloud info'?

This gist shows the output which is clearly not the expected output of 
`gcloud`, and the output of `gcloud info`.  

    https://gist.github.com/rask0l/d80bf5f4087b1a32940e

4. Please provide any additional information below.

Project: porch-gcp
Cluster: development-blue
Node: gke-development-blue-a5851c00-node-v126

Regards, 
Nick Turner | Porch.com
nicholast@porch.com (nicholast@helpscore.com)
```

Original issue reported on code.google.com by `nichol...@helpscore.com` on 28 Jul 2015 at 8:07
- Merged into: #157

**Comment by GoogleCodeExporter** [comment]
```
For completeness, here is the contents of the gist: 

nickyt@gke-development-blue-a5851c00-node-v126:~$ gcloud
Traceback (most recent call last):
  File "/usr/local/bin/../share/google/google-cloud-sdk/./lib/googlecloudsdk/gcloud/gcloud.py", line 195, in main
    _cli.Execute()
  File "/usr/local/bin/../share/google/google-cloud-sdk/./lib/googlecloudsdk/calliope/cli.py", line 534, in Execute
    args = self.__parser.parse_args(args)
  File "/usr/local/bin/../share/google/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 74, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/local/bin/../share/google/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 65, in parse_known_args
    args, argv = super(ArgumentParser, self).parse_known_args(args, namespace)
  File "/usr/local/bin/../share/google/google-cloud-sdk/./lib/argparse/__init__.py", line 1735, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/local/bin/../share/google/google-cloud-sdk/./lib/argparse/__init__.py", line 1952, in _parse_known_args
    self.error(_('too few arguments'))
  File "/usr/local/bin/../share/google/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 189, in error
    self._calliope_command, self._calliope_command.ai)
  File "/usr/local/bin/../share/google/google-cloud-sdk/./lib/googlecloudsdk/calliope/usage_text.py", line 381, in ShortHelpText
    command.LoadAllSubElements()
  File "/usr/local/bin/../share/google/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 956, in LoadAllSubElements
    element = self.LoadSubElement(name)
  File "/usr/local/bin/../share/google/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 989, in LoadSubElement
    self._config_hooks, parent_group=self, allow_empty=allow_empty)
  File "/usr/local/bin/../share/google/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 807, in __init__
    self._GetModuleFromPath(module_dir, module_path, path, construction_id),
  File "/usr/local/bin/../share/google/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 725, in _GetModuleFromPath
    name_to_give, os.path.join(module_dir, *module_path))
  File "/usr/local/bin/../share/google/google-cloud-sdk/./lib/googlecloudsdk/core/util/pkg_resources.py", line 62, in GetModuleFromPath
    module = imp.load_module(name_to_give, f, file_path, items)
  File "/usr/local/share/google/google-cloud-sdk/lib/googlecloudsdk/projects/commands/__init__.py", line 8, in <module>
    from googlecloudapis.developerprojects import v2beta1
CommandLoadFailure: Problem loading gcloud.projects: No module named 
developerprojects.

If you would like to report this issue, please run the following command:
  gcloud feedback

nickyt@gke-development-blue-a5851c00-node-v126:~$ gcloud info
Google Cloud SDK [0.9.70]

Platform: [Linux, x86_64]
Python Version: [2.7.3 (default, Mar 13 2014, 11:03:55)  [GCC 4.7.2]]
Site Packages: [Disabled]

Installation Root: [/usr/local/share/google/google-cloud-sdk]
Installed Components:
  core: [2015.07.16]
  core-nix: [2015.06.02]
  gsutil-nix: [4.12]
  gsutil: [4.13]
  bq: [2.0.18]
  bq-nix: [2.0.18]
System PATH: [/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games]
Cloud SDK on PATH: [False]

Installation Properties: [/usr/local/share/google/google-cloud-sdk/properties]
User Config Directory: [/home/nickyt/.config/gcloud]
User Properties: [/home/nickyt/.config/gcloud/properties]
Current Workspace: [None]
Workspace Config Directory: [None]
Workspace Properties: [None]

Account: [920738820133-compute@developer.gserviceaccount.com]
Project: [porch-gcp]

Current Properties:
  [core]
    project: [porch-gcp]
    account: [920738820133-compute@developer.gserviceaccount.com]

Logs Directory: [/home/nickyt/.config/gcloud/logs]
Last Log File: [/home/nickyt/.config/gcloud/logs/2015.07.28/19.49.59.311170.log]
```

Original comment by `nichol...@helpscore.com` on 28 Jul 2015 at 8:12

**Comment by GoogleCodeExporter** [comment]
```
Hi Nick,

Thanks for reporting this, and sorry you ran into an issue here.

To workaround, you should be able to run `gcloud components reinstall` (or if 
that's not working due to import errors, re-install manually).

It looks to me like this is a duplicate of 
https://code.google.com/p/google-cloud-sdk/issues/detail?id=157 (issue with 
out-of-date files after an update; the line in projects/commands/__init__.py 
hasn't been in the Cloud SDK for months now), so I'm going to mark it as such. 
Do you remember at when you installed the Cloud SDK, and how frequently you've 
updated?
```

Original comment by `z...@google.com` on 29 Jul 2015 at 4:27
- Changed state: **Duplicate**

**Comment by GoogleCodeExporter** [comment]
```
Apologies, and thanks, reinstall worked.  
```

Original comment by `nichol...@helpscore.com` on 29 Jul 2015 at 5:35
