### ISSUE TITLE
Constant, recurring issue: ServerNotFoundError: Unable to find the server at accounts.google.com

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#179]
```
What steps will reproduce the problem?

* Running 'gcloud preview app deploy my_app.yaml'
* works on every app I try to deploy, so presumably a systemic issue

What is the expected output? What do you see instead?

* I expect to see it deploy. Instead, I see the following:

me@myComputer:~/Documents/parent_proj/my_app$ gcloud preview app deploy 
my_app.yaml 
WARNING: The [application] field is specified in file 
[/home/me/Documents/parent_proj/my_app/my_app.yaml].  This field is not used by 
gcloud and should be removed.
You are about to deploy the following modules:
 - parent_proj-cloud-dev/my_app (from [/home/me/Documents/parent_proj/my_app/my_app.yaml])
     Deployed URL: [https://20150728t155506-dot-my_app-dot-parent_proj-cloud-dev.appspot.com]
     (add --set-default if you also want to make this module available from
     [https://my_app-dot-parent_proj-cloud-dev.appspot.com])

Beginning deployment...
Verifying that Managed VMs are enabled and ready.
If this is your first deployment, this may take a while...done.

ERROR: (gcloud.preview.app.deploy) Unable to find the server at 
accounts.google.com
me@myComputer:~/Documents/parent_proj/my_app$ gcloud preview app deploy 
my_app.yaml 
WARNING: The [application] field is specified in file 
[/home/me/Documents/parent_proj/my_app/my_app.yaml].  This field is not used by 
gcloud and should be removed.
You are about to deploy the following modules:
 - parent_proj-cloud-dev/my_app (from [/home/me/Documents/parent_proj/my_app/my_app.yaml])
     Deployed URL: [https://20150728t160109-dot-my_app-dot-parent_proj-cloud-dev.appspot.com]
     (add --set-default if you also want to make this module available from
     [https://my_app-dot-parent_proj-cloud-dev.appspot.com])

Beginning deployment...
Verifying that Managed VMs are enabled and ready.
If this is your first deployment, this may take a while...done.
Traceback (most recent call last):
  File "/home/me/google-cloud-sdk/./lib/googlecloudsdk/gcloud/gcloud.py", line 195, in main
    _cli.Execute()
  File "/home/me/google-cloud-sdk/./lib/googlecloudsdk/calliope/cli.py", line 548, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "/home/me/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 1102, in Run
    result = command_instance.Run(args)
  File "/home/me/google-cloud-sdk/lib/googlecloudsdk/appengine/app_commands/deploy.py", line 192, in Run
    args.remote)
  File "/home/me/google-cloud-sdk/./lib/googlecloudsdk/appengine/lib/deploy_command_util.py", line 47, in BuildAndPushDockerImages
    client.PrepareVmRuntime()
  File "/home/me/google-cloud-sdk/./lib/googlecloudsdk/appengine/lib/appengine_client.py", line 281, in PrepareVmRuntime
    rpcserver.Send('/api/vms/prepare', app_id=self.project)
  File "/home/me/google-cloud-sdk/./lib/googlecloudsdk/appengine/lib/util.py", line 359, in Send
    response = self._server.Send(*args, **kwargs)
  File "/home/me/google-cloud-sdk/./lib/googlecloudsdk/appengine/lib/external/tools/appengine_rpc_httplib2.py", line 229, in Send
    url, method=method, body=payload, headers=headers)
  File "/home/me/google-cloud-sdk/./lib/oauth2client/client.py", line 540, in new_request
    self._refresh(request_orig)
  File "/home/me/google-cloud-sdk/./lib/oauth2client/client.py", line 768, in _refresh
    self._do_refresh_request(http_request)
  File "/home/me/google-cloud-sdk/./lib/oauth2client/client.py", line 799, in _do_refresh_request
    self.token_uri, method='POST', body=body, headers=headers)
  File "/home/me/google-cloud-sdk/./lib/httplib2/__init__.py", line 1608, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/home/me/google-cloud-sdk/./lib/httplib2/__init__.py", line 1350, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/home/me/google-cloud-sdk/./lib/httplib2/__init__.py", line 1278, in _conn_request
    raise ServerNotFoundError("Unable to find the server at %s" % conn.host)
ServerNotFoundError: Unable to find the server at accounts.google.com



Please provide any additional information below.


The output of 'gcloud info':

Google Cloud SDK [0.9.70]

Platform: [Linux, x86_64]
Python Version: [2.7.9 (default, Apr  2 2015, 15:33:21)  [GCC 4.9.2]]
Site Packages: [Disabled]

Installation Root: [/home/me/google-cloud-sdk]
Installed Components:
  core: [2015.07.16]
  app-engine-python: [1.9.23]
  core-nix: [2015.06.02]
  kubectl: []
  app-engine-java: [1.9.23]
  gcloud: [2015.07.16]
  gsutil-nix: [4.12]
  gsutil: [4.13]
  bq: [2.0.18]
  preview: [2015.07.16]
  kubectl-linux-x86_64: [1.0.0]
  app: [2015.07.16]
  bq-nix: [2.0.18]
System PATH: 
[/home/me/google-cloud-sdk/bin:/home/me/google-cloud-sdk/bin:/usr/local/sbin:/us
r/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/me/g
o/bin:/usr/local/go/bin:/home/me/google-cloud-sdk/google_appengine/:/home/me/goo
gle-cloud-sdk/appengine-java-sdk-1.9.23/:/home/me/google-cloud-sdk/go_appengine/
]
Cloud SDK on PATH: [True]

Installation Properties: [/home/me/google-cloud-sdk/properties]
User Config Directory: [/home/me/.config/gcloud]
User Properties: [/home/me/.config/gcloud/properties]
Current Workspace: [None]
Workspace Config Directory: [None]
Workspace Properties: [None]

Account: [me@rastechsoftware.com]
Project: [parent_proj-cloud-dev]

Current Properties:
  [core]
    project: [parent_proj-cloud-dev]
    account: [me@myemail.com]
    disable_usage_reporting: [False]
[output truncated]

```

Original issue reported on code.google.com by `Bryn.Mar...@gmail.com` on 28 Jul 2015 at 8:12

**Comment by GoogleCodeExporter** [comment]
```
Are there any strange network/firewall/proxy settings in your environment? What 
is the output of `ping accounts.google.com`?
```

Original comment by `z...@google.com` on 28 Jul 2015 at 9:33
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
Please re-open if you have more information.
```

Original comment by `z...@google.com` on 27 Aug 2015 at 10:41
- Changed state: **Invalid**

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
I encountered the same problem today.

the results I am getting from `ping accounts.google.com` are 

$ ping accounts.google.com
PING accounts.l.google.com (216.58.210.13) 56(84) bytes of data.
64 bytes from lhr08s06-in-f13.1e100.net (216.58.210.13): icmp_seq=1 ttl=58 
time=4.22 ms
64 bytes from lhr08s06-in-f13.1e100.net (216.58.210.13): icmp_seq=2 ttl=58 
time=137 ms
64 bytes from lhr08s06-in-f13.1e100.net (216.58.210.13): icmp_seq=3 ttl=58 
time=59.9 ms
64 bytes from lhr08s06-in-f13.1e100.net (216.58.210.13): icmp_seq=4 ttl=58 
time=356 ms
64 bytes from lhr08s06-in-f13.1e100.net (216.58.210.13): icmp_seq=5 ttl=58 
time=38.0 ms


I have no proxy and I can access the console through my web browser.

Does anyone know what is going on here?

Thanks
```

Original comment by `cad10...@gmail.com` on 8 Oct 2015 at 2:05

**Comment by GoogleCodeExporter** [comment]
```
That's very odd. What's the output of:

    $ python -c "import urllib2; print urllib2.urlopen('https://accounts.google.com').read()"


You should see a bunch of HTML.

Can you post a full stacktrace?
```

Original comment by `z...@google.com` on 8 Oct 2015 at 4:40
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
Thank you for getting back to me.

Annoyingly the problem just seems to have fixed itself at about 4pm my time.

(the traceback is attached)
```

Original comment by `cad10...@gmail.com` on 8 Oct 2015 at 5:52

Attachments:
- [traceback.txt](https://storage.googleapis.com/google-code-attachments/google-cloud-sdk/issue-179/comment-6/traceback.txt)

**Comment by GoogleCodeExporter** [comment]
```
the traceback from earlier today

$ appcfg -V andriod update . --oauth2
02:23 PM Application: stink-tarentino; version: andriod (was: 1000)
02:23 PM Host: appengine.google.com
Traceback (most recent call last):
  File "/home/ciaran/.virtualenvs/swisscom/lib/python2.7/site-packages/google_appengine/appcfg.py", line 127, in <module>
    run_file(__file__, globals())
  File "/home/ciaran/.virtualenvs/swisscom/lib/python2.7/site-packages/google_appengine/appcfg.py", line 123, in run_file
    execfile(_PATHS.script_file(script_name), globals_)
  File "/home/ciaran/.virtualenvs/swisscom/lib/python2.7/site-packages/google_appengine/google/appengine/tools/appcfg.py", line 5397, in <module>
    main(sys.argv)
  File "/home/ciaran/.virtualenvs/swisscom/lib/python2.7/site-packages/google_appengine/google/appengine/tools/appcfg.py", line 5388, in main
    result = AppCfgApp(argv).Run()
  File "/home/ciaran/.virtualenvs/swisscom/lib/python2.7/site-packages/google_appengine/google/appengine/tools/appcfg.py", line 2978, in Run
    self.action(self)
  File "/home/ciaran/.virtualenvs/swisscom/lib/python2.7/site-packages/google_appengine/google/appengine/tools/appcfg.py", line 5044, in __call__
    return method()
  File "/home/ciaran/.virtualenvs/swisscom/lib/python2.7/site-packages/google_appengine/google/appengine/tools/appcfg.py", line 3791, in Update
    self._UpdateWithParsedAppYaml(appyaml, self.basepath)
  File "/home/ciaran/.virtualenvs/swisscom/lib/python2.7/site-packages/google_appengine/google/appengine/tools/appcfg.py", line 3812, in _UpdateWithParsedAppYaml
    updatecheck.CheckForUpdates()
  File "/home/ciaran/.virtualenvs/swisscom/lib/python2.7/site-packages/google_appengine/google/appengine/tools/sdk_update_checker.py", line 243, in CheckForUpdates
    runtime=runtime))
  File "/home/ciaran/.virtualenvs/swisscom/lib/python2.7/site-packages/google_appengine/google/appengine/tools/appengine_rpc_httplib2.py", line 228, in Send
    url, method=method, body=payload, headers=headers)
  File "/home/ciaran/.virtualenvs/swisscom/lib/python2.7/site-packages/google_appengine/lib/httplib2/httplib2/__init__.py", line 1584, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/home/ciaran/.virtualenvs/swisscom/lib/python2.7/site-packages/google_appengine/lib/httplib2/httplib2/__init__.py", line 1332, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/home/ciaran/.virtualenvs/swisscom/lib/python2.7/site-packages/google_appengine/lib/httplib2/httplib2/__init__.py", line 1274, in _conn_request
    raise ServerNotFoundError("Unable to find the server at %s" % conn.host)
httplib2.ServerNotFoundError: Unable to find the server at appengine.google.com
```

Original comment by `cad10...@gmail.com` on 8 Oct 2015 at 5:55

**Comment by GoogleCodeExporter** [comment]
```
Hm...looks like a temporary connectivity hiccup; the Python command worked as 
expected. I don't think it's in a part of the networking stack that we have any 
control over (maybe a DNS problem?), so I think I'm going to close this. 
Re-open if you experience it again.

Thanks for the extra information, and I'm glad it worked itself out.
```

Original comment by `z...@google.com` on 8 Oct 2015 at 5:56
- Changed state: **WontFix**

**Comment by GoogleCodeExporter** [comment]
```
alls well that ends well :)
```

Original comment by `cad10...@gmail.com` on 8 Oct 2015 at 5:57

**Comment by GoogleCodeExporter** [comment]
```
thanks. Alls well that ends well
```

Original comment by `cad10...@gmail.com` on 8 Oct 2015 at 5:57
