### ISSUE TITLE
Mac OSX 10.7.5 - Fatal errors on update and attempted reinstall

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#18]
```
What steps will reproduce the problem?
1. curl https://dl.google.com/dl/cloudsdk/release/install_google_cloud_sdk.bash 
| bash

Manual download and install produces same errors on install.

Install worked fine prior to today's update.   Update fails due to same errors.


curl https://dl.google.com/dl/cloudsdk/release/install_google_cloud_sdk.bash | 
bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3707  100  3707    0     0   5777      0 --:--:-- --:--:-- --:--:-- 17162
curl -f https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz > 
tmp.K8axYW7pd9/google-cloud-sdk.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  332k  100  332k    0     0   339k      0 --:--:-- --:--:-- --:--:--  359k

Directory to extract under (this will create a directory google-cloud-sdk) 
(/Users/username):GoogleCompute
tar -C GoogleCompute -xvf tmp.K8axYW7pd9/google-cloud-sdk.tar.gz
x google-cloud-sdk/
x google-cloud-sdk/.install/
x google-cloud-sdk/.install/core.snapshot.json
x google-cloud-sdk/.install/.download/
x google-cloud-sdk/.install/core.manifest
x google-cloud-sdk/bin/
x google-cloud-sdk/bin/bootstrapping/
x google-cloud-sdk/bin/bootstrapping/.install_configurations
x google-cloud-sdk/bin/bootstrapping/install.py
x google-cloud-sdk/bin/bootstrapping/bootstrapping.py
x google-cloud-sdk/bin/bootstrapping/__init__.py
x google-cloud-sdk/bin/bootstrapping/.default_components
x google-cloud-sdk/bin/bootstrapping/setup.py
x google-cloud-sdk/bin/bootstrapping/prerun.py
x google-cloud-sdk/bin/bootstrapping/print_env_info.py
x google-cloud-sdk/RELEASE_NOTES
x google-cloud-sdk/README
x google-cloud-sdk/lib/
x google-cloud-sdk/lib/argcomplete/
x google-cloud-sdk/lib/argcomplete/my_argparse.py
x google-cloud-sdk/lib/argcomplete/completers.py
x google-cloud-sdk/lib/argcomplete/scripts/
x 
google-cloud-sdk/lib/argcomplete/scripts/python-argcomplete-check-easy-install-s
cript
x google-cloud-sdk/lib/argcomplete/scripts/register-python-argcomplete
x google-cloud-sdk/lib/argcomplete/scripts/activate-global-python-argcomplete
x google-cloud-sdk/lib/argcomplete/__init__.py
x google-cloud-sdk/lib/argcomplete/my_shlex.py
x google-cloud-sdk/lib/google/
x google-cloud-sdk/lib/google/cloud/
x google-cloud-sdk/lib/google/cloud/__init__.py
x google-cloud-sdk/lib/google/cloud/sdk/
x google-cloud-sdk/lib/google/cloud/sdk/gcloud/
x google-cloud-sdk/lib/google/cloud/sdk/gcloud/__init__.py
x google-cloud-sdk/lib/google/cloud/sdk/gcloud/gcloud.yaml
x google-cloud-sdk/lib/google/cloud/sdk/gcloud/gcloud.py
x google-cloud-sdk/lib/google/cloud/sdk/gcloud/sdktools/
x google-cloud-sdk/lib/google/cloud/sdk/gcloud/sdktools/config/
x google-cloud-sdk/lib/google/cloud/sdk/gcloud/sdktools/config/list.py
x google-cloud-sdk/lib/google/cloud/sdk/gcloud/sdktools/config/set.py
x google-cloud-sdk/lib/google/cloud/sdk/gcloud/sdktools/config/unset.py
x google-cloud-sdk/lib/google/cloud/sdk/gcloud/sdktools/config/__init__.py
x google-cloud-sdk/lib/google/cloud/sdk/gcloud/sdktools/root/
x google-cloud-sdk/lib/google/cloud/sdk/gcloud/sdktools/root/interactive.py
x google-cloud-sdk/lib/google/cloud/sdk/gcloud/sdktools/root/version.py
x google-cloud-sdk/lib/google/cloud/sdk/gcloud/sdktools/root/__init__.py
x google-cloud-sdk/lib/google/cloud/sdk/gcloud/sdktools/__init__.py
x google-cloud-sdk/lib/google/cloud/sdk/gcloud/sdktools/auth/
x google-cloud-sdk/lib/google/cloud/sdk/gcloud/sdktools/auth/list.py
x 
google-cloud-sdk/lib/google/cloud/sdk/gcloud/sdktools/auth/enable_google_repos.p
y
x 
google-cloud-sdk/lib/google/cloud/sdk/gcloud/sdktools/auth/activate_refresh_toke
n.py
x google-cloud-sdk/lib/google/cloud/sdk/gcloud/sdktools/auth/__init__.py
x google-cloud-sdk/lib/google/cloud/sdk/gcloud/sdktools/auth/login.py
x google-cloud-sdk/lib/google/cloud/sdk/gcloud/sdktools/auth/revoke.py
x google-cloud-sdk/lib/google/cloud/sdk/gcloud/sdktools/components/
x google-cloud-sdk/lib/google/cloud/sdk/gcloud/sdktools/components/list.py
x google-cloud-sdk/lib/google/cloud/sdk/gcloud/sdktools/components/restore.py
x google-cloud-sdk/lib/google/cloud/sdk/gcloud/sdktools/components/remove.py
x google-cloud-sdk/lib/google/cloud/sdk/gcloud/sdktools/components/__init__.py
x google-cloud-sdk/lib/google/cloud/sdk/gcloud/sdktools/components/update.py
x google-cloud-sdk/lib/google/cloud/sdk/__init__.py
x google-cloud-sdk/lib/google/cloud/sdk/calliope/
x google-cloud-sdk/lib/google/cloud/sdk/calliope/base.py
x google-cloud-sdk/lib/google/cloud/sdk/calliope/actions.py
x google-cloud-sdk/lib/google/cloud/sdk/calliope/__init__.py
x google-cloud-sdk/lib/google/cloud/sdk/calliope/exceptions.py
x google-cloud-sdk/lib/google/cloud/sdk/core/
x google-cloud-sdk/lib/google/cloud/sdk/core/util/
x google-cloud-sdk/lib/google/cloud/sdk/core/util/files.py
x google-cloud-sdk/lib/google/cloud/sdk/core/util/console_io.py
x google-cloud-sdk/lib/google/cloud/sdk/core/util/platforms.py
x google-cloud-sdk/lib/google/cloud/sdk/core/util/__init__.py
x google-cloud-sdk/lib/google/cloud/sdk/core/util/edit.py
x google-cloud-sdk/lib/google/cloud/sdk/core/metrics.py
x google-cloud-sdk/lib/google/cloud/sdk/core/log.py
x google-cloud-sdk/lib/google/cloud/sdk/core/VERSION
x google-cloud-sdk/lib/google/cloud/sdk/core/config.json
x google-cloud-sdk/lib/google/cloud/sdk/core/updater/
x google-cloud-sdk/lib/google/cloud/sdk/core/updater/schemas.py
x google-cloud-sdk/lib/google/cloud/sdk/core/updater/local_state.py
x google-cloud-sdk/lib/google/cloud/sdk/core/updater/update_manager.py
x google-cloud-sdk/lib/google/cloud/sdk/core/updater/__init__.py
x google-cloud-sdk/lib/google/cloud/sdk/core/updater/snapshots.py
x google-cloud-sdk/lib/google/cloud/sdk/core/updater/installers.py
x google-cloud-sdk/lib/google/cloud/sdk/core/cli.py
x google-cloud-sdk/lib/google/cloud/sdk/core/__init__.py
x google-cloud-sdk/lib/google/cloud/sdk/core/credentials/
x google-cloud-sdk/lib/google/cloud/sdk/core/credentials/flow.py
x google-cloud-sdk/lib/google/cloud/sdk/core/credentials/__init__.py
x google-cloud-sdk/lib/google/cloud/sdk/core/credentials/gitp2d.py
x google-cloud-sdk/lib/google/cloud/sdk/core/credentials/oauth2_landing.html
x google-cloud-sdk/lib/google/cloud/sdk/core/credentials/store.py
x google-cloud-sdk/lib/google/cloud/sdk/core/credentials/gce.py
x google-cloud-sdk/lib/google/cloud/sdk/core/credentials/legacy.py
x google-cloud-sdk/lib/google/cloud/sdk/core/config.py
x google-cloud-sdk/lib/google/cloud/sdk/core/properties.py
x google-cloud-sdk/lib/google/__init__.py
x google-cloud-sdk/lib/google/apputils/
x google-cloud-sdk/lib/google/apputils/setup_command.py
x google-cloud-sdk/lib/google/apputils/debug.py
x google-cloud-sdk/lib/google/apputils/basetest.py
x google-cloud-sdk/lib/google/apputils/app.py
x google-cloud-sdk/lib/google/apputils/file_util.py
x google-cloud-sdk/lib/google/apputils/__init__.py
x google-cloud-sdk/lib/google/apputils/shellutil.py
x google-cloud-sdk/lib/google/apputils/datelib.py
x google-cloud-sdk/lib/google/apputils/appcommands.py
x google-cloud-sdk/lib/google/apputils/run_script_module.py
x google-cloud-sdk/lib/google/apputils/resources.py
x google-cloud-sdk/lib/google/apputils/stopwatch.py
x google-cloud-sdk/lib/oauth2/
x google-cloud-sdk/lib/oauth2/__init__.py
x google-cloud-sdk/lib/yaml/
x google-cloud-sdk/lib/yaml/serializer.py
x google-cloud-sdk/lib/yaml/resolver.py
x google-cloud-sdk/lib/yaml/events.py
x google-cloud-sdk/lib/yaml/nodes.py
x google-cloud-sdk/lib/yaml/loader.py
x google-cloud-sdk/lib/yaml/representer.py
x google-cloud-sdk/lib/yaml/parser.py
x google-cloud-sdk/lib/yaml/emitter.py
x google-cloud-sdk/lib/yaml/__init__.py
x google-cloud-sdk/lib/yaml/cyaml.py
x google-cloud-sdk/lib/yaml/dumper.py
x google-cloud-sdk/lib/yaml/composer.py
x google-cloud-sdk/lib/yaml/reader.py
x google-cloud-sdk/lib/yaml/scanner.py
x google-cloud-sdk/lib/yaml/tokens.py
x google-cloud-sdk/lib/yaml/constructor.py
x google-cloud-sdk/lib/yaml/error.py
x google-cloud-sdk/lib/oauth2client/
x google-cloud-sdk/lib/oauth2client/clientsecrets.py
x google-cloud-sdk/lib/oauth2client/django_orm.py
x google-cloud-sdk/lib/oauth2client/appengine.py
x google-cloud-sdk/lib/oauth2client/tools.py
x google-cloud-sdk/lib/oauth2client/__init__.py
x google-cloud-sdk/lib/oauth2client/old_run.py
x google-cloud-sdk/lib/oauth2client/file.py
x google-cloud-sdk/lib/oauth2client/multistore_file.py
x google-cloud-sdk/lib/oauth2client/anyjson.py
x google-cloud-sdk/lib/oauth2client/keyring_storage.py
x google-cloud-sdk/lib/oauth2client/gce.py
x google-cloud-sdk/lib/oauth2client/locked_file.py
x google-cloud-sdk/lib/oauth2client/crypt.py
x google-cloud-sdk/lib/oauth2client/client.py
x google-cloud-sdk/lib/oauth2client/util.py
x google-cloud-sdk/lib/oauth2client/xsrfutil.py
x google-cloud-sdk/lib/socks/
x google-cloud-sdk/lib/socks/__init__.py
x google-cloud-sdk/lib/httplib2/
x google-cloud-sdk/lib/httplib2/iri2uri.py
x google-cloud-sdk/lib/httplib2/__init__.py
x google-cloud-sdk/lib/httplib2/LICENSE
x google-cloud-sdk/lib/httplib2/cacerts.txt
x google-cloud-sdk/lib/uritemplate/
x google-cloud-sdk/lib/uritemplate/uritemplate.py
x google-cloud-sdk/lib/uritemplate/__init__.py
x google-cloud-sdk/lib/apiclient/
x google-cloud-sdk/lib/apiclient/mimeparse.py
x google-cloud-sdk/lib/apiclient/http.py
x google-cloud-sdk/lib/apiclient/oauth.py
x google-cloud-sdk/lib/apiclient/__init__.py
x google-cloud-sdk/lib/apiclient/model.py
x google-cloud-sdk/lib/apiclient/push.py
x google-cloud-sdk/lib/apiclient/channel.py
x google-cloud-sdk/lib/apiclient/errors.py
x google-cloud-sdk/lib/apiclient/discovery.py
x google-cloud-sdk/lib/apiclient/schema.py
x google-cloud-sdk/lib/gflags/
x google-cloud-sdk/lib/gflags/ChangeLog
x google-cloud-sdk/lib/gflags/setup.cfg
x google-cloud-sdk/lib/gflags/MANIFEST.in
x google-cloud-sdk/lib/gflags/gflags2man.py
x google-cloud-sdk/lib/gflags/gflags_validators.py
x google-cloud-sdk/lib/gflags/README
x google-cloud-sdk/lib/gflags/__init__.py
x google-cloud-sdk/lib/gflags/NEWS
x google-cloud-sdk/lib/gflags/PKG-INFO
x google-cloud-sdk/lib/gflags/Makefile
x google-cloud-sdk/lib/gflags/setup.py
x google-cloud-sdk/lib/gflags/AUTHORS
x google-cloud-sdk/lib/gflags/COPYING
x google-cloud-sdk/lib/gflags/LICENSE
x google-cloud-sdk/install.sh
x google-cloud-sdk/install.bat
x google-cloud-sdk/LICENSE

GoogleCompute/google-cloud-sdk/install.sh
Welcome to the Google Cloud SDK!

The Google Cloud SDK is currently in developer preview. To help improve the
quality of this product, we collect anonymized data on how the SDK is used.
You may choose to opt out of this collection now (by choosing 'N' at the below
prompt), or at any time in the future by running the following command:
    gcloud config --global-only set disable_usage_reporting true

Do you want to help improve the Google Cloud SDK (Y/n)?  y


This will install all the core command line tools necessary for working with
the Google Cloud Platform.

If you are developing an App Engine application, please select the 
language your application is written in.  This will install the 
required tools and runtimes for working in that language.  If 
necessary, you can add and remove languages later through the gcloud 
component manager.
  [1]  Java
  [2]  Python and PHP
  [3]  Go
  [4]  No App Engine (you can install App Engine tools later)
Please enter your numeric choice (4):  2


The following components will be installed:
    -------------------------------------------------------------------------------
    | App Engine Launcher Application for Mac              |      1.8.9 |  7.4 MB |
    | App Engine SDK for Python and PHP                    |      1.8.9 | 35.4 MB |
    | Big Query Command Line Tool                          |     2.0.17 |  < 1 MB |
    | Big Query Command Line Tool (Platform Specific)      |     2.0.17 |  < 1 MB |
    | Cloud SDK Core Command Line Tools                    |          1 |         |
    | Cloud SDK Core Libraries (Platform Specific)         | 2013.11.19 |  < 1 MB |
    | Cloud SDK for Python and PHP Developers              |          1 |         |
    | Cloud SQL Admin Command Line Interface               | 2013.12.17 |  < 1 MB |
    | Cloud Storage Command Line Tool                      |       3.40 |  1.7 MB |
    | Cloud Storage Command Line Tool (Platform Specific)  |       3.40 |  < 1 MB |
    | Compute Engine Command Line Tool                     |     1.13.0 |  < 1 MB |
    | Compute Engine Command Line Tool (Platform Specific) |     1.13.0 |  < 1 MB |
    -------------------------------------------------------------------------------

Creating update staging area...


Installing: App Engine Launcher Application for Mac ... Traceback (most recent 
call last):
  File "/Users/username/GoogleCompute/GoogleCompute/google-cloud-sdk/bin/bootstrapping/install.py", line 283, in <module>
    Install(pargs.disable_installation_options)
  File "/Users/username/GoogleCompute/GoogleCompute/google-cloud-sdk/bin/bootstrapping/install.py", line 247, in Install
    components = InstallComponents(to_install)
  File "/Users/username/GoogleCompute/GoogleCompute/google-cloud-sdk/bin/bootstrapping/install.py", line 269, in InstallComponents
    components.update(component_ids=component_ids, allow_no_backup=True)
  File "/Users/username/GoogleCompute/GoogleCompute/google-cloud-sdk/bin/bootstrapping/../../lib/google/cloud/sdk/calliope/__init__.py", line 925, in __call__
    return self._Execute(cli_mode=False, kwargs=kwargs)
  File "/Users/username/GoogleCompute/GoogleCompute/google-cloud-sdk/bin/bootstrapping/../../lib/google/cloud/sdk/calliope/__init__.py", line 960, in _Execute
    cli_mode=cli_mode)
  File "/Users/username/GoogleCompute/GoogleCompute/google-cloud-sdk/bin/bootstrapping/../../lib/google/cloud/sdk/calliope/__init__.py", line 702, in Run
    result = command_instance.Run(args)
  File "/Users/username/GoogleCompute/GoogleCompute/google-cloud-sdk/bin/bootstrapping/../../lib/google/cloud/sdk/gcloud/sdktools/components/update.py", line 38, in Run
    manager.Update(args.component_ids, allow_no_backup=args.allow_no_backup)
  File "/Users/username/GoogleCompute/GoogleCompute/google-cloud-sdk/bin/bootstrapping/../../lib/google/cloud/sdk/core/updater/update_manager.py", line 88, in _TryFunc
    return func(*args, **kwargs)
  File "/Users/username/GoogleCompute/GoogleCompute/google-cloud-sdk/bin/bootstrapping/../../lib/google/cloud/sdk/core/updater/update_manager.py", line 465, in Update
    self._InstallFunction(staging_state, diff))
  File "/Users/username/GoogleCompute/GoogleCompute/google-cloud-sdk/bin/bootstrapping/../../lib/google/cloud/sdk/core/updater/update_manager.py", line 377, in _UpdateAndPrint
    action_func(component.id)
  File "/Users/username/GoogleCompute/GoogleCompute/google-cloud-sdk/bin/bootstrapping/../../lib/google/cloud/sdk/core/updater/update_manager.py", line 384, in Inner
    return install_state.Install(diff.latest, component_id)
  File "/Users/username/GoogleCompute/GoogleCompute/google-cloud-sdk/bin/bootstrapping/../../lib/google/cloud/sdk/core/updater/local_state.py", line 73, in _TryFunc
    return func(*args, **kwargs)
  File "/Users/username/GoogleCompute/GoogleCompute/google-cloud-sdk/bin/bootstrapping/../../lib/google/cloud/sdk/core/updater/local_state.py", line 409, in Install
    files = self._GetInstaller(snapshot).Install(component_id)
  File "/Users/username/GoogleCompute/GoogleCompute/google-cloud-sdk/bin/bootstrapping/../../lib/google/cloud/sdk/core/updater/installers.py", line 78, in Install
    return self._InstallTar(component)
  File "/Users/username/GoogleCompute/GoogleCompute/google-cloud-sdk/bin/bootstrapping/../../lib/google/cloud/sdk/core/updater/installers.py", line 115, in _InstallTar
    url, self.__download_directory, self.__sdk_root)
  File "/Users/username/GoogleCompute/GoogleCompute/google-cloud-sdk/bin/bootstrapping/../../lib/google/cloud/sdk/core/updater/installers.py", line 146, in DownloadAndExtractTar
    with file_utils.Context(tarfile.open(name=download_file_path)) as tar:
AttributeError: 'module' object has no attribute 'open'

```

Original issue reported on code.google.com by `brads...@gmail.com` on 16 Jan 2014 at 4:32

**Comment by GoogleCodeExporter** [comment]
```
Results in same error when using sudo as well.
```

Original comment by `brads...@gmail.com` on 16 Jan 2014 at 11:08

**Comment by GoogleCodeExporter** [comment]
```
If you install ActiveState python and change system path ordering to override 
Apple's built-in python, then installation is clean and successful.  But 
installation was easy, clean, and successful prior to the 01-15-14 update, 
without having to install another python interpreter...
```

Original comment by `brads...@gmail.com` on 16 Jan 2014 at 5:28

**Comment by GoogleCodeExporter** [comment]
```
This is a strange error to be getting from tarfile which is a standard module.  
Can we get some more information about your Python environment (the standard 
OSX Python, not the ActiveState one)?  Please run the following in a Python 
shell and send the output:

import sys
import tarfile

print sys.version
print sys.path
print tarfile.__file__
print tarfile.__version__

```

Original comment by `markp...@google.com` on 16 Jan 2014 at 6:26

**Comment by GoogleCodeExporter** [comment]
```
$ which python
/usr/bin/python

$ /usr/bin/python
Python 2.7.1 (r271:86832, Aug  5 2011, 03:30:24) 
[GCC 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2335.15.00)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> import tarfile
>>> 
>>> print sys.version
2.7.1 (r271:86832, Aug  5 2011, 03:30:24) 
[GCC 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2335.15.00)]
>>> print sys.path
['', 
'/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip', 
'/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7', 
'/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-dar
win', 
'/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac
', 
'/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac
/lib-scriptpackages', 
'/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python', 
'/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk',

'/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old'
, 
'/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynl
oad', 
'/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyOb
jC', '/Library/Python/2.7/site-packages']
>>> print tarfile.__file__
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tarfile.p
yc
>>> print tarfile.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute '__version__'
>>> 

```

Original comment by `brads...@gmail.com` on 16 Jan 2014 at 7:20

**Comment by GoogleCodeExporter** [comment]
```
The fact that it does not have a version is concerning.  Can you attach the 
entire file: 
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tarfile.p
y

this bug so we can have a look?
```

Original comment by `markp...@google.com` on 16 Jan 2014 at 7:56

**Comment by GoogleCodeExporter** [comment]
```
Only tarfile.pyc and tarfile.pyo versions are present, no .py...
```

Original comment by `brads...@gmail.com` on 16 Jan 2014 at 8:03

Attachments:
- [tarfile.pyc](https://storage.googleapis.com/google-code-attachments/google-cloud-sdk/issue-18/comment-6/tarfile.pyc)
- [tarfile.pyo](https://storage.googleapis.com/google-code-attachments/google-cloud-sdk/issue-18/comment-6/tarfile.pyo)

**Comment by GoogleCodeExporter** [comment]
```
The lack of a .py file is a problem because it means Python has no choice but 
to look at the binary .pyc.  Your tarfile.pyc is invalid (look at how small it 
is compared to the .pyo).  If you import it in Python and do a dir() it has no 
methods or classes at all.

Not sure how this used to work you (maybe you were using a different version of 
python or maybe it got corrupted at some point in the middle?).  Best bet is to 
use your new Python runtime, or try to repair this one.
```

Original comment by `markp...@google.com` on 16 Jan 2014 at 9:26
- Changed state: **Invalid**

**Comment by GoogleCodeExporter** [comment]
```
I may have inadvertently corrupted tarfile.pyc in an attempt to resolve the 
issue.  At one point yesterday, I touched tarfile.py, creating an empty file.  
It may have generated a tarfile.pyc from that empty file.

Apple apparently does not ship .py's, there's not a single .py file present in 
the directory.

There was no problem whatsoever with my google cloud sdk prior to 01-15-14.   I 
installed cleanly on 01-10-14, with just stock Apple python.

I was tired of being nagged by "upgrade" sdk messages yesterday, so I complied 
and updated.  The update didn't work, period.  Nor did a clean install.  


```

Original comment by `brads...@gmail.com` on 16 Jan 2014 at 9:51
