### ISSUE TITLE
`gcloud compute config-ssh` failing with strack trace on Windows

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#187]
```
What steps will reproduce the problem?

1. Did gcloud compute config-ssh once.
2. Added a VM.
3. Tried to run gcloud compute config-ssh again to update my settings.

What is the expected output? What do you see instead?

I expected it to update my config or tell me I need to run another command if I 
just have to update it.


Please provide any additional information below.


The output of 'gcloud info':

Google Cloud SDK [0.9.70]

Platform: [Windows, x86_64]
Python Version: [2.7.6 (default, Nov 10 2013, 19:24:24) [MSC v.1500 64 bit 
(AMD64)]]
Site Packages: [Disabled]

Installation Root: [C:\Program Files\Google\Cloud SDK\google-cloud-sdk]
Installed Components:
  core: [2015.07.16]
  bq-win: [2.0.18]
  core-win: [2015.06.02]
  gcloud: [2015.07.16]
  windows-ssh-tools: [2015.06.02]
  gsutil: [4.13]
  gsutil-win: [4.12]
  bq: [2.0.18]
System PATH: [C:\Program Files\Google\Cloud 
SDK\google-cloud-sdk\bin\..\bin\sdk;C:\ProgramData\Oracle\Java\javapath;C:\Progr
am Files (x86)\Common Files\Microsoft Shared\Windows 
Live;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32
\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Microsoft SQL 
Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL 
Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL 
Server\100\DTS\Binn\;C:\Program Files (x86)\Autodesk\Backburner\;C:\Program 
Files\Common Files\Autodesk Shared\;C:\Program Files\TortoiseSVN\bin;C:\Program 
Files (x86)\QuickTime\QTSystem\;C:\Program Files (x86)\NVIDIA 
Corporation\PhysX\Common;C:\Program Files\Google\Cloud 
SDK\google-cloud-sdk\bin;C:\Program Files\Common Files\Microsoft Shared\Windows 
Live;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files 
(x86)\Nmap]
Cloud SDK on PATH: [True]

[output truncated]

```

Original issue reported on code.google.com by `ch...@upswing.io` on 4 Aug 2015 at 3:15

**Comment by GoogleCodeExporter** [comment]
```
Did gcloud compute config-ssh worked for you after step 1?

Does not look like this command is supported on Windows.
```

Original comment by `che...@google.com` on 4 Aug 2015 at 8:23

**Comment by GoogleCodeExporter** [comment]
```
Yes step 1 worked the first time. It created the configurations for my 
instances at the time.  It was only after running it the second time with newly 
added instances did I get this error.
```

Original comment by `ch...@upswing.io` on 4 Aug 2015 at 8:25

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the update.

> It created the configurations for my instances at the time.

So you were able to use
  gcloud compute ssh <alias>

> It was only after running it the second time with newly added instances did I 
get this error.

Can you copy paste the error into this report?

```

Original comment by `che...@google.com` on 4 Aug 2015 at 8:53

**Comment by GoogleCodeExporter** [comment]
```
Yes, I was able to use gcloud compute ssh <alias>. I was also able to ssh using 
the hostnames that gcloud compute config-ssh setup for me in my .ssh/config 
file.

The error I received from the config-ssh command the second time I ran it with 
the updated settings was:

Traceback (most recent call last):
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\gcloud\gcloud.py", line 195, in main
    _cli.Execute()
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\cli.py", line 548, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\backend.py", line 1102, in Run
    result = command_instance.Run(args)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\lib\googlecloudsdk\compute\subcommands\config_ssh.py", line 194, in Run
    new_content = re.sub(section_re, compute_section, existing_content)
  File "C:\python27_x64\lib\re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "C:\python27_x64\lib\re.py", line 270, in _subx
    template = _compile_repl(template, pattern)
  File "C:\python27_x64\lib\re.py", line 257, in _compile_repl
    raise error, v # invalid expression
error: missing group name

If you would like to report this issue, please run the following command:
  gcloud feedback


I used the gcloud feedback command to create this issue, but I guess it didn't 
copy the actual exception that occurred. It could be as simple as my leaving 
off some required parameter, but I couldn't find anything referencing group in 
my quick glance, and also figured that it shouldn't throw an exception if it 
was simply a missed parameter.
```

Original comment by `ch...@upswing.io` on 5 Aug 2015 at 12:52

**Comment by GoogleCodeExporter** [comment]
```
Just updated the sdk hoping that it might have fixed the issue. It did not, but 
did notice the line number change for the most recent function call. Here is 
the most recent stack trace:

Traceback (most recent call last):
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\gcloud\gcloud.py", line 193, in main
    _cli.Execute()
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\cli.py", line 548, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\backend.py", line 1102, in Run
    result = command_instance.Run(args)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\compute\subcommands\config_ssh.py", line 194, in Run
    new_content = re.sub(section_re, compute_section, existing_content)
  File "C:\python27_x64\lib\re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "C:\python27_x64\lib\re.py", line 270, in _subx
    template = _compile_repl(template, pattern)
  File "C:\python27_x64\lib\re.py", line 257, in _compile_repl
    raise error, v # invalid expression
error: missing group name

```

Original comment by `ch...@upswing.io` on 5 Aug 2015 at 7:52

**Comment by GoogleCodeExporter** [comment]
```
I had this happen where I tried to config-ssh for a second project after 
already having setup one. I found a work around where doing a "gcloud compute 
config-ssh --remove" allowed me to successfully setup the second project. Which 
leaves me doing this every time I bounce between projects if I want to have the 
ssh aliases.
```

Original comment by `TheGreat...@gmail.com` on 20 Aug 2015 at 7:33

**Comment by GoogleCodeExporter** [comment]
```
Obviously the gcloud exceptions shouldn't be happening.  We'll look into this 
further. 
```

Original comment by `jeffvaughan@google.com` on 24 Aug 2015 at 5:29
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
Original comment by `jeffvaughan@google.com` on 24 Aug 2015 at 5:30
- Changed title: **`gcloud compute config-ssh` failing with strack trace on Windows**

**Comment by GoogleCodeExporter** [comment]
```
Here is a workaround you can try to see if it fixes your problem.

Edit "C:\Program Files\Google\Cloud 
SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\compute\subcommands\config_ssh.
py"
line 194 should be:
new_content = re.sub(section_re, compute_section, existing_content)
change it to:
new_content = re.sub(section_re, re.escape(compute_section), existing_content)

thanks
```

Original comment by `gsfow...@google.com` on 26 Aug 2015 at 6:17

**Comment by GoogleCodeExporter** [comment]
```
That workaround will not work but we have a fix in testing. Thanks.
```

Original comment by `gsfow...@google.com` on 27 Aug 2015 at 9:00

**Comment by GoogleCodeExporter** [comment]
```
This should be fixed now. Please re-open if it's not.
```

Original comment by `z...@google.com` on 13 Oct 2015 at 3:30
- Changed state: **Fixed**
