### ISSUE TITLE
Cloning SQL instance from specific bin log position using gcloud CLI does not work

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#201]
```
What steps will reproduce the problem?
Use Google Cloud SDK CLI to try to clone an sql instance from a specific bin 
log position, i.e.:
gcloud sql instances clone SRC TARGET --bin-log-file BINLOGFILE 
--bin-log-position BINLOGPOS


What is the expected output? What do you see instead?
Expected output would be to see the operation starting, instead I get a python 
error trace:
Traceback (most recent call last):
  File "/Users/joel/google-cloud-sdk/./lib/googlecloudsdk/gcloud/gcloud.py", line 193, in main
    _cli.Execute()
  File "/Users/joel/google-cloud-sdk/./lib/googlecloudsdk/calliope/cli.py", line 548, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "/Users/joel/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 1102, in Run
    result = command_instance.Run(args)
  File "/Users/joel/google-cloud-sdk/./lib/googlecloudsdk/sql/util.py", line 229, in Func
    return foo(*args, **kwargs)
  File "/Users/joel/google-cloud-sdk/./lib/googlecloudsdk/sql/tools/instances/clone.py", line 112, in Run
    binLogPosition=args.bin_log_position)
AttributeError: 'SqlInstancesCloneRequest' object has no attribute 
'cloneContext'

If you would like to report this issue, please run the following command:
  gcloud feedback



Please provide any additional information below.


The output of 'gcloud info':

Google Cloud SDK [0.9.71]

Platform: [Mac OS X, x86_64]
Python Version: [2.7.10 (default, Jul  3 2015, 01:23:30)  [GCC 4.2.1 Compatible 
Apple LLVM 6.1.0 (clang-602.0.53)]]
Site Packages: [Disabled]

Installation Root: [/Users/joel/google-cloud-sdk]
Installed Components:
  core: [2015.07.24]
  core-nix: [2015.06.02]
  gcloud: [2015.07.24]
  gsutil-nix: [4.12]
  gsutil: [4.13]
  bq: [2.0.18]
  bq-nix: [2.0.18]
System PATH: 
[/Users/joel/google-cloud-sdk/bin:/Users/joel/go_appengine:/Users/joel/.rbenv/sh
ims:/Users/joel/Repos/cocos2d-js-v3.1/tools/cocos2d-console/bin:/Users/joel/go:/
usr/local/share/npm/bin:/usr/local/heroku/bin:/usr/local/sbin:/usr/local/bin:/us
r/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin]
Cloud SDK on PATH: [True]

Installation Properties: [/Users/joel/google-cloud-sdk/properties]
User Config Directory: [/Users/joel/.config/gcloud]
User Properties: [/Users/joel/.config/gcloud/properties]
Current Workspace: [None]
Workspace Config Directory: [None]
Workspace Properties: [None]

Account: [joel.bonander@a3j.se]
Project: [inner-rhythm-89014]

Current Properties:
  [core]
    project: [inner-rhythm-89014]
    account: [joel.bonander@a3j.se]
    disable_usage_reporting: [True]

Logs Directory: [/Users/joel/.config/gcloud/logs]
Last Log File: [/Users/joel/.config/gcloud/logs/2015.08.12/11.05.23.825294.log]

```

Original issue reported on code.google.com by `joel.bon...@a3j.se` on 12 Aug 2015 at 9:11

Attachments:
- [11.05.23.825294.log](https://storage.googleapis.com/google-code-attachments/google-cloud-sdk/issue-201/comment-0/11.05.23.825294.log)

**Comment by GoogleCodeExporter** [comment]
```
Hi,
Has there been any progress on this, i am also facing the same issue as i was 
planning to use Cloud Mysql in my production, but this might cause me to try 
other options or if there is a way around then please let me know.

Regards,
Pradeep
```

Original comment by `pradam.p...@gmail.com` on 3 Oct 2015 at 3:38

**Comment by GoogleCodeExporter** [comment]
```
This issue should be fixed in Cloud SDK version 0.9.82 or 0.9.83.

Sorry that it took us so long to get around to this.
```

Original comment by `z...@google.com` on 5 Oct 2015 at 2:17
- Changed state: **Accepted**
