### ISSUE TITLE
Issue running command [gcloud beta emulators datastore env]

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#212]
```
Issue running command [gcloud beta emulators datastore env].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "calliope/cli.py", line 563, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "calliope/backend.py", line 1121, in Run
    result = command_instance.Run(args)
  File "emulators/commands/datastore/env_init.py", line 22, in Run
    return util.ReadEnvYaml(args.data_dir)
  File "emulators/lib/util.py", line 86, in ReadEnvYaml
    with files.Context(open(env_file_path, 'r')) as env_file:
IOError: [Errno 2] No such file or directory: 
'/Users/<user>/.config/gcloud/emulators/datastore/env.yaml'

Installation information:

Google Cloud SDK [0.9.74]

Platform: [Mac OS X, x86_64]
Python Version: [2.7.10 (default, May 29 2015, 06:32:40)  [GCC 4.2.1 Compatible 
Apple LLVM 6.1.0 (clang-602.0.53)]]
Site Packages: [Disabled]

Installation Root: [/Applications/google-cloud-sdk]
Installed Components:
  core: [2015.08.17]
  app-engine-python: [1.9.25]
  core-nix: [2015.06.02]
  kubectl: []
  app-engine-java: [1.9.25]
  gcloud: [2015.08.17]
  gsutil-nix: [4.12]
  bq-nix: [2.0.18]
  app-engine-python-extras: [1.9.21]
  beta: [2015.08.17]
  gsutil: [4.13]
  bq: [2.0.18]
  alpha: [2015.08.17]
  gcd-emulator: [v1beta2-3.0.0]
  preview: [2015.08.17]
  app: [2015.08.17]
  kubectl-darwin-x86_64: [1.0.3]
[output truncated]

```

Original issue reported on code.google.com by `morit...@google.com` on 20 Aug 2015 at 12:37

**Comment by GoogleCodeExporter** [comment]
```
Thanks for reporting this. This issue arises when the env-init command is 
executed without ever starting the emulator. We will put in a fix that checks 
for this condition and displays an appropriate message.
```

Original comment by `vil...@google.com` on 20 Aug 2015 at 3:30

**Comment by GoogleCodeExporter** [comment]
Original comment by `vil...@google.com` on 20 Aug 2015 at 3:31
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
The fix will be included in the next release.
```

Original comment by `vil...@google.com` on 25 Aug 2015 at 2:36
- Changed state: **Fixed**
