### ISSUE TITLE
gae deployment crash

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#214]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk/calliope/cli.py", line 563, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk/calliope/backend.py", line 1121, in Run
    result = command_instance.Run(args)
  File "googlecloudsdk/appengine/app_commands/deploy.py", line 235, in Run
    client.DeployModule(module, version, info.parsed, info.file)
  File "googlecloudsdk/appengine/lib/appengine_client.py", line 294, in DeployModule
    return appversion.DoUpload()
  File "googlecloudsdk/appengine/lib/appengine_deployments.py", line 1027, in DoUpload
    missing_files = self.Begin()
  File "googlecloudsdk/appengine/lib/appengine_deployments.py", line 629, in Begin
    CloneFiles('/api/appversion/cloneblobs', blobs_to_clone, 'static')
  File "googlecloudsdk/appengine/lib/appengine_deployments.py", line 618, in CloneFiles
    payload=BuildClonePostBody(chunk))
  File "googlecloudsdk/appengine/lib/util.py", line 294, in Send
    result = self.rpcserver.Send(url, payload=payload, **kwargs)
  File "googlecloudsdk/appengine/lib/util.py", line 359, in Send
    response = self._server.Send(*args, **kwargs)
  File "googlecloudsdk/appengine/lib/external/tools/appengine_rpc_httplib2.py", line 229, in Send
    url, method=method, body=payload, headers=headers)
  File "oauth2client/client.py", line 562, in new_request
    redirections, connection_type)
[output truncated]

```

Original issue reported on code.google.com by `luvtheed...@gmail.com` on 20 Aug 2015 at 5:07

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the report.  What version of gcloud did you see this with?  Was 
there other output you can share?
```

Original comment by `jeffvaughan@google.com` on 20 Aug 2015 at 2:27
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 13 Oct 2015 at 3:25
- Changed state: **Invalid**
