### ISSUE TITLE
Running command [gcloud preview app deploy] fails with traceback only, apparently due to network issues 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#216]
```
What steps will reproduce the problem?

$ gcloud preview app deploy app.yaml backend.yaml --project sp-myapp --version 
2-0-0


What is the expected output? What do you see instead?

I expected to see a clean deploy as usual, but instead I get a python error 
traceback only without any clear error message after 30 to 60 seconds as 
follows:


Beginning deployment...
Updating module [default]...done.
Traceback (most recent call last):
  File "/Users/Markuso/google-cloud-sdk/./lib/googlecloudsdk/gcloud/gcloud.py", line 228, in main
    _cli.Execute()
  File "/Users/Markuso/google-cloud-sdk/./lib/googlecloudsdk/calliope/cli.py", line 563, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "/Users/Markuso/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 1121, in Run
    result = command_instance.Run(args)
  File "/Users/Markuso/google-cloud-sdk/./lib/googlecloudsdk/appengine/app_commands/deploy.py", line 235, in Run
    client.DeployModule(module, version, info.parsed, info.file)
  File "/Users/Markuso/google-cloud-sdk/./lib/googlecloudsdk/appengine/lib/appengine_client.py", line 294, in DeployModule
    return appversion.DoUpload()
  File "/Users/Markuso/google-cloud-sdk/./lib/googlecloudsdk/appengine/lib/appengine_deployments.py", line 1034, in DoUpload
    self.Precompile()
  File "/Users/Markuso/google-cloud-sdk/./lib/googlecloudsdk/appengine/lib/appengine_deployments.py", line 688, in Precompile
    files = self.PrecompileBatch(files)
  File "/Users/Markuso/google-cloud-sdk/./lib/googlecloudsdk/appengine/lib/appengine_deployments.py", line 706, in PrecompileBatch
    payload=payload)
  File "/Users/Markuso/google-cloud-sdk/./lib/googlecloudsdk/appengine/lib/util.py", line 294, in Send
    result = self.rpcserver.Send(url, payload=payload, **kwargs)
  File "/Users/Markuso/google-cloud-sdk/./lib/googlecloudsdk/appengine/lib/util.py", line 359, in Send
    response = self._server.Send(*args, **kwargs)
  File "/Users/Markuso/google-cloud-sdk/./lib/googlecloudsdk/appengine/lib/external/tools/appengine_rpc_httplib2.py", line 229, in Send
    url, method=method, body=payload, headers=headers)
  File "/Users/Markuso/google-cloud-sdk/./lib/oauth2client/client.py", line 562, in new_request
    redirections, connection_type)
  File "/Users/Markuso/google-cloud-sdk/./lib/httplib2/__init__.py", line 1608, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/Users/Markuso/google-cloud-sdk/./lib/httplib2/__init__.py", line 1350, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/Users/Markuso/google-cloud-sdk/./lib/httplib2/__init__.py", line 1306, in _conn_request
    response = conn.getresponse()
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1067, in getresponse
    response.begin()
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 409, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 365, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 246, in recv
    return self.read(buflen)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 165, in read
    return self._sslobj.read(len)

If you would like to report this issue, please run the following command:
  gcloud feedback




Please provide any additional information below.

Google Cloud SDK [0.9.74]

Platform: [Mac OS X, x86_64]
Python Version: [2.7.8 (default, Jun 24 2015, 07:11:00)  [GCC 4.2.1 Compatible 
Apple LLVM 6.0 (clang-600.0.57)]]
Site Packages: [Disabled]

Installation Root: [/Users/Markuso/google-cloud-sdk]
Installed Components:
  core: [2015.08.17]
  app-engine-python: [1.9.25]
  core-nix: [2015.06.02]
  app-engine-java: [1.9.25]
  gcloud: [2015.08.17]
  gsutil-nix: [4.12]
  app-engine-python-extras: [1.9.21]
  gsutil: [4.13]
  preview: [2015.08.17]
  app: [2015.08.17]
System PATH: 
[/usr/local/bin:/usr/local/share/python:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/
sbin:/Users/Markuso/google-cloud-sdk/bin]
Cloud SDK on PATH: [True]


```

Original issue reported on code.google.com by `markus.o...@gmail.com` on 23 Aug 2015 at 5:17

**Comment by GoogleCodeExporter** [comment]
```
FYI - this is really urgent for us as we are trying to deploy important fixes 
to our app. So if there is a work around that we can do on our end then please 
share.
```

Original comment by `markus.o...@gmail.com` on 23 Aug 2015 at 5:37

**Comment by GoogleCodeExporter** [comment]
```
Hi Markus,

Thanks for reporting.  Can you please try this command again passing 
`--verbosity debug` and attach the output to this bug?

Cheers,
Jeff
```

Original comment by `jeffvaughan@google.com` on 24 Aug 2015 at 4:35

**Comment by GoogleCodeExporter** [comment]
Original comment by `jeffvaughan@google.com` on 24 Aug 2015 at 4:35
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
Hi Jeff

Thank you for your suggestion. I ran the command with `--verbosity debug` and 
it resulted in a successful deployment. It did output many debug lines on the 
screen but I feel there is no need to attach them here publicly as they contain 
so much of our code and structure.

I am thinking that there was some kind of api endpoint on App Engine that was 
not reachable yesterday through SSL protocol or such.

Thank you again.
Markus
```

Original comment by `markus.o...@gmail.com` on 24 Aug 2015 at 12:22

**Comment by GoogleCodeExporter** [comment]
```
I'm glad it worked but that's super frustrating.  It appears that the exception 
that you were seeing is consistent with networking trouble.  Obvious, the 
output here is a lousy user experience.  We'll work on getting it cleaned up.

I'm updating the title of this bug per this discussion.
```

Original comment by `jeffvaughan@google.com` on 24 Aug 2015 at 2:57
- Changed title: *_Running command [gcloud preview app deploy] can fails with traceback only, apparently due to network issues *_
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
Original comment by `jeffvaughan@google.com` on 24 Aug 2015 at 3:01
- Changed title: *_Running command [gcloud preview app deploy] fails with traceback only, apparently due to network issues *_

**Comment by GoogleCodeExporter** [comment]
```
Please reopen this issue if this error is reoccurs/reproducable.
```

Original comment by `che...@google.com` on 7 Jan 2016 at 3:30
- Changed state: **Obsolete**
