### ISSUE TITLE
gcloud init docker, gcloud init (anything)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#217]
```
Issue running command [gcloud init].

What steps will reproduce the problem?

gcloud init docker, gcloud init (anything)

What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "calliope/cli.py", line 563, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "calliope/backend.py", line 1121, in Run
    result = command_instance.Run(args)
  File "calliope/exceptions.py", line 87, in TryFunc
    return func(*args, **kwargs)
  File "gcloud/sdktools/root/init.py", line 146, in Run
    args.project, workspaces.DEFAULT_REPOSITORY_ALIAS)
  File "core/workspaces.py", line 333, in CloneProjectRepository
    self.CloneGitRepository(uri, alias)
  File "core/workspaces.py", line 197, in GitFunc
    CheckGitVersion((0, 0, 0))
  File "core/workspaces.py", line 146, in CheckGitVersion
    output = compat26.subprocess.check_output(['git', 'version'])
  File "core/util/compat26.py", line 36, in check_output
    raise subprocess.CalledProcessError(p.returncode, cmd, stdout_data)
CalledProcessError: Command '['git', 'version']' returned non-zero exit status 
-11

Installation information:

Google Cloud SDK [0.9.74]

Platform: [Mac OS X, x86]
Python Version: [2.7.1 (r271:86832, Jul 31 2011, 19:30:53)  [GCC 4.2.1 (Based 
on Apple Inc. build 5658) (LLVM build 2335.15.00)]]
Site Packages: [Disabled]

Installation Root: [/Users/jamesbarlow/google-cloud-sdk]
Installed Components:
  core: [2015.08.17]
  core-nix: [2015.06.02]
  gcloud: [2015.08.17]
  gsutil-nix: [4.12]
  gsutil: [4.13]
  bq: [2.0.18]
  bq-nix: [2.0.18]
[output truncated]

============== TRUNCATED INFORMATION (PLEASE CONSIDER INCLUDING) ===============
System PATH: 
[/Users/jamesbarlow/google-cloud-sdk/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/loca
l/bin:/usr/X11/bin:/usr/local/git/bin]
Cloud SDK on PATH: [True]

Installation Properties: [/Users/jamesbarlow/google-cloud-sdk/properties]
User Config Directory: [/Users/jamesbarlow/.config/gcloud]
User Properties: [/Users/jamesbarlow/.config/gcloud/properties]
Current Workspace: [None]
Workspace Config Directory: [None]
Workspace Properties: [None]

Account: [nginxhostingco@gmail.com]
Project: [id]

Current Properties:
  [core]
    project: [id]
    account: [nginxhostingco@gmail.com]
    disable_usage_reporting: [False]

Logs Directory: [/Users/jamesbarlow/.config/gcloud/logs]
Last Log File: 
[/Users/jamesbarlow/.config/gcloud/logs/2015.08.24/01.00.11.985479.log]


```

Original issue reported on code.google.com by `nginxhos...@gmail.com` on 24 Aug 2015 at 5:02

**Comment by GoogleCodeExporter** [comment]
```
gotta check the logs, I have an older mac (only running 10.7).  However I am on 
the terminal 24/7 (have other python based and ruby apps, php/mysql (generally 
a mix of all the above using wordpress) - heck even my vagrant box running node 
with wordpress and multiple app nodes, is running smoothly, not fast, just 
smooth.  No crashing.  So honestly, not sure yet.  
```

Original comment by `nginxhos...@gmail.com` on 24 Aug 2015 at 5:05

**Comment by GoogleCodeExporter** [comment]
```
gcloud should be trying to invoke git from your system path.  What do you get 
if you run `git version` and check out the status code.  I.e.  run the 
following:

  git version
  echo $?
```

Original comment by `jeffvaughan@google.com` on 24 Aug 2015 at 5:20
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
The behavior of `gcloud init` has changed.
```

Original comment by `z...@google.com` on 13 Oct 2015 at 3:28
- Changed state: **Obsolete**
