### ISSUE TITLE
Running gcloud components update Fails with CRC Error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#22]
```
What steps will reproduce the problem?
1.  Run "gcloud components update" on Google dev machine

What is the expected output? What do you see instead?
grindel@deathtongue:~$ gcloud components update
The following components will be updated:
    --------------------------------------------------------------------------------
    | App Engine SDK for Java                              |      1.9.0 | 144.1 MB |
    | Big Query Command Line Tool                          |     2.0.18 |   < 1 MB |
    | Big Query Command Line Tool (Platform Specific)      |     2.0.18 |   < 1 MB |
    | Cloud SDK Core Libraries                             | 2014.03.05 |   < 1 MB |
    | Cloud SDK Core Libraries (Platform Specific)         | 2014.03.05 |   < 1 MB |
    | Cloud SQL Admin Command Line Interface               | 2014.03.05 |   < 1 MB |
    | Cloud Storage Command Line Tool (Platform Specific)  |       3.42 |   < 1 MB |
    | Compute Engine Command Line Tool                     |     1.14.2 |   < 1 MB |
    | Compute Engine Command Line Tool (Platform Specific) |     1.13.0 |   < 1 MB |
    --------------------------------------------------------------------------------
Do you want to continue (Y/n)?
Creating update staging area...
Uninstalling: App Engine SDK for Java ... Done 
Uninstalling: Big Query Command Line Tool ... Done
Uninstalling: Big Query Command Line Tool (Platform Specific) ... Done
Uninstalling: Cloud SDK Core Libraries ... Done
Uninstalling: Cloud SDK Core Libraries (Platform Specific) ... Done
Uninstalling: Cloud SQL Admin Command Line Interface ... Done
Uninstalling: Cloud Storage Command Line Tool (Platform Specific) ... Done
Uninstalling: Compute Engine Command Line Tool ... Done
Uninstalling: Compute Engine Command Line Tool (Platform Specific) ... Done
Installing: App Engine SDK for Java ... Traceback (most recent call last):
  File "/usr/local/google/home/grindel/google-cloud-sdk/bin/../lib/google/cloud/sdk/gcloud/gcloud.py", line 91, in <module>
    main()
  File "/usr/local/google/home/grindel/google-cloud-sdk/bin/../lib/google/cloud/sdk/gcloud/gcloud.py", line 88, in main
    _loader.Execute()
  File "/usr/local/google/home/grindel/google-cloud-sdk/bin/../lib/google/cloud/sdk/calliope/__init__.py", line 1361, in Execute
    cur._Execute(cli_mode=True, kwargs=kwargs)
  File "/usr/local/google/home/grindel/google-cloud-sdk/bin/../lib/google/cloud/sdk/calliope/__init__.py", line 960, in _Execute
    cli_mode=cli_mode)
  File "/usr/local/google/home/grindel/google-cloud-sdk/bin/../lib/google/cloud/sdk/calliope/__init__.py", line 702, in Run
    result = command_instance.Run(args)
  File "/usr/local/google/home/grindel/google-cloud-sdk/bin/../lib/google/cloud/sdk/gcloud/sdktools/components/update.py", line 38, in Run
    manager.Update(args.component_ids, allow_no_backup=args.allow_no_backup)
  File "/usr/local/google/home/grindel/google-cloud-sdk/bin/../lib/google/cloud/sdk/core/updater/update_manager.py", line 88, in _TryFunc
    return func(*args, **kwargs)
  File "/usr/local/google/home/grindel/google-cloud-sdk/bin/../lib/google/cloud/sdk/core/updater/update_manager.py", line 465, in Update
    self._InstallFunction(staging_state, diff))
 File "/usr/local/google/home/grindel/google-cloud-sdk/bin/../lib/google/cloud/sdk/core/updater/update_manager.py", line 377, in _UpdateAndPrint
    action_func(component.id)
  File "/usr/local/google/home/grindel/google-cloud-sdk/bin/../lib/google/cloud/sdk/core/updater/update_manager.py", line 384, in Inner
    return install_state.Install(diff.latest, component_id)
  File "/usr/local/google/home/grindel/google-cloud-sdk/bin/../lib/google/cloud/sdk/core/updater/local_state.py", line 73, in _TryFunc
    return func(*args, **kwargs)
  File "/usr/local/google/home/grindel/google-cloud-sdk/bin/../lib/google/cloud/sdk/core/updater/local_state.py", line 409, in Install
    files = self._GetInstaller(snapshot).Install(component_id)
  File "/usr/local/google/home/grindel/google-cloud-sdk/bin/../lib/google/cloud/sdk/core/updater/installers.py", line 78, in Install
    return self._InstallTar(component)
  File "/usr/local/google/home/grindel/google-cloud-sdk/bin/../lib/google/cloud/sdk/core/updater/installers.py", line 115, in _InstallTar
    url, self.__download_directory, self.__sdk_root)
  File "/usr/local/google/home/grindel/google-cloud-sdk/bin/../lib/google/cloud/sdk/core/updater/installers.py", line 147, in DownloadAndExtractTar
    tar.extractall(extract_dir)
  File "/usr/lib/python2.7/tarfile.py", line 2048, in extractall
    self.extract(tarinfo, path)
  File "/usr/lib/python2.7/tarfile.py", line 2085, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
  File "/usr/lib/python2.7/tarfile.py", line 2161, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/usr/lib/python2.7/tarfile.py", line 2201, in makefile
    copyfileobj(source, target)
  File "/usr/lib/python2.7/tarfile.py", line 266, in copyfileobj
    shutil.copyfileobj(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 49, in copyfileobj
    buf = fsrc.read(length)
  File "/usr/lib/python2.7/tarfile.py", line 819, in read
    buf += self.fileobj.read(size - len(buf))  
  File "/usr/lib/python2.7/tarfile.py", line 737, in read
    return self.readnormal(size)
  File "/usr/lib/python2.7/tarfile.py", line 746, in readnormal
    return self.fileobj.read(size)
  File "/usr/lib/python2.7/gzip.py", line 256, in read
    self._read(readsize)
  File "/usr/lib/python2.7/gzip.py", line 303, in _read
    self._read_eof()
  File "/usr/lib/python2.7/gzip.py", line 342, in _read_eof
    hex(self.crc)))
IOError: CRC check failed 0x9dc25389 != 0xdbdb271bL

What version of the product are you using? On what operating system?
Goobuntu

grindel@deathtongue:~$ gcloud --version
Google Cloud SDK 0.9.16
Copyright Google Inc. 2013.
bq 2.0.17
bq-nix 2.0.17
core 2014.01.27
core-nix 2014.01.27
gae-java 1.8.9
gae-java-nix 1.8.9
gcutil 1.13.0
gcutil-nix 1.13.0
gsutil 3.42
gsutil-nix 3.42
sql 2014.01.28
There are available updates for some Cloud SDK components.  To 
install them, please run:
 $ gcloud components update

Please provide any additional information below.


```

Original issue reported on code.google.com by `grin...@google.com` on 18 Mar 2014 at 7:25

**Comment by GoogleCodeExporter** [comment]
```
Sounds like the download got corrupted, and the error checking prevented you 
from installing something bad. Try a new download.
```

Original comment by `jasm...@google.com` on 16 Apr 2014 at 5:44
- Changed state: **WontFix**

**Comment by GoogleCodeExporter** [comment]
Original comment by `jasm...@google.com` on 16 Apr 2014 at 5:45
- Changed state: **WorkingAsIntended**
