### ISSUE TITLE
gcloud auth login crash

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#222]
```


Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk/calliope/cli.py", line 580, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk/calliope/backend.py", line 1129, in Run
    result = command_instance.Run(args)
  File "googlecloudsdk/calliope/exceptions.py", line 86, in TryFunc
    return func(*args, **kwargs)
  File "googlecloudsdk/gcloud/sdktools/auth/login.py", line 95, in Run
    creds = self.DoWebFlow(args.launch_browser)
  File "googlecloudsdk/gcloud/sdktools/auth/login.py", line 153, in DoWebFlow
    return c_store.AcquireFromWebFlow(launch_browser=launch_browser)
  File "googlecloudsdk/core/credentials/store.py", line 384, in AcquireFromWebFlow
    http=_Http())
  File "googlecloudsdk/core/credentials/flow.py", line 156, in Run
    credential = flow.step2_exchange(code, http=http)
  File "oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "oauth2client/client.py", line 1993, in step2_exchange
    headers=headers)
  File "httplib2/__init__.py", line 1608, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "httplib2/__init__.py", line 1350, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "httplib2/__init__.py", line 1306, in _conn_request
    response = conn.getresponse()
[output truncated]

```

Original issue reported on code.google.com by `xiaohui....@gmail.com` on 27 Aug 2015 at 7:23
- Merged into: #14

**Comment by GoogleCodeExporter** [comment]
```
Hi there,

Do you mind posting the traceback in its entirety? That will help us debug 
(unfortunately, there's a limit to how long we can post on this issue tracker.

It looks network related:  are you behind a proxy by any chance?
```

Original comment by `z...@google.com` on 27 Aug 2015 at 2:54
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
You are right, I run gcloud behind gfw. Many more Information as bellow:

WARNING: The output of gcloud info is too long to pre-populate the new issue 
form.
WARNING: Truncating included information. Please consider including the 
remainder:
===================================================== TRUNCATED INFORMATION 
(PLEASE CONSIDER INCLUDING) 
======================================================
File 
"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.
py", line 1119, in getresponse
    raise ResponseNotReady()
ResponseNotReady

Installation information:

Google Cloud SDK [0.9.75]

Platform: [Mac OS X, x86_64]
Python Version: [2.7.10 (default, Jul 14 2015, 19:46:27)  [GCC 4.2.1 Compatible 
Apple LLVM 6.0 (clang-600.0.39)]]
Site Packages: [Disabled]

Installation Root: [/Users/xiaohui/tmp/google-cloud-sdk]
Installed Components:
  core: [2015.08.23]
  core-nix: [2015.06.02]
  kubectl: []
  gcloud: [2015.08.23]
  gsutil-nix: [4.12]
  gsutil: [4.13]
  bq: [2.0.18]
  bq-nix: [2.0.18]
  kubectl-darwin-x86_64: [1.0.3]
System PATH: 
[/usr/local/heroku/bin:/Users/xiaohui/tmp/google-cloud-sdk/bin:/usr/local/var/rb
env/shims:/Users/xiaohui/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sb
in:/sbin:/opt/X11/bin:/Users/xiaohui/developer/go/bin]
Cloud SDK on PATH: [True]

Installation Properties: [/Users/xiaohui/tmp/google-cloud-sdk/properties]
User Config Directory: [/Users/xiaohui/.config/gcloud]
User Properties: [/Users/xiaohui/.config/gcloud/properties]
Current Workspace: [None]
Workspace Config Directory: [None]
Workspace Properties: [None]

Account: [xiaohui.zju@gmail.com]
Project: [xiaohui-k8s]

Current Properties:
  [core]
    project: [xiaohui-k8s]
    account: [xiaohui.zju@gmail.com]
    disable_usage_reporting: [True]
  [container]
    cluster: [k8s-test]
  [compute]
    zone: [asia-east1-a]

Logs Directory: [/Users/xiaohui/.config/gcloud/logs]
Last Log File: 
[/Users/xiaohui/.config/gcloud/logs/2015.08.30/09.59.45.186988.log]
================================================================================
=============================================================================
```

Original comment by `xiaohui....@gmail.com` on 30 Aug 2015 at 2:06

Attachments:
- [09.59.45.186988.log](https://storage.googleapis.com/google-code-attachments/google-cloud-sdk/issue-222/comment-2/09.59.45.186988.log)

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 13 Oct 2015 at 3:11
- Changed state: **Duplicate**
