### ISSUE TITLE
Node js Hello world deployment error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#223]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\cli.py", line 580, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\backend.py", line 1129, in Run
    result = command_instance.Run(args)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\appengine\app_commands\deploy.py", line 214, in Run
    implicit_remote_build)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\appengine\lib\deploy_command_util.py", line 71, in BuildAndPushDockerImages
    with docker_util.DockerHost(cli, version_id, remote) as docker_client:
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\appengine\lib\images\docker_util.py", line 206, in __enter__
    self._vm = Provision(self._cli, self._name, self._zone)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\appengine\lib\images\docker_util.py", line 51, in Provision
    vm = _CreateVm(cli, name, zone)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\appengine\lib\images\docker_util.py", line 104, in _CreateVm
    return _Vm(cli, vm_info[0])
[output truncated]

```

Original issue reported on code.google.com by `lakshman...@gmail.com` on 27 Aug 2015 at 7:31

**Comment by GoogleCodeExporter** [comment]
```
Hi there,

Do you mind posting the remaining part of the traceback, along with the output 
of `gcloud info`? This will better help us troubleshoot.

Google Code won't allow pre-populating the "Create Issue" page with comments 
that are too long.
```

Original comment by `z...@google.com` on 27 Aug 2015 at 2:08
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 13 Oct 2015 at 3:15
- Changed state: **Invalid**
