### ISSUE TITLE
Cannot deploy when default shell is tcsh

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#224]
```
When I run

    gcloud preview app deploy --project khan-academy --version znd-150805-csilvers-test-gcloud app.yaml -q --verbosity=debug --bucket gs://ka_deploy/

It says this:

---
[...]
Synchronizing files to [gs://ka_deploy/].
DEBUG: Running command: [/bin/tcsh /home/csilvers/google-cloud-sdk/bin/gsutil 
-m rsync -R -c /tmp/tmpYrLkZZ gs://ka_deploy/], Env: [None]
CLOUDSDK_PYTHON_SITEPACKAGES=1: Command not found.
Badly placed ()'s.
DEBUG: (gcloud.preview.app.deploy) Could not synchronize files. The gsutil 
command exited with status [1].
Traceback (most recent call last):
  File "/home/csilvers/google-cloud-sdk/./lib/googlecloudsdk/calliope/cli.py", line 580, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "/home/csilvers/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 1129, in Run
    result = command_instance.Run(args)
  File "/home/csilvers/google-cloud-sdk/./lib/googlecloudsdk/appengine/app_commands/deploy.py", line 222, in Run
    app_config.Modules().items(), args.bucket)
  File "/home/csilvers/google-cloud-sdk/./lib/googlecloudsdk/appengine/lib/deploy_app_command_util.py", line 50, in CopyFilesToCodeBucket
    '[{s}].').format(s=rsync_exit_code))
ToolException: Could not synchronize files. The gsutil command exited with 
status [1].

---

googlecloudsdk/core/util/execution_utils.GetShellExecutable() prefers to use 
your default shell, which (obviously) does the wrong thing when what you're 
executing is a (bourne) shell script.

I think the solution is to change GetShellExecutable to only search for shells 
that are a superset of sh.  This would probably need to be a hard-coded list, 
e.g. from https://en.wikipedia.org/wiki/Unix_shell#Bourne_shell_compatible or 
http://tangentsoft.net/misc/unix-shells.svg.  At least, I can't find a way to 
programatically tell whether a shell is bourne-compatible or not.
```

Original issue reported on code.google.com by `csilv...@khanacademy.org` on 27 Aug 2015 at 9:47

**Comment by GoogleCodeExporter** [comment]
```
Thanks for reporting this, and thanks for digging into the code enough to let 
us know exactly what we have to fix.

I'll go ahead and implement this change shortly, and make sure that deployment 
works under a csh-derivative shell.
```

Original comment by `z...@google.com` on 27 Aug 2015 at 10:09
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
Targeting a fix for version 0.9.77.

Let me know if you're not able to work around in the meantime.
```

Original comment by `z...@google.com` on 28 Aug 2015 at 8:33

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 12 Oct 2015 at 4:17
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
I am running Google Cloud SDK 0.9.82 and I still see this issue if I don't set 
app/use_appengine_api to false.
```

Original comment by `vi...@wizeline.com` on 19 Oct 2015 at 11:12

**Comment by GoogleCodeExporter** [comment]
```
Is the stack trace identical? Do you mind pasting it?

Are you using tcsh or some other shell?
```

Original comment by `z...@google.com` on 20 Oct 2015 at 2:09
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
And all of the sudden it just worked. Thanks for following up.
```

Original comment by `vi...@wizeline.com` on 20 Oct 2015 at 4:20

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 20 Oct 2015 at 4:54
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Looks like its still here, below is the trace
DEBUG: (gcloud.preview.app.deploy) Could not synchronize files. The gsutil 
command exited with status [1]. Command output is available in 
[/Users/shakirthowseen/.config/gcloud/logs/2015.11.01/21.53.28.242675.log].
Traceback (most recent call last):
  File "/Users/shakirthowseen/Projects/reservedboxapi/Y/google-cloud-sdk/./lib/googlecloudsdk/calliope/cli.py", line 598, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "/Users/shakirthowseen/Projects/reservedboxapi/Y/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 1226, in Run
    resources = command_instance.Run(args)
  File "/Users/shakirthowseen/Projects/reservedboxapi/Y/google-cloud-sdk/./lib/googlecloudsdk/appengine/app_commands/deploy.py", line 274, in Run
    app_config.NonHermeticModules().items(), code_bucket)
  File "/Users/shakirthowseen/Projects/reservedboxapi/Y/google-cloud-sdk/./lib/googlecloudsdk/appengine/lib/deploy_app_command_util.py", line 52, in CopyFilesToCodeBucket
    s=exit_code, l=log.GetLogFilePath()))
ToolException: Could not synchronize files. The gsutil command exited with 
status [1]. Command output is available in 
[/Users/shakirthowseen/.config/gcloud/logs/2015.11.01/21.53.28.242675.log].
ERROR: (gcloud.preview.app.deploy) Could not synchronize files. The gsutil 
command exited with status [1]. Command output is available in 
[/Users/shakirthowseen/.config/gcloud/logs/2015.11.01/21.53.28.242675.log].

```

Original comment by `Shakirt...@gmail.com` on 2 Nov 2015 at 5:58

**Comment by GoogleCodeExporter** [comment]
```
The above bug was because it wasn't able to create a bucket 
"staging.appid.appspot.com", after I verified that I own the domain it worked
```

Original comment by `Shakirt...@gmail.com` on 2 Nov 2015 at 8:41
