### ISSUE TITLE
can't create compute instance

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#226]
```
Issue running command [gcloud compute instances create].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\cli.py", line 580, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\backend.py", line 1129, in Run
    result = command_instance.Run(args)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\compute\lib\base_classes.py", line 870, in Run
    request_protobufs = self.CreateRequests(args)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\compute\subcommands\instances\create.py", line 412, in CreateRequests
    network_interface = self.CreateNetworkInterfaceMessage(args, instance_refs)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\compute\subcommands\instances\create.py", line 347, in CreateNetworkInterfaceMessage
    address = self.ExpandAddressFlag(args, region)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\compute\lib\addresses_utils.py", line 103, in ExpandAddressFlag
    socket.inet_pton(socket.AF_INET6, args.address)
AttributeError: 'module' object has no attribute 'inet_pton'

Installation information:

Google Cloud SDK [0.9.75]

Platform: [Windows, x86_64]
[output truncated]

```

Original issue reported on code.google.com by `t.ogawa...@gmail.com` on 28 Aug 2015 at 11:33
- Merged into: #291

**Comment by GoogleCodeExporter** [comment]
```
C:\Program Files\Google\Cloud SDK>gcloud compute instances create instance1 
--address my-ip --zone us-central1-a --image debian-7 --machine-type 
n1-standard-1
```

Original comment by `t.ogawa...@gmail.com` on 28 Aug 2015 at 11:35

**Comment by GoogleCodeExporter** [comment]
```
I can create compute instance on the Developers Console.
```

Original comment by `t.ogawa...@gmail.com` on 28 Aug 2015 at 11:35

**Comment by GoogleCodeExporter** [comment]
```
Hi there,

What version of Python are you using to run the Cloud SDK? `socket` is a Python 
built-in module, and the `inet_pton` method being missing suggests a corrupted 
Python installation to me.

Copying the output of `gcloud info` here would be very helpful; it contains 
Python installation and more.

Also, do you mind running the command `python.exe -c "import socket; 
socket.inet_pton"` with the Python executable that `gcloud info` shows?
```

Original comment by `z...@google.com` on 28 Aug 2015 at 3:42
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
Issue 248 has been merged into this issue.
```

Original comment by `z...@google.com` on 11 Sep 2015 at 12:13

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 8 Oct 2015 at 4:32
- Changed state: **Duplicate**
