### ISSUE TITLE
crash while trying to access server through ssh

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#227]
```
Issue running command [gcloud compute ssh].

What steps will reproduce the problem?
gcloud compute --project " " ssh --zone "us-central1-a" " "

What is the expected output? What do you see instead?
server login, error


Please provide any additional information below.


Traceback (most recent call last):
  File "calliope/cli.py", line 563, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "calliope/backend.py", line 1121, in Run
    result = command_instance.Run(args)
  File "compute/subcommands/ssh.py", line 114, in Run
    external_ip_address = self.GetInstanceExternalIpAddress(instance_ref)
  File "compute/lib/ssh_utils.py", line 379, in GetInstanceExternalIpAddress
    error_message='Could not fetch instance:')
  File "compute/lib/utils.py", line 95, in RaiseToolException
    RaiseException(problems, calliope_exceptions.ToolException, error_message)
  File "compute/lib/utils.py", line 107, in RaiseException
    errors))
ToolException: Could not fetch instance:
 - The resource 'projects/programming4design' was not found

Installation information:

Google Cloud SDK [0.9.75]

Platform: [Linux, x86_64]
Python Version: [2.7.6 (default, Jun 22 2015, 17:58:13)  [GCC 4.8.2]]
Site Packages: [Disabled]

Installation Root: [/home/tomas/y/google-cloud-sdk]
Installed Components:
  core: [2015.08.23]
  core-nix: [2015.06.02]
  gcloud: [2015.08.23]
  gsutil-nix: [4.12]
  gsutil: [4.13]
  bq: [2.0.18]
  bq-nix: [2.0.18]
System PATH: 
[/home/tomas/y/google-cloud-sdk/bin:/home/tomas/bin:/usr/local/sbin:/usr/local/b
in:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games]
Cloud SDK on PATH: [True]

[output truncated]

```

Original issue reported on code.google.com by `t...@programming4design.com` on 28 Aug 2015 at 1:14

**Comment by GoogleCodeExporter** [comment]
```
Thanks for reaching out.  Typically the message,

  The resource 'projects/programming4design' was not found

indicates either the programming4desgin project doesn't exist or that your 
current account doesn't have permission to to access it.  Can you try the 
following to help troubleshoot?

  -  Run `gcloud config list account` and verify that gcloud has the correct account set?  

  - Verify in http://console.developers.google.com/ that account has access to the programming4design project.

  - Rerrun `gcloud auth login` to refresh your credentials.

Let us know what you find.

Also, I assume the stack trace was provided by `gcloud feedback` and didn't 
show up in your terminal.  Please also let us know if that's not right.
```

Original comment by `jeffvaughan@google.com` on 28 Aug 2015 at 3:09
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 13 Oct 2015 at 3:18
- Changed state: **Invalid**
