### ISSUE TITLE
Error when gcloud compute

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#229]
```
What steps will reproduce the problem?

Cloud sdk , trying to connect to a tomcat server in my project

gcloud compute


What is the expected output? What do you see instead?

To open up a putty session into the tomcat server

Please provide any additional information below.


Traceback (most recent call last):
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\cli.py", line 557, in Execute
    args = self.__parser.parse_args(args)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\backend.py", line 75, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\backend.py", line 66, in parse_known_args
    args, argv = super(ArgumentParser, self).parse_known_args(args, namespace)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\argparse\__init__.py", line 1735, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\argparse\__init__.py", line 1923, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\argparse\__init__.py", line 1900, in consume_positionals
    take_action(action, args)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\argparse\__init__.py", line 1793, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\argparse\__init__.py", line 2229, in _get_values
[output truncated]

```

Original issue reported on code.google.com by `subha.ko...@gmail.com` on 28 Aug 2015 at 9:27

**Comment by GoogleCodeExporter** [comment]
```
Thanks for reporting this. Do you mind posting the whole traceback? It can be 
found in the Cloud SDK log directory, shown by the output of `gcloud info`. 
Unfortunately, Google Code truncates messages that are too long.
```

Original comment by `z...@google.com` on 29 Aug 2015 at 2:50
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 13 Oct 2015 at 3:33
- Changed state: **Invalid**
