### ISSUE TITLE
Getting ResponseNotReady error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#23]
```
I started getting ResponseNotReady messages when attempting to use gcutil after 
a session where I interrupted a --permit_root_ssh session. It might not be 
connected to this so I include the full session so that you can troubleshoot 
the real cause.

Cheers,

Jun


====

$ whoami 
USER
$ sudo su
Password:
sh-3.2# gcutil --permit_root_ssh --service_version="v1" --project="PROJECT" ssh 
"MACHINE"

There are available updates for some Cloud SDK components.  To 
install them, please run:
 $ gcloud components update

INFO: Zone for MACHINE detected as us-central1-a.
INFO: Running command line: ssh -o UserKnownHostsFile=/dev/null -o 
CheckHostIP=no -o StrictHostKeyChecking=no -i 
/var/root/.ssh/google_compute_engine -A -p 22 root@xxx.xxx.xxx.xxx --
Warning: Permanently added 'xxx.xxx.xxx.xxx' (RSA) to the list of known hosts.
SecGenericPasswordCreate failed
Enter passphrase for key '/var/root/.ssh/google_compute_engine': 
Permission denied (publickey).
sh-3.2# exit
exit
$ gcutil --permit_root_ssh --service_version="v1" --project="PROJECT" ssh 
"MACHINE"
^[b
There are available updates for some Cloud SDK components.  To 
install them, please run:
 $ gcloud components update

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 505, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/jun/google-cloud-sdk/bin/bootstrapping/../../lib/google/cloud/sdk/core/metrics.py", line 128, in __Run
    self.__SendEvent(headers, base_params, event)
  File "/Users/jun/google-cloud-sdk/bin/bootstrapping/../../lib/google/cloud/sdk/core/metrics.py", line 156, in __SendEvent
    h.request(_ENDPOINT, method='POST', body=body, headers=headers)
  File "/Users/jun/google-cloud-sdk/bin/bootstrapping/../../lib/httplib2/__init__.py", line 1586, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/Users/jun/google-cloud-sdk/bin/bootstrapping/../../lib/httplib2/__init__.py", line 1333, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/Users/jun/google-cloud-sdk/bin/bootstrapping/../../lib/httplib2/__init__.py", line 1289, in _conn_request
    response = conn.getresponse()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1015, in getresponse
    raise ResponseNotReady()
ResponseNotReady

ResponseNotReady

$ gcutil --service_version="v1" --project="PROJECT" ssh "MACHINE"
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 505, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/jun/google-cloud-sdk/bin/bootstrapping/../../lib/google/cloud/sdk/core/metrics.py", line 128, in __Run
    self.__SendEvent(headers, base_params, event)
  File "/Users/jun/google-cloud-sdk/bin/bootstrapping/../../lib/google/cloud/sdk/core/metrics.py", line 156, in __SendEvent
    h.request(_ENDPOINT, method='POST', body=body, headers=headers)
  File "/Users/jun/google-cloud-sdk/bin/bootstrapping/../../lib/httplib2/__init__.py", line 1586, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/Users/jun/google-cloud-sdk/bin/bootstrapping/../../lib/httplib2/__init__.py", line 1333, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/Users/jun/google-cloud-sdk/bin/bootstrapping/../../lib/httplib2/__init__.py", line 1289, in _conn_request
    response = conn.getresponse()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1015, in getresponse
    raise ResponseNotReady()
ResponseNotReady


There are available updates for some Cloud SDK components.  To 
install them, please run:
 $ gcloud components update

ResponseNotReady

$ gcloud components update

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 505, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/jun/google-cloud-sdk/bin/../lib/google/cloud/sdk/core/metrics.py", line 128, in __Run
    self.__SendEvent(headers, base_params, event)
  File "/Users/jun/google-cloud-sdk/bin/../lib/google/cloud/sdk/core/metrics.py", line 156, in __SendEvent
    h.request(_ENDPOINT, method='POST', body=body, headers=headers)
  File "/Users/jun/google-cloud-sdk/bin/../lib/httplib2/__init__.py", line 1586, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/Users/jun/google-cloud-sdk/bin/../lib/httplib2/__init__.py", line 1333, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/Users/jun/google-cloud-sdk/bin/../lib/httplib2/__init__.py", line 1289, in _conn_request
    response = conn.getresponse()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1015, in getresponse
    raise ResponseNotReady()
ResponseNotReady


The following components will be updated:
    ------------------------------------------------------------------------------
    | Big Query Command Line Tool                          |     2.0.18 | < 1 MB |
    | Big Query Command Line Tool (Platform Specific)      |     2.0.18 | < 1 MB |
    | Cloud SDK Core Libraries                             | 2014.03.05 | < 1 MB |
    | Cloud SDK Core Libraries (Platform Specific)         | 2014.03.05 | < 1 MB |
    | Cloud SQL Admin Command Line Interface               | 2014.03.05 | < 1 MB |
    | Cloud Storage Command Line Tool (Platform Specific)  |       3.42 | < 1 MB |
    | Compute Engine Command Line Tool                     |     1.14.2 | < 1 MB |
    | Compute Engine Command Line Tool (Platform Specific) |     1.13.0 | < 1 MB |
    ------------------------------------------------------------------------------

Do you want to continue (Y/n)?  
Creating update staging area...

Uninstalling: Big Query Command Line Tool ... Done
Uninstalling: Big Query Command Line Tool (Platform Specific) ... Done
Uninstalling: Cloud SDK Core Libraries ... Done
Uninstalling: Cloud SDK Core Libraries (Platform Specific) ... Done
Uninstalling: Cloud SQL Admin Command Line Interface ... Done
Uninstalling: Cloud Storage Command Line Tool (Platform Specific) ... Done
Uninstalling: Compute Engine Command Line Tool ... Done
Uninstalling: Compute Engine Command Line Tool (Platform Specific) ... Done

Installing: Big Query Command Line Tool ... Done
Installing: Big Query Command Line Tool (Platform Specific) ... Done
Installing: Cloud SDK Core Libraries ... Done
Installing: Cloud SDK Core Libraries (Platform Specific) ... Done
Installing: Cloud SQL Admin Command Line Interface ... Done
Installing: Cloud Storage Command Line Tool (Platform Specific) ... Done
Installing: Compute Engine Command Line Tool ... Done
Installing: Compute Engine Command Line Tool (Platform Specific) ... Done

Creating backup and activating new installation...

Done!

$ gcutil --service_version="v1" --project="PROJECT" ssh "MACHINE"
ResponseNotReady

$ gcutil --service_version="v1" --project="PROJECT" ssh --zone="us-central1-a" 
"MACHINE"
ResponseNotReady


```

Original issue reported on code.google.com by `j...@iilab.org` on 19 Mar 2014 at 3:54

**Comment by GoogleCodeExporter** [comment]
```
Hi Jun, sorry for the delayed response.  We have made a lot of changes to 
gcloud as well as gcutil ssh since this bug was filed.  If you are still seeing 
this problem, please re-open the issue.  Also, please check out `gcloud compute 
ssh` which is now the replacement for `gcutil ssh`.
```

Original comment by `markp...@google.com` on 13 Aug 2014 at 9:32
- Changed state: **Obsolete**
