### ISSUE TITLE
I can't publish test project to gcloud.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#232]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "D:\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\cli.py", line 580, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "D:\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\backend.py", line 1129, in Run
    result = command_instance.Run(args)
  File "D:\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\compute\subcommands\copy_files.py", line 126, in Run
    self.ActuallyRun(args, scp_args, user, external_ip_address)
  File "D:\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\compute\lib\ssh_utils.py", line 424, in ActuallyRun
    has_keys = self.EnsureSSHKeyIsInProject(user)
  File "D:\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\compute\lib\ssh_utils.py", line 243, in EnsureSSHKeyIsInProject
    public_key = self.GetPublicKey()
  File "D:\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\compute\lib\ssh_utils.py", line 305, in GetPublicKey
    _RunExecutable(keygen_args)
  File "D:\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\compute\lib\ssh_utils.py", line 113, in _RunExecutable
    raise SshLikeCmdFailed(cmd_args[0], return_code=e.returncode)
[output truncated]



I use windows 8.
the progress is stopped at prompt "Copying certificates for secure access. you 
may be prompted to create an SSH key pair."

I wnat to know the reason and repair it.
```

Original issue reported on code.google.com by `jstein...@gmail.com` on 31 Aug 2015 at 6:01
- Merged into: #228

Attachments:
- [14.48.07.313000.log](https://storage.googleapis.com/google-code-attachments/google-cloud-sdk/issue-232/comment-0/14.48.07.313000.log)

**Comment by GoogleCodeExporter** [comment]
```
As part of the deployment `gcloud preview app deploy` will provision a
Google Compute Engine instance to build the Docker image containing your
Application to be later deployed to Google App Engine.
The tool will prompt you to generate an SSH key pair. This is needed to
establish secure communication with GCE. To do that, it will spawn
ssh-keygen, which in turn will ask you for a password for the private
part of the key pair about to be generated.

Your logs indicate that ssh-keygen exited with an error (return code 1,
see [1]).

Did you get the prompt? It normally says

    Enter passphrase (empty for no passphrase):

and just sits there waiting for your input.

If not, I'd try executing D:\Google\Cloud 
SDK\google-cloud-sdk\bin\sdk\ssh-keygen.EXE
to see whether it works when not being called by gcloud.

[1]: 
https://code.google.com/p/google-cloud-sdk/issues/attachmentText?id=232&aid=2320
000000&name=14.48.07.313000.log&token=ABZ6GAfHBuSamY8dFY1EOC4IKq39TEPUlg%3A14410
28399569#19
```

Original comment by `lorenz.l...@gmail.com` on 31 Aug 2015 at 1:50

**Comment by GoogleCodeExporter** [comment]
```
Thanks for chiming in, Lorenz! Those are good suggestions.

In particular if you run the following command and it succeeds, the deployment 
should be able to proceed:

    D:\Google\Cloud SDK\google-cloud-sdk\bin\sdk\ssh-keygen.EXE -f ~/.ssh/google_compute_engine -t rsa -N ''

Let us know if that doesn't work (if it does, we're tracking the solution in 
issue 228).
```

Original comment by `z...@google.com` on 31 Aug 2015 at 3:48
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
Now I check it again.
The screen message is same previous status. still stop at message "Copying ... 
" (see below)

but, the log message is different previous one.
please check this status.
I can't untill set the prompt. and the ssh-keygen.EXE is work well.

monitor messages
================
C:\gcloud\1-hello-world>gcloud preview app deploy ./app.yaml --set-default
You are about to deploy the following modules:
 - hellojstein/default (from [C:\gcloud\1-hello-world\app.yaml])
     Deployed URL: [https://hellojstein.appspot.com]

Do you want to continue (Y/n)?

Beginning deployment...
Verifying that Managed VMs are enabled and ready.

Provisioning remote build service.
Copying certificates for secure access. You may be prompted to create an SSH key
pair.
============

Thanks for your interest and care.
```

Original comment by `jstein...@gmail.com` on 21 Sep 2015 at 7:09

Attachments:
- [15.43.16.996000.log](https://storage.googleapis.com/google-code-attachments/google-cloud-sdk/issue-232/comment-3/15.43.16.996000.log)

**Comment by GoogleCodeExporter** [comment]
```
Please verify the existence of the following file:

   C:\Users\jstein\.ssh\google_compute_engine

Once you have done that, please try creating a Google Compute Engine VM:

    > gcloud compute instances create --zone=us-central1-f ssh-test

Then, attempt to SSH into it:

    > gcloud compute ssh --zone=us-central1-f ssh-test

Verify that that works. If not, please post the output.

Please make sure to delete it when you're done, so you're not charged for it.
    > gcloud compute instances delete --zone=us-central1-f ssh-test
```

Original comment by `z...@google.com` on 21 Sep 2015 at 12:32

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 13 Oct 2015 at 3:35
- Changed state: **Duplicate**
