### ISSUE TITLE
windows auth login error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#236]
```
Issue running command [gcloud auth login].

What steps will reproduce the problem?
install CLoud SDK
open Cmd and type gcloud auth login
chrome shows up - log to your account and grant required permissions
after submit it crashes


What is the expected output? What do you see instead?
It should log me in


Please provide any additional information below.


Traceback (most recent call last):
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\cli.py", line 580, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\backend.py", line 1129, in Run
    result = command_instance.Run(args)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\exceptions.py", line 86, in TryFunc
    return func(*args, **kwargs)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\gcloud\sdktools\auth\login.py", line 107, in Run
    c_store.Store(creds, account)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\core\credentials\store.py", line 298, in Store
    _GetLegacyGen(account, creds).WriteTemplate()
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\core\credentials\store.py", line 303, in _GetLegacyGen
    multistore_path=config.Paths().LegacyCredentialsMultistorePath(account),
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\core\config.py", line 459, in LegacyCredentialsMultistorePath
    return os.path.join(self.LegacyCredentialsDir(account), 'multistore.json')
[output truncated]

```

Original issue reported on code.google.com by `to...@tylcham.com` on 2 Sep 2015 at 2:41

**Comment by GoogleCodeExporter** [comment]
```
Hi there,

Do you mind posting the rest of the truncated output? (Google Code caps the 
length of a pre-populated issue body).

Are there any non-ASCII characters in your Windows username? How about in the 
directory into which you installed the Cloud SDK?
```

Original comment by `z...@google.com` on 2 Sep 2015 at 2:43
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
Hi,
I have "á" and "š" in my windows username

gcloud command is located here :
C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\gcloud.cmd

This is full output from command line:
C:\Users\Tomáš>gcloud auth login
Your browser has been opened to visit:

    https://accounts.google.com/o/oauth2/auth?redirect_uri=http%3A%2F%2Flocalhos
t%3A8085%2F&prompt=select_account&response_type=code&client_id=32555940559.apps.
googleusercontent.com&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.e
mail+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform+https%3A%2F%2Fwww.
googleapis.com%2Fauth%2Fappengine.admin+https%3A%2F%2Fwww.googleapis.com%2Fauth%
2Fcompute&access_type=offline


Traceback (most recent call last):
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecl
oudsdk\gcloud\gcloud.py", line 228, in main
    _cli.Execute()
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecl
oudsdk\calliope\cli.py", line 580, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecl
oudsdk\calliope\backend.py", line 1129, in Run
    result = command_instance.Run(args)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecl
oudsdk\calliope\exceptions.py", line 86, in TryFunc
    return func(*args, **kwargs)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecl
oudsdk\gcloud\sdktools\auth\login.py", line 107, in Run
    c_store.Store(creds, account)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecl
oudsdk\core\credentials\store.py", line 298, in Store
    _GetLegacyGen(account, creds).WriteTemplate()
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecl
oudsdk\core\credentials\store.py", line 303, in _GetLegacyGen
    multistore_path=config.Paths().LegacyCredentialsMultistorePath(account),
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecl
oudsdk\core\config.py", line 459, in LegacyCredentialsMultistorePath
    return os.path.join(self.LegacyCredentialsDir(account), 'multistore.json')
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecl
oudsdk\core\config.py", line 448, in LegacyCredentialsDir
    return os.path.join(self.global_config_dir, 'legacy_credentials', account)
  File "C:\Python27\lib\ntpath.py", line 108, in join
    path += "\\" + b


If you would like to report this issue, please run the following command:
  gcloud feedback
```

Original comment by `to...@tylcham.com` on 2 Sep 2015 at 3:43

**Comment by GoogleCodeExporter** [comment]
```
Ahh, okay. There's a known issue with configuration directories (which go 
inside of your home directory) with non-ASCII characters. (See also issue #145).

To work around this, you can set the environment variable CLOUDSDK_CONFIG to 
point to a directory that your user can write to that only contains ASCII.

Sorry about the inconvenience. We're working on making the Cloud SDK more 
Unicode-friendly, but will have to make some changes to our testing framework 
in order to shake out all of the bugs.
```

Original comment by `z...@google.com` on 2 Sep 2015 at 6:08
- Changed state: **Accepted**
