### ISSUE TITLE
gcloud init: windows permission denied

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#237]
```
Issue running command [gcloud init].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\cli.py", line 580, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\backend.py", line 1129, in Run
    result = command_instance.Run(args)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\exceptions.py", line 86, in TryFunc
    return func(*args, **kwargs)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\gcloud\sdktools\root\init.py", line 133, in Run
    files.MakeDir(workspace_dir)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\core\util\files.py", line 57, in MakeDir
    ('Please verify that you have permissions to write to the parent '
Error: Could not create directory [C:\Program Files\Google\Cloud 
SDK\konate-kader-1990]: Permission denied.

Please verify that you have permissions to write to the parent directory.

Installation information:

Google Cloud SDK [0.9.76]

Platform: [Windows, x86_64]
Python Version: [2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit 
(AMD64)]]
Site Packages: [Disabled]

Installation Root: [C:\Program Files\Google\Cloud SDK\google-cloud-sdk]
Installed Components:
  core: [2015.08.27]
  bq-win: [2.0.18]
[output 

```

Original issue reported on code.google.com by `konateab...@gmail.com` on 3 Sep 2015 at 10:37

**Comment by GoogleCodeExporter** [comment]
```
By any chance you trying to clone your projects git repository? if so you can 
run
  gcloud beta source repos clone default

Current gcloud init command will soon be removed, and replaced by current
  gcloud beta init
command.

Let us know if any of these options work for you.


```

Original comment by `che...@google.com` on 4 Sep 2015 at 4:23
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
Original comment by `che...@google.com` on 4 Sep 2015 at 5:18
- Changed title: **gcloud init: windows permission denied**

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 13 Oct 2015 at 3:36
- Changed state: **Invalid**
