### ISSUE TITLE
Trying to login to a cloud instance and got this crash 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#239]
```
What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk/calliope/cli.py", line 580, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk/calliope/backend.py", line 1113, in Run
    last_group = context_filter(tool_context, Http, args)
  File "googlecloudsdk/calliope/backend.py", line 484, in ContextFilter
    group.Filter(context, args)
  File "googlecloudsdk/compute/subcommands/__init__.py", line 54, in Filter
    _DoFilter(context, self.Http(), 'v1', args)
  File "googlecloudsdk/calliope/base.py", line 278, in Http
    return self._http_func(auth=auth, creds=creds, **kwargs)
  File "googlecloudsdk/calliope/backend.py", line 1108, in Http
    **kwargs)
  File "googlecloudsdk/core/cli.py", line 116, in Http
    creds = c_store.Load()
  File "googlecloudsdk/core/credentials/store.py", line 250, in Load
    Refresh(cred)
  File "googlecloudsdk/core/credentials/store.py", line 268, in Refresh
    creds.refresh(http or _Http())
  File "oauth2client/client.py", line 597, in refresh
    self._refresh(http.request)
  File "oauth2client/client.py", line 780, in _refresh
    self._do_refresh_request(http_request)
  File "oauth2client/client.py", line 799, in _do_refresh_request
    self.token_uri, method='POST', body=body, headers=headers)
  File "httplib2/__init__.py", line 1608, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
[output truncated]

```

Original issue reported on code.google.com by `ch...@manson.ie` on 4 Sep 2015 at 1:32

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the report. Can you also post 
  * what command you were trying to run,
  * remaining part of the stacktrace,
  * output of gcloud info
this will help us narrow down the issue.
```

Original comment by `che...@google.com` on 4 Sep 2015 at 4:10

**Comment by GoogleCodeExporter** [comment]
Original comment by `che...@google.com` on 4 Sep 2015 at 4:11
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 13 Oct 2015 at 3:36
- Changed state: **Invalid**
