### ISSUE TITLE
Unable to install Alpha

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#240]
```
What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk/calliope/cli.py", line 557, in Execute
    args = self.__parser.parse_args(args)
  File "googlecloudsdk/calliope/backend.py", line 75, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "googlecloudsdk/calliope/backend.py", line 66, in parse_known_args
    args, argv = super(ArgumentParser, self).parse_known_args(args, namespace)
  File "argparse/__init__.py", line 1735, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "argparse/__init__.py", line 1944, in _parse_known_args
    stop_index = consume_positionals(start_index)
  File "argparse/__init__.py", line 1900, in consume_positionals
    take_action(action, args)
  File "argparse/__init__.py", line 1809, in take_action
    action(self, namespace, argument_values, option_string)
  File "googlecloudsdk/calliope/backend.py", line 287, in __call__
    parser, namespace, values, option_string=option_string)
  File "argparse/__init__.py", line 1111, in __call__
    namespace, arg_strings = parser.parse_known_args(arg_strings, namespace)
  File "googlecloudsdk/calliope/backend.py", line 66, in parse_known_args
    args, argv = super(ArgumentParser, self).parse_known_args(args, namespace)
  File "argparse/__init__.py", line 1735, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "argparse/__init__.py", line 1944, in _parse_known_args
    stop_index = consume_positionals(start_index)
[output truncated]

```

Original issue reported on code.google.com by `madalave...@gmail.com` on 5 Sep 2015 at 6:36

**Comment by GoogleCodeExporter** [comment]
```
Would you be able to include the rest of the error stack trace?

What command you were running to get to alpha commands enabled?
```

Original comment by `che...@google.com` on 8 Sep 2015 at 3:34
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
Closing, as we don't have enough information to diagnose this issue.

Please re-open if you're still experiencing this.
```

Original comment by `z...@google.com` on 24 Nov 2015 at 4:41
- Changed state: **Invalid**
