### ISSUE TITLE
Not sure why> gcloud init

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#245]
```
Issue running command [gcloud init].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "calliope/cli.py", line 580, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "calliope/backend.py", line 1129, in Run
    result = command_instance.Run(args)
  File "calliope/exceptions.py", line 86, in TryFunc
    return func(*args, **kwargs)
  File "gcloud/sdktools/root/init.py", line 147, in Run
    args.project, workspaces.DEFAULT_REPOSITORY_ALIAS)
  File "core/workspaces.py", line 331, in CloneProjectRepository
    self.CloneGitRepository(uri, alias)
  File "core/workspaces.py", line 195, in GitFunc
    CheckGitVersion((0, 0, 0))
  File "core/workspaces.py", line 144, in CheckGitVersion
    output = compat26.subprocess.check_output(['git', 'version'])
  File "core/util/compat26.py", line 36, in check_output
    raise subprocess.CalledProcessError(p.returncode, cmd, stdout_data)
CalledProcessError: Command '['git', 'version']' returned non-zero exit status 
69

Installation information:

Google Cloud SDK [0.9.77]

Platform: [Mac OS X, x86_64]
Python Version: [2.7.5 (default, Mar  9 2014, 22:15:05)  [GCC 4.2.1 Compatible 
Apple LLVM 5.0 (clang-500.0.68)]]
Site Packages: [Disabled]

Installation Root: [/Users/lasse/google-cloud-sdk]
Installed Components:
  core: [2015.09.03]
  core-nix: [2015.09.03]
  gcloud: [2015.09.03]
  gsutil-nix: [4.14]
  gsutil: [4.14]
  bq: [2.0.18]
  bq-nix: [2.0.18]
[output truncated]

```

Original issue reported on code.google.com by `unce...@gmail.com` on 10 Sep 2015 at 7:57

**Comment by GoogleCodeExporter** [comment]
```
gcloud init uses git to clone projects git repository.
If you run [git version] command does it work, what does it print, is git 
installed and is on your path.

That said [gcloud init] is being replaced in a few weeks time with [gcloud beta 
init].
If you want to clone the git repository you can use
  gcloud beta source repos clone
or new
  gcloud beta init

```

Original comment by `che...@google.com` on 10 Sep 2015 at 12:44
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 13 Oct 2015 at 3:16
- Changed state: **Invalid**
