### ISSUE TITLE
I couldn't gcloud auth activate-service-account

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#247]
```
Issue running command [gcloud auth activate].

What steps will reproduce the problem?
I entered the command: gcloud auth activate-service-account 
acount@developer.gserviceaccount.com --key-file acount.p12 --prompt-for-password

What is the expected output? What do you see instead?
It should activate the account in gcloud

Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk/calliope/cli.py", line 580, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk/calliope/backend.py", line 1129, in Run
    result = command_instance.Run(args)
  File "googlecloudsdk/gcloud/sdktools/auth/activate_service_account.py", line 123, in Run
    c_store.Refresh(cred)
  File "googlecloudsdk/core/credentials/store.py", line 267, in Refresh
    creds.refresh(http or _Http())
  File "oauth2client/client.py", line 597, in refresh
    self._refresh(http.request)
  File "oauth2client/client.py", line 768, in _refresh
    self._do_refresh_request(http_request)
  File "oauth2client/client.py", line 794, in _do_refresh_request
    body = self._generate_refresh_request_body()
  File "oauth2client/client.py", line 1423, in _generate_refresh_request_body
    assertion = self._generate_assertion()
  File "oauth2client/client.py", line 1552, in _generate_assertion
    private_key, self.private_key_password), payload)
  File "oauth2client/crypt.py", line 173, in from_string
    pkey = crypto.load_pkcs12(key, password).get_privatekey()
Error: [('PKCS12 routines', 'PKCS12_parse', 'mac verify failure')]

Installation information:

Google Cloud SDK [0.9.77]

Platform: [Mac OS X, x86_64]
Python Version: [2.7.10 (default, Jul 14 2015, 19:46:27)  [GCC 4.2.1 Compatible 
Apple LLVM 6.0 (clang-600.0.39)]]
Site Packages: [Disabled]

[output truncated]

```

Original issue reported on code.google.com by `luis.arc...@aporta.org.mx` on 10 Sep 2015 at 3:57

**Comment by GoogleCodeExporter** [comment]
```
I believe you may have mistyped the password at the password prompt.
We are looking into to printing an error message instead of a stack trace.
```

Original comment by `gsfow...@google.com` on 22 Sep 2015 at 5:53
- Changed state: **NeedsMoreInfo**
