### ISSUE TITLE
VM instance creation failure from CLI

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#248]
```
Issue running command [gcloud compute instances create].

What steps will reproduce the problem?
The full command from the CLI was:   
gcloud compute instances create www1 --zone us-central1-a --network cloud-net 
--address www-static --tags http-rule


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\cli.py", line 580, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\backend.py", line 1129, in Run
    result = command_instance.Run(args)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\compute\lib\base_classes.py", line 870, in Run
    request_protobufs = self.CreateRequests(args)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\compute\subcommands\instances\create.py", line 412, in CreateRequests
    network_interface = self.CreateNetworkInterfaceMessage(args, instance_refs)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\compute\subcommands\instances\create.py", line 347, in CreateNetworkInterfaceMessage
    address = self.ExpandAddressFlag(args, region)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\compute\lib\addresses_utils.py", line 103, in ExpandAddressFlag
    socket.inet_pton(socket.AF_INET6, args.address)
AttributeError: 'module' object has no attribute 'inet_pton'

Installation information:

Google Cloud SDK [0.9.77]

Platform: [Windows, x86_64]
[output truncated]

```

Original issue reported on code.google.com by `stevenco...@gmail.com` on 11 Sep 2015 at 1:18
- Merged into: #226

Attachments:
- [20.13.37.409000.log](https://storage.googleapis.com/google-code-attachments/google-cloud-sdk/issue-248/comment-0/20.13.37.409000.log)

**Comment by GoogleCodeExporter** [comment]
```
Hi there,

What version of Python are you using to run the Cloud SDK? `socket` is a Python 
built-in module, and the `inet_pton` method being missing suggests a corrupted 
Python installation to me.

Copying the full output of `gcloud info` here would be very helpful; it 
contains Python installation and more.

Also, do you mind running the command `python.exe -c "import socket; 
socket.inet_pton"` with the Python executable that `gcloud info` shows?

(Please do this all in the other issue.)
```

Original comment by `z...@google.com` on 11 Sep 2015 at 12:13
- Changed state: **Duplicate**
