### ISSUE TITLE
Fail to Clone your empty Cloud Repository to a local Git repository

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#249]
```
Issue running command [gcloud init].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\cli.py", line 580, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\backend.py", line 1129, in Run
    result = command_instance.Run(args)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\exceptions.py", line 86, in TryFunc
    return func(*args, **kwargs)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\gcloud\sdktools\root\init.py", line 133, in Run
    files.MakeDir(workspace_dir)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\core\util\files.py", line 57, in MakeDir
    ('Please verify that you have permissions to write to the parent '
Error: Could not create directory [C:\Program Files (x86)\Google\Cloud 
SDK\firstphp-1068]: Permission denied.

Please verify that you have permissions to write to the parent directory.

Installation information:

Google Cloud SDK [0.9.77]

Platform: [Windows, x86_64]
Python Version: [2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit 
(Intel)]]
Site Packages: [Disabled]

Installation Root: [C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk]
[output truncated]

```

Original issue reported on code.google.com by `tklee....@gmail.com` on 14 Sep 2015 at 6:19

**Comment by GoogleCodeExporter** [comment]
```
Thank you for the feedback. 

Do you have permission to edit/write to the C:\Program Files (x86)\Google\Cloud 
SDK\ directory? 

Was Cloud SDK installed using some other account?
```

Original comment by `vil...@google.com` on 14 Sep 2015 at 9:30

**Comment by GoogleCodeExporter** [comment]
```
Also you might consider
  gcloud beta source repos clone
command for this purpose, where you can specify target directory different from 
current. Next week this command will be released as [gcloud source repos clone].

```

Original comment by `che...@google.com` on 16 Sep 2015 at 5:59
- Changed state: **NeedsMoreInfo**
