### ISSUE TITLE
Crash trying to deploy

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#250]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk/calliope/cli.py", line 580, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk/calliope/backend.py", line 1129, in Run
    result = command_instance.Run(args)
  File "googlecloudsdk/appengine/app_commands/deploy.py", line 244, in Run
    client.SetDefaultVersion(modules=[module], version=version)
  File "googlecloudsdk/appengine/lib/appengine_client.py", line 334, in SetDefaultVersion
    self._GetRpcServer().Send(url)
  File "googlecloudsdk/appengine/lib/util.py", line 359, in Send
    response = self._server.Send(*args, **kwargs)
  File "googlecloudsdk/appengine/lib/external/tools/appengine_rpc_httplib2.py", line 229, in Send
    url, method=method, body=payload, headers=headers)
  File "oauth2client/client.py", line 562, in new_request
    redirections, connection_type)
  File "httplib2/__init__.py", line 1608, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "httplib2/__init__.py", line 1350, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "httplib2/__init__.py", line 1306, in _conn_request
    response = conn.getresponse()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1061, in getresponse
[output truncated]

```

Original issue reported on code.google.com by `els...@gmail.com` on 15 Sep 2015 at 7:25

**Comment by GoogleCodeExporter** [comment]
```
Looks like a network hiccup.

Does the problem persist upon retry?

Are there any unusual network/firewall/proxy settings at play?

Do you mind posting the remaining output from the log? We're limited in the 
number of characters we can pre-populate on Google Code.
```

Original comment by `z...@google.com` on 15 Sep 2015 at 4:53

**Comment by GoogleCodeExporter** [comment]
Original comment by `gsfow...@google.com` on 22 Sep 2015 at 5:54
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
Closing as we don't have enough information to diagnose the issue.

Please re-open if you're still experiencing this.
```

Original comment by `z...@google.com` on 20 Nov 2015 at 10:31
- Changed state: **Invalid**
