### ISSUE TITLE
ssh alias krach

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#251]
```
Issue running command [gcloud compute ssh].

What steps will reproduce the problem?

source .bash_alias
ssh-nagios

What is the expected output? What do you see instead?

alias ssh-nagios='gcloud compute ssh nagios --zone europe-west1-d --project 
looklet-prod'


Please provide any additional information below.


Traceback (most recent call last):
  File "./lib/googlecloudsdk/calliope/cli.py", line 559, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "./lib/googlecloudsdk/calliope/backend.py", line 1020, in Run
    result = command_instance.Run(args)
  File "lib/googlecloudsdk/compute/subcommands/ssh.py", line 116, in Run
    interactive_ssh=interactive_ssh)
  File "./lib/googlecloudsdk/compute/lib/ssh_utils.py", line 370, in ActuallyRun
    _RunExecutable(cmd_args, interactive_ssh=interactive_ssh)
  File "./lib/googlecloudsdk/compute/lib/ssh_utils.py", line 85, in _RunExecutable
    .format(cmd_args[0], e.returncode))
ToolException: [/usr/bin/ssh] exited with return code [255].

Installation information:

Google Cloud SDK [0.9.77]

Platform: [Mac OS X, x86_64]
Python Version: [2.7.6 (default, Sep  9 2014, 15:04:36)  [GCC 4.2.1 Compatible 
Apple LLVM 6.0 (clang-600.0.39)]]
Site Packages: [Disabled]

Installation Root: [/Users/stellan/google-cloud-sdk]
Installed Components:
  core: [2015.09.03]
  core-nix: [2015.09.03]
  compute: [2015.03.23]
  gsutil-nix: [4.14]
  beta: [2015.08.17]
  gsutil: [4.14]
  bq: [2.0.18]
  dns: [2015.03.23]
  sql: [2015.03.23]
  gcutil: [1.16.5]
  gcutil-nix: [1.16.5]
  bq-nix: [2.0.18]
System PATH: 
[/Users/stellan/google-cloud-sdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbi
n]
Cloud SDK on PATH: [True]

[output truncated]

```

Original issue reported on code.google.com by `stel...@looklet.com` on 15 Sep 2015 at 12:46

**Comment by GoogleCodeExporter** [comment]
```
Thank you for the feedback.

Are you able to run 'gcloud compute ssh nagios --zone europe-west1-d --project 
looklet-prod' successfully without the alias setup?
```

Original comment by `vil...@google.com` on 15 Sep 2015 at 7:01
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
Did reinstall The gcloud packande on my Mac. After that The gcloud command
did start to work.  Can be the new Mac update that broke it.

/Stellan
Den 15 sep 2015 21:01 skrev <google-cloud-sdk@googlecode.com>:
```

Original comment by `stel...@looklet.com` on 15 Sep 2015 at 7:32

**Comment by GoogleCodeExporter** [comment]
```
Glad to hear you were able to resolve the issue. Please let us know if it 
happens again, so we can get to the bottom of it.
```

Original comment by `vil...@google.com` on 15 Sep 2015 at 7:40
- Changed state: **Done**
