### ISSUE TITLE
crashed

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#252]
```
What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\cli.py", line 580, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\backend.py", line 1113, in Run
    last_group = context_filter(tool_context, Http, args)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\backend.py", line 484, in ContextFilter
    group.Filter(context, args)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\compute\subcommands\__init__.py", line 54, in Filter
    _DoFilter(context, self.Http(), 'v1', args)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\base.py", line 278, in Http
    return self._http_func(auth=auth, creds=creds, **kwargs)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\backend.py", line 1108, in Http
    **kwargs)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\core\cli.py", line 115, in Http
    creds = c_store.Load()
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\core\credentials\store.py", line 249, in Load
[output truncated]

```

Original issue reported on code.google.com by `icrms...@gmail.com` on 16 Sep 2015 at 5:10

**Comment by GoogleCodeExporter** [comment]
```
Can you provide the command line that produced the stack trace, and also 
include a few more lines of the stack trace?
Thanks
```

Original comment by `gsfow...@google.com` on 22 Sep 2015 at 5:57
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
Closing, as we don't have enough information to diagnose this issue.

Please re-open if you're still experiencing this.
```

Original comment by `z...@google.com` on 24 Nov 2015 at 4:43
- Changed state: **Invalid**
