### ISSUE TITLE
Cannot Use the ssl-certificates CLI command

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#255]
```
What steps will reproduce the problem?
Running the command 

`gcloud beta compute ssl-certificates create cibox --certificate 
templates/ssl.crt --private-key templates/ssl.key`

What is the expected output? What do you see instead?
We expect a new SSL certificate be added to Google Cloud, instead we see the 
following python stacktrace:

Traceback (most recent call last):
  File "/google-cloud-sdk/./lib/googlecloudsdk/gcloud/gcloud.py", line 231, in main
    _cli.Execute()
  File "/google-cloud-sdk/./lib/googlecloudsdk/calliope/cli.py", line 557, in Execute
    args = self.__parser.parse_args(args)
  File "/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 75, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 66, in parse_known_args
    args, argv = super(ArgumentParser, self).parse_known_args(args, namespace)
  File "/google-cloud-sdk/./lib/argparse/__init__.py", line 1735, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/google-cloud-sdk/./lib/argparse/__init__.py", line 1923, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/google-cloud-sdk/./lib/argparse/__init__.py", line 1900, in consume_positionals
    take_action(action, args)
  File "/google-cloud-sdk/./lib/argparse/__init__.py", line 1809, in take_action
    action(self, namespace, argument_values, option_string)
  File "/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 287, in __call__
    parser, namespace, values, option_string=option_string)
  File "/google-cloud-sdk/./lib/argparse/__init__.py", line 1111, in __call__
    namespace, arg_strings = parser.parse_known_args(arg_strings, namespace)
  File "/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 66, in parse_known_args
    args, argv = super(ArgumentParser, self).parse_known_args(args, namespace)
  File "/google-cloud-sdk/./lib/argparse/__init__.py", line 1735, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/google-cloud-sdk/./lib/argparse/__init__.py", line 1923, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/google-cloud-sdk/./lib/argparse/__init__.py", line 1900, in consume_positionals
    take_action(action, args)
  File "/google-cloud-sdk/./lib/argparse/__init__.py", line 1793, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "/google-cloud-sdk/./lib/argparse/__init__.py", line 2229, in _get_values
    self._check_value(action, value[0])
  File "/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 133, in _check_value
    if is_subparser and action.IsValidChoice(value):
  File "/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 276, in IsValidChoice
    return self._calliope_command.IsValidSubElement(choice)
  File "/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 972, in IsValidSubElement
    return bool(self.LoadSubElement(name))
  File "/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 1010, in LoadSubElement
    self._config_hooks, parent_group=self, allow_empty=allow_empty)
  File "/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 828, in __init__
    self._GetModuleFromPath(module_dir, module_path, path, construction_id),
  File "/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 746, in _GetModuleFromPath
    name_to_give, os.path.join(module_dir, *module_path))
  File "/google-cloud-sdk/./lib/googlecloudsdk/core/util/pkg_resources.py", line 97, in GetModuleFromPath
    module = imp.load_module(name_to_give, f, file_path, items)
  File "/google-cloud-sdk/./lib/googlecloudsdk/compute/subcommands/__init__.py", line 8, in <module>

  File "/google-cloud-sdk/./lib/googlecloudsdk/compute/lib/utils.py", line 10, in <module>
    from googlecloudsdk.core import log
CommandLoadFailure: Problem loading gcloud.beta.compute: No module named 
googlecloudapis.compute.alpha.
```

Original issue reported on code.google.com by `si...@inboxhealth.com` on 17 Sep 2015 at 2:23

**Comment by GoogleCodeExporter** [comment]
```
Can you send the output of
  gcloud info
Thanks
```

Original comment by `gsfow...@google.com` on 22 Sep 2015 at 6:05
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
Closing, as we don't have enough information to diagnose this issue.

Please re-open if you're still experiencing this.
```

Original comment by `z...@google.com` on 24 Nov 2015 at 4:41
- Changed state: **Invalid**
