### ISSUE TITLE
Error running gcloud auth login

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#256]
```
Issue running command [gcloud auth login].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\cli.py", line 580, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\backend.py", line 1129, in Run
    result = command_instance.Run(args)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\exceptions.py", line 86, in TryFunc
    return func(*args, **kwargs)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\gcloud\sdktools\auth\login.py", line 99, in Run
    creds = self.DoWebFlow(args.launch_browser)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\gcloud\sdktools\auth\login.py", line 160, in DoWebFlow
    return c_store.AcquireFromWebFlow(launch_browser=launch_browser)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\core\credentials\store.py", line 383, in AcquireFromWebFlow
    http=_Http())
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\core\credentials\flow.py", line 156, in Run
    credential = flow.step2_exchange(code, http=http)
[output truncated]

```

Original issue reported on code.google.com by `njoeb...@gmail.com` on 17 Sep 2015 at 3:35

**Comment by GoogleCodeExporter** [comment]
```
Web browser opened up successfully and stated that I authenticated 
successfully, but when I run gcloud auth list, no accounts are listed.
```

Original comment by `njoeb...@gmail.com` on 17 Sep 2015 at 3:44

**Comment by GoogleCodeExporter** [comment]
```
Can you send the output of
  gcloud info
and also provide all of the stack trace lines.
Thanks
```

Original comment by `gsfow...@google.com` on 22 Sep 2015 at 6:07
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
go ahead a close this.  it was on my end.  firewall issue.
```

Original comment by `njoeb...@gmail.com` on 22 Sep 2015 at 2:34

**Comment by GoogleCodeExporter** [comment]
```
Glad you were able to figure it out!
```

Original comment by `z...@google.com` on 22 Sep 2015 at 3:23
- Changed state: **Invalid**

**Comment by GoogleCodeExporter** [comment]
```
Glad you were able to figure it out!
```

Original comment by `z...@google.com` on 22 Sep 2015 at 3:23
