### ISSUE TITLE
Managed-VM module is not executed in a container

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#259]
```
What steps will reproduce the problem?

Running an application with a managed-vm module requiring a platform specific 
library

What is the expected output? What do you see instead?

It should build the docker container and run it. It says "Dockerfile found" and 
then does not build it. Instead it is trying to run the module on the local 
execution environment which fails, because the module includes `.so` files 
which are compiled for the target environment (linux). It shows the error (logs 
in german): %1 is not a Win32-Application

"C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\gcloud.cmd" preview app 
run ./src/api/api.yaml ./src/worker/worker.yaml --enable-mvm-logs --log-level 
debug
Module [default] found in file 
[C:\Users\Friedrich\PycharmProjects\client\src\api\api.yaml]
Module [worker] found in file 
[C:\Users\Friedrich\PycharmProjects\client\src\worker\worker.yaml]
INFO: Looking for the Dockerfile in 
C:\Users\Friedrich\PycharmProjects\client\src\worker
INFO: Using Dockerfile found in 
C:\Users\Friedrich\PycharmProjects\client\src\worker
INFO     2015-09-18 10:17:34,483 application_configuration.py:399] No version 
specified. Generated version id: 20150918t101734
INFO     2015-09-18 10:17:34,483 devappserver2.py:763] Skipping SDK update 
check.
INFO     2015-09-18 10:17:34,596 api_server.py:205] Starting API server at: 
http://localhost:50120
INFO     2015-09-18 10:17:34,608 dispatcher.py:197] Starting module "default" 
running at: http://localhost:8080
INFO     2015-09-18 10:17:34,621 dispatcher.py:197] Starting module "worker" 
running at: http://localhost:8081
INFO     2015-09-18 10:17:34,625 admin_server.py:118] Starting admin server at: 
http://localhost:8000
INFO     2015-09-18 10:17:36,634 module.py:1769] New instance for module 
"worker" serving on:
http://localhost:8081

INFO     2015-09-18 10:17:36,635 module.py:1769] New instance for module 
"worker" serving on: http://localhost:8081

ERROR    2015-09-18 08:17:37,332 wsgi.py:263] 
Traceback (most recent call last):
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\runtime\wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\runtime\wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\runtime\wsgi.py", line 85, in LoadObject
    obj = __import__(path[0])
  File "C:\Users\Friedrich\PycharmProjects\client\src\worker\main.py", line 15, in <module>
    from client.cloud_client import Client
  File "C:\Users\Friedrich\PycharmProjects\client\src\worker\client\cloud_client.py", line 23, in <module>
    cdll.LoadLibrary(path + '/libstack.so')
  File "C:\python27_x64\lib\ctypes\__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "C:\python27_x64\lib\ctypes\__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 193] %1 ist keine zul�ssige Win32-Anwendung
INFO     2015-09-18 10:17:37,341 module.py:809] worker: "GET /_ah/start 
HTTP/1.1" 500 -

It 

What is the output of 'gcloud info'?


Installation Root: [C:\Program Files\Google\Cloud SDK\google-cloud-sdk]
Installed Components:
  core: [2015.09.11]
  app-engine-python: [1.9.26]
  bq-win: [2.0.18]
  core-win: [2015.08.10]
  app-engine-java: [1.9.26]
  gcloud: [2015.09.11]
  windows-ssh-tools: [2015.06.02]
  app-engine-python-extras: [1.9.21]
  gsutil: [4.15]
  bq: [2.0.18]
  preview: [2015.09.03]
  app: [2015.09.11]
  gsutil-win: [4.13]
System PATH: REMOVED
Cloud SDK on PATH: [True]

Installation Properties: [C:\Program Files\Google\Cloud 
SDK\google-cloud-sdk\properties]
User Config Directory: [C:\Users\Friedrich\AppData\Roaming\gcloud]
User Properties: [C:\Users\Friedrich\AppData\Roaming\gcloud\properties]
Current Workspace: [None]
Workspace Config Directory: [None]
Workspace Properties: [None]

Account: [friedrich.maeckle@googlemail.com]
Project: [client]

Current Properties:
  [core]
    project: [client]
    account: [friedrich.maeckle@googlemail.com]
    disable_usage_reporting: [True]

Logs Directory: [C:\Users\Friedrich\AppData\Roaming\gcloud\logs]
Last Log File: [C:\Users\Friedrich\AppData\Roaming\gcloud\logs\2015.09.18\10.28.
05.087000.log]

Please provide any additional information below.

I updated my machine to use the docker toolbox (docker-machine), since 
boot2docker showed a deprecated warning. I had to delete the boot2docker image, 
since the migration to docker-machine failed.

This is kind of frustrating since the documentation about how to get managed-vm 
local development running was removed from the GAE documentation website: Was 
at 
https://cloud.google.com/appengine/docs/managed-vms/getting-started#install_dock
er

This worked before on boot2docker, but after an update to the latest gcloud sdk 
and docker-machine it fails.

```

Original issue reported on code.google.com by `friedric...@googlemail.com` on 18 Sep 2015 at 8:47

**Comment by GoogleCodeExporter** [comment]
```
Read the release notes for gcloud 0.9.71 for why this is happening.

https://dl.google.com/dl/cloudsdk/release/RELEASE_NOTES

And for some context read comments #9 onwards in this bug report.

https://code.google.com/p/google-cloud-sdk/issues/detail?id=163
```

Original comment by `pdknsk` on 21 Sep 2015 at 5:05

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
Original comment by `gsfow...@google.com` on 23 Sep 2015 at 10:45
- Changed state: **WorkingAsIntended**
