### ISSUE TITLE
gcloud compute instances list crashed

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#262]
```
Issue running command [gcloud compute instances list].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "calliope/cli.py", line 580, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "calliope/backend.py", line 1131, in Run
    output_formatter(result)
  File "calliope/backend.py", line 1125, in <lambda>
    output_formatter = lambda obj: command_instance.Display(args, obj)
  File "compute/lib/base_classes.py", line 318, in Display
    PrintTable(resources, self._resource_spec.table_cols)
  File "compute/lib/base_classes.py", line 53, in PrintTable
    for resource in resources:
  File "compute/lib/base_classes.py", line 303, in Run
    for item in items:
  File "compute/lib/lister.py", line 44, in ProcessResults
    yield field_selector.Apply(resource)
  File "compute/lib/property_selector.py", line 359, in Apply
    res = _DictToOrderedDict(obj)
  File "compute/lib/property_selector.py", line 177, in _DictToOrderedDict
    new_obj = collections.OrderedDict(sorted(obj.items()))
AttributeError: 'module' object has no attribute 'OrderedDict'

Installation information:

Google Cloud SDK [0.9.78]

Platform: [Mac OS X, x86_64]
Python Version: [2.6.9 (unknown, May 25 2015, 13:03:05)  [GCC 4.2.1 Compatible 
Apple LLVM 6.0 (clang-600.0.56)]]
Site Packages: [Disabled]

Installation Root: [/Users/rejeev/google-cloud-sdk]
Installed Components:
  core: [2015.09.11]
  core-nix: [2015.09.03]
  gcloud: [2015.09.11]
  gsutil-nix: [4.14]
  gsutil: [4.15]
[output truncated]

```

Original issue reported on code.google.com by `i...@learntoscore.com` on 21 Sep 2015 at 1:46

**Comment by GoogleCodeExporter** [comment]
```
Python Version: 2.6.9

From the System Requirements at https://cloud.google.com/sdk/ you can see that 
the Google Cloud SDK requires Python 2.7.x.
```

Original comment by `svalen...@google.com` on 21 Sep 2015 at 4:13

**Comment by GoogleCodeExporter** [comment]
Original comment by `svalen...@google.com` on 21 Sep 2015 at 4:14
- Changed state: **WontFix**
