### ISSUE TITLE
permission to write to the parent directory

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#264]
```
Issue running command [gcloud init].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\cli.py", line 580, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\backend.py", line 1129, in Run
    result = command_instance.Run(args)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\exceptions.py", line 86, in TryFunc
    return func(*args, **kwargs)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\gcloud\sdktools\root\init.py", line 133, in Run
    files.MakeDir(workspace_dir)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\core\util\files.py", line 57, in MakeDir
    ('Please verify that you have permissions to write to the parent '
Error: Could not create directory [C:\Program Files (x86)\Google\Cloud 
SDK\mydrupal-1073]: Permission denied.

Please verify that you have permissions to write to the parent directory.

Installation information:

Google Cloud SDK [0.9.78]

Platform: [Windows, x86_64]
Python Version: [2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit 
(AMD64)]]
Site Packages: [Disabled]

Installation Root: [C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk]
[output truncated]

```

Original issue reported on code.google.com by `p8c...@gmail.com` on 22 Sep 2015 at 10:30

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the report.
When you run gcloud init you have to be in directory where you have write 
permissions.

That said if you are looking to clone associated git repo, consider using
  gcloud beta source repos clone default
command.

Also we are releasing new gcloud init command (currently gcloud beta init if 
you like to try) which behaves somewhat differently. It is also possible to use 
that to clone repos, but again you should be in a directory where you can 
create files and directories.

```

Original comment by `che...@google.com` on 22 Sep 2015 at 3:16
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
Original comment by `gsfow...@google.com` on 23 Sep 2015 at 1:20
- Changed state: **WorkingAsIntended**
