### ISSUE TITLE
failure when running gcloud ssh

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#265]
```
What steps will reproduce the problem? Ran beta component install, now gcloud 
auth ssh command fails


What is the expected output? What do you see instead? shell of the VM that I 
want to ssh to. Instead I see the python errors below.


Please provide any additional information below. Running it on Mac OS 10.10.5


Traceback (most recent call last):
  File "googlecloudsdk/calliope/cli.py", line 557, in Execute
    args = self.__parser.parse_args(args)
  File "googlecloudsdk/calliope/backend.py", line 75, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "googlecloudsdk/calliope/backend.py", line 66, in parse_known_args
    args, argv = super(ArgumentParser, self).parse_known_args(args, namespace)
  File "argparse/__init__.py", line 1735, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "argparse/__init__.py", line 1923, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "argparse/__init__.py", line 1900, in consume_positionals
    take_action(action, args)
  File "argparse/__init__.py", line 1793, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "argparse/__init__.py", line 2229, in _get_values
    self._check_value(action, value[0])
  File "googlecloudsdk/calliope/backend.py", line 152, in _check_value
    self._calliope_command.LoadAllSubElements()
  File "googlecloudsdk/calliope/backend.py", line 977, in LoadAllSubElements
    element = self.LoadSubElement(name)
  File "googlecloudsdk/calliope/backend.py", line 1010, in LoadSubElement
    self._config_hooks, parent_group=self, allow_empty=allow_empty)
  File "googlecloudsdk/calliope/backend.py", line 828, in __init__
    self._GetModuleFromPath(module_dir, module_path, path, construction_id),
[output truncated]

```

Original issue reported on code.google.com by `mach...@gmail.com` on 22 Sep 2015 at 9:50

**Comment by GoogleCodeExporter** [comment]
```
I remove the beta and preview components and did a reinstall as suggested in 
case 157. This seem to fix the issue.
```

Original comment by `mach...@gmail.com` on 22 Sep 2015 at 10:01

**Comment by GoogleCodeExporter** [comment]
Original comment by `gsfow...@google.com` on 23 Sep 2015 at 1:34
- Changed state: **Done**
