### ISSUE TITLE
broken gcloud on macosx after re-install

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#267]
```
Issue running command [gcloud auth login].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk/calliope/cli.py", line 591, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk/calliope/backend.py", line 1191, in Run
    resources = command_instance.Run(args)
  File "googlecloudsdk/calliope/exceptions.py", line 96, in TryFunc
    return func(*args, **kwargs)
  File "googlecloudsdk/gcloud/sdktools/auth/login.py", line 104, in Run
    creds = self.DoWebFlow(args.launch_browser)
  File "googlecloudsdk/gcloud/sdktools/auth/login.py", line 165, in DoWebFlow
    return c_store.AcquireFromWebFlow(launch_browser=launch_browser)
  File "googlecloudsdk/core/credentials/store.py", line 383, in AcquireFromWebFlow
    http=_Http())
  File "googlecloudsdk/core/credentials/flow.py", line 156, in Run
    credential = flow.step2_exchange(code, http=http)
  File "oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "oauth2client/client.py", line 1993, in step2_exchange
    headers=headers)
  File "httplib2/__init__.py", line 1608, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "httplib2/__init__.py", line 1350, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "httplib2/__init__.py", line 1272, in _conn_request
    conn.connect()
[output truncated]

```

Original issue reported on code.google.com by `shopper....@gmail.com` on 27 Sep 2015 at 8:38

**Comment by GoogleCodeExporter** [comment]
```
Hi,

It looks like you may have a corrupted installation.  This happens rarely 
during `gcloud components update` operations.  Is that how you updated gcloud?  
Can you share us any specific steps you took that might help us troubleshoot?

In the meantime, you should be able to get gcloud into a workings state by 
deleting your installation (with rm -rf <cloud-sdk-directory>) and reinstalling 
following the instructions here: https://cloud.google.com/sdk/

Please let us know if reinstalling from https://cloud.google.com/sdk/ gets you 
into a working state.
```

Original comment by `jeffvaughan@google.com` on 28 Sep 2015 at 4:13
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 4 Jan 2016 at 2:13
- Changed state: **Invalid**
