### ISSUE TITLE
I cannot connect to gcloud by gcloud command

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#269]
```
Issue running command [gcloud compute ssh].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\cli.py", line 591, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\backend.py", line 1191, in Run
    resources = command_instance.Run(args)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\compute\subcommands\ssh.py", line 114, in Run
    external_ip_address = self.GetInstanceExternalIpAddress(instance_ref)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\compute\lib\ssh_utils.py", line 435, in GetInstanceExternalIpAddress
    error_message='Could not fetch instance:')
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\compute\lib\utils.py", line 96, in RaiseToolException
    RaiseException(problems, calliope_exceptions.ToolException, error_message)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\compute\lib\utils.py", line 108, in RaiseException
    errors))
ToolException: Could not fetch instance:
 - The resource 'projects/careful-drummer-108113/zones/us-central1-a/instances/my-instance' was not found

Installation information:

Google Cloud SDK [0.9.79]

[output truncated]

```

Original issue reported on code.google.com by `contrais...@gmail.com` on 29 Sep 2015 at 8:33

**Comment by GoogleCodeExporter** [comment]
```
Hmmm... it looks like an instance named `my-instance` can't be found in zone 
`us-central1-a`.  Do you seen your instance (in that zone) if you run the 
following list command?
   gcloud compute instances list
```

Original comment by `jeffvaughan@google.com` on 29 Sep 2015 at 6:51
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 4 Jan 2016 at 2:17
- Changed state: **Invalid**
