### ISSUE TITLE
GCloud Beta Errors

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#270]
```
What steps will reproduce the problem?
gcloud beta compute reset-windows-password

What is the expected output? What do you see instead?
Don't know. Error codes.

Please provide any additional information below.


Traceback (most recent call last):
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\cli.py", line 568, in Execute
    args = self.__parser.parse_args(args)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\backend.py", line 76, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\backend.py", line 67, in parse_known_args
    args, argv = super(ArgumentParser, self).parse_known_args(args, namespace)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\argparse\__init__.py", line 1735, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\argparse\__init__.py", line 1923, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\argparse\__init__.py", line 1900, in consume_positionals
    take_action(action, args)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\argparse\__init__.py", line 1809, in take_action
    action(self, namespace, argument_values, option_string)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\backend.py", line 288, in __call__
[output truncated]

```

Original issue reported on code.google.com by `matthieu...@reseller-secloudexperts.com` on 29 Sep 2015 at 2:18

**Comment by GoogleCodeExporter** [comment]
```
hmm... This looks like a very odd error.  It's possible that there's a been a 
problem installing/updating gcloud.

Could you please try reinstalling gcloud following the instructions here,
  https://cloud.google.com/sdk/
and then retry?

What platform are you running on?
```

Original comment by `jeffvaughan@google.com` on 1 Oct 2015 at 9:11
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 4 Jan 2016 at 2:13
- Changed state: **Invalid**
