### ISSUE TITLE
gcloud init failed during [gcloud auth login]

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#275]
```
Issue running command [gcloud auth login].

What steps will reproduce the problem?

gcloud init 

What is the expected output? What do you see instead?

gcloud auth login, also failed

Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk/calliope/cli.py", line 590, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk/calliope/backend.py", line 1222, in Run
    resources = command_instance.Run(args)
  File "googlecloudsdk/calliope/exceptions.py", line 96, in TryFunc
    return func(*args, **kwargs)
  File "googlecloudsdk/gcloud/sdktools/auth/login.py", line 104, in Run
    creds = self.DoWebFlow(args.launch_browser)
  File "googlecloudsdk/gcloud/sdktools/auth/login.py", line 165, in DoWebFlow
    return c_store.AcquireFromWebFlow(launch_browser=launch_browser)
  File "googlecloudsdk/core/credentials/store.py", line 383, in AcquireFromWebFlow
    http=_Http())
  File "googlecloudsdk/core/credentials/flow.py", line 156, in Run
    credential = flow.step2_exchange(code, http=http)
  File "oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "oauth2client/client.py", line 1993, in step2_exchange
    headers=headers)
  File "httplib2/__init__.py", line 1608, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "httplib2/__init__.py", line 1350, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "httplib2/__init__.py", line 1306, in _conn_request
    response = conn.getresponse()
[output truncated]

```

Original issue reported on code.google.com by `DuYujie....@gmail.com` on 1 Oct 2015 at 8:52

**Comment by GoogleCodeExporter** [comment]
```
Thanks for reporting the issues. By any chance you are behind some kind of 
proxy? If so can you tell what kind and whether it requires authentication?
```

Original comment by `che...@google.com` on 1 Oct 2015 at 11:33
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
Astrill
```

Original comment by `DuYujie....@gmail.com` on 9 Oct 2015 at 7:49

**Comment by GoogleCodeExporter** [comment]
```
I am not that familiar with Astrill, but you can try
gcloud auth login --no-launch-browser
as a workaround.
```

Original comment by `svalen...@google.com` on 9 Oct 2015 at 3:29

**Comment by GoogleCodeExporter** [comment]
```
Did above suggestion work for you?
```

Original comment by `che...@google.com` on 7 Jan 2016 at 3:25
- Changed title: **gcloud init failed during [gcloud auth login]**

**Comment by GoogleCodeExporter** [comment]
```
I have resolved this problem use the other VPN proxy.
```

Original comment by `DuYujie....@gmail.com` on 11 Jan 2016 at 1:23

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 18 Feb 2016 at 7:17
- Changed state: **WorkingAsIntended**
