### ISSUE TITLE
some issue

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#281]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "C:\Users\LukaszOltarzewski\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\cli.py", line 590, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "C:\Users\LukaszOltarzewski\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\backend.py", line 1222, in Run
    resources = command_instance.Run(args)
  File "C:\Users\LukaszOltarzewski\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\appengine\app_commands\deploy.py", line 220, in Run
    remote_build)
  File "C:\Users\LukaszOltarzewski\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\appengine\lib\deploy_command_util.py", line 122, in BuildAndPushDockerImages
    with docker_util.DockerHost(cli, version_id, remote) as docker_client:
  File "C:\Users\LukaszOltarzewski\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\appengine\lib\images\docker_util.py", line 208, in __enter__
    self._vm = Provision(self._cli, self._name, self._zone)
  File "C:\Users\LukaszOltarzewski\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\appengine\lib\images\docker_util.py", line 51, in Provision
    vm = _CreateVm(cli, name, zone)
[output truncated]

```

Original issue reported on code.google.com by `lukasz.o...@gmail.com` on 3 Oct 2015 at 6:27

**Comment by GoogleCodeExporter** [comment]
```
Hi there,

Can you provide some more information? Copying the truncated output from the 
`gcloud feedback` command, especially the complete traceback, would be great.
```

Original comment by `z...@google.com` on 5 Oct 2015 at 5:22
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 13 Oct 2015 at 3:17
- Changed state: **Invalid**
