### ISSUE TITLE
issue deploying app on managedvm

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#282]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\cli.py", line 580, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\backend.py", line 1129, in Run
    result = command_instance.Run(args)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\compute\lib\base_classes.py", line 902, in Run
    utils.RaiseToolException(errors)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\compute\lib\utils.py", line 96, in RaiseToolException
    RaiseException(problems, calliope_exceptions.ToolException, error_message)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\compute\lib\utils.py", line 108, in RaiseException
    errors))
ToolException: Some requests did not succeed:
 - The resource 'projects/sandbox-kseshavarapu/zones/us-central1-f/instances/gae-builder-vm-1' already exists

Installation information:

Google Cloud SDK [0.9.78]

Platform: [Windows, x86_64]
Python Version: [2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit 
(AMD64)]]
Site Packages: [Disabled]

Installation Root: [C:\Program Files\Google\Cloud SDK\google-cloud-sdk]
Installed Components:
  core: [2015.09.11]
  app-engine-python: [1.9.26]
[output
bq-win: [2.0.18]
  core-win: [2015.08.10]
  app: [2015.09.11]
  gcloud: [2015.09.11]
  windows-ssh-tools: [2015.06.02]
  beta: [2015.08.17]
  gsutil: [4.15]
  bq: [2.0.18]
  preview: [2015.09.03]
  app-engine-java: [1.9.26]
  gsutil-win: [4.13]
System PATH: [C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\bin\sdk;
C:\python27_x64\;C:\python27_x64\Scripts;D:\sencha\bin\Sencha\Cmd\5.0.3.324;D:\R
uby22-x64\bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows
;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program
 Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;c:\Pr
ogram Files (x86)\Common Files\Roxio Shared\OEM\DLLShared\;c:\Program Files (x86
)\Common Files\Roxio Shared\OEM\DLLShared\;c:\Program Files (x86)\Common Files\R
oxio Shared\OEM\12.0\DLLShared\;c:\Program Files (x86)\Roxio\OEM\AudioCore\;C:\P
rogram Files (x86)\Sennheiser\SoftD:\sencha\bin\Sencha\Cmd\5.0.3.324;D:\Ruby22-x
64\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System
32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Com
mon Files\Intel\WirelessCommon\;c:\Program Files (x86)\Common Files\Roxio Shared
\OEM\DLLShared\;c:\Program Files (x86)\Common Files\Roxio Shared\OEM\DLLShared\;
c:\Program Files (x86)\Common Files\Roxio Shared\OEM\12.0\DLLShared\;c:\Program
Files (x86)\Roxio\OEM\AudioCore\;C:\Program Files (x86)\Sennheiser\SoftphoneSDK\
phoneSDK\;C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin;C:\Program File
s (x86)\Skype\Phone\;D:\gradle-2.7\bin;C:\Program Files\Intel\WiFi\bin\;C:\Progr
am Files\Common Files\Intel\WirelessCommon\;D:\Java\jdk1.7.0_13\bin;;D:\Program
Files\Docker Toolbox]
Cloud SDK on PATH: [True]

Installation Properties: [C:\Program Files\Google\Cloud SDK\google-cloud-sdk\pro
perties]
User Config Directory: [C:\Users\j1008690\AppData\Roaming\gcloud]
User Properties: [C:\Users\j1008690\AppData\Roaming\gcloud\properties]
Current Workspace: [None]
Workspace Config Directory: [None]
Workspace Properties: [None]

Account: [kusuma.seshavarapu@jda.com]
Project: [sandbox-kseshavarapu]

Current Properties:
  [core]
    project: [sandbox-kseshavarapu]
    account: [kusuma.seshavarapu@jda.com]
    disable_usage_reporting: [False]

Logs Directory: [C:\Users\j1008690\AppData\Roaming\gcloud\logs]
Last Log File: [C:\Users\j1008690\AppData\Roaming\gcloud\logs\2015.10.05\10.25.1
3.092000.log]
```

Original issue reported on code.google.com by `kusuma.s...@jda.com` on 5 Oct 2015 at 5:08

**Comment by GoogleCodeExporter** [comment]
```
Thanks for reporting this.

I'll pass on the issue to the Managed VMs team.
```

Original comment by `z...@google.com` on 5 Oct 2015 at 5:50
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
This occurred for me as well when a deploy failed. Is it possible to reset that 
instance so it works again?
```

Original comment by `shinryuu...@gmail.com` on 20 Jan 2016 at 6:18

**Comment by GoogleCodeExporter** [comment]
```
This issue keeps popping up very frequently while deploying to managed vm. To 
resolve it go to computeengine dashboard and delete the instance manually and 
redploy.
```

Original comment by `kusuma.s...@jda.com` on 21 Jan 2016 at 10:40
