### ISSUE TITLE
cannot run cloud anymore from my mac terminal

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#283]
```
What steps will reproduce the problem?

I have tried, as usually, connect to my instance from mac terminal:

gcloud compute --project "unified-ion-98218" ssh --zone "us-central1-f" 
"instance-2"


What is the expected output? What do you see instead?

I cannot anymore. Here is the output:

Richard-Air:~ rp$ sudo gcloud compute --project "unified-ion-98218" ssh --zone 
"us-central1-f" "instance-2"
Password:
Traceback (most recent call last):
  File "/Applications/google-cloud-sdk/./lib/googlecloudsdk/gcloud/gcloud.py", line 231, in main
    _cli.Execute()
  File "/Applications/google-cloud-sdk/./lib/googlecloudsdk/calliope/cli.py", line 567, in Execute
    args = self.__parser.parse_args(args)
  File "/Applications/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 84, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/Applications/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 75, in parse_known_args
    args, argv = super(ArgumentParser, self).parse_known_args(args, namespace)
  File "/Applications/google-cloud-sdk/./lib/argparse/__init__.py", line 1735, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/Applications/google-cloud-sdk/./lib/argparse/__init__.py", line 1923, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/Applications/google-cloud-sdk/./lib/argparse/__init__.py", line 1900, in consume_positionals
    take_action(action, args)
  File "/Applications/google-cloud-sdk/./lib/argparse/__init__.py", line 1793, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "/Applications/google-cloud-sdk/./lib/argparse/__init__.py", line 2229, in _get_values
    self._check_value(action, value[0])
  File "/Applications/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 142, in _check_value
    if is_subparser and action.IsValidChoice(value):
  File "/Applications/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 285, in IsValidChoice
    return self._calliope_command.IsValidSubElement(choice)
  File "/Applications/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 1068, in IsValidSubElement
    return bool(self.LoadSubElement(name))
  File "/Applications/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 1106, in LoadSubElement
    self._config_hooks, parent_group=self, allow_empty=allow_empty)
  File "/Applications/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 924, in __init__
    self._GetModuleFromPath(module_dir, module_path, path, construction_id),
  File "/Applications/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 842, in _GetModuleFromPath
    name_to_give, os.path.join(module_dir, *module_path))
  File "/Applications/google-cloud-sdk/./lib/googlecloudsdk/core/util/pkg_resources.py", line 97, in GetModuleFromPath
    module = imp.load_module(name_to_give, f, file_path, items)
  File "/Applications/google-cloud-sdk/./lib/googlecloudsdk/compute/subcommands/__init__.py", line 8, in <module>

  File "/Applications/google-cloud-sdk/./lib/googlecloudsdk/compute/lib/utils.py", line 10, in <module>
    from googlecloudsdk.core import log
CommandLoadFailure: Problem loading gcloud.compute: No module named 
googlecloudapis.compute.alpha.

If you would like to report this issue, please run the following command:
  gcloud feedback
Richard-Air:~ rp$ 


What is the output of 'gcloud info'?

Richard-Air:~ rp$ gcloud info
Google Cloud SDK [0.9.80]

Platform: [Mac OS X, x86_64]
Python Version: [2.7.10 (default, Jul 14 2015, 19:46:27)  [GCC 4.2.1 Compatible 
Apple LLVM 6.0 (clang-600.0.39)]]
Site Packages: [Disabled]

Installation Root: [/Applications/google-cloud-sdk]
Installed Components:
  core: [2015.09.25]
  core-nix: [2015.09.03]
  compute: [2015.06.19]
  gcutil-msg: [2015.06.09]
  app: [2015.09.25]
  gcloud: [2015.09.25]
  gsutil-nix: [4.14]
  gsutil: [4.15]
  bq: [2.0.18]
  dns: [2015.06.02]
  sql: [2015.06.19]
  bq-nix: [2.0.18]
System PATH: 
[/Applications/google-cloud-sdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
:/opt/X11/bin]
Cloud SDK on PATH: [True]

Installation Properties: [/Applications/google-cloud-sdk/properties]
User Config Directory: [/Users/rp/.config/gcloud]
User Properties: [/Users/rp/.config/gcloud/properties]
Current Workspace: [None]
Workspace Config Directory: [None]
Workspace Properties: [None]

Account: [None]
Project: [None]

Current Properties:
  [core]
    disable_usage_reporting: [True]

Logs Directory: [/Users/rp/.config/gcloud/logs]
Last Log File: [/Users/rp/.config/gcloud/logs/2015.10.05/11.07.58.860636.log]


Richard-Air:~ rp$ 



Please provide any additional information below.

I think this happened after I have installed some other cloud components to use 
with cloud repository (i guess cloud preview)

```

Original issue reported on code.google.com by `rpalen...@gmail.com` on 5 Oct 2015 at 9:11
- Merged into: #157

**Comment by GoogleCodeExporter** [comment]
```
Looks like a broken installation. Try re-installing and let us know if that 
doesn't work.
```

Original comment by `z...@google.com` on 5 Oct 2015 at 12:59
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
Many thanks for prompt reply. Now it works.
```

Original comment by `rpalen...@gmail.com` on 5 Oct 2015 at 1:35

**Comment by GoogleCodeExporter** [comment]
```
Glad to hear!

I'm going to mark this as a duplicate of our general installation-corruption 
bug.
```

Original comment by `z...@google.com` on 5 Oct 2015 at 1:55
- Changed state: **Duplicate**
