### ISSUE TITLE
Unable to login via gcloud auth login

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#285]
```
Issue running command [gcloud auth login].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\cli.py", line 590, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\backend.py", line 1222, in Run
    resources = command_instance.Run(args)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\exceptions.py", line 96, in TryFunc
    return func(*args, **kwargs)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\gcloud\sdktools\auth\login.py", line 104, in Run
    creds = self.DoWebFlow(args.launch_browser)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\gcloud\sdktools\auth\login.py", line 165, in DoWebFlow
    return c_store.AcquireFromWebFlow(launch_browser=launch_browser)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\core\credentials\store.py", line 383, in AcquireFromWebFlow
    http=_Http())
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\core\credentials\flow.py", line 156, in Run
    credential = flow.step2_exchange(code, http=http)
[output truncated]

```

Original issue reported on code.google.com by `rathnam...@gmail.com` on 5 Oct 2015 at 10:55

**Comment by GoogleCodeExporter** [comment]
```
Hi there,

Do you mind reporting the rest of the stack trace?

Are you behind a firewall, or do you have any unusual network settings?
```

Original comment by `z...@google.com` on 5 Oct 2015 at 5:02
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
Yes if I connect with Other VPN network ..it works fine...this issue is
with our work place network.
```

Original comment by `rathnam...@gmail.com` on 6 Oct 2015 at 6:54

**Comment by GoogleCodeExporter** [comment]
```
In that case, there's nothing we can do about it.

You can set the HTTP_PROXY and HTTPS_PROXY environment variables to configure a 
proxy.
```

Original comment by `z...@google.com` on 6 Oct 2015 at 2:42
- Changed state: **WontFix**
