### ISSUE TITLE
Issue running command [gcloud init].

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#287]
```
Issue running command [gcloud init].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\cli.py", line 590, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\backend.py", line 1222, in Run
    resources = command_instance.Run(args)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\gcloud\sdktools\root\init.py", line 78, in Run
    if not self._PickAccount(args.console_only):
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\gcloud\sdktools\root\init.py", line 130, in _PickAccount
    disable_user_output=False):
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\gcloud\sdktools\root\init.py", line 354, in _RunCmd
    return self.cli.Execute(args)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\cli.py", line 590, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\backend.py", line 1222, in Run
    resources = command_instance.Run(args)
[output truncated]


```

Original issue reported on code.google.com by `srinivas...@gmail.com` on 6 Oct 2015 at 11:50

**Comment by GoogleCodeExporter** [comment]
```
What sequence of steps did you try before you got failure?
From the error it looks like [gcloud init] was trying to run [gcloud auth 
login].
Can you run [gcloud auth login] separately ?

Are you behind some proxy?
```

Original comment by `che...@google.com` on 6 Oct 2015 at 12:26
- Changed state: **NeedsMoreInfo**
