### ISSUE TITLE
gcloud gives stack trace

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#288]
```
What steps will reproduce the problem?
gcloud

What is the expected output? What do you see instead?
Something reasonable or an error message.

Crash

Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk/calliope/cli.py", line 549, in Execute
    args = self.__parser.parse_args(args)
  File "googlecloudsdk/calliope/backend.py", line 75, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "googlecloudsdk/calliope/backend.py", line 66, in parse_known_args
    args, argv = super(ArgumentParser, self).parse_known_args(args, namespace)
  File "argparse/__init__.py", line 1735, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "argparse/__init__.py", line 1952, in _parse_known_args
    self.error(_('too few arguments'))
  File "googlecloudsdk/calliope/backend.py", line 207, in error
    self._calliope_command, self._calliope_command.ai)
  File "googlecloudsdk/calliope/usage_text.py", line 388, in ShortHelpText
    command.LoadAllSubElements()
  File "googlecloudsdk/calliope/backend.py", line 969, in LoadAllSubElements
    element = self.LoadSubElement(name)
  File "googlecloudsdk/calliope/backend.py", line 1002, in LoadSubElement
    self._config_hooks, parent_group=self, allow_empty=allow_empty)
  File "googlecloudsdk/calliope/backend.py", line 820, in __init__
    self._GetModuleFromPath(module_dir, module_path, path, construction_id),
  File "googlecloudsdk/calliope/backend.py", line 738, in _GetModuleFromPath
    name_to_give, os.path.join(module_dir, *module_path))
  File "googlecloudsdk/core/util/pkg_resources.py", line 97, in GetModuleFromPath
[output truncated]

```

Original issue reported on code.google.com by `johnjbar...@google.com` on 6 Oct 2015 at 8:34

**Comment by GoogleCodeExporter** [comment]
```
What gcloud version are you running?

I can't reproduce this using 0.9.80, the latest version. I get a help message 
and the error "too few arguments".
```

Original comment by `z...@google.com` on 6 Oct 2015 at 8:46
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
Whatever gcloud version I had installed.

I did gcloud components update and now I get the same result as you.
```

Original comment by `johnjbar...@google.com` on 6 Oct 2015 at 8:50

**Comment by GoogleCodeExporter** [comment]
```
Great!
```

Original comment by `z...@google.com` on 6 Oct 2015 at 8:54
- Changed state: **Obsolete**
