### ISSUE TITLE
Crash when copy files from server to local

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#290]
```
What steps will reproduce the problem?
SCP from server to local.

What is the expected output? What do you see instead?
Copy progress.Fail to create correct output.

Please provide any additional information below.


Traceback (most recent call last):
  File "calliope/cli.py", line 590, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "calliope/backend.py", line 1211, in Run
    last_group = context_filter(tool_context, Http, args)
  File "calliope/backend.py", line 579, in ContextFilter
    group.Filter(context, args)
  File "compute/subcommands/__init__.py", line 54, in Filter
    _DoFilter(context, self.Http(), 'v1', args)
  File "calliope/base.py", line 280, in Http
    return self._http_func(auth=auth, creds=creds, **kwargs)
  File "calliope/backend.py", line 1206, in Http
    **kwargs)
  File "core/cli.py", line 121, in Http
    creds = c_store.Load()
  File "core/credentials/store.py", line 237, in Load
    if account in c_gce.Metadata().Accounts():
  File "core/credentials/gce.py", line 189, in Metadata
    _metadata_lock.lock(function=_CreateMetadata, argument=None)
  File "/usr/lib/python2.7/mutex.py", line 44, in lock
    function(argument)
  File "core/credentials/gce.py", line 188, in _CreateMetadata
    _metadata = _GCEMetadata()
  File "core/credentials/gce.py", line 45, in __init__
    self.connected = gce_cache.GetOnGCE()
  File "core/credentials/gce_cache.py", line 91, in GetOnGCE
    return _SINGLETON_ON_GCE_CACHE.GetOnGCE(check_age)
  File "core/credentials/gce_cache.py", line 54, in GetOnGCE
    self._UpdateFileCache()
  File "core/credentials/gce_cache.py", line 71, in _UpdateFileCache
[output truncated]

```

Original issue reported on code.google.com by `shamrajpoot001` on 8 Oct 2015 at 1:26

**Comment by GoogleCodeExporter** [comment]
```
Thanks for reporting! Do you mind posting the full stack trace? (Should be 
included in the `gcloud feedback` output in your terminal). This will help us 
debug further.

Can you SSH into this server? Can you copy files from your local machine to the 
server?
```

Original comment by `z...@google.com` on 8 Oct 2015 at 1:29
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
Yes i can able to copy files to and from the server to local and
visa-versa. But this error appear frequently.
```

Original comment by `shamrajpoot001` on 8 Oct 2015 at 5:05

**Comment by GoogleCodeExporter** [comment]
```
Do you mind posting the full stack trace?
```

Original comment by `z...@google.com` on 8 Oct 2015 at 5:07

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 4 Jan 2016 at 2:18
- Changed state: **Invalid**
