### ISSUE TITLE
Crash while creating image connected to static 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#291]
```
Issue running command [gcloud compute instances create].

What steps will reproduce the problem?
C:\Program Files (x86)\Google\Cloud SDK>gcloud compute instances create www1 --i
mage "https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/
backports-debian-7-wheezy-v20150929" --zone us-central1-a --network cloud-net --
address www-static --tags http-rule

What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\cli.py", line 589, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\backend.py", line 1221, in Run
    resources = command_instance.Run(args)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\compute\lib\base_classes.py", line 867, in Run
    request_protobufs = self.CreateRequests(args)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\compute\subcommands\instances\create.py", line 410, in CreateRequests
    network_interface = self.CreateNetworkInterfaceMessage(args, instance_refs)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\compute\subcommands\instances\create.py", line 345, in CreateNetworkInterfaceMessage
    address = self.ExpandAddressFlag(args, region)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\compute\lib\addresses_utils.py", line 103, in ExpandAddressFlag
    socket.inet_pton(socket.AF_INET6, args.address)
AttributeError: 'module' object has no attribute 'inet_pton'

Installation information:

Google Cloud SDK [0.9.81]

Platform: [Windows, x86_64]
[output truncated%

```

Original issue reported on code.google.com by `bren...@itsimplified.com.au` on 8 Oct 2015 at 4:37

**Comment by GoogleCodeExporter** [comment]
```
Hi there,

Thanks for reporting this.

It looks as though handling addresses on Windows uses a Unix-specific part of 
the Python standard library. We're working on a fix now.
```

Original comment by `z...@google.com` on 8 Oct 2015 at 4:03
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
Issue 226 has been merged into this issue.
```

Original comment by `z...@google.com` on 8 Oct 2015 at 4:32

**Comment by GoogleCodeExporter** [comment]
```
There will be a fix for this issue in Cloud SDK version 0.9.83.
```

Original comment by `z...@google.com` on 13 Oct 2015 at 3:51
