### ISSUE TITLE
gcloud auth login

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#292]
```
Issue running command [gcloud auth login].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk/calliope/cli.py", line 589, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk/calliope/backend.py", line 1221, in Run
    resources = command_instance.Run(args)
  File "googlecloudsdk/calliope/exceptions.py", line 96, in TryFunc
    return func(*args, **kwargs)
  File "googlecloudsdk/gcloud/sdktools/auth/login.py", line 103, in Run
    creds = self.DoWebFlow(args.launch_browser)
  File "googlecloudsdk/gcloud/sdktools/auth/login.py", line 164, in DoWebFlow
    return c_store.AcquireFromWebFlow(launch_browser=launch_browser)
  File "googlecloudsdk/core/credentials/store.py", line 383, in AcquireFromWebFlow
    http=_Http())
  File "googlecloudsdk/core/credentials/flow.py", line 156, in Run
    credential = flow.step2_exchange(code, http=http)
  File "oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "oauth2client/client.py", line 1993, in step2_exchange
    headers=headers)
  File "httplib2/__init__.py", line 1608, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "httplib2/__init__.py", line 1350, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "httplib2/__init__.py", line 1306, in _conn_request
    response = conn.getresponse()
[output truncated]

```

Original issue reported on code.google.com by `im.yuq...@gmail.com` on 8 Oct 2015 at 6:37

**Comment by GoogleCodeExporter** [comment]
```
Hi there,

Thanks for reporting this. Do you mind posting the full stack trace, along with 
the output of `gcloud info`?

Are you behind a proxy?

Can you try `gcloud auth login --no-launch-browser` as a workaround?
```

Original comment by `z...@google.com` on 8 Oct 2015 at 7:33
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
Hi there,

Thanks for reporting this. Do you mind posting the full stack trace, along with 
the output of `gcloud info`?

Are you behind a proxy?

Can you try `gcloud auth login --no-launch-browser` as a workaround?
```

Original comment by `z...@google.com` on 8 Oct 2015 at 7:34

**Comment by GoogleCodeExporter** [comment]
```
Hi,

It's working for me now, after reinstall gcloud. Thank you.
```

Original comment by `im.yuq...@gmail.com` on 9 Oct 2015 at 2:11

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 13 Oct 2015 at 3:18
- Changed state: **WontFix**
