### ISSUE TITLE
gcloud command not found

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#293]
```
What steps will reproduce the problem?
I installed latest Cloud SDK for windows with installer. Python 2.7 is 
installed, laucher says everything is complete.

What is the expected output? What do you see instead?
I type in cmd.exe "gcloud": gloud is either typed wrong or could not be found.

What is the output of 'gcloud info'?
It's not possible to execute.

Please provide any additional information below.
Checked the SDK path, there is no "bin" folder. Don't know what the problem is.
```

Original issue reported on code.google.com by `paulleon...@gmail.com` on 8 Oct 2015 at 3:18

**Comment by GoogleCodeExporter** [comment]
```
Hi there,

Thanks for reporting this. Do you mind attempting to install again? If there's 
no bin/ folder, that suggests an incomplete installation.
```

Original comment by `z...@google.com` on 8 Oct 2015 at 3:21
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
I installed again and again, uninstalled, installed for all users, not just me, 
everything. Doensn't help.

Maybe this helps:

Output folder: C:\Users\Paul\AppData\Local\Google\Cloud SDK
Checking for Python 2.7...
Create folder: C:\Users\Paul\AppData\Local\Google\Cloud SDK\google-cloud-sdk
Extract: google-cloud-sdk\install_google_cloud_sdk.py... 100%
Downloading Google Cloud SDK and installing components...
Traceback (most recent call last):
  File "google-cloud-sdk\install_google_cloud_sdk.py", line 99, in <module>
    main()
  File "google-cloud-sdk\install_google_cloud_sdk.py", line 83, in main
    archive_path = DownloadArchive(t, url)
  File "google-cloud-sdk\install_google_cloud_sdk.py", line 63, in DownloadArchive
    req = urlopen(url)
  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 431, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 449, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 1240, in https_open
    context=self._context)
  File "C:\Python27\lib\urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate 
verify failed (_ssl.c:590)>
Adding C:\Users\Paul\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin to the 
PATH.
Unsetting CLOUDSDK_PYTHON environment variable.
Google Cloud SDK has been installed!

```

Original comment by `paulleon...@gmail.com` on 8 Oct 2015 at 3:23

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the additional information.

Looks like your Python installation is having a hard time connecting securely 
to Google. What Python version are you using? What happens when you run

    > python -c 'import urllib2; print urllib2.urlopen("https://dl.google.com/").read()'

using that Python installation.

We need to do a better job of detecting when the installation fails.
```

Original comment by `z...@google.com` on 8 Oct 2015 at 3:28
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
I'm using python 2.7.10.

As far as I can tell, it is the same error.


>>> import urllib2; print urllib2.urlopen("https://dl.google.com/").read()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 431, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 449, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 1240, in https_open
    context=self._context)
  File "C:\Python27\lib\urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate 
verify failed (_ssl.c:590)>
>>>
```

Original comment by `paulleon...@gmail.com` on 8 Oct 2015 at 3:32

**Comment by GoogleCodeExporter** [comment]
```
Okay, then it's a problem with the way Python is hooked up to your computer's 
certificate store, or a problem with the certificate store itself.

Can you try connecting to that URL using a web browser (one that's not Chrome 
would be great, since I think Chrome does some funky stuff with its certificate 
stores). IE or Edge would be great.
```

Original comment by `z...@google.com` on 8 Oct 2015 at 3:39

**Comment by GoogleCodeExporter** [comment]
```
Well, I'm not really good at reading or writing code, so the only thing I can 
see it should download 
https://dl.google.com/dl/cloudsdk/channels/rapid/google-cloud-sdk.tar.gz

I downloaded this file using browser, extracted it and tried executing 
install.bat because I'm on windows.
This happens:

Welcome to the Google Cloud SDK!

To help improve the quality of this product, we collect anonymized data on how
the SDK is used. You may choose to opt out of this collection now (by choosing
'N' at the below prompt), or at any time in the future by running the following
command:
    gcloud config set --scope=user disable_usage_reporting true

Do you want to help improve the Google Cloud SDK (Y/n)?  Y


This will install all the core command line tools necessary for working with
the Google Cloud Platform.

ERROR: (gcloud.components.update) Failed to fetch component listing from 
server. Check your network settings and try again.
Google Cloud SDK installer will now exit.
Drücken Sie eine beliebige Taste . . .
```

Original comment by `paulleon...@gmail.com` on 8 Oct 2015 at 3:49

**Comment by GoogleCodeExporter** [comment]
```
Upon further research, it looks like you're hitting this OpenSSL bug: 
http://stackoverflow.com/questions/27804710/python-urllib2-ssl-error/27826829#27
826829

We'll take a look at ways that we can work around this bug on our end. You may 
be able to use a solution like the one here: 
http://stackoverflow.com/a/31915123/4922212
```

Original comment by `z...@google.com` on 8 Oct 2015 at 8:06

**Comment by GoogleCodeExporter** [comment]
```
I just downloaded Python 2.7.9.
It worked! Thank you!
```

Original comment by `paulleon...@gmail.com` on 9 Oct 2015 at 2:20

**Comment by GoogleCodeExporter** [comment]
```
Doesn't work for Python 2.7.10 & 3.5.0
Works fine for Python 2.7.9
```

Original comment by `mykhailo...@gmail.com` on 16 Oct 2015 at 9:22

**Comment by GoogleCodeExporter** [comment]
```
We've added a workaround for systems with incorrectly-configured certificate 
stores for Python and we're targeting Cloud SDK release 0.9.88.
```

Original comment by `z...@google.com` on 19 Nov 2015 at 3:22

**Comment by GoogleCodeExporter** [comment]
```
0.9.88 is out. Please let us know if you can still reproduce this issue.
```

Original comment by `z...@google.com` on 24 Nov 2015 at 9:27
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
This issue is still happening with a download i tried few mts back. Can you 
please help?
```

Original comment by `jagad...@voicemonk.com` on 26 Nov 2015 at 7:13

**Comment by GoogleCodeExporter** [comment]
```
What's the error message you're getting? Can you paste it here?
```

Original comment by `z...@google.com` on 27 Nov 2015 at 6:50

**Comment by GoogleCodeExporter** [comment]
```
Output folder: C:\Program Files (x86)\Google\Cloud SDK
Checking for Python 2.7...
Create folder: C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk
Extract: google-cloud-sdk\install_google_cloud_sdk.py
Create bat file: C:\Program Files (x86)\Google\Cloud SDK\cloud_env.bat
Downloading Google Cloud SDK and installing components...
Traceback (most recent call last):
  File "google-cloud-sdk\install_google_cloud_sdk.py", line 99, in <module>
    main()
  File "google-cloud-sdk\install_google_cloud_sdk.py", line 83, in main
    archive_path = DownloadArchive(t, url)
  File "google-cloud-sdk\install_google_cloud_sdk.py", line 63, in DownloadArchive
    req = urlopen(url)
  File "C:\python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\python27\lib\urllib2.py", line 431, in open
    response = self._open(req, data)
  File "C:\python27\lib\urllib2.py", line 449, in _open
    '_open', req)
  File "C:\python27\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "C:\python27\lib\urllib2.py", line 1240, in https_open
    context=self._context)
  File "C:\python27\lib\urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate 
verify failed (_ssl.c:590)>
Failed to install.

Windows 10
Python 2.7.10

Trying "urllib2.urlopen("https://dl.google.com/").read()" directly yields:

print urllib2.urlopen("https://dl.google.com/").read()
  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 431, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 449, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 1240, in https_open
    context=self._context)
  File "C:\Python27\lib\urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate 
verify failed (_ssl.c:590)>


```

Original comment by `daz.wil...@gmail.com` on 1 Dec 2015 at 1:41

**Comment by GoogleCodeExporter** [comment]
```
I installed from the zip/archive and this *worked*. So, it appears to be a 
problem with the Windows installer.
```

Original comment by `daz.wil...@gmail.com` on 1 Dec 2015 at 1:52

**Comment by GoogleCodeExporter** [comment]
```
Thanks for letting us know. There shouldn't be any differences between the 
Windows installer and the zip/archive installation method, so something's a 
little fishy. We'll investigate.
```

Original comment by `z...@google.com` on 1 Dec 2015 at 3:41
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
Is there any chance that you're using different Python installations in the 
installer vs. when installing from the archive?
```

Original comment by `z...@google.com` on 1 Dec 2015 at 3:53
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
It is possible (and I will check). The python installation on the Windows 
machine is updated (since I installed the Cloud SDK previously was working) and 
I don't recall doing it. This was my motivation for upgrading.

It used to be in c:\python27_x64 (2.7.9) and it is now in c:\python27 (2.7.10). 
Gcloud was working. When I tried to use it yesterday (before upgrading), it 
threw errors at being unable to find the python interpreter and, when I checked 
c:\python27_x64, the directory contained neither python.exe nor pythonw.exe (?) 
and I assumed this was because the previous version had been uninstalled.

After I installed from the archive, I had to  manually set CLOUDSDK_PYTHON to 
the new directory in order to use gcloud.
```

Original comment by `daz.wil...@gmail.com` on 1 Dec 2015 at 4:38

**Comment by GoogleCodeExporter** [comment]
```
I checked the Windows machine and am confident (not certain) that there's only 
one (2.7.10) python installation on it. As I recall the installer logs that it 
found a python interpreter but doesn't (?) provide specific information on 
where/which python interpreter.
```

Original comment by `daz.wil...@gmail.com` on 3 Dec 2015 at 5:57

**Comment by GoogleCodeExporter** [comment]
```
Now that you have one fixed version of python, can you please try installing 
using the installer to see whether it still encounters an error? Thanks.
```

Original comment by `vil...@google.com` on 3 Dec 2015 at 6:04

**Comment by GoogleCodeExporter** [comment]
```
same-same
```

Original comment by `daz.wil...@gmail.com` on 4 Dec 2015 at 3:25

**Comment by GoogleCodeExporter** [comment]
```
and... I didn't fix anything. The check appeared to prove that I only had one 
version of python installed 2.7.10
```

Original comment by `daz.wil...@gmail.com` on 4 Dec 2015 at 3:31
