### ISSUE TITLE
gcloud beta dataproc operations list, followed by delete or describe - items missing

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#295]
```
Issue running command [gcloud beta dataproc operations delete].
gcloud beta dataproc operations list
NAME                                                                            
       DONE
operations/projects/rugged-memory-819/operations/1dd2feb8-d7c6-4ecf-8c8c-170ec46
b817f  *
operations/projects/rugged-memory-819/operations/5c217a8c-9fc2-496d-be30-f1ed11b
af8d3  *
operations/projects/rugged-memory-819/operations/ab227009-3b03-4176-8936-017d1c9
a8daa  *
operations/projects/rugged-memory-819/operations/da054094-b115-467f-b40d-ffba41b
9490a  *
operations/projects/rugged-memory-819/operations/de09d155-ba24-4c3f-b40f-c73ec6c
b0116  *
 lesv  ⋯  cloud-bigtable-examples  java  wordcount-mapred
uce  gcloud beta dataproc operations delete 
1dd2feb8-d7c6-4ecf-8c8c-170ec46b817f
The operation '1dd2feb8-d7c6-4ecf-8c8c-170ec46b817f' will be deleted.

Do you want to continue (Y/n)?  y

Traceback (most recent call last):
  File "/Users/lesv/google-cloud-sdk/./lib/googlecloudsdk/gcloud/gcloud.py", line 231, in main
    _cli.Execute()
  File "/Users/lesv/google-cloud-sdk/./lib/googlecloudsdk/calliope/cli.py", line 589, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "/Users/lesv/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 1221, in Run
    resources = command_instance.Run(args)
  File "/Users/lesv/google-cloud-sdk/./lib/googlecloudsdk/dataproc/lib/util.py", line 64, in CatchHTTPErrorRaiseHTTPException
    msg = FormatHttpError(error)
  File "/Users/lesv/google-cloud-sdk/./lib/googlecloudsdk/dataproc/lib/util.py", line 34, in FormatHttpError
    return str(error)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 
1853-1855: ordinal not in range(128)

If you would like to report this issue, please run the following command:
  gcloud feedback
 lesv  ⋯  cloud-bigtable-examples  java  wordcount-mapred
uce  gcloud beta dataproc operations describe 
1dd2feb8-d7c6-4ecf-8c8c-170ec46b817f
Traceback (most recent call last):
  File "/Users/lesv/google-cloud-sdk/./lib/googlecloudsdk/gcloud/gcloud.py", line 231, in main
    _cli.Execute()
  File "/Users/lesv/google-cloud-sdk/./lib/googlecloudsdk/calliope/cli.py", line 589, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "/Users/lesv/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 1221, in Run
    resources = command_instance.Run(args)
  File "/Users/lesv/google-cloud-sdk/./lib/googlecloudsdk/dataproc/lib/util.py", line 64, in CatchHTTPErrorRaiseHTTPException
    msg = FormatHttpError(error)
  File "/Users/lesv/google-cloud-sdk/./lib/googlecloudsdk/dataproc/lib/util.py", line 34, in FormatHttpError
    return str(error)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 
1853-1855: ordinal not in range(128)

If you would like to report this issue, please run the following command:
  gcloud feedback
What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "calliope/cli.py", line 589, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "calliope/backend.py", line 1221, in Run
    resources = command_instance.Run(args)
  File "dataproc/lib/util.py", line 64, in CatchHTTPErrorRaiseHTTPException
    msg = FormatHttpError(error)
  File "dataproc/lib/util.py", line 34, in FormatHttpError
    return str(error)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 
1853-1855: ordinal not in range(128)

Installation information:

Google Cloud SDK [0.9.81]

Platform: [Mac OS X, x86_64]
Python Version: [2.7.10 (default, Jul 14 2015, 19:46:27)  [GCC 4.2.1 Compatible 
Apple LLVM 6.0 (clang-600.0.39)]]
Site Packages: [Disabled]

Installation Root: [/Users/lesv/google-cloud-sdk]
Installed Components:
  core: [2015.10.05]
  app-engine-python: [1.9.27]
  core-nix: [2015.09.03]
  kubectl: []
  app-engine-java: [1.9.27]
  gcloud: [2015.10.05]
  gsutil-nix: [4.14]
  app-engine-php: [ ]
  beta: [2015.10.05]
  gsutil: [4.15]
  bq: [2.0.18]
  app-engine-php-darwin: [2015.08.17]
  alpha: [2015.10.05]
  bq-nix: [2.0.18]
  app: [2015.10.05]
  kubectl-darwin-x86_64: [1.0.6]
[output truncated]


============================================================== TRUNCATED 
INFORMATION (PLEASE CONSIDER INCLUDING) 
===============================================================
System PATH: 
[/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/bin:/Users/lesv
/google-cloud-sdk/bin:/Users/lesv/homebrew/bin:/Users/lesv/bin:/Users/lesv/go/bi
n:/Users/lesv/android-sdk-macosx/tools:/Users/lesv/android-sdk-macosx/platorm-to
ols:/Users/lesv/bin/apache-maven-3.3.3/bin:/Users/lesv/Bigtable-EAP/hbase-1.1.1/
bin:/Users/lesv/google-cloud-sdk/bin:/usr/local/git/current/bin:/usr/local/bin:/
usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/go/bin:/opt
/ImageMagick/bin:/usr/local/MacGPG2/bin]
Cloud SDK on PATH: [True]

Installation Properties: [/Users/lesv/google-cloud-sdk/properties]
User Config Directory: [/Users/lesv/.config/gcloud]
User Properties: [/Users/lesv/.config/gcloud/properties]
Current Workspace: [None]
Workspace Config Directory: [None]
Workspace Properties: [None]

Account: [lesv@google.com]
Project: [rugged-memory-819]

Current Properties:
  [core]
    project: [rugged-memory-819]
    account: [lesv@google.com]
    disable_usage_reporting: [False]
  [app]
    hosted_registry: [true]
    suppress_change_warning: [true]
  [compute]
    region: [us-central1]
    zone: [us-central1-b]

Logs Directory: [/Users/lesv/.config/gcloud/logs]
Last Log File: [/Users/lesv/.config/gcloud/logs/2015.10.08/10.23.34.910116.log]
================================================================================
================================================================================
================
```

Original issue reported on code.google.com by `l...@google.com` on 8 Oct 2015 at 5:26

**Comment by GoogleCodeExporter** [comment]
```
Thanks for reporting! We'll take a look at handling these errors in a better 
fashion.
```

Original comment by `z...@google.com` on 8 Oct 2015 at 8:10
