### ISSUE TITLE
Deployment of app fails with the following output.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#297]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk/calliope/cli.py", line 589, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk/calliope/backend.py", line 1221, in Run
    resources = command_instance.Run(args)
  File "googlecloudsdk/appengine/app_commands/deploy.py", line 220, in Run
    remote_build)
  File "googlecloudsdk/appengine/lib/deploy_command_util.py", line 168, in BuildAndPushDockerImages
    info.file, docker_client, image_name)
  File "googlecloudsdk/appengine/lib/deploy_command_util.py", line 199, in BuildAndPushDockerImage
    nocache=False)) as image:
  File "googlecloudsdk/appengine/lib/docker/containers.py", line 125, in __enter__
    self.Build()
  File "googlecloudsdk/appengine/lib/docker/containers.py", line 153, in Build
    rm=self._image_opts.rm, pull=False)
  File "docker/docker/client.py", line 394, in build
    timeout=timeout,
  File "docker/docker/client.py", line 103, in _post
    return self.post(url, **self._set_request_timeout(kwargs))
  File "requests/sessions.py", line 507, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
[output truncated]

```

Original issue reported on code.google.com by `sbmtha...@gmail.com` on 10 Oct 2015 at 5:18

**Comment by GoogleCodeExporter** [comment]
```
It looks like gcloud is having trouble connecting to a Docker daemon. Can you 
attach the output of `gcloud info` and the full command line you ran?
```

Original comment by `dlor...@google.com` on 10 Oct 2015 at 5:37
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
Issue 615 has been merged into this issue.
```

Original comment by `z...@google.com` on 2 Mar 2016 at 2:34
