### ISSUE TITLE
tried to upgrade the components - got this error about directory not empty

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#298]
```
Issue running command [gcloud components update].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "calliope/cli.py", line 590, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "calliope/backend.py", line 1222, in Run
    resources = command_instance.Run(args)
  File "gcloud/sdktools/components/update.py", line 64, in Run
    args.component_ids, allow_no_backup=args.allow_no_backup)
  File "core/updater/update_manager.py", line 718, in Update
    staging_state = install_state.CloneToStaging(pb.SetProgress)
  File "core/updater/local_state.py", line 82, in _TryFunc
    return func(*args, **kwargs)
  File "core/updater/local_state.py", line 269, in CloneToStaging
    self._ClearStaging(progress_callback=rm_staging_cb)
  File "core/updater/local_state.py", line 82, in _TryFunc
    return func(*args, **kwargs)
  File "core/updater/local_state.py", line 421, in _ClearStaging
    file_utils.RmTree(self.__sdk_staging_root)
  File "core/util/files.py", line 164, in RmTree
    shutil.rmtree(path, onerror=_HandleRemoveError)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
[output truncated]

```

Original issue reported on code.google.com by `e...@sandler.co.il` on 11 Oct 2015 at 6:29

**Comment by GoogleCodeExporter** [comment]
```
Thanks for reporting this bug! Do you mind posting the full traceback? There's 
a limitation in the Google Code issue tracker that prevents the full length 
from being auto-populated.

Have you tried re-installing? Is the problem repeatable?
```

Original comment by `z...@google.com` on 11 Oct 2015 at 10:47
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
I think we can close this as I've ran the command again now and it seem to have 
worked fine. Not sure what the problem was.

Yesterday I tried running it multiple times (without first reinstalling). It 
failed in both my Mac as well as on a Linux VM I have.

Today it worked on both.
```

Original comment by `e...@sandler.co.il` on 12 Oct 2015 at 6:27

**Comment by GoogleCodeExporter** [comment]
```
Thanks for following up! Glad it worked out eventually.
```

Original comment by `z...@google.com` on 12 Oct 2015 at 1:05
- Changed state: **Obsolete**
