### ISSUE TITLE
Error received while trying "gcloud auth login"

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#299]
```
Issue running command [gcloud auth login].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\cli.py", line 589, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\backend.py", line 1221, in Run
    resources = command_instance.Run(args)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\exceptions.py", line 96, in TryFunc
    return func(*args, **kwargs)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\gcloud\sdktools\auth\login.py", line 103, in Run
    creds = self.DoWebFlow(args.launch_browser)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\gcloud\sdktools\auth\login.py", line 164, in DoWebFlow
    return c_store.AcquireFromWebFlow(launch_browser=launch_browser)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\core\credentials\store.py", line 383, in AcquireFromWebFlow
    http=_Http())
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\core\credentials\flow.py", line 156, in Run
    credential = flow.step2_exchange(code, http=http)
[output truncated]

```

Original issue reported on code.google.com by `stijn.no...@gmail.com` on 12 Oct 2015 at 9:54
- Merged into: #14

**Comment by GoogleCodeExporter** [comment]
```
Thanks for reporting this! Do you mind posting the remaining output?

Are you behind a proxy, by any chance? Or are there any other unusual network 
settings?
```

Original comment by `z...@google.com` on 12 Oct 2015 at 3:04
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
Hi

I didn't realize that the output was truncated.
As I didn't save the error message, I have no way of getting it back, unless I 
reproduce the error; which I cannot do right now.

The commands opened my browser, opened the approval page and allowed me to 
approve; but apparently the approval wasn't sent back to the gcloud instance.
So, while the webpage showed me that the auth was successful, it actually was 
not.

It seems that this error was due to a firewall blocking something.
Switching to a different, less/non-restricted network fixed the issue.

Kr,
Stijn

*What steps will reproduce the problem?*
Try to use gcloud behind a corporate firewall

*What is the expected output?*
A successful authentication of the gcloud instance.
*What do you see instead?*
Some error message related to network connection closed to soon (iirc).
```

Original comment by `stijn.no...@gmail.com` on 13 Oct 2015 at 7:14

**Comment by GoogleCodeExporter** [comment]
```
The output is all contained in the log file (see `gcloud info` for the location 
of your log files). If you run `gcloud feedback --log-file C:\<path to log 
file>`, it'll print out the full output.

Thanks for the additional information. I think this is a duplicate issue; I'm 
marking as such.

As a workaround, try using `gcloud auth login --no-launch-browser` or a service 
account 
(<https://cloud.google.com/sdk/gcloud/reference/auth/activate-service-account>; 
you can create one in the Cloud Console). You can also work around by leaving 
the firewall.
```

Original comment by `z...@google.com` on 13 Oct 2015 at 4:09
- Changed state: **Duplicate**

**Comment by GoogleCodeExporter** [comment]
```
Nevertheless, here's the output (Issue 299)

2015-10-12 11:53:03,053 DEBUG    root            Loaded Command Group: 
['gcloud', 'auth']
2015-10-12 11:53:03,073 DEBUG    root            Loaded Command Group: 
['gcloud', 'auth', 'login']
2015-10-12 11:53:03,076 DEBUG    root            Running gcloud.auth.login with 
Namespace(__calliope_internal_deepest_parser=ArgumentParser(prog='gcloud.auth.lo
gin', usage=None, description='Obtains access credentials for the Google Cloud 
Platform resources of the\ngiven account, via a web flow.  If the account 
already has valid credentials,\nit is set as active without re-running the web 
flow.', version=None, formatter_class=<class 'argparse.HelpFormatter'>, 
conflict_handler='error', add_help=False), account=None, activate=True, 
brief=False, cmd_func=<bound method Command.Run of 
<googlecloudsdk.calliope.backend.Command object at 0x0000000003856438>>, 
command_path=['gcloud', 'auth', 'login'], configuration=None, document=None, 
force=False, format=None, h=None, help=None, http_timeout=None, 
launch_browser=True, log_http=None, project=None, quiet=None, trace_email=None, 
trace_log=False, trace_token=None, user_output_enabled=None, verbosity=None, 
version=None).
2015-10-12 11:53:03,131 INFO     ___FILE_ONLY___ Your browser has been opened 
to visit:

    https://accounts.google.com/o/oauth2/auth?**********_I prefer to censor this_**********



2015-10-12 11:53:14,246 DEBUG    ___FILE_ONLY___ 
Traceback (most recent call last):
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\cli.py", line 589, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\backend.py", line 1221, in Run
    resources = command_instance.Run(args)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\exceptions.py", line 96, in TryFunc
    return func(*args, **kwargs)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\gcloud\sdktools\auth\login.py", line 103, in Run
    creds = self.DoWebFlow(args.launch_browser)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\gcloud\sdktools\auth\login.py", line 164, in DoWebFlow
    return c_store.AcquireFromWebFlow(launch_browser=launch_browser)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\core\credentials\store.py", line 383, in AcquireFromWebFlow
    http=_Http())
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\core\credentials\flow.py", line 156, in Run
    credential = flow.step2_exchange(code, http=http)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\oauth2client\util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\oauth2client\client.py", line 1993, in step2_exchange
    headers=headers)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\httplib2\__init__.py", line 1608, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\httplib2\__init__.py", line 1350, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\httplib2\__init__.py", line 1306, in _conn_request
    response = conn.getresponse()
  File "C:\Python27\lib\httplib.py", line 1055, in getresponse
    raise ResponseNotReady()
ResponseNotReady
2015-10-12 11:53:14,255 INFO     ___FILE_ONLY___ Traceback (most recent call 
last):

2015-10-12 11:53:14,256 INFO     ___FILE_ONLY___   File "C:\Program Files 
(x86)\Google\Cloud 
SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\gcloud\gcloud.py", line 231, 
in main

2015-10-12 11:53:14,256 INFO     ___FILE_ONLY___     _cli.Execute()

2015-10-12 11:53:14,257 INFO     ___FILE_ONLY___   File "C:\Program Files 
(x86)\Google\Cloud 
SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\cli.py", line 589, in 
Execute

2015-10-12 11:53:14,259 INFO     ___FILE_ONLY___     result = 
args.cmd_func(cli=self, args=args)

2015-10-12 11:53:14,259 INFO     ___FILE_ONLY___   File "C:\Program Files 
(x86)\Google\Cloud 
SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\backend.py", line 
1221, in Run

2015-10-12 11:53:14,260 INFO     ___FILE_ONLY___     resources = 
command_instance.Run(args)

2015-10-12 11:53:14,260 INFO     ___FILE_ONLY___   File "C:\Program Files 
(x86)\Google\Cloud 
SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\exceptions.py", line 
96, in TryFunc

2015-10-12 11:53:14,262 INFO     ___FILE_ONLY___     return func(*args, 
**kwargs)

2015-10-12 11:53:14,263 INFO     ___FILE_ONLY___   File "C:\Program Files 
(x86)\Google\Cloud 
SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\gcloud\sdktools\auth\login.py",
 line 103, in Run

2015-10-12 11:53:14,265 INFO     ___FILE_ONLY___     creds = 
self.DoWebFlow(args.launch_browser)

2015-10-12 11:53:14,266 INFO     ___FILE_ONLY___   File "C:\Program Files 
(x86)\Google\Cloud 
SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\gcloud\sdktools\auth\login.py",
 line 164, in DoWebFlow

2015-10-12 11:53:14,269 INFO     ___FILE_ONLY___     return 
c_store.AcquireFromWebFlow(launch_browser=launch_browser)

2015-10-12 11:53:14,269 INFO     ___FILE_ONLY___   File "C:\Program Files 
(x86)\Google\Cloud 
SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\core\credentials\store.py", 
line 383, in AcquireFromWebFlow

2015-10-12 11:53:14,270 INFO     ___FILE_ONLY___     http=_Http())

2015-10-12 11:53:14,272 INFO     ___FILE_ONLY___   File "C:\Program Files 
(x86)\Google\Cloud 
SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\core\credentials\flow.py", 
line 156, in Run

2015-10-12 11:53:14,273 INFO     ___FILE_ONLY___     credential = 
flow.step2_exchange(code, http=http)

2015-10-12 11:53:14,275 INFO     ___FILE_ONLY___   File "C:\Program Files 
(x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\oauth2client\util.py", 
line 137, in positional_wrapper

2015-10-12 11:53:14,276 INFO     ___FILE_ONLY___     return wrapped(*args, 
**kwargs)

2015-10-12 11:53:14,276 INFO     ___FILE_ONLY___   File "C:\Program Files 
(x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\oauth2client\client.py", 
line 1993, in step2_exchange

2015-10-12 11:53:14,278 INFO     ___FILE_ONLY___     headers=headers)

2015-10-12 11:53:14,279 INFO     ___FILE_ONLY___   File "C:\Program Files 
(x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\httplib2\__init__.py", 
line 1608, in request

2015-10-12 11:53:14,280 INFO     ___FILE_ONLY___     (response, content) = 
self._request(conn, authority, uri, request_uri, method, body, headers, 
redirections, cachekey)

2015-10-12 11:53:14,282 INFO     ___FILE_ONLY___   File "C:\Program Files 
(x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\httplib2\__init__.py", 
line 1350, in _request

2015-10-12 11:53:14,282 INFO     ___FILE_ONLY___     (response, content) = 
self._conn_request(conn, request_uri, method, body, headers)

2015-10-12 11:53:14,283 INFO     ___FILE_ONLY___   File "C:\Program Files 
(x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\httplib2\__init__.py", 
line 1306, in _conn_request

2015-10-12 11:53:14,285 INFO     ___FILE_ONLY___     response = 
conn.getresponse()

2015-10-12 11:53:14,286 INFO     ___FILE_ONLY___   File 
"C:\Python27\lib\httplib.py", line 1055, in getresponse

2015-10-12 11:53:14,286 INFO     ___FILE_ONLY___     raise ResponseNotReady()

2015-10-12 11:53:14,289 INFO     ___FILE_ONLY___ ResponseNotReady: 

2015-10-12 11:53:14,290 INFO     ___FILE_ONLY___ 
If you would like to report this issue, please run the following command:

2015-10-12 11:53:14,292 INFO     ___FILE_ONLY___   gcloud feedback
```

Original comment by `stijn.no...@gmail.com` on 14 Oct 2015 at 3:28

**Comment by GoogleCodeExporter** [comment]
```
Thank you!

For the record, the OAuth URL doesn't contain anything specific to your 
account, so it's safe to share publicly. It should always be:

    https://accounts.google.com/o/oauth2/auth?client_id=32555940559.apps.googleusercontent.com&prompt=select_account&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fappengine.admin+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcompute&access_type=offline&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A8085%2F

Of course, no worries that you didn't share it.
```

Original comment by `z...@google.com` on 14 Oct 2015 at 3:40
