### ISSUE TITLE
ImportError: No module named cloud.sdk.core while you have google module already

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#3]
```
What steps will reproduce the problem?
1. install any python module that use 'google' as module name (like other 
google tools, such as protobuf)
2. follow the instruction on 
https://developers.google.com/cloud/sdk/gettingstarted
3. while doing './google-cloud-sdk/INSTALL'

What is the expected output? What do you see instead?
expected: successfully installed
seen: 
Welcome to the Google Cloud SDK!
Traceback (most recent call last):
  File "/Users/littleq/opt/google-cloud-sdk/bin/bootstrapping/install.py", line 10, in <module>
    import bootstrapping
  File "/Users/littleq/opt/google-cloud-sdk/bin/bootstrapping/bootstrapping.py", line 17, in <module>
    from google.cloud.sdk.core import config
ImportError: No module named cloud.sdk.core

What version of the product are you using? On what operating system?
today's latest version (2013-10-28)
free Mac OS X Mavericks


Please provide any additional information below.
I think the previous 'google' module is still useful, I need to use that, so I 
don't want to uninstall that one. how could I do?

```

Original issue reported on code.google.com by `littleq0903` on 29 Oct 2013 at 3:47
- Merged into: #5

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the report.

Could you check to make sure that 
google-cloud-sdk/lib/google/cloud/sdk/core/*.py exists?

Have you done anything unusual with how your site package imports work? We've 
tested on a vanilla mavericks, but perhaps there's a case we didn't consider.
```

Original comment by `jasm...@google.com` on 29 Oct 2013 at 1:23

**Comment by GoogleCodeExporter** [comment]
```
I had the same issue raising from using pyenv.
Reverting back to system python fixed it.
```

Original comment by `l...@netmail.eu` on 7 Nov 2013 at 9:38

**Comment by GoogleCodeExporter** [comment]
```
I ran into this issue on Ubuntu 13.10 after installing the python protobuf 
package.

Is there a workaround for the moment or am I stuck having to install the 
protobuf package in a separate python enviroment?
```

Original comment by `camrudnick@gmail.com` on 7 Dec 2013 at 4:10

**Comment by GoogleCodeExporter** [comment]
```
Install cloud sdk in virual emvironment.
```

Original comment by `littleq0903` on 7 Dec 2013 at 4:43

**Comment by GoogleCodeExporter** [comment]
Original comment by `markp...@google.com` on 26 Dec 2013 at 5:34
- Changed state: **Duplicate**
