### ISSUE TITLE
Issue running command [gcloud compute ssh].

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#300]
```
Issue running command [gcloud compute ssh].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk/calliope/cli.py", line 589, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk/calliope/backend.py", line 1221, in Run
    resources = command_instance.Run(args)
  File "googlecloudsdk/compute/subcommands/ssh.py", line 113, in Run
    external_ip_address = self.GetInstanceExternalIpAddress(instance_ref)
  File "googlecloudsdk/compute/lib/ssh_utils.py", line 431, in GetInstanceExternalIpAddress
    custom_get_requests=None))
  File "googlecloudsdk/compute/lib/request_helper.py", line 136, in MakeRequests
    requests=requests, http=http, batch_url=batch_url)
  File "googlecloudsdk/compute/lib/batch_helper.py", line 30, in MakeRequests
    responses = batch.Execute(http)
  File "googlecloudsdk/third_party/apitools/base/py/batch.py", line 181, in Execute
    batch_http_request.Execute(http)
  File "googlecloudsdk/third_party/apitools/base/py/batch.py", line 423, in Execute
    self._Execute(http)
  File "googlecloudsdk/third_party/apitools/base/py/batch.py", line 386, in _Execute
    response = http_wrapper.MakeRequest(http, request)
  File "googlecloudsdk/third_party/apitools/base/py/http_wrapper.py", line 310, in MakeRequest
    retry_func(ExceptionRetryArgs(http, http_request, e, retry))
  File "googlecloudsdk/third_party/apitools/base/py/http_wrapper.py", line 302, in MakeRequest
    check_response_func=check_response_func)
[output truncated]

```

Original issue reported on code.google.com by `ramkanna...@gmail.com` on 12 Oct 2015 at 9:48

**Comment by GoogleCodeExporter** [comment]
```
Thanks for reporting this!

Do you mind posting the full output of the `gcloud feedback` command?

Have you ever been able to use the `gcloud compute ssh` command before? Do you 
have any unusual network settings? Are you behind a proxy?
```

Original comment by `z...@google.com` on 12 Oct 2015 at 9:56
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
I have reinstalled the cloudsdk and this issue is not happening now
```

Original comment by `ramkanna...@gmail.com` on 19 Oct 2015 at 5:25
