### ISSUE TITLE
Gcloud ssh error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#301]
```
What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk/calliope/cli.py", line 589, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk/calliope/backend.py", line 1210, in Run
    last_group = context_filter(tool_context, Http, args)
  File "googlecloudsdk/calliope/backend.py", line 578, in ContextFilter
    group.Filter(context, args)
  File "googlecloudsdk/compute/subcommands/__init__.py", line 54, in Filter
    _DoFilter(context, self.Http(), 'v1', args)
  File "googlecloudsdk/calliope/base.py", line 279, in Http
    return self._http_func(auth=auth, creds=creds, **kwargs)
  File "googlecloudsdk/calliope/backend.py", line 1205, in Http
    **kwargs)
  File "googlecloudsdk/core/cli.py", line 121, in Http
    creds = c_store.Load()
  File "googlecloudsdk/core/credentials/store.py", line 249, in Load
    Refresh(cred)
  File "googlecloudsdk/core/credentials/store.py", line 267, in Refresh
    creds.refresh(http or _Http())
  File "oauth2client/client.py", line 597, in refresh
    self._refresh(http.request)
  File "oauth2client/client.py", line 780, in _refresh
    self._do_refresh_request(http_request)
  File "oauth2client/client.py", line 799, in _do_refresh_request
    self.token_uri, method='POST', body=body, headers=headers)
  File "httplib2/__init__.py", line 1608, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
[output truncated]

```

Original issue reported on code.google.com by `nick....@abracontrols.com` on 13 Oct 2015 at 3:46

**Comment by GoogleCodeExporter** [comment]
```
Hi there,

Thanks for reporting this. Do you mind posting the remaining output from the 
`gcloud feedback` command?

Are you behind a firewall, or do you have any other unusual network settings? 
Have you been able to run other `gcloud` commands successfully?

As a workaround, you can use the SSH functionality of the Cloud Developers 
Console (https://console.developers.google.com/).
```

Original comment by `z...@google.com` on 13 Oct 2015 at 3:49
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
Traceback (most recent call last):
  File "/Users/xinzhouliu/google-cloud-sdk/./lib/googlecloudsdk/gcloud/gcloud.py", line 231, in main
    _cli.Execute()
  File "/Users/xinzhouliu/google-cloud-sdk/./lib/googlecloudsdk/calliope/cli.py", line 589, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "/Users/xinzhouliu/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 1210, in Run
    last_group = context_filter(tool_context, Http, args)
  File "/Users/xinzhouliu/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 578, in ContextFilter
    group.Filter(context, args)
  File "/Users/xinzhouliu/google-cloud-sdk/./lib/googlecloudsdk/compute/subcommands/__init__.py", line 54, in Filter
    _DoFilter(context, self.Http(), 'v1', args)
  File "/Users/xinzhouliu/google-cloud-sdk/./lib/googlecloudsdk/calliope/base.py", line 279, in Http
    return self._http_func(auth=auth, creds=creds, **kwargs)
  File "/Users/xinzhouliu/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 1205, in Http
    **kwargs)
  File "/Users/xinzhouliu/google-cloud-sdk/./lib/googlecloudsdk/core/cli.py", line 121, in Http
    creds = c_store.Load()
  File "/Users/xinzhouliu/google-cloud-sdk/./lib/googlecloudsdk/core/credentials/store.py", line 249, in Load
    Refresh(cred)
  File "/Users/xinzhouliu/google-cloud-sdk/./lib/googlecloudsdk/core/credentials/store.py", line 267, in Refresh
    creds.refresh(http or _Http())
  File "/Users/xinzhouliu/google-cloud-sdk/./lib/oauth2client/client.py", line 597, in refresh
    self._refresh(http.request)
  File "/Users/xinzhouliu/google-cloud-sdk/./lib/oauth2client/client.py", line 780, in _refresh
    self._do_refresh_request(http_request)
  File "/Users/xinzhouliu/google-cloud-sdk/./lib/oauth2client/client.py", line 799, in _do_refresh_request
    self.token_uri, method='POST', body=body, headers=headers)
  File "/Users/xinzhouliu/google-cloud-sdk/./lib/httplib2/__init__.py", line 1608, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/Users/xinzhouliu/google-cloud-sdk/./lib/httplib2/__init__.py", line 1350, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/Users/xinzhouliu/google-cloud-sdk/./lib/httplib2/__init__.py", line 1272, in _conn_request
    conn.connect()
  File "/Users/xinzhouliu/google-cloud-sdk/./lib/httplib2/__init__.py", line 1059, in connect
    raise SSLHandshakeError(e)
SSLHandshakeError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed 
(_ssl.c:590)
```

Original comment by `nick....@abracontrols.com` on 13 Oct 2015 at 3:56

**Comment by GoogleCodeExporter** [comment]
```
OS X El Capitan
After upgrade gcloud happen, use iTerm2
```

Original comment by `nick....@abracontrols.com` on 13 Oct 2015 at 3:59

**Comment by GoogleCodeExporter** [comment]
```
It would appear that you're unable to authenticate with Google Cloud Platform 
because of an SSL issue.

Are you able to connect to `https://accounts.google.com` in a browser without 
any security issues? What about from Python generally?
```

Original comment by `z...@google.com` on 14 Oct 2015 at 3:21

**Comment by GoogleCodeExporter** [comment]
```
Today is working again. I have no idea what happen. 

I haven't do any thing yet, even I haven't restart my computer, but it's 
working today.

Nick
```

Original comment by `nick....@abracontrols.com` on 14 Oct 2015 at 3:23

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 4 Jan 2016 at 2:16
- Changed state: **Invalid**
