### ISSUE TITLE
Error while replicating project from repository

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#302]
```
Issue running command [gcloud source repos clone].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\cli.py", line 589, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\backend.py", line 1221, in Run
    resources = command_instance.Run(args)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\exceptions.py", line 96, in TryFunc
    return func(*args, **kwargs)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\source\commands\repos\clone.py", line 79, in Run
    path = project_repo.Clone(destination_path=args.dst or args.src)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\source\lib\git.py", line 203, in Clone
    ['git', 'remote', 'show', 'origin'])
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\core\util\compat26.py", line 30, in check_output
    universal_newlines=universal_newlines, cwd=cwd)
  File "C:\python27_x64\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\python27_x64\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
[output truncated]

```

Original issue reported on code.google.com by `manuel.a...@inswitch.us` on 13 Oct 2015 at 4:48

**Comment by GoogleCodeExporter** [comment]
```
Hi there,

Thanks for reporting this. Do you mind posting the remainder of the traceback, 
along with the other information from `gcloud info`?
```

Original comment by `z...@google.com` on 13 Oct 2015 at 5:19
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
Please re-open with more information if you're still experiencing this issue.
```

Original comment by `z...@google.com` on 18 Feb 2016 at 9:54
- Changed state: **Invalid**
