### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#303]
```
Issue running command [gcloud source repos clone].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\cli.py", line 589, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\backend.py", line 1221, in Run
    resources = command_instance.Run(args)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\exceptions.py", line 96, in TryFunc
    return func(*args, **kwargs)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\source\commands\repos\clone.py", line 79, in Run
    path = project_repo.Clone(destination_path=args.dst or args.src)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\source\lib\git.py", line 203, in Clone
    ['git', 'remote', 'show', 'origin'])
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\core\util\compat26.py", line 30, in check_output
    universal_newlines=universal_newlines, cwd=cwd)
  File "C:\python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

Installation information:

Google Cloud SDK [0.9.81]
[outpu

```

Original issue reported on code.google.com by `krsourab...@gmail.com` on 14 Oct 2015 at 6:07

**Comment by GoogleCodeExporter** [comment]
```
Thanks for reporting this.

It looks as though the Cloud SDK is having trouble finding your `git` 
installation. Do you have git installed? Is it on your %PATH%? In the same 
terminal, if you type `git --version` (no path), what is the output?
```

Original comment by `z...@google.com` on 14 Oct 2015 at 11:55
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
Closing, as we don't have enough information to diagnose this issue.

Please re-open if you're still experiencing this.
```

Original comment by `z...@google.com` on 24 Nov 2015 at 4:42
- Changed state: **Invalid**
