### ISSUE TITLE
gcloud updt

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#304]
```
What steps will reproduce the problem?
gcloud components update

What is the expected output? What do you see instead?
update successful is expected - lots of errors seen

Please provide any additional information below.

|- Creating update staging area                             -|
|============================================================|
Traceback (most recent call last):
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\gcloud\gcloud.py", line 193, in main
    _cli.Execute()
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\cli.py", line 548, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\backend.py", line 1102, in Run
    result = command_instance.Run(args)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\gcloud\sdktools\components\update.py", line 64, in Run
    args.component_ids, allow_no_backup=args.allow_no_backup)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\core\updater\update_manager.py", line 646, in Update
    staging_state = install_state.CloneToStaging(pb.SetProgress)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\core\updater\local_state.py", line 83, in _TryFunc
    return func(*args, **kwargs)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\core\updater\local_state.py", line 293, in CloneToStaging
    dirs.update(manifest.InstalledDirectories())
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\core\updater\local_state.py", line 628, in InstalledDirectories
    with open(self.manifest_file) as f:
IOError: [Errno 2] No such file or directory: 'C:\\Program Files\\Google\\Cloud 
SDK\\google-cloud-sdk\\.install\\bq-win.manifest'


The output of 'gcloud info':

Google Cloud SDK [0.9.71]

Platform: [Windows, x86_64]
Python Version: [2.7.6 (default, Nov 10 2013, 19:24:24) [MSC v.1500 64 bit 
(AMD64)]]
Site Packages: [Disabled]

Installation Root: [C:\Program Files\Google\Cloud SDK\google-cloud-sdk]
Installed Components:
  core: [2015.07.24]
  bq-win: [2.0.18]
  core-win: [2015.07.24]
  gcloud: [2015.07.24]
  windows-ssh-tools: [2015.06.02]
  gsutil: [4.13]
  gsutil-win: [4.13]
  bq: [2.0.18]
[output truncated]

```

Original issue reported on code.google.com by `phillipr...@geotab.com` on 14 Oct 2015 at 4:57
- Merged into: #157

**Comment by GoogleCodeExporter** [comment]
```
Thanks for reporting.

You should be able to work around this by removing the installation directory 
and installing again.
```

Original comment by `z...@google.com` on 14 Oct 2015 at 5:58
- Changed state: **Duplicate**
