### ISSUE TITLE
Deployment problems

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#305]
```
Issue running command [gcloud preview app run].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "calliope/cli.py", line 589, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "calliope/backend.py", line 1221, in Run
    resources = command_instance.Run(args)
  File "appengine/app_commands/run.py", line 335, in Run
    util.FindOrCopyDockerfile(info.runtime, os.path.dirname(info.file))
  File "appengine/lib/images/util.py", line 54, in FindOrCopyDockerfile
    src_data = pkg_resources.GetData(src)
  File "core/util/pkg_resources.py", line 304, in GetData
    raise IOError('File not found {0}'.format(path))
IOError: File not found appengine/dockerfiles/custom_app/Dockerfile

Installation information:

Google Cloud SDK [0.9.82]

Platform: [Linux, x86_64]
Python Version: [2.7.6 (default, Jun 22 2015, 17:58:13)  [GCC 4.8.2]]
Site Packages: [Disabled]

Installation Root: [/home/sherif/google-cloud-sdk]
Installed Components:
  core: [2015.10.08]
  app-engine-python: [1.9.27]
  core-nix: [2015.09.03]
  app-engine-java: [1.9.27]
  gcloud: [2015.10.08]
  gsutil-nix: [4.14]
  app-engine-php: [ ]
  gsutil: [4.15]
  bq: [2.0.18]
  app: [2015.10.08]
  bq-nix: [2.0.18]
[output truncated]

```

Original issue reported on code.google.com by `sherifmo...@gmail.com` on 14 Oct 2015 at 5:03

**Comment by GoogleCodeExporter** [comment]
```
Hey,

Is this a problem deploying or running locally? What's in your app.yaml, and do 
you have a Dockerfile specified in your directory?
```

Original comment by `dlor...@google.com` on 14 Oct 2015 at 5:32

**Comment by GoogleCodeExporter** [comment]
```
Hi,

Thank you for your quick response. This is a problem deploying to the cloud. It 
actually occurs when going through the tutorials, specifically step 5 (Manage 
Python Dependencies). Before that everything deploys fine. I started an 
entirely new project and went through the tutorials again, the same problem is 
then recreated. 

I've attached my app.yaml, main.py, Dockerfile and requirements.txt .

Perhaps one more thing to point out:
In all the previous steps my app wouldn't deploy unless I change the runtime 
from python27 to custom in my app.yaml. Otherwise I would get an error 
indicating that the automatically generated Dockerfile and the runtime are 
incompatible. 


```

Original comment by `sherifmo...@gmail.com` on 14 Oct 2015 at 7:18

Attachments:
- [app.yaml](https://storage.googleapis.com/google-code-attachments/google-cloud-sdk/issue-305/comment-2/app.yaml)
- [Dockerfile](https://storage.googleapis.com/google-code-attachments/google-cloud-sdk/issue-305/comment-2/Dockerfile)
- [main.py](https://storage.googleapis.com/google-code-attachments/google-cloud-sdk/issue-305/comment-2/main.py)
- [requirements.txt](https://storage.googleapis.com/google-code-attachments/google-cloud-sdk/issue-305/comment-2/requirements.txt)

**Comment by GoogleCodeExporter** [comment]
```
Deleting the automatically generated .pyc files solved the issue on the 
previously described error. 
```

Original comment by `sherifmo...@gmail.com` on 14 Oct 2015 at 7:38

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the update. It is very helpful. We will look into this issue so it 
does not reoccur.
```

Original comment by `che...@google.com` on 20 Oct 2015 at 1:01
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
Original comment by `dlor...@google.com` on 20 Nov 2015 at 11:26
- Changed state: **Obsolete**
