### ISSUE TITLE
Crash when running gcloud components update

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#306]
```
Issue running command [gcloud components update].

What steps will reproduce the problem?
I just ran gcloud components update


What is the expected output? What do you see instead?
I expected the components to have been updated. However, I got the crash

Please provide any additional information below.


Traceback (most recent call last):
  File "calliope/cli.py", line 590, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "calliope/backend.py", line 1222, in Run
    resources = command_instance.Run(args)
  File "gcloud/sdktools/components/update.py", line 64, in Run
    args.component_ids, allow_no_backup=args.allow_no_backup)
  File "core/updater/update_manager.py", line 724, in Update
    first=False, last=False)
  File "core/updater/update_manager.py", line 597, in _UpdateWithProgressBar
    action_func(component.id, progress_callback=pb.SetProgress)
  File "core/updater/update_manager.py", line 604, in Inner
    command_path='components.update')
  File "core/updater/local_state.py", line 82, in _TryFunc
    return func(*args, **kwargs)
  File "core/updater/local_state.py", line 485, in Install
    command_path=command_path)
  File "core/updater/installers.py", line 116, in Install
    command_path=command_path)
  File "core/updater/installers.py", line 158, in _InstallTar
    command_path=command_path)
  File "core/updater/installers.py", line 227, in DownloadAndExtractTar
    tar.extract(member, extract_dir)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tarfile.py", line 2109, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
[output truncated]

```

Original issue reported on code.google.com by `kohene...@goodwatercap.com` on 14 Oct 2015 at 9:35

**Comment by GoogleCodeExporter** [comment]
```
Thanks for reporting! Do you mind posting the rest of the traceback? The Google 
Code issue tracker limits the length of pre-populated form data.

You can likely work around by re-installing.
```

Original comment by `z...@google.com` on 14 Oct 2015 at 11:22
- Changed state: **NeedsMoreInfo**
