### ISSUE TITLE
[gcloud init] (crash detected)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#309]
```
Issue running command [gcloud init].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk/calliope/cli.py", line 589, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk/calliope/backend.py", line 1221, in Run
    resources = command_instance.Run(args)
  File "googlecloudsdk/surface/init.py", line 77, in Run
    if not self._PickAccount(args.console_only):
  File "googlecloudsdk/surface/init.py", line 129, in _PickAccount
    disable_user_output=False):
  File "googlecloudsdk/surface/init.py", line 373, in _RunCmd
    return self.cli.Execute(args)
  File "googlecloudsdk/calliope/cli.py", line 589, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk/calliope/backend.py", line 1221, in Run
    resources = command_instance.Run(args)
  File "googlecloudsdk/calliope/exceptions.py", line 96, in TryFunc
    return func(*args, **kwargs)
  File "googlecloudsdk/surface/auth/login.py", line 104, in Run
    creds = self.DoWebFlow(args.launch_browser)
  File "googlecloudsdk/surface/auth/login.py", line 165, in DoWebFlow
    return c_store.AcquireFromWebFlow(launch_browser=launch_browser)
  File "googlecloudsdk/core/credentials/store.py", line 383, in AcquireFromWebFlow
    http=_Http())
  File "googlecloudsdk/core/credentials/flow.py", line 156, in Run
    credential = flow.step2_exchange(code, http=http)
  File "oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
[output truncated]

```

Original issue reported on code.google.com by `car...@idea.me` on 15 Oct 2015 at 1:34

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the report. [gcloud init] essentially runs [gcloud auth login].
I assume you will get same result.

Are you behind some proxy/firewall. Can you tell what kind.

As a workaround you can run
  gcloud auth-login --no-launch-browser

Once authenticated, use [gcloud init] again and select just authenticated 
credentials.
Let us know if that worked for you.

```

Original comment by `che...@google.com` on 16 Oct 2015 at 1:04
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
I'm having the same problem for the past two weeks. I'm a AWS user and wanted 
to switch to Google Cloud - but this problem is stopping me.

I have Anaconda installed (python packages). But for gCloud purposes, I 
installed a fresh version of stand alone python and added it to the path (in 
the beginning). But still getting the same error when I try any gCloud init(or 
gcloud auth-login --no-launch-browser) : "ERROR: gcloud crashed 
(BadStatusLine): ''"

I'm a windows 7 user - and have no problems with the AWS CLI. PLEASE HELP!
```

Original comment by `rset...@gmail.com` on 28 Dec 2015 at 7:21

**Comment by GoogleCodeExporter** [comment]
```
Thanks for reporting an issue. So when you run
  gcloud auth-login --no-launch-browser
you get URL to go to. As you copy paste the url to the browser and login you 
get a code. Once you enter the code is it then you get this error?

Also are you behind proxy/firewall ? If so do you set http_proxy environment 
variable?

Finally can you copy paste output of [gcloud info] this will help us diagnose 
the issue. 
```

Original comment by `che...@google.com` on 29 Dec 2015 at 1:40

**Comment by GoogleCodeExporter** [comment]
```
Hello,
Thanks for the followup. Today i tried to uninstall - and reinstall google 
cloud sdk. The install wizard gives the same error "ERROR: gcloud crashed 
(BadStatusLine): ''"

I'm not behind a proxy/firewall.

If you google the problem you willl see that a LOT of windows users are facing 
the same issue (check stackoverflow). Google is missing a lot of potential 
customers because of this. Pls help.
```

Original comment by `rset...@gmail.com` on 16 Jan 2016 at 12:04

**Comment by GoogleCodeExporter** [comment]
```
Thanks for reporting the issue.

BadStatusLine error is produced by python httplib library.

Can you try alternative installation method:
  https://cloud.google.com/sdk/#install-archive

which does not use installer.

Also if you experience an issue can you include content of
C:\Users\USER\AppData\Roaming\gcloud\logs\* files.

I tried searching stackoverflow for similar issues but could not find. Would 
you mind adding few links with similar issues you found.

Thanks.


```

Original comment by `che...@google.com` on 19 Jan 2016 at 4:17

**Comment by GoogleCodeExporter** [comment]
```
I tried the "Installation from an archive (.zip) on Windows" as suggested above 
- still getting same error. Attaching the command line output and log files.

I tried using standalone python and anaconda python (using PATH) - same error.

16.08.54.456000.log: using normal standalone python
15.36.27.683000.log: using Anaconda distribution of Python


```

Original comment by `rset...@gmail.com` on 24 Jan 2016 at 12:30

Attachments:
- [cmdline output.txt](https://storage.googleapis.com/google-code-attachments/google-cloud-sdk/issue-309/comment-6/cmdline output.txt)
- [16.08.54.456000.log](https://storage.googleapis.com/google-code-attachments/google-cloud-sdk/issue-309/comment-6/16.08.54.456000.log)
- [15.36.27.683000.log](https://storage.googleapis.com/google-code-attachments/google-cloud-sdk/issue-309/comment-6/15.36.27.683000.log)

**Comment by GoogleCodeExporter** [comment]
```
Hi There, Can someone pls respond. I'm about to start a bigdata project - If 
you cannot help me i unfortunately have to go with AWS again.
```

Original comment by `rset...@gmail.com` on 1 Feb 2016 at 6:24

**Comment by GoogleCodeExporter** [comment]
```
Sorry for delayed response. I was just looking into your error.

As I understand you are running install inside GCE VM. Just curious why you 
need to do that, given that GCE instances come preinstalled with it.

But it should still be possible to install/reinstall.
Can you set
 set CLOUDSDK_CORE_CHECK_GCE_METADATA=false
in your environment before installing.

It seems failure is occurring during check to GCE metadata server. This would 
bypass this codepath.
Note that on GCE vms you still want to use service accounts, which what GCE 
metadata server facilitates.

```

Original comment by `che...@google.com` on 1 Feb 2016 at 6:53

**Comment by GoogleCodeExporter** [comment]
```
Hello,

I'm not installing from a GCE VM. I'm directly installing from in window laptop 
running Windows 7.

I tried setting the above environment variable var 
(CLOUDSDK_CORE_CHECK_GCE_METADATA=false): now i'm getting some kind of ssl 
related error. Attaching the logs. Pls help.
```

Original comment by `rset...@gmail.com` on 2 Feb 2016 at 5:28

Attachments:
- [Command line log.txt](https://storage.googleapis.com/google-code-attachments/google-cloud-sdk/issue-309/comment-9/Command line log.txt)
- [21.20.32.066000.log](https://storage.googleapis.com/google-code-attachments/google-cloud-sdk/issue-309/comment-9/21.20.32.066000.log)

**Comment by GoogleCodeExporter** [comment]
```
IS it possible to get on a Google hangout/skype call to resolve this pls?
```

Original comment by `rset...@gmail.com` on 2 Feb 2016 at 5:42

**Comment by GoogleCodeExporter** [comment]
```
I have sent you email privately. We can continue troubleshooting there.
```

Original comment by `che...@google.com` on 2 Feb 2016 at 7:29
