### ISSUE TITLE
Issue running command [gcloud compute instances list]

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#310]
```
Issue running command [gcloud compute instances list].

What steps will reproduce the problem?
in general, running 'gcloud compute' cmds

What is the expected output? What do you see instead?
-List teh existing instances

Please provide any additional information below.


Traceback (most recent call last):
  File "calliope/cli.py", line 589, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "calliope/backend.py", line 1222, in Run
    display.Displayer(command_instance, args, resources).Display()
  File "calliope/display.py", line 76, in Display
    self._command.Display(self._args, self._resources)
  File "compute/lib/base_classes.py", line 319, in Display
    PrintTable(resources, self._resource_spec.table_cols)
  File "compute/lib/base_classes.py", line 53, in PrintTable
    for resource in resources:
  File "compute/lib/base_classes.py", line 304, in Run
    for item in items:
  File "compute/lib/lister.py", line 46, in ProcessResults
    yield field_selector.Apply(resource)
  File "compute/lib/property_selector.py", line 359, in Apply
    res = _DictToOrderedDict(obj)
  File "compute/lib/property_selector.py", line 177, in _DictToOrderedDict
    new_obj = collections.OrderedDict(sorted(obj.items()))
AttributeError: 'module' object has no attribute 'OrderedDict'

Installation information:

Google Cloud SDK [0.9.82]

Platform: [Linux, x86_64]
Python Version: [2.6.9 (unknown, Jul 28 2014, 08:24:16)  [GCC 4.3.4 
[gcc-4_3-branch revision 152973]]]
Site Packages: [Disabled]

Installation Root: [/home/lmccabe/google-cloud-sdk]
Installed Components:
  core: [2015.10.08]
  core-nix: [2015.09.03]
  kubectl: []
  gcloud: [2015.10.08]
  gsutil-nix: [4.14]
[output truncated]

```

Original issue reported on code.google.com by `camelia....@gmail.com` on 15 Oct 2015 at 7:32

**Comment by GoogleCodeExporter** [comment]
```
Hi there,

Thanks for reporting.

The issue appears to be that you're using an old version of Python. While we 
attempt to maintain compatibility with Python 2.6, the Cloud SDK requires 
Python 2.7 for full support. Please upgrade your Python version and try again.
```

Original comment by `z...@google.com` on 15 Oct 2015 at 7:35
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
Original comment by `stephe...@google.com` on 17 Dec 2015 at 6:23
- Added labels: **py2.6**
