### ISSUE TITLE
Installing gcloud 0.9.82 possibly caused issue with importing webapp2 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#312]
```
What steps will reproduce the problem?
After installing the gcloud 0.9.82 it asked me to remove the old version of 
dev_appserver.py located in google app engine launcher. 

When I tried to run "dev_appserver.py ./app.yaml --log_level=debug" again it 
couldn't import webapp2 despite this was mentioned in the app.yaml file.


What is the expected output? What do you see instead?


Please provide any additional information below.


Installation information:

Google Cloud SDK [0.9.82]

Platform: [Mac OS X, x86_64]
Python Version: [2.7.10 (default, Jun  1 2015, 09:44:56)  [GCC 4.2.1 Compatible 
Apple LLVM 6.1.0 (clang-602.0.53)]]
Site Packages: [Disabled]

Installation Root: [/Users/jonathan/google-cloud-sdk]
Installed Components:
  core: [2015.10.08]
  app-engine-python: [1.9.27]
  core-nix: [2015.09.03]
  app-engine-java: [1.9.27]
  gcloud: [2015.10.08]
  gsutil-nix: [4.14]
  app-engine-php: [ ]
  gsutil: [4.15]
  bq: [2.0.18]
  app-engine-php-darwin: [2015.08.17]
  app: [2015.10.08]
  bq-nix: [2.0.18]
System PATH: 
[/Users/jonathan/google-cloud-sdk/bin:/Users/jonathan/.venvburrito/bin:/usr/loca
l/bin:/usr/local/sbin:/Users/jonathan/bin:/usr/bin:/bin:/usr/sbin:/sbin:]
Cloud SDK on PATH: [True]

Installation Properties: [/Users/jonathan/google-cloud-sdk/properties]
User Config Directory: [/Users/jonathan/.config/gcloud]
User Properties: [/Users/jonathan/.config/gcloud/properties]
Current Workspace: [None]
Workspace Config Directory: [None]
Workspace Properties: [None]

Account: [jonathan@boxedice.com]
Project: [clever-span-499]

Current Properties:
  [core]
    project: [clever-span-499]
    account: [jonathan@boxedice.com]
    disable_usage_reporting: [True]
  [app]
    use_appengine_api: [True]

Logs Directory: [/Users/jonathan/.config/gcloud/logs]
[output truncated]

```

Original issue reported on code.google.com by `shinryuu...@gmail.com` on 15 Oct 2015 at 9:12
- Merged into: #294

**Comment by GoogleCodeExporter** [comment]
```
Running tests also gave this:

Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/Users/jonathan/projects/honshuu-console/tests/test_search.py", line 6, in <module>
    from google.appengine.api import users
ImportError: No module named appengine.api
```

Original comment by `shinryuu...@gmail.com` on 15 Oct 2015 at 9:50

**Comment by GoogleCodeExporter** [comment]
Original comment by `dlor...@google.com` on 16 Oct 2015 at 4:43
- Changed state: **Duplicate**
