### ISSUE TITLE
Node.js Hello Word app from https://cloud.google.com/nodejs/getting-started/hello-world deploy does not work

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#313]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\cli.py", line 589, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\backend.py", line 1221, in Run
    resources = command_instance.Run(args)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\appengine\app_commands\deploy.py", line 222, in Run
    remote_build)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\appengine\lib\deploy_command_util.py", line 139, in BuildAndPushDockerImages
    with docker_util.DockerHost(cli, version_id, remote) as docker_client:
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\appengine\lib\images\docker_util.py", line 209, in __enter__
    self._vm = Provision(self._cli, self._name, self._zone)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\appengine\lib\images\docker_util.py", line 44, in Provision
    if _ShouldConfigureNetwork(cli):
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\appengine\lib\images\docker_util.py", line 69, in _ShouldConfigureNetwork
[output truncated]

```

Original issue reported on code.google.com by `gyen...@gmail.com` on 16 Oct 2015 at 12:56
- Merged into: #314

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the report. Would you be able to provide there rest of this 
stacktrace.

If you run [gcloud info] you can see where the log files are located, the trace 
should be part of one of the log files.
```

Original comment by `che...@google.com` on 19 Oct 2015 at 9:01
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
I would like to try Node.js app on Your App Engine. I follow this article 
https://cloud.google.com/nodejs/getting-started/hello-world
When I deploy the sample app, gcloud throw exception, please see the log file 
bellow.
```

Original comment by `gyen...@gmail.com` on 20 Oct 2015 at 6:26

Attachments:
- [14.50.20.277000.log](https://storage.googleapis.com/google-code-attachments/google-cloud-sdk/issue-313/comment-2/14.50.20.277000.log)

**Comment by GoogleCodeExporter** [comment]
```
Thanks for attaching log file. It is very useful to debug the issue.
We are working on a fix. We will update this ticket.

In meantime can you update to latest version. [gcloud components update].

Also by any chance your home path shown by [gcloud info] has non-ascii 
characters.

```

Original comment by `che...@google.com` on 20 Oct 2015 at 11:50

**Comment by GoogleCodeExporter** [comment]
```
Yes, I updated gcloud to the latest version.

Yes it contains one non-ascii character.
```

Original comment by `gyen...@gmail.com` on 20 Oct 2015 at 12:44

**Comment by GoogleCodeExporter** [comment]
```
This issue seems to be similar to 
https://code.google.com/p/google-cloud-sdk/issues/detail?id=314, while it fails 
at different point.

We are working on a fix, and will update this ticket once fix is released.

In meantime can you set (for example)
  set CLOUDSDK_CONFIG=C:\googlecloudsdk
and try the command again.

This will use configuration path which is different from default and without 
non-ascii characters. You will have to re-authenticate, use [gcloud init] to do 
that.

Let us know if this works for you.
```

Original comment by `che...@google.com` on 20 Oct 2015 at 12:56

**Comment by GoogleCodeExporter** [comment]
```
Thank You! It works.
```

Original comment by `gyen...@gmail.com` on 20 Oct 2015 at 1:00

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 20 Nov 2015 at 11:00
- Changed state: **Duplicate**
