### ISSUE TITLE
gcloud init error on an empty directory

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#314]
```
Issue running command [gcloud init].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\cli.py", line 589, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\backend.py", line 1221, in Run
    resources = command_instance.Run(args)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\surface\init.py", line 83, in Run
    self._PickDefaultRegionAndZone()
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\surface\init.py", line 232, in _PickDefaultRegionAndZone
    project_info = self._RunCmd(['compute', 'project-info', 'describe'])
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\surface\init.py", line 373, in _RunCmd
    return self.cli.Execute(args)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\cli.py", line 589, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\backend.py", line 1221, in Run
    resources = command_instance.Run(args)
[output truncated]

```

Original issue reported on code.google.com by `gyen...@gmail.com` on 16 Oct 2015 at 1:20

**Comment by GoogleCodeExporter** [comment]
```
This looks like same issue as 
https://code.google.com/p/google-cloud-sdk/issues/detail?id=319
```

Original comment by `che...@google.com` on 19 Oct 2015 at 8:59
- Changed state: **Duplicate**

**Comment by GoogleCodeExporter** [comment]
```
I run gcloud init in the empty directory.

I attach the log file.
```

Original comment by `gyen...@gmail.com` on 20 Oct 2015 at 6:20

Attachments:
- [13.09.17.791000.log](https://storage.googleapis.com/google-code-attachments/google-cloud-sdk/issue-314/comment-2/13.09.17.791000.log)

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the report, log is very useful.

By any chance your home directory path have any non-ascii characters.


```

Original comment by `che...@google.com` on 20 Oct 2015 at 12:32

**Comment by GoogleCodeExporter** [comment]
```
Yes it contains one non-ascii character.
```

Original comment by `gyen...@gmail.com` on 20 Oct 2015 at 12:44

**Comment by GoogleCodeExporter** [comment]
```
We are working on a fix, and will update this ticket once fix is released.

In meantime you can set (for example)
  set CLOUDSDK_CONFIG=C:\googlecloudsdk
and try the command again.
This will use configuration path which is different from default and without 
non-ascii characters. You will have to re-authenticate, use [gcloud init] to do 
that.

```

Original comment by `che...@google.com` on 20 Oct 2015 at 12:52
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
It works.
Thank You!
```

Original comment by `gyen...@gmail.com` on 20 Oct 2015 at 1:01

**Comment by GoogleCodeExporter** [comment]
```
Issue 313 has been merged into this issue.
```

Original comment by `z...@google.com` on 20 Nov 2015 at 11:00
