### ISSUE TITLE
gcloud init

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#317]
```
Too tired to fill out the questions... If you email me asking for more info, I 
will email you back tomorrow. Cheers.


Issue running command [gcloud init].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "calliope/cli.py", line 589, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "calliope/backend.py", line 1221, in Run
    resources = command_instance.Run(args)
  File "surface/init.py", line 83, in Run
    self._PickDefaultRegionAndZone()
  File "surface/init.py", line 232, in _PickDefaultRegionAndZone
    project_info = self._RunCmd(['compute', 'project-info', 'describe'])
  File "surface/init.py", line 373, in _RunCmd
    return self.cli.Execute(args)
  File "calliope/cli.py", line 589, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "calliope/backend.py", line 1221, in Run
    resources = command_instance.Run(args)
  File "compute/lib/base_classes.py", line 659, in Run
    resources = list(self.ComputeDynamicProperties(args, resources))
  File "compute/lib/lister.py", line 46, in ProcessResults
    yield field_selector.Apply(resource)
  File "compute/lib/property_selector.py", line 359, in Apply
    res = _DictToOrderedDict(obj)
  File "compute/lib/property_selector.py", line 177, in _DictToOrderedDict
    new_obj = collections.OrderedDict(sorted(obj.items()))
AttributeError: 'module' object has no attribute 'OrderedDict'

Installation information:

Google Cloud SDK [0.9.82]

Platform: [Linux, x86_64]
Python Version: [2.6.5 (r265:79063, Apr 16 2010, 13:57:41)  [GCC 4.4.3]]
Site Packages: [Disabled]

[output truncated]

```

Original issue reported on code.google.com by `Hickory...@gmail.com` on 18 Oct 2015 at 10:57

**Comment by GoogleCodeExporter** [comment]
```
Looks like you're using a 2.6 version of Python; the Cloud SDK only officially 
supports 2.7+. If you switch to such a version, you'll have no issues.
```

Original comment by `z...@google.com` on 18 Oct 2015 at 11:27

**Comment by GoogleCodeExporter** [comment]
```
Just curious if using python 2.6 is requirement for you.
```

Original comment by `che...@google.com` on 19 Oct 2015 at 8:56
- Changed state: **WontFix**
