### ISSUE TITLE
Error message for [gcloud init] when Compute API is not enabled.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#319]
```
Issue running command [gcloud init].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "calliope/cli.py", line 589, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "calliope/backend.py", line 1221, in Run
    resources = command_instance.Run(args)
  File "compute/lib/base_classes.py", line 664, in Run
    error_message='Could not fetch resource:')
  File "compute/lib/utils.py", line 96, in RaiseToolException
    RaiseException(problems, calliope_exceptions.ToolException, error_message)
  File "compute/lib/utils.py", line 108, in RaiseException
    errors))
ToolException: Could not fetch resource:
 - Access Not Configured. The API (Compute Engine API) is not enabled for your project. Please use the Google Developers Console to update your configuration.

Installation information:

Google Cloud SDK [0.9.82]

Platform: [Mac OS X, x86_64]
Python Version: [2.7.10 (default, Aug 22 2015, 20:33:39)  [GCC 4.2.1 Compatible 
Apple LLVM 7.0.0 (clang-700.0.59.1)]]
Site Packages: [Disabled]

Installation Root: [/Users/huampoyotl/google-cloud-sdk]
Installed Components:
  core: [2015.10.08]
  core-nix: [2015.09.03]
  kubectl: []
  gcloud: [2015.10.08]
  gsutil-nix: [4.14]
  gsutil: [4.15]
  bq: [2.0.18]
  bq-nix: [2.0.18]
  kubectl-darwin-x86_64: [1.0.6]
System PATH: 
[/Users/huampoyotl/google-cloud-sdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/
sbin]
Cloud SDK on PATH: [True]

[output truncated]

```

Original issue reported on code.google.com by `and...@generaweb.net` on 19 Oct 2015 at 7:15

**Comment by GoogleCodeExporter** [comment]
```
Thanks for reporting the issue. The message is a little cryptic, but this error 
occured because command was not able to get compute info on your project.

You can enable compute api for your project via (replace YOUR_PROJECT_NAME):
  https://console.developers.google.com/project/YOUR_PROJECT_NAME/apiui/apiview/compute_component/overview

will make sure to fix error message.

Let us know if it worked for you.





```

Original comment by `che...@google.com` on 19 Oct 2015 at 7:48
- Changed title: **Error message for [gcloud init] when Compute API is not enabled.**
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
Issue 314 has been merged into this issue.
```

Original comment by `che...@google.com` on 19 Oct 2015 at 8:59
