### ISSUE TITLE
Not able to find instances

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#320]
```
What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\cli.py", line 589, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\backend.py", line 1210, in Run
    last_group = context_filter(tool_context, Http, args)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\backend.py", line 578, in ContextFilter
    group.Filter(context, args)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\compute\subcommands\__init__.py", line 54, in Filter
    _DoFilter(context, self.Http(), 'v1', args)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\base.py", line 279, in Http
    return self._http_func(auth=auth, creds=creds, **kwargs)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\backend.py", line 1205, in Http
    **kwargs)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\core\cli.py", line 121, in Http
    creds = c_store.Load()
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\core\credentials\store.py", line 237, in Load
[output truncated]

```

Original issue reported on code.google.com by `gersh...@jsleads.com` on 20 Oct 2015 at 2:49

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the report. Can you say which command you were trying to run.

Would it be possible to attach a log file with this crash information?
If you run [gcloud info] it will tell you location of log files.
```

Original comment by `che...@google.com` on 20 Oct 2015 at 1:00
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 4 Jan 2016 at 2:18
- Changed state: **Invalid**
