### ISSUE TITLE
Failed to run [compute project-info describe]

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#323]
```
Issue running command [gcloud init].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\cli.py", line 589, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\backend.py", line 1221, in Run
    resources = command_instance.Run(args)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\surface\init.py", line 83, in Run
    self._PickDefaultRegionAndZone()
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\surface\init.py", line 232, in _PickDefaultRegionAndZone
    project_info = self._RunCmd(['compute', 'project-info', 'describe'])
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\surface\init.py", line 373, in _RunCmd
    return self.cli.Execute(args)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\cli.py", line 589, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\backend.py", line 1210, in Run
    last_group = context_filter(tool_context, Http, args)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\backend.py", line 578, in ContextFilter
[output tru

```

Original issue reported on code.google.com by `o.ram...@gmail.com` on 21 Oct 2015 at 7:10

**Comment by GoogleCodeExporter** [comment]
```
Thanks for reporting the issues.

Does the project you entered/selected in [gcloud init] have "Compute Engine 
APIs" enabled?
```

Original comment by `che...@google.com` on 22 Oct 2015 at 1:07
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
Issue 384 has been merged into this issue.
```

Original comment by `che...@google.com` on 11 Nov 2015 at 12:29

**Comment by GoogleCodeExporter** [comment]
```
Closing as we don't have enough information to diagnose.

Please re-open if you can provide the requested information.
```

Original comment by `z...@google.com` on 9 Feb 2016 at 2:08
- Changed state: **Invalid**
