### ISSUE TITLE
deploy dart appengine app crashes

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#324]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk/calliope/cli.py", line 589, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk/calliope/backend.py", line 1221, in Run
    resources = command_instance.Run(args)
  File "googlecloudsdk/appengine/app_commands/deploy.py", line 222, in Run
    remote_build)
  File "googlecloudsdk/appengine/lib/deploy_command_util.py", line 150, in BuildAndPushDockerImages
    info.file, docker_client, image_name)
  File "googlecloudsdk/appengine/lib/deploy_command_util.py", line 181, in BuildAndPushDockerImage
    image.Build(docker_client)
  File "googlecloudsdk/appengine/lib/docker_image.py", line 94, in Build
    nocache=self._nocache, rm=self._rm, pull=False)
  File "docker/docker/client.py", line 394, in build
    timeout=timeout,
  File "docker/docker/client.py", line 103, in _post
    return self.post(url, **self._set_request_timeout(kwargs))
  File "requests/sessions.py", line 507, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))

[output truncated]

```

Original issue reported on code.google.com by `tomasz.k...@moocode.net` on 21 Oct 2015 at 8:41

**Comment by GoogleCodeExporter** [comment]
```
Is this error reproducible? "Connection reset by peer" is usually transient. We 
will look into catching this error.
```

Original comment by `stephe...@google.com` on 9 Nov 2015 at 3:11
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
Original comment by `stephe...@google.com` on 9 Nov 2015 at 3:12
- Added labels: **Priority-Low**
- Removed labels: **Priority-Medium**

**Comment by GoogleCodeExporter** [comment]
```
Closing as we don't have enough information to diagnose the issue. Please 
re-open if you encounter this problem again.
```

Original comment by `z...@google.com` on 20 Nov 2015 at 11:01
- Changed state: **Invalid**

**Comment by GoogleCodeExporter** [comment]
```
never happend to me again - closing is ok
```

Original comment by `tomasz.k...@moocode.net` on 21 Nov 2015 at 7:45
