### ISSUE TITLE
gcloud auth login - causing issues

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#330]
```
Issue running command [gcloud auth login].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\cli.py", line 589, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\backend.py", line 1221, in Run
    resources = command_instance.Run(args)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\exceptions.py", line 96, in TryFunc
    return func(*args, **kwargs)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\surface\auth\login.py", line 104, in Run
    creds = self.DoWebFlow(args.launch_browser)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\surface\auth\login.py", line 165, in DoWebFlow
    return c_store.AcquireFromWebFlow(launch_browser=launch_browser)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\core\credentials\store.py", line 383, in AcquireFromWebFlow
    http=_Http())
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\core\credentials\flow.py", line 156, in Run
    credential = flow.step2_exchange(code, http=http)
[output truncated]

```

Original issue reported on code.google.com by `pal.ragh...@gmail.com` on 22 Oct 2015 at 7:25

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the report. By any chance you are behind some proxy/firewall, if so 
what kind?

Can you use [gcloud auth login --no-launch-browser] workflow. You will have to 
copy paste the link to the browser yourself, and then paste back the code.
```

Original comment by `che...@google.com` on 22 Oct 2015 at 12:51
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
Issue 338 has been merged into this issue.
```

Original comment by `che...@google.com` on 10 Nov 2015 at 12:44

**Comment by GoogleCodeExporter** [comment]
```
Issue 380 has been merged into this issue.
```

Original comment by `che...@google.com` on 10 Nov 2015 at 12:44

**Comment by GoogleCodeExporter** [comment]
```
Issue 401 has been merged into this issue.
```

Original comment by `z...@google.com` on 24 Nov 2015 at 4:46

**Comment by GoogleCodeExporter** [comment]
```
Issue 386 has been merged into this issue.
```

Original comment by `z...@google.com` on 24 Nov 2015 at 5:53
