### ISSUE TITLE
SSL Error intermittently 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#334]
```
Issue running command [gcloud compute instances list].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk/calliope/cli.py", line 592, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk/calliope/backend.py", line 1224, in Run
    display.Displayer(command_instance, args, resources).Display()
  File "googlecloudsdk/calliope/display.py", line 76, in Display
    self._command.Display(self._args, self._resources)
  File "googlecloudsdk/shared/compute/base_classes.py", line 313, in Display
    PrintTable(resources, self._resource_spec.table_cols)
  File "googlecloudsdk/shared/compute/base_classes.py", line 51, in PrintTable
    for resource in resources:
  File "googlecloudsdk/shared/compute/base_classes.py", line 298, in Run
    for item in items:
  File "googlecloudsdk/shared/compute/lister.py", line 41, in ProcessResults
    for resource in resources:
  File "googlecloudsdk/shared/compute/lister.py", line 13, in _ConvertProtobufsToDicts
    for resource in resources:
  File "googlecloudsdk/shared/compute/base_classes.py", line 230, in FilterResults
    for item in items:
  File "googlecloudsdk/shared/compute/request_helper.py", line 127, in MakeRequests
    requests=requests, http=http, batch_url=batch_url, errors=errors):
  File "googlecloudsdk/shared/compute/request_helper.py", line 45, in _List
    batch_url=batch_url)
  File "googlecloudsdk/shared/compute/batch_helper.py", line 30, in MakeRequests
    responses = batch.Execute(http)
[output truncated]



```

Original issue reported on code.google.com by `kannan.r...@macys.com` on 22 Oct 2015 at 9:59

**Comment by GoogleCodeExporter** [comment]
```
Thank you for the feedback. Could you please: 

1) Provide the output of gcloud info (after stripping out private data)
2) Provide the full stack trace of the error

Thanks.
```

Original comment by `vil...@google.com` on 22 Oct 2015 at 11:00
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
Google Cloud SDK [0.9.83]

Platform: [Mac OS X, x86_64]
Python Version: [2.7.5 (default, Mar  9 2014, 22:15:05)  [GCC 4.2.1 Compatible 
Apple LLVM 5.0 (clang-500.0.68)]]
Site Packages: [Disabled]

Installation Root: [/Users/xx/Documents/googlecloud/google-cloud-sdk]
Installed Components:
  core: [2015.10.16]
  core-nix: [2015.09.03]
  gcloud: [2015.10.16]
  gsutil-nix: [4.14]
  gsutil: [4.15]
  bq: [2.0.18]
  bq-nix: [2.0.18]
System PATH: 
[/usr/local/heroku/bin:/Users/xx/Documents/googlecloud/google-cloud-sdk/bin:/Use
rs/xx/.rbenv/shims:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/git/b
in:/opt/oracle/instantclient_10_2:/opt/subversion/bin:/stella/liquibase/liquibas
e-3.2.2-bin:/Users/xx/stuff/scala/scala-2.11.2/bin:/opt/apache-maven-3.2.3/bin:/
opt/apache-jmeter-2.12/bin:/opt/gradle-2.4/bin]
Cloud SDK on PATH: [True]

Installation Properties: 
[/Users/xx/Documents/googlecloud/google-cloud-sdk/properties]
User Config Directory: [/Users/xx/.config/gcloud]
User Properties: [/Users/xx/.config/gcloud/properties]
Current Workspace: [None]
Workspace Config Directory: [None]
Workspace Properties: [None]

Account: [xx]
Project: [stealth-project]

Current Properties:
  [core]
    project: [stealth-project]
    account: [xx]
    disable_usage_reporting: [False]
  [app]
    use_appengine_api: [True]
  [compute]
    zone: [us-central1-f]

Logs Directory: [/Users/xx/.config/gcloud/logs]
Last Log File: [/Users/xx/.config/gcloud/logs/2015.10.22/16.15.32.140678.log]

```

Original comment by `kannan.r...@macys.com` on 22 Oct 2015 at 11:18

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the output of gcloud info. Could you also provide the full traceback 
(you can find it in the log files at /Users/xx/.config/gcloud/logs/*)?

SSL errors are usually the result of problems in network connectivity. Have you 
been experiencing general network issues?
```

Original comment by `vil...@google.com` on 23 Oct 2015 at 5:02

**Comment by GoogleCodeExporter** [comment]
```
Thanks your help. Even we are thing it is the network issue.But we don't have 
enough detail to confirm it is  network issue or am I missing something during 
setup. I am attaching the log file with mail.
```

Original comment by `kannan.r...@macys.com` on 23 Oct 2015 at 8:27

**Comment by GoogleCodeExporter** [comment]
Original comment by `kannan.r...@macys.com` on 3 Nov 2015 at 10:33

**Comment by GoogleCodeExporter** [comment]
Original comment by `kannan.r...@macys.com` on 3 Nov 2015 at 10:35

Attachments:
- [google.log](https://storage.googleapis.com/google-code-attachments/google-cloud-sdk/issue-334/comment-6/google.log)

**Comment by GoogleCodeExporter** [comment]
```
We now handle this error more intelligently and print relevant network 
information. It looks like this was the result of a network issue from your 
logs.

Thanks for reporting!
```

Original comment by `z...@google.com` on 4 Jan 2016 at 2:20
- Changed state: **Obsolete**
