### ISSUE TITLE
Gcloud init issue

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#335]
```
Issue running command [gcloud init].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\cli.py", line 592, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\backend.py", line 1223, in Run
    resources = command_instance.Run(args)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\surface\init.py", line 77, in Run
    if not self._PickAccount(args.console_only):
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\surface\init.py", line 129, in _PickAccount
    disable_user_output=False):
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\surface\init.py", line 373, in _RunCmd
    return self.cli.Execute(args)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\cli.py", line 592, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\backend.py", line 1223, in Run
    resources = command_instance.Run(args)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\exceptions.py", line 98, in TryFunc
[output trunca

```

Original issue reported on code.google.com by `trustbox...@gmail.com` on 23 Oct 2015 at 8:24

**Comment by GoogleCodeExporter** [comment]
```
Thanks for reporting the issues.

Traceback is cut off, but it looks like it failed to run [gcloud auth login].
By any chance you are behind proxy/firewall? If so what kind?

Can you run [gcloud auth login --no-launch-browser] and manually authenticate.
Than run [gcloud init] and select authenticated account to continue.

Also it would be great if you can include/attach log of above failure. You can 
run [gcloud info] to see location of the log files.

Let us know if any of this works for you.


```

Original comment by `che...@google.com` on 23 Oct 2015 at 10:53
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
Closing, as we don't have enough information to diagnose this issue.

Please re-open if you're still experiencing this.
```

Original comment by `z...@google.com` on 24 Nov 2015 at 4:41
- Changed state: **Invalid**
