### ISSUE TITLE
gcloud init issues

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#338]
```
Issue running command [gcloud init].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk/calliope/cli.py", line 592, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk/calliope/backend.py", line 1223, in Run
    resources = command_instance.Run(args)
  File "googlecloudsdk/surface/init.py", line 77, in Run
    if not self._PickAccount(args.console_only):
  File "googlecloudsdk/surface/init.py", line 129, in _PickAccount
    disable_user_output=False):
  File "googlecloudsdk/surface/init.py", line 373, in _RunCmd
    return self.cli.Execute(args)
  File "googlecloudsdk/calliope/cli.py", line 592, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk/calliope/backend.py", line 1223, in Run
    resources = command_instance.Run(args)
  File "googlecloudsdk/calliope/exceptions.py", line 98, in TryFunc
    return func(*args, **kwargs)
  File "googlecloudsdk/surface/auth/login.py", line 111, in Run
    creds = self.DoWebFlow(args.launch_browser)
  File "googlecloudsdk/surface/auth/login.py", line 176, in DoWebFlow
    return c_store.AcquireFromWebFlow(launch_browser=launch_browser)
  File "googlecloudsdk/core/credentials/store.py", line 383, in AcquireFromWebFlow
    http=_Http())
  File "googlecloudsdk/core/credentials/flow.py", line 156, in Run
    credential = flow.step2_exchange(code, http=http)
  File "oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
[output truncated]

```

Original issue reported on code.google.com by `gdev.fa1...@gmail.com` on 24 Oct 2015 at 9:11
- Merged into: #330

**Comment by GoogleCodeExporter** [comment]
Original comment by `che...@google.com` on 10 Nov 2015 at 12:44
- Changed state: **Duplicate**
