### ISSUE TITLE
couldn't deploy nodejs tutorial app using mongodb - localhost worked fine

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#341]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "calliope/cli.py", line 590, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "calliope/backend.py", line 1222, in Run
    resources = command_instance.Run(args)
  File "appengine/app_commands/deploy.py", line 220, in Run
    remote_build)
  File "appengine/lib/deploy_command_util.py", line 128, in BuildAndPushDockerImages
    cleanup = ensure_dockerfile()
  File "appengine/lib/deploy_command_util.py", line 68, in GenerateDockerfile
    return configurator.GenerateConfigs()
  File "appengine/lib/runtimes/nodejs.py", line 160, in GenerateConfigs
    cleanup=self.deploy)
  File "appengine/lib/images/util.py", line 52, in FindOrCopyDockerfile
    return _CopyDefaultDockerfile(runtime, dst, cleanup)
  File "appengine/lib/images/util.py", line 145, in _CopyDefaultDockerfile
    with open(os.path.join(dst, os.path.basename(src)), 'w') as dst_file:
IOError: [Errno 13] Permission denied: 
'/Users/alper/Sandbox/gcloud/2-structured-data/Dockerfile'

Installation information:

Google Cloud SDK [0.9.80]

Platform: [Mac OS X, x86_64]
Python Version: [2.7.10 (default, Aug 29 2015, 00:14:10)  [GCC 4.2.1 Compatible 
Apple LLVM 6.0 (clang-600.0.54)]]
Site Packages: [Disabled]

Installation Root: [/Users/alper/google-cloud-sdk]
Installed Components:
  core: [2015.09.25]
  core-nix: [2015.09.03]
  app: [2015.09.25]
  gcloud: [2015.09.25]
[output truncated]

```

Original issue reported on code.google.com by `pekdem...@gmail.com` on 25 Oct 2015 at 3:41

**Comment by GoogleCodeExporter** [comment]
```
Hey,

In this case, gcloud is attempting to write a temporary file to your directory 
as part of the deployment, but it looks like gcloud doesn't have permission to 
write to this directory. We have some ongoing work that will allow us to skip 
writing this file to disk, but until then you'll probably have to make sure 
gcloud has permission to write to this directory.
```

Original comment by `dlor...@google.com` on 26 Oct 2015 at 1:01

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the help
```

Original comment by `pekdem...@gmail.com` on 26 Oct 2015 at 2:11

**Comment by GoogleCodeExporter** [comment]
```
Happy to help. I'll close this out since we're tracking the other fix elsewhere.
```

Original comment by `dlor...@google.com` on 26 Oct 2015 at 1:11

**Comment by GoogleCodeExporter** [comment]
Original comment by `dlor...@google.com` on 26 Oct 2015 at 1:11
- Changed state: **WorkingAsIntended**
