### ISSUE TITLE
trying to log into my instance using gcloud crashes

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#342]
```
What steps will reproduce the problem?

gcloud compute --project "testweb1ari" ssh --zone "us-central1-a" "instance-1"

What is the expected output? What do you see instead?

I should be able to log into the server
Please provide any additional information below.

This used to work but no longer does.
gcutil --service_version="v1" --project="testweb1ari" ssh  
--zone="us-central1-a" "instance-1"

gcutil is no longer on the system (my local machine)




Traceback (most recent call last):
  File "calliope/cli.py", line 580, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "calliope/backend.py", line 1113, in Run
    last_group = context_filter(tool_context, Http, args)
  File "calliope/backend.py", line 484, in ContextFilter
    group.Filter(context, args)
  File "compute/subcommands/__init__.py", line 54, in Filter
    _DoFilter(context, self.Http(), 'v1', args)
  File "calliope/base.py", line 278, in Http
    return self._http_func(auth=auth, creds=creds, **kwargs)
  File "calliope/backend.py", line 1108, in Http
    **kwargs)
  File "core/cli.py", line 110, in Http
    gcloud_ua = MakeUserAgentString(cmd_path)
  File "core/cli.py", line 63, in MakeUserAgentString
    platform.python_version(),
  File "/usr/lib/python2.7/platform.py", line 1508, in python_version
    return _sys_version()[1]
  File "/usr/lib/python2.7/platform.py", line 1463, in _sys_version
    repr(sys_version))
ValueError: failed to parse CPython sys.version: '2.7.6 | 64-bit | (default, 
Sep 15 2014, 17:43:19) \n[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]'

Installation information:

Google Cloud SDK [0.9.76]

Platform: [Mac OS X, x86_64]
Python Version: [2.7.6 | 64-bit | (default, Sep 15 2014, 17:43:19)  [GCC 4.2.1 
(Apple Inc. build 5666) (dot 3)]]
Site Packages: [Enabled]

Installation Root: [/Users/aspivakovsky/google-cloud-sdk]
Installed Components:
[output truncated]

```

Original issue reported on code.google.com by `aspivako...@gmail.com` on 25 Oct 2015 at 11:17

**Comment by GoogleCodeExporter** [comment]
```
Sorry This is a duplicate ticket

A different Python distribution was being called.

export CLOUDSDK_PYTHON=/usr/bin/python

fixes the problem for me


```

Original comment by `aspivako...@gmail.com` on 25 Oct 2015 at 12:14

**Comment by GoogleCodeExporter** [comment]
```
Thanks for updating.
```

Original comment by `z...@google.com` on 25 Oct 2015 at 9:44
- Changed state: **WorkingAsIntended**
