### ISSUE TITLE
Problem with intialising gcloud init command

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#345]
```
Issue running command [gcloud init].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\cli.py", line 592, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\backend.py", line 1223, in Run
    resources = command_instance.Run(args)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\surface\init.py", line 77, in Run
    if not self._PickAccount(args.console_only):
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\surface\init.py", line 129, in _PickAccount
    disable_user_output=False):
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\surface\init.py", line 373, in _RunCmd
    return self.cli.Execute(args)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\cli.py", line 592, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\backend.py", line 1223, in Run
    resources = command_instance.Run(args)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\exceptions.py", line 98, in TryFunc
[output trunca

```

Original issue reported on code.google.com by `bhargav...@gmail.com` on 26 Oct 2015 at 11:55

**Comment by GoogleCodeExporter** [comment]
```
Thank you for the feedback. Can you please provide:

1) The output of gcloud info (with any private information redacted).
2) The full output/message/traceback that was displayed when you ran 'gcloud 
init'.

```

Original comment by `vil...@google.com` on 26 Oct 2015 at 8:21
- Changed state: **NeedsMoreInfo**
