### ISSUE TITLE
I can't use gcloud anymore???? This happened after I updated

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#347]
```
Issue running command [gcloud init].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "calliope/cli.py", line 592, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "calliope/backend.py", line 1223, in Run
    resources = command_instance.Run(args)
  File "surface/init.py", line 83, in Run
    self._PickDefaultRegionAndZone()
  File "surface/init.py", line 232, in _PickDefaultRegionAndZone
    project_info = self._RunCmd(['compute', 'project-info', 'describe'])
  File "surface/init.py", line 355, in _RunCmd
    if not self.cli.IsValidCommand(cmd):
  File "calliope/cli.py", line 526, in IsValidCommand
    return self.__top_element.IsValidSubPath(cmd)
  File "calliope/backend.py", line 775, in IsValidSubPath
    current = current.LoadSubElement(part)
  File "calliope/backend.py", line 1107, in LoadSubElement
    self._config_hooks, parent_group=self, allow_empty=allow_empty)
  File "calliope/backend.py", line 925, in __init__
    self._GetModuleFromPath(module_dir, module_path, path, construction_id),
  File "calliope/backend.py", line 843, in _GetModuleFromPath
    name_to_give, os.path.join(module_dir, *module_path))
  File "core/util/pkg_resources.py", line 97, in GetModuleFromPath
    module = imp.load_module(name_to_give, f, file_path, items)
  File "compute/subcommands/__init__.py", line 12, in <module>
    from googlecloudsdk.compute.lib import utils as internal_utils
  File "compute/lib/utils.py", line 20, in <module>

[output truncated]

```

Original issue reported on code.google.com by `abramsjo...@gmail.com` on 26 Oct 2015 at 11:22

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the report.

It seems the stack trace is cut short, would it be possible to attach full log 
of this error. If you run [gcloud info] it should show location of log files.

But from what I can see that this failed when executing [gcloud compute 
project-info describe].

Two questions:
  1. When you entered project id by any chance you had a typo?
  2. If not does your project have Compute Engine API enabled?


```

Original comment by `che...@google.com` on 27 Oct 2015 at 12:17
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 4 Jan 2016 at 2:11
- Changed state: **Invalid**
