### ISSUE TITLE
I do not know what is happening

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#348]
```
Issue running command [gcloud compute ssh].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "calliope/cli.py", line 592, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "calliope/backend.py", line 1223, in Run
    resources = command_instance.Run(args)
  File "compute/subcommands/ssh.py", line 154, in Run
    use_account_service=self._use_accounts_service)
  File "shared/compute/ssh_utils.py", line 486, in ActuallyRun
    _RunExecutable(cmd_args, interactive_ssh=interactive_ssh)
  File "shared/compute/ssh_utils.py", line 113, in _RunExecutable
    raise SshLikeCmdFailed(cmd_args[0], return_code=e.returncode)
SshLikeCmdFailed: [/usr/bin/ssh] exited with return code [255]. See 
https://cloud.google.com/compute/docs/troubleshooting#ssherrors for 
troubleshooting hints.

Installation information:

Google Cloud SDK [0.9.83]

Platform: [Mac OS X, x86_64]
Python Version: [2.7.10 |Anaconda 2.3.0 (x86_64)| (default, Sep 15 2015, 
14:29:08)  [GCC 4.2.1 (Apple Inc. build 5577)]]
Site Packages: [Disabled]

Installation Root: [/Users/xiaohei/google-cloud-sdk]
Installed Components:
  core: [2015.10.16]
  core-nix: [2015.09.03]
  gcloud: [2015.10.16]
  gsutil-nix: [4.14]
  gsutil: [4.15]
  bq: [2.0.18]
  bq-nix: [2.0.18]
[output truncated]

```

Original issue reported on code.google.com by `bo.no...@gmail.com` on 27 Oct 2015 at 7:03

**Comment by GoogleCodeExporter** [comment]
```
Can you send the error message? thanks
```

Original comment by `gsfow...@google.com` on 4 Nov 2015 at 5:03
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 4 Jan 2016 at 2:11
- Changed state: **Invalid**
