### ISSUE TITLE
Crash when install on drive C, run on like E

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#349]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\cli.py", line 592, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\backend.py", line 1223, in Run
    resources = command_instance.Run(args)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\appengine\app_commands\deploy.py", line 259, in Run
    remote_build)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\appengine\lib\deploy_command_util.py", line 143, in BuildAndPushDockerImages
    with docker_util.DockerHost(cli, version_id, remote) as docker_client:
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\appengine\lib\images\docker_util.py", line 209, in __enter__
    self._vm = Provision(self._cli, self._name, self._zone)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\appengine\lib\images\docker_util.py", line 52, in Provision
    vm = _CreateVm(cli, name, zone)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\appengine\lib\images\docker_util.py", line 107, in _CreateVm
    return _Vm(cli, vm_info[0])
[output truncated]

```

Original issue reported on code.google.com by `son.ngu...@cvisionhk.com` on 28 Oct 2015 at 3:54
- Merged into: #258

**Comment by GoogleCodeExporter** [comment]
Original comment by `gsfow...@google.com` on 4 Nov 2015 at 2:58
- Changed state: **Duplicate**
