### ISSUE TITLE
Gcloud components update exception

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#35]
```
What steps will reproduce the problem?

> gcloud -version
Google Cloud SDK 0.9.21
> gcloud components update

Creating update staging area...

Traceback (most recent call last):
  File "/usr/local/nexus/tools/google-cloud-sdk/bin/.././lib/googlecloudsdk/gcloud/gcloud.py", line 105, in <module>
    main()


What is the expected output? What do you see instead?

Not a Python stack trace

What is the output of 'gcloud version'?

Google Cloud SDK 0.9.21

bq 2.0.18
bq-nix 2.0.18
core 2014.04.08
core-nix 2014.04.08
gae-go-darwin-x86_64 1.9.3
gae-java 1.9.3
gae-java-nix 1.8.9
gae-python 1.9.3
gae-python-launcher-mac 1.9.3
gcutil 1.15.0
gcutil-nix 1.13.0
gsutil 3.42
gsutil-nix 3.42
sql 2014.04.15


Please provide any additional information below.

Creating update staging area...

Traceback (most recent call last):
  File "/usr/local/nexus/tools/google-cloud-sdk/bin/.././lib/googlecloudsdk/gcloud/gcloud.py", line 105, in <module>
    main()
  File "/usr/local/nexus/tools/google-cloud-sdk/bin/.././lib/googlecloudsdk/gcloud/gcloud.py", line 101, in main
    _loader.Execute()
  File "/usr/local/nexus/tools/google-cloud-sdk/bin/.././lib/googlecloudsdk/calliope/__init__.py", line 1460, in Execute
    post_run_hooks=self.__post_run_hooks, kwargs=kwargs)
  File "/usr/local/nexus/tools/google-cloud-sdk/bin/.././lib/googlecloudsdk/calliope/__init__.py", line 1084, in _Execute
    pre_run_hooks=pre_run_hooks, post_run_hooks=post_run_hooks)
  File "/usr/local/nexus/tools/google-cloud-sdk/bin/.././lib/googlecloudsdk/calliope/__init__.py", line 816, in Run
    result = command_instance.Run(args)
  File "/usr/local/nexus/tools/google-cloud-sdk/lib/googlecloudsdk/gcloud/sdktools/components/update.py", line 38, in Run
    manager.Update(args.component_ids, allow_no_backup=args.allow_no_backup)
  File "/usr/local/nexus/tools/google-cloud-sdk/bin/.././lib/googlecloudsdk/core/updater/update_manager.py", line 88, in _TryFunc
    return func(*args, **kwargs)
  File "/usr/local/nexus/tools/google-cloud-sdk/bin/.././lib/googlecloudsdk/core/updater/update_manager.py", line 461, in Update
    staging_state = install_state.CloneToStaging()
  File "/usr/local/nexus/tools/google-cloud-sdk/bin/.././lib/googlecloudsdk/core/updater/local_state.py", line 73, in _TryFunc
    return func(*args, **kwargs)
  File "/usr/local/nexus/tools/google-cloud-sdk/bin/.././lib/googlecloudsdk/core/updater/local_state.py", line 266, in CloneToStaging
    self.ClearBackup()
  File "/usr/local/nexus/tools/google-cloud-sdk/bin/.././lib/googlecloudsdk/core/updater/local_state.py", line 73, in _TryFunc
    return func(*args, **kwargs)
  File "/usr/local/nexus/tools/google-cloud-sdk/bin/.././lib/googlecloudsdk/core/updater/local_state.py", line 374, in ClearBackup
    file_utils.RmTree(self.__backup_directory)
  File "/usr/local/nexus/tools/google-cloud-sdk/bin/.././lib/googlecloudsdk/core/util/files.py", line 142, in RmTree
    shutil.rmtree(path, onerror=_HandleRemoveError)
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 256, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/local/nexus/tools/google-cloud-sdk/bin/.././lib/googlecloudsdk/core/util/files.py", line 130, in _HandleRemoveError
    raise exc_info
OSError

```

Original issue reported on code.google.com by `rich.burdon` on 15 May 2014 at 10:45

**Comment by GoogleCodeExporter** [comment]
```
Similar behavior on window.
Transscript following:


C:\Windows\system32>gcloud components update

The following components will be updated:
    ----------------------------------------------------------------------------
---
    | App Engine Launcher Application for Windows          |      1.9.6 | 11.2 M
B |
    | BigQuery Command Line Tool                           |     2.0.18 |  < 1 M
B |
    | Cloud SDK Core Libraries                             | 2014.06.05 |  < 1 M
B |
    | Cloud SDK Core Libraries (Platform Specific)         | 2014.06.03 |  < 1 M
B |
    | Cloud SQL Admin Command Line Interface               | 2014.06.03 |  < 1 M
B |
    | Cloud Storage Command Line Tool                      |        4.1 |  2.0 M
B |
    | Compute Engine Command Line Interface (RC)           | 2014.06.05 |  < 1 M
B |
    | Compute Engine Command Line Tool                     |     1.16.0 |  < 1 M
B |
    | Compute Engine Command Line Tool (Platform Specific) |     1.16.0 |  < 1 M
B |
    | gcloud app Python Extensions                         |      1.9.6 |  6.5 M
B |
    | gcloud app Python Extensions (Extra Libraries)       |      1.9.6 | 29.6 M
B |
    ----------------------------------------------------------------------------
---
The following components will be installed:
    --------------------------------------------------------
    | Windows command line ssh tools | 2014.06.03 | < 1 MB |
    --------------------------------------------------------

Do you want to continue (Y/n)?  y

Creating update staging area...

Uninstalling: App Engine Launcher Application for Windows ... Done
Uninstalling: BigQuery Command Line Tool ... Done
Uninstalling: Cloud SDK Core Libraries ... Done
Uninstalling: Cloud SDK Core Libraries (Platform Specific) ... Done
Uninstalling: Cloud SQL Admin Command Line Interface ... Done
Uninstalling: Cloud Storage Command Line Tool ... Done
Uninstalling: Compute Engine Command Line Interface (RC) ... Done
Uninstalling: Compute Engine Command Line Tool ... Done
Uninstalling: Compute Engine Command Line Tool (Platform Specific) ... Done
Uninstalling: gcloud app Python Extensions ... Done
Uninstalling: gcloud app Python Extensions (Extra Libraries) ... Done

Installing: App Engine Launcher Application for Windows ... Done
Installing: BigQuery Command Line Tool ... Done
Installing: Cloud SDK Core Libraries ... Done
Installing: Cloud SDK Core Libraries (Platform Specific) ... Done
Installing: Cloud SQL Admin Command Line Interface ... Done
Installing: Cloud Storage Command Line Tool ... Done
Installing: Compute Engine Command Line Interface (RC) ... Done
Installing: Compute Engine Command Line Tool ... Done
Installing: Compute Engine Command Line Tool (Platform Specific) ... Done
Installing: Windows command line ssh tools ... Done
Installing: gcloud app Python Extensions ... Done
Installing: gcloud app Python Extensions (Extra Libraries) ... Done

Creating backup and activating new installation...
Traceback (most recent call last):
  File "C:\tools\google-cloud-sdk\bin\..\./lib\googlecloudsdk\gcloud\gcloud.py",
 line 139, in <module>
  File "C:\tools\google-cloud-sdk\bin\..\./lib\googlecloudsdk\gcloud\gcloud.py",
 line 135, in main
  File "C:\tools\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\__init__.
py", line 1615, in Execute
  File "C:\tools\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\__init__.
py", line 1166, in _Execute
  File "C:\tools\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\__init__.
py", line 885, in Run
  File "C:\tools\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\exception
s.py", line 78, in TryFunc
  File "C:\tools\google-cloud-sdk\lib\googlecloudsdk\gcloud\sdktools\components\
update.py", line 37, in Run
  File "C:\tools\google-cloud-sdk\bin\..\./lib\googlecloudsdk\core\updater\updat
e_manager.py", line 88, in _TryFunc
  File "C:\tools\google-cloud-sdk\bin\..\./lib\googlecloudsdk\core\updater\updat
e_manager.py", line 470, in Update
  File "C:\tools\google-cloud-sdk\bin\..\./lib\googlecloudsdk\core\updater\local
_state.py", line 73, in _TryFunc
  File "C:\tools\google-cloud-sdk\bin\..\./lib\googlecloudsdk\core\updater\local
_state.py", line 321, in ReplaceWith
  File "C:\tools\google-cloud-sdk\bin\..\./lib\googlecloudsdk\core\util\files.py
", line 195, in MoveDir
  File "C:\tools\google-cloud-sdk\bin\..\./lib\googlecloudsdk\core\util\files.py
", line 142, in RmTree
  File "C:\Python27\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Python27\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Python27\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Python27\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Python27\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Python27\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Python27\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Python27\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Python27\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Python27\lib\shutil.py", line 256, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "C:\tools\google-cloud-sdk\bin\..\./lib\googlecloudsdk\core\util\files.py
", line 130, in _HandleRemoveError
WindowsError
The system cannot find the path specified.

```

Original comment by `CeesWess...@gmail.com` on 6 Jun 2014 at 1:56

**Comment by GoogleCodeExporter** [comment]
```
Not sure if this helps, but the error was resolved on at least two win7 
machines by removing old/outdated python 2.7.2 and installing latest i.e. 
python 2.7.7.
```

Original comment by `ananduna...@gmail.com` on 19 Jun 2014 at 4:59

**Comment by GoogleCodeExporter** [comment]
```
same problem on OS X

oglecloudsdk/core/updater/update_manager.py", line 464, in Update
    staging_state = install_state.CloneToStaging()
  File "/Users/xxx/google-cloud-sdk/./lib/googlecloudsdk/core/updater/local_state.py", line 73, in _TryFunc
    return func(*args, **kwargs)
  File "/Users/xxx/google-cloud-sdk/./lib/googlecloudsdk/core/updater/local_state.py", line 265, in CloneToStaging
    file_utils.RmTree(self.__sdk_staging_root)
  File "/Users/xxx/google-cloud-sdk/./lib/googlecloudsdk/core/util/files.py", line 142, in RmTree
    shutil.rmtree(path, onerror=_HandleRemoveError)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "/Users/xxx/google-cloud-sdk/./lib/googlecloudsdk/core/util/files.py", line 130, in _HandleRemoveError
    raise exc_info
OSError

There's also this odd state in the google-cloud-sdk.staging directory
not sure what those users and groups are:

s -l
total 0
drwx------  8 40128  5000   272 Jun 23 00:49 bin
drwxr-xr-x  3 root   staff  102 Jun 23 00:49 lib
drwx------  4 40128  5000   136 Jun  3 16:35 platform



```

Original comment by `s...@blinkfire.com` on 24 Jun 2014 at 4:19

Attachments:
- [Screen Shot 2014-06-23 at 11.15.24 PM.png](https://storage.googleapis.com/google-code-attachments/google-cloud-sdk/issue-35/comment-3/Screen Shot 2014-06-23 at 11.15.24 PM.png)

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
To "solve" the problem on windows, execute gcloud components update as admin.

Sorry about my english.
```

Original comment by `wagnerma...@gmail.com` on 19 Jul 2014 at 3:25

**Comment by GoogleCodeExporter** [comment]
```
For the WindowError, you need to run 'gcloud components update' in an 
Administrator shell. 
```

Original comment by `rdayal@google.com` on 13 Aug 2014 at 10:48

**Comment by GoogleCodeExporter** [comment]
```
Running it as admin doesn't solve it in my case.
```

Original comment by `de...@derekperkins.com` on 13 Aug 2014 at 10:57

**Comment by GoogleCodeExporter** [comment]
```
For the Mac-related errors, how did you install the Cloud SDK? Did you install 
it as root?

In comment #3, that's definitely strange. Given that you installed the Cloud 
SDK in your user directory, there shouldn't be any permission problems. What's 
the location of the google-cloud-sdk.staging directory?


```

Original comment by `rdayal@google.com` on 13 Aug 2014 at 11:02

**Comment by GoogleCodeExporter** [comment]
Original comment by `rdayal@google.com` on 13 Aug 2014 at 11:02

**Comment by GoogleCodeExporter** [comment]
```
google-cloud-sdk.staging is in my home directory.   i'm fairly sure did not
install this with sudo or anything, as you very rarely do that on the
mac...but the lib directory does look curious

ls -l google-cloud-sdk.staging/
total 0
drwx------  8 40128  5000   272 Jun 22 22:49 bin
drwxr-xr-x  3 root   staff  102 Jun 22 22:49 lib
drwx------  4 40128  5000   136 Jun  3 14:35 platform
```

Original comment by `s...@blinkfire.com` on 13 Aug 2014 at 11:09

**Comment by GoogleCodeExporter** [comment]
```
In my Windows setup, it's installed under c:\google-cloud-sdk. I installed it 
initially with the zipped download, and updates have worked for months until 
1.9.7.

How do I find what the staging directory is? All I see in my error trace is 
self.__sdk_staging_root.
```

Original comment by `de...@derekperkins.com` on 13 Aug 2014 at 11:10

**Comment by GoogleCodeExporter** [comment]
```
@derek: Are you seeing the exact same stack trace as the original reporter?
```

Original comment by `rdayal@google.com` on 18 Aug 2014 at 2:23

**Comment by GoogleCodeExporter** [comment]
```
@sjo: Could you try using sudo to remove the google-cloud-sdk.staging/ 
directory and then performing an update?
```

Original comment by `rdayal@google.com` on 18 Aug 2014 at 2:23

**Comment by GoogleCodeExporter** [comment]
Original comment by `rdayal@google.com` on 27 Aug 2014 at 1:38
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
Hi, i faced the same problem installing gcloud on fedora-20

see trace:
component manager.
 [1] Java
 [2] Python and PHP
 [3] Go
 [4] No App Engine (you can install App Engine tools later)
Please enter your numeric choice (4):  3


The following components will be installed:
    --------------------------------------------------------------------------------------------
    | App Engine SDK for Go                                             | 2014.09.30 |         |
    | App Engine SDK for Go (Platform Specific)                         | 2014.09.10 |  < 1 MB |
    | App Engine SDK for Python and PHP                                 | 2014.05.06 |  < 1 MB |
    | BigQuery Command Line Tool                                        |     2.0.18 |  < 1 MB |
    | BigQuery Command Line Tool (Platform Specific)                    |     2.0.18 |  < 1 MB |
    | Cloud DNS Admin Command Line Interface                            | 2014.09.02 |  < 1 MB |
    | Cloud SDK Core Command Line Tools                                 |          1 |         |
    | Cloud SDK Core Libraries (Platform Specific)                      | 2014.09.30 |  < 1 MB |
    | Cloud SDK for Go Developers                                       |          1 |         |
    | Cloud SQL Admin Command Line Interface                            | 2014.09.30 |  < 1 MB |
    | Cloud Storage Command Line Tool                                   |        4.6 |  2.1 MB |
    | Cloud Storage Command Line Tool (Platform Specific)               |        4.6 |  < 1 MB |
    | Compute Engine Command Line Interface                             | 2014.09.30 |  < 1 MB |
    | Compute Engine Command Line Tool (deprecated)                     |     1.16.5 |  < 1 MB |
    | Compute Engine Command Line Tool (deprecated) (Platform Specific) |     1.16.5 |  < 1 MB |
    | gcloud app Go Extensions (Linux, x86_64)                          |     1.9.12 | 34.0 MB |
    | gcloud app Python Extensions                                      |     1.9.12 |  6.5 MB |
    | gcloud app Python Extensions (Extra Libraries)                    |      1.9.6 | 29.6 MB |
    --------------------------------------------------------------------------------------------

Creating update staging area...


Installing: App Engine SDK for Go ... Done
Installing: App Engine SDK for Go (Platform Specific) ... Done
Installing: App Engine SDK for Python and PHP ... Done
Installing: BigQuery Command Line Tool ... Done
Installing: BigQuery Command Line Tool (Platform Specific) ... Done
Installing: Cloud DNS Admin Command Line Interface ... Traceback (most recent 
call last):
  File "/home/google-cloud-sdk/bin/bootstrapping/install.py", line 368, in <module>
    main()
  File "/home/google-cloud-sdk/bin/bootstrapping/install.py", line 347, in main
    pargs.additional_components)
  File "/home/google-cloud-sdk/bin/bootstrapping/install.py", line 310, in Install
    components = InstallComponents(to_install)
  File "/home/google-cloud-sdk/bin/bootstrapping/install.py", line 332, in InstallComponents
    components.update(component_ids=component_ids, allow_no_backup=True)
  File "/home/google-cloud-sdk/bin/bootstrapping/../../lib/googlecloudsdk/calliope/frontend.py", line 235, in __call__
    post_run_hooks=None, kwargs=kwargs)
  File "/home/google-cloud-sdk/bin/bootstrapping/../../lib/googlecloudsdk/calliope/frontend.py", line 274, in _Execute
    pre_run_hooks=pre_run_hooks, post_run_hooks=post_run_hooks)
  File "/home/google-cloud-sdk/bin/bootstrapping/../../lib/googlecloudsdk/calliope/backend.py", line 882, in Run
    result = command_instance.Run(args)
  File "/home/google-cloud-sdk/lib/googlecloudsdk/gcloud/sdktools/components/update.py", line 65, in Run
    args.component_ids, allow_no_backup=args.allow_no_backup)
  File "/home/google-cloud-sdk/bin/bootstrapping/../../lib/googlecloudsdk/core/updater/update_manager.py", line 465, in Update
    self._InstallFunction(staging_state, diff))
  File "/home/google-cloud-sdk/bin/bootstrapping/../../lib/googlecloudsdk/core/updater/update_manager.py", line 380, in _UpdateAndPrint
    action_func(component.id)
  File "/home/google-cloud-sdk/bin/bootstrapping/../../lib/googlecloudsdk/core/updater/update_manager.py", line 386, in Inner
    return install_state.Install(diff.latest, component_id)
  File "/home/google-cloud-sdk/bin/bootstrapping/../../lib/googlecloudsdk/core/updater/local_state.py", line 81, in _TryFunc
    return func(*args, **kwargs)
  File "/home/google-cloud-sdk/bin/bootstrapping/../../lib/googlecloudsdk/core/updater/local_state.py", line 405, in Install
    files = self._GetInstaller(snapshot).Install(component_id)
  File "/home/google-cloud-sdk/bin/bootstrapping/../../lib/googlecloudsdk/core/updater/installers.py", line 109, in Install
    return self._InstallTar(component)
  File "/home/google-cloud-sdk/bin/bootstrapping/../../lib/googlecloudsdk/core/updater/installers.py", line 146, in _InstallTar
    raise ComponentDownloadFailedError(component.id, e)
googlecloudsdk.core.updater.installers.ComponentDownloadFailedError: The 
component [dns] failed to download.

<urlopen error _ssl.c:489: The handshake operation timed out>


Also doing 'gcloud anycommand' gives 
[root@localhost ~]# gcloud
bash: gcloud: command not found

did u find any soln????
```

Original comment by `priyanka...@gmail.com` on 9 Oct 2014 at 11:24

**Comment by GoogleCodeExporter** [comment]
```
This is a different error than this issue is referring to.  Based on the error, 
it looks like your connection just timed out.  Is this repeatable?  Are you on 
a wireless connection?
```

Original comment by `markp...@google.com` on 10 Oct 2014 at 4:28

**Comment by GoogleCodeExporter** [comment]
```
I have encountered similar problem, though instead of stack trace, I'm 
receiving an error message.
Windows, not sure about gcloud version as previous installation have been 
erased.


|============================================================|
|- Uninstalling: App Engine Managed VMs Component (Preview) -|
|============================================================|
|- Uninstalling: Cloud SDK Core Libraries                   -|
|============================================================|
|- Uninstalling: Cloud SQL Admin Command Line Interface     -|
|============================================================|
|- Uninstalling: Cloud Storage Command Line Tool            -|
|============================================================|
|- Uninstalling: Compute Engine Command Line Interface      -|
|============================================================|
|- Uninstalling: Developer Preview gcloud Commands          -|
|============================================================|
|- Installing: App Engine Command Line Interface (Preview)  -|
|============================================================|
|- Installing: App Engine Managed VMs Component (Preview)   -|
|============================================================|
|- Installing: Cloud SDK Core Libraries                     -|
|============================================================|
|- Installing: Cloud SQL Admin Command Line Interface       -|
|============================================================|
|- Installing: Cloud Storage Command Line Tool              -|
|============================================================|
|- Installing: Compute Engine Command Line Interface        -|
|============================================================|
|- Installing: Developer Preview gcloud Commands            -|
|============================================================|

Creating backup and activating new installation...
ERROR: (gcloud.components.update) The process cannot access the file because it 
is being used by another process: [C:\Pr
ogram Files\Google\Cloud 
SDK\google-cloud-sdk\platform\google_appengine\goroot\src\pkg\strconv\atof.go]

Ensure you have the permissions to access the file and that the file is not in 
use.
The system cannot find the path specified.

D:\>gcloud components update
'gcloud' is not recognized as an internal or external command,
operable program or batch file.



p.s.: Unfortunately default environment settings for gcloud shell is set to not 
have off-screen buffer, so that's all that is available.
Also, "MODE 120,40" is undocumented and unreliable syntax, if you are going to 
use it, use proper syntax: MODE CON COLS=120 LINES=40
But I would suggest removing it from cloud_env.bat altogether because it forces 
command line buffer to equal screen size (even overriding user settings), no 
history output is available because of that
```

Original comment by `Shadow.G...@gmail.com` on 8 Feb 2015 at 11:09

**Comment by GoogleCodeExporter** [comment]
```
Old version was 0.9.44 (2015/01/21) (release_notes file was left behind), new 
0.9.46.
There's google-cloud-sdk folder which is mostly empty, and 
google-cloud-sdk.staging
with new version.
```

Original comment by `Shadow.G...@gmail.com` on 8 Feb 2015 at 11:12

**Comment by GoogleCodeExporter** [comment]
```
The Windows filesystem locks file when they are in use (by a process, or if you 
have a cmd shell open in a directory, etc) which prevents the updater from 
completing successfully.  Depending on when the error occurs, this is sometimes 
unrecoverable by the updater.  If it fails during the "Activating new 
installation" step, you can try removing the "C:\Program Files\Google\Cloud 
SDK\google-cloud-sdk" directory and renaming the staging directory (C:\Program 
Files\Google\Cloud SDK\google-cloud-sdk.staging) to replace it.

If staging is incomplete (it shouldn't be in this case), just delete the 
installation directory and rerun the installer.

We are working on a new Windows installer which should make the update process 
a little more reliable.
```

Original comment by `markp...@google.com` on 9 Feb 2015 at 4:33
- Changed state: **WontFix**
