### ISSUE TITLE
I SSh key configarurate faild on Windows 10

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#352]
```
Issue running command [gcloud compute ssh].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "C:\Users\Neo\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\cli.py", line 592, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "C:\Users\Neo\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\backend.py", line 1223, in Run
    resources = command_instance.Run(args)
  File "C:\Users\Neo\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\compute\subcommands\ssh.py", line 154, in Run
    use_account_service=self._use_accounts_service)
  File "C:\Users\Neo\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\shared\compute\ssh_utils.py", line 479, in ActuallyRun
    has_keys = self.EnsureSSHKeyIsInProject(user)
  File "C:\Users\Neo\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\shared\compute\ssh_utils.py", line 292, in EnsureSSHKeyIsInProject
    self.messages, user, public_key, existing_metadata)
  File "C:\Users\Neo\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\shared\compute\ssh_utils.py", line 173, in _AddSSHKeyToMetadataMessage
    constants.SSH_KEYS_METADATA_KEY: _PrepareSSHKeysValue(ssh_keys)},
  File "C:\Users\Neo\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\shared\compute\ssh_utils.py", line 155, in _PrepareSSHKeysValue
[output tr

```

Original issue reported on code.google.com by `mamakaka...@citromail.hu` on 28 Oct 2015 at 3:08

Attachments:
- [Képernyőfelvétel (213).png](https://storage.googleapis.com/google-code-attachments/google-cloud-sdk/issue-352/comment-0/Képernyőfelvétel %28213%29.png)

**Comment by GoogleCodeExporter** [comment]
```
Unfortunately the interesting part of the traceback was truncated by 'gcloud 
feedback' (we are working on that!). Can you run the command again, and then 
run gcloud feedback, and cut and paste the tail end of the traceback into the 
report?
thanks
```

Original comment by `gsfow...@google.com` on 9 Nov 2015 at 3:50
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 4 Jan 2016 at 2:17
- Changed state: **Invalid**
