### ISSUE TITLE
Failed deploy created undeletable version

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#354]
```
What steps will reproduce the problem?

I deployed with:

gcloud preview app deploy app.yaml --docker-build=remote --version 
$BUILD_GROUP_NUMBER --force --promote


What is the expected output? What do you see instead?

I expected the deploy to succeed, but it failed with an internal error.  
Moreover, I now cannot delete the version it created (730) -- trying to do so 
from the console fails with an "Unknown error".  At least it didn't spin up 
instances for the failed version...

Here's the original deploy error:

2015-10-29 02:50:37,304 DEBUG    root            (gcloud.preview.app.deploy) 
Error Response: [13] An internal error occurred.
Traceback (most recent call last):
  File "/root/google-cloud-sdk/./lib/googlecloudsdk/calliope/cli.py", line 598, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "/root/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 1226, in Run
    resources = command_instance.Run(args)
  File "/root/google-cloud-sdk/./lib/googlecloudsdk/appengine/app_commands/deploy.py", line 288, in Run
    images.get(module))
  File "/root/google-cloud-sdk/./lib/googlecloudsdk/appengine/lib/appengine_api_client.py", line 78, in DeployModule
    return operations.WaitForOperation(self.client.apps_operations, operation)
  File "/root/google-cloud-sdk/./lib/googlecloudsdk/appengine/lib/api/operations.py", line 55, in WaitForOperation
    encoding.MessageToPyValue(completed_operation.error)))


What is the output of 'gcloud info'?

Google Cloud SDK [0.9.84]

Platform: [Linux, x86_64]
Python Version: [2.7.6 (default, Mar 22 2014, 22:59:56)  [GCC 4.8.2]]
Site Packages: [Enabled]

Installation Root: [/root/google-cloud-sdk]
Installed Components:
  core: [2015.10.23]
  core-nix: [2015.09.03]
  app: [2015.10.23]
  gcloud: [2015.10.23]
  gsutil-nix: [4.14]
  gsutil: [4.15]
  bq: [2.0.18]
  bq-nix: [2.0.18]
System PATH: 
[/root/bin:/root/shippable_ve/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/
bin:/sbin:/bin:/root/usr/local/bin:/root/google-cloud-sdk/bin]
Cloud SDK on PATH: [True]

Installation Properties: [/root/google-cloud-sdk/properties]
User Config Directory: [/root/.config/gcloud]
User Properties: [/root/.config/gcloud/properties]
Current Workspace: [None]
Workspace Config Directory: [None]
Workspace Properties: [None]

Account: [piotr@reviewable.io]
Project: [reviewable-prod]

Current Properties:
  [core]
    project: [reviewable-prod]
    account: [piotr@reviewable.io]
    disable_usage_reporting: [False]
  [app]
    use_appengine_api: [True]

Logs Directory: [/root/.config/gcloud/logs]
Last Log File: [/root/.config/gcloud/logs/2015.10.29/02.47.53.062569.log]

Please provide any additional information below.


```

Original issue reported on code.google.com by `pi...@ideanest.com` on 29 Oct 2015 at 3:05

**Comment by GoogleCodeExporter** [comment]
```
I'm experiencing the same issue. When I remove 

application_readable: true

from my static handlers, it deploys without error. I have no problem running it 
locally and can deploy with appcfg.py without issue.
```

Original comment by `dawsj...@apps.disney.com` on 29 Oct 2015 at 6:57

**Comment by GoogleCodeExporter** [comment]
```
Hey,

Could you attach the full app.yaml contents, or as much of it as you're willing 
to post publicly? You could also email directly to me at dlorenc@google.com.

dawsj028 - could you send me the app id?
```

Original comment by `dlor...@google.com` on 29 Oct 2015 at 7:17
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
I attached my app.yaml file.  Note that the broken version did somehow get 
deleted later -- I think by a subsequent run of my build, via `gcloud preview 
app modules delete default --version 730`.  So maybe the "undeletable version" 
problem was just in the console.

```

Original comment by `pi...@ideanest.com` on 29 Oct 2015 at 7:45

Attachments:
- [app.yaml](https://storage.googleapis.com/google-code-attachments/google-cloud-sdk/issue-354/comment-3/app.yaml)

**Comment by GoogleCodeExporter** [comment]
```
This should be fixed now. Thanks for the report.
```

Original comment by `dlor...@google.com` on 25 Feb 2016 at 9:44
- Changed state: **Fixed**
