### ISSUE TITLE
'application_readable: true' in static handlers causes (gcloud.preview.app.deploy) Error Response: [13] 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#356]
```
What steps will reproduce the problem?

Create an app.yaml file with a static file handler and 'application_readable: 
true'

Attempt to deploy using 'gcloud preview app deploy app.yaml --version test'

What is the expected output? What do you see instead?

I expect to have the project deployed to version 'test'

Instead I see the following error (from the logs):

2015-10-29 09:02:17,719 DEBUG    root            (gcloud.preview.app.deploy) 
Error Response: [13] An internal error occurred.
Traceback (most recent call last):
  File "/Users/dawsj028/google-cloud-sdk/./lib/googlecloudsdk/calliope/cli.py", line 598, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "/Users/dawsj028/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 1226, in Run
    resources = command_instance.Run(args)
  File "/Users/dawsj028/google-cloud-sdk/./lib/googlecloudsdk/appengine/app_commands/deploy.py", line 288, in Run
    images.get(module))
  File "/Users/dawsj028/google-cloud-sdk/./lib/googlecloudsdk/appengine/lib/appengine_api_client.py", line 78, in DeployModule
    return operations.WaitForOperation(self.client.apps_operations, operation)
  File "/Users/dawsj028/google-cloud-sdk/./lib/googlecloudsdk/appengine/lib/api/operations.py", line 55, in WaitForOperation
    encoding.MessageToPyValue(completed_operation.error)))
OperationError: Error Response: [13] An internal error occurred.
2015-10-29 09:02:17,724 ERROR    root            (gcloud.preview.app.deploy) 
Error Response: [13] An internal error occurred.
2015-10-29 09:02:17,968 DEBUG    root            Metrics reporting process 
started...

What is the output of 'gcloud info'?

Google Cloud SDK [0.9.84]

Platform: [Mac OS X, x86_64]
Python Version: [2.7.10 (default, Jul 14 2015, 19:46:27)  [GCC 4.2.1 Compatible 
Apple LLVM 6.0 (clang-600.0.39)]]
Site Packages: [Disabled]

Installation Root: [/Users/username/google-cloud-sdk]
Installed Components:
  core: [2015.10.23]
  core-nix: [2015.09.03]
  app: [2015.10.23]
  gcloud: [2015.10.23]
  gsutil-nix: [4.14]
  gsutil: [4.15]
  bq: [2.0.18]
  bq-nix: [2.0.18]
System PATH: 
[/Users/username/google-cloud-sdk/bin:/usr/local/Cellar/ruby:/usr/local/heroku/b
in:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/
usr/local/sbinP]
Cloud SDK on PATH: [True]

WARNING: There are old versions of the Google Cloud Platform tools on your 
system PATH.
  /Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/dev_appserver.py

Installation Properties: [/Users/username/google-cloud-sdk/properties]
User Config Directory: [/Users/username/.config/gcloud]
User Properties: [/Users/username/.config/gcloud/properties]
Current Workspace: [None]
Workspace Config Directory: [None]
Workspace Properties: [None]

Account: [xxxxxxxx]
Project: [xxxxxxxx]

Current Properties:
  [core]
    project: [xxxxxxxx]
    account: [xxxxxxxx]
    disable_usage_reporting: [False]
  [app]
    use_appengine_api: [True]
    suppress_change_warning: [true]
  [compute]
    region: [us-central1]
    zone: [us-central1-f]

Logs Directory: [/Users/username/.config/gcloud/logs]
Last Log File: 
[/Users/username/.config/gcloud/logs/2015.10.29/11.47.41.197962.log]


Please provide any additional information below.


```

Original issue reported on code.google.com by `dawsj...@apps.disney.com` on 29 Oct 2015 at 7:06

**Comment by GoogleCodeExporter** [comment]
Original comment by `dlor...@google.com` on 29 Oct 2015 at 7:24
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
This fix should be rolled out to production. Thanks for the report!
```

Original comment by `dlor...@google.com` on 20 Nov 2015 at 11:28
- Changed state: **Fixed**
