### ISSUE TITLE
Deploy consistently fails with "Timed out creating VMs"

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#357]
```
What steps will reproduce the problem?

I'm trying to deploy my app as usual:

gcloud preview app deploy app.yaml --docker-build=remote --version 
$BUILD_GROUP_NUMBER --force --promote


What is the expected output? What do you see instead?

I expect my app to be deployed.  Instead, I get the error below (3 times in a 
row now).  The new version is created (but not made the default) and instances 
started up, so it appears to be some kind of partial failure.  Sure would be 
nice if the deploy operation was atomic -- it's getting annoying to clean up 
after it (what feels like) every other time.

2015-10-29 20:40:25,953 DEBUG    root            (gcloud.preview.app.deploy) 
Error Response: [4] Timed out creating VMs.
Traceback (most recent call last):
  File "/root/google-cloud-sdk/./lib/googlecloudsdk/calliope/cli.py", line 598, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "/root/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 1226, in Run
    resources = command_instance.Run(args)
  File "/root/google-cloud-sdk/./lib/googlecloudsdk/appengine/app_commands/deploy.py", line 288, in Run
    images.get(module))
  File "/root/google-cloud-sdk/./lib/googlecloudsdk/appengine/lib/appengine_api_client.py", line 78, in DeployModule
    return operations.WaitForOperation(self.client.apps_operations, operation)
  File "/root/google-cloud-sdk/./lib/googlecloudsdk/appengine/lib/api/operations.py", line 55, in WaitForOperation
    encoding.MessageToPyValue(completed_operation.error)))


What is the output of 'gcloud info'?

Google Cloud SDK [0.9.84]

Platform: [Linux, x86_64]
Python Version: [2.7.6 (default, Mar 22 2014, 22:59:56)  [GCC 4.8.2]]
Site Packages: [Enabled]

Installation Root: [/root/google-cloud-sdk]
Installed Components:
  core: [2015.10.23]
  core-nix: [2015.09.03]
  app: [2015.10.23]
  gcloud: [2015.10.23]
  gsutil-nix: [4.14]
  gsutil: [4.15]
  bq: [2.0.18]
  bq-nix: [2.0.18]
System PATH: 
[/root/bin:/root/shippable_ve/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/
bin:/sbin:/bin:/root/usr/local/bin:/root/google-cloud-sdk/bin]
Cloud SDK on PATH: [True]

Installation Properties: [/root/google-cloud-sdk/properties]
User Config Directory: [/root/.config/gcloud]
User Properties: [/root/.config/gcloud/properties]
Current Workspace: [None]
Workspace Config Directory: [None]
Workspace Properties: [None]

Account: [piotr@reviewable.io]
Project: [reviewable-prod]

Current Properties:
  [core]
    project: [reviewable-prod]
    account: [piotr@reviewable.io]
    disable_usage_reporting: [False]
  [app]
    use_appengine_api: [True]

Logs Directory: [/root/.config/gcloud/logs]
Last Log File: [/root/.config/gcloud/logs/2015.10.29/20.36.04.371928.log]


Please provide any additional information below.


```

Original issue reported on code.google.com by `pi...@ideanest.com` on 29 Oct 2015 at 8:48

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the report. We are looking into it.
```

Original comment by `gsfow...@google.com` on 3 Nov 2015 at 8:35

**Comment by GoogleCodeExporter** [comment]
```
This was caused by a server-side issue last week. It should be resolved now.
```

Original comment by `dlor...@google.com` on 3 Nov 2015 at 10:07
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Just got this today. I had published ok a few hours earlier, but then it failed.
```

Original comment by `chris.ea...@appendmedia.com` on 5 Nov 2015 at 1:13

**Comment by GoogleCodeExporter** [comment]
```
Issue 370 has been merged into this issue.
```

Original comment by `dlor...@google.com` on 5 Nov 2015 at 2:06

**Comment by GoogleCodeExporter** [comment]
```
This ticket says "fixed" but the problem is still present.
```

Original comment by `thedevex...@gmail.com` on 5 Nov 2015 at 8:45

**Comment by GoogleCodeExporter** [comment]
```
Thanks for letting us know.
```

Original comment by `z...@google.com` on 5 Nov 2015 at 11:22
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
I think I may have figured out what causes this. It turns out that even though 
my app runs fine locally, it crashes immediately inside the docker image.

This seems to cause the GCE instance to spin endlessly, and in the case of a 
gcloud deploy, to eventually time out.

Now that remote docker builds are a default, it may be a good idea to change 
the "Timeout" error message to something along the lines of "The app inside the 
docker container was not responding, and may not have exited prematurely." So 
it gives newbie users like myself something to look into, instead of assuming 
the fault lies with AE or GCE.

Hope that helps!
```

Original comment by `chris.ea...@appendmedia.com` on 6 Nov 2015 at 10:29

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the report. We have a few features planned that will make debugging 
issues like this easier.
```

Original comment by `dlor...@google.com` on 25 Feb 2016 at 9:45
- Changed state: **Fixed**
