### ISSUE TITLE
Crash on connection to project.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#359]
```
Issue running command [gcloud init].

What steps will reproduce the problem?
Attempted to connect to project on Google Cloud Development Platform

What is the expected output? What do you see instead?
I expected to clone the repository. 
Instead I got the error below. 
Please provide any additional information below.
Windows had a similar hang up at this point but it offered to try to download 
the default directory which worked. 

Traceback (most recent call last):
  File "calliope/cli.py", line 598, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "calliope/backend.py", line 1226, in Run
    resources = command_instance.Run(args)
  File "surface/init.py", line 83, in Run
    self._PickDefaultRegionAndZone()
  File "surface/init.py", line 232, in _PickDefaultRegionAndZone
    project_info = self._RunCmd(['compute', 'project-info', 'describe'])
  File "surface/init.py", line 373, in _RunCmd
    return self.cli.Execute(args)
  File "calliope/cli.py", line 598, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "calliope/backend.py", line 1226, in Run
    resources = command_instance.Run(args)
  File "api_lib/compute/base_classes.py", line 652, in Run
    resources = list(self.ComputeDynamicProperties(args, resources))
  File "api_lib/compute/lister.py", line 44, in ProcessResults
    yield field_selector.Apply(resource)
  File "api_lib/compute/property_selector.py", line 359, in Apply
    res = _DictToOrderedDict(obj)
  File "api_lib/compute/property_selector.py", line 177, in _DictToOrderedDict
    new_obj = collections.OrderedDict(sorted(obj.items()))
AttributeError: 'module' object has no attribute 'OrderedDict'

Installation information:

Google Cloud SDK [0.9.84]

Platform: [Linux, x86_64]
Python Version: [2.6.6 (r266:84292, Feb 22 2013, 00:00:18)  [GCC 4.4.7 20120313 
(Red Hat 4.4.7-3)]]
[output truncated]

```

Original issue reported on code.google.com by `origamii...@gmail.com` on 30 Oct 2015 at 6:49

**Comment by GoogleCodeExporter** [comment]
```
Thanks for reporting the issues. You are hitting one of the known python 2.6 
incompatibilities.

Is it an option for you to additionally install python 2.7. You do not have to 
replace default, if you set 

export CLOUDSDK_PYTHON=/path/to/python2.7

in your .profile or .bashrc file to tell gcloud where to find python.

Let us know if this works for you. Also curious about the reason for using 
python 2.6.

```

Original comment by `che...@google.com` on 30 Oct 2015 at 10:58
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
Original comment by `gsfow...@google.com` on 9 Nov 2015 at 5:40
- Changed state: **Started**
