### ISSUE TITLE
gcloud preview doesn't exist

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#36]
```
What steps will reproduce the problem?

https://developers.google.com/cloud/sdk/cloudplatform

$ gcloud preview app run DIRECTORY

ERROR: (gcloud) Invalid subcommand: 'preview'.

$ gcloud compute --help

ERROR: (gcloud) Invalid subcommand: 'compute'. Did you mean 'auth'?


What is the expected output? What do you see instead?

Run the app?

What is the output of 'gcloud version'?
Google Cloud SDK 0.9.21

bq 2.0.18
bq-nix 2.0.18
core 2014.04.08
core-nix 2014.04.08
gae-go-darwin-x86_64 1.9.3
gae-java 1.9.3
gae-java-nix 1.8.9
gae-python 1.9.3
gae-python-launcher-mac 1.9.3
gcutil 1.15.0
gcutil-nix 1.13.0
gsutil 3.42
gsutil-nix 3.42
sql 2014.04.15

Please provide any additional information below.


```

Original issue reported on code.google.com by `rich.burdon` on 15 May 2014 at 11:00

**Comment by GoogleCodeExporter** [comment]
```
gcloud update was failing so I could get the latest version.
I've reinstalled everything from scratch and now I get different errors:

burdon-mbp:~/projects/src/alienlaboratories/web> gcloud preview app run 
src/main/resources
WARNING: The [application] field is specified in file [app.yaml].  This field 
is not used by gcloud and should be removed.
ERROR: No default module could be found (is this an AppEngine app directory?)
Traceback (most recent call last):
  File "/usr/local/nexus/tools/google-cloud-sdk/./lib/googlecloudsdk/gcloud/gcloud.py", line 138, in <module>
    main()
  File "/usr/local/nexus/tools/google-cloud-sdk/./lib/googlecloudsdk/gcloud/gcloud.py", line 134, in main
    _cli.Execute()
  File "/usr/local/nexus/tools/google-cloud-sdk/./lib/googlecloudsdk/calliope/__init__.py", line 1612, in Execute
    post_run_hooks=self.__post_run_hooks, kwargs=kwargs)
  File "/usr/local/nexus/tools/google-cloud-sdk/./lib/googlecloudsdk/calliope/__init__.py", line 1166, in _Execute
    pre_run_hooks=pre_run_hooks, post_run_hooks=post_run_hooks)
  File "/usr/local/nexus/tools/google-cloud-sdk/./lib/googlecloudsdk/calliope/__init__.py", line 885, in Run
    result = command_instance.Run(args)
  File "/usr/local/nexus/tools/google-cloud-sdk/./lib/googlecloudsdk/calliope/exceptions.py", line 78, in TryFunc
    return func(*args, **kwargs)
  File "/usr/local/nexus/tools/google-cloud-sdk/lib/googlecloudsdk/appengine/app_commands/run.py", line 49, in Run
    app_dir = yaml_parsing.AppDirectory(args.directory, project=None)
  File "/usr/local/nexus/tools/google-cloud-sdk/./lib/googlecloudsdk/appengine/lib/yaml_parsing.py", line 233, in __init__
    raise AppDirLoadError(self.__directory)
googlecloudsdk.appengine.lib.yaml_parsing.AppDirLoadError: Errors occurred 
while parsing the AppEngine app in directory: [src/main/resources]

```

Original comment by `rich.burdon` on 15 May 2014 at 11:33

**Comment by GoogleCodeExporter** [comment]
```
What is src/main/resources? You have to provide app run with an app directory.

Keep in mind that 'gcloud [preview] app' is still under development, and should 
only be used for experimental/testing purposes.

But that error certainly shouldn't escape as a stack trace, so I'll mirror this 
bug internally and update this one when it is addressed.
```

Original comment by `jasm...@google.com` on 16 May 2014 at 1:42

**Comment by GoogleCodeExporter** [comment]
Original comment by `rdayal@google.com` on 13 Aug 2014 at 11:11
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
Original comment by `markp...@google.com` on 25 Aug 2014 at 6:16
- Changed state: **Fixed**
