### ISSUE TITLE
unable to deploy bigtable example to managedvm err:Not enough VMs ready (1/2 ready, 1 still deploying)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#360]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?
run mvn gcloud:deploy on cloudbigtableexamples in managedvm module

What is the expected output? What do you see instead?
expected: app deployed and accessible from browser
actual:CannotStartServingError: Not enough VMs ready (1/2 ready, 1 still 
deploying). Version: 20151030t123536.388208395436616202

This can happen when your application does not start successfully.
Please check your project logs at:
https://console.developers.google.com/project/jdalabs-retail-me-dev01/appengine/
logs?versionId=20151030t123536&moduleId=default

Please provide any additional information below.


Traceback (most recent call last):
  File "calliope/cli.py", line 591, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "calliope/backend.py", line 1191, in Run
    resources = command_instance.Run(args)
  File "appengine/app_commands/deploy.py", line 237, in Run
    client.DeployModule(module, version, info.parsed, info.file)
  File "appengine/lib/appengine_client.py", line 295, in DeployModule
    return appversion.DoUpload()
  File "appengine/lib/appengine_deployments.py", line 1053, in DoUpload
    app_summary = self.Commit()
  File "appengine/lib/appengine_deployments.py", line 753, in Commit
    success, response = util.RetryNoBackoff(self.IsServing, PrintRetryMessage)
  File "appengine/lib/util.py", line 225, in RetryNoBackoff
    max_tries)
  File "appengine/lib/util.py", line 186, in RetryWithBackoff
    done, value = func()
  File "appengine/lib/appengine_deployments.py", line 889, in IsServing
    raise CannotStartServingError(message)
CannotStartServingError: Not enough VMs ready (1/2 ready, 1 still deploying). 
Version: 20151030t123536.388208395436616202

This can happen when your application does not start successfully.
Please check your project logs at:
https://console.developers.google.com/project/jdalabs-retail-me-dev01/appengine/
logs?versionId=20151030t123536&moduleId=default

(You may have to select a log name to see the logs.)

Installation information:

Google Cloud SDK [0.9.79]

Platform: [Mac OS X, x86_64]
[output truncated]
Python Version: [2.7.5 (default, Mar  9 2014, 22:15:05)  [GCC 4.2.1 Compatible 
Apple LLVM 5.0 (clang-500.0.68)]]
Site Packages: [Disabled]

Installation Root: [/usr/local/share/google/google-cloud-sdk]
Installed Components:
  core: [2015.09.23]
  app-engine-python: [1.9.26]
  core-nix: [2015.09.03]
  app: [2015.09.23]
  gcloud: [2015.09.21]
  gsutil-nix: [4.14]
  gsutil: [4.15]
  bq: [2.0.18]
  preview: [2015.09.21]
  app-engine-java: [1.9.26]
  bq-nix: [2.0.18]
System PATH: 
[/usr/local/share/google/google-cloud-sdk/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr
/local/bin:/usr/local/git/bin:/usr/local/apache-maven-3.2.1/bin]
Cloud SDK on PATH: [True]

Installation Properties: [/usr/local/share/google/google-cloud-sdk/properties]
User Config Directory: [/Users/J1008690/.config/gcloud]
User Properties: [/Users/J1008690/.config/gcloud/properties]
Current Workspace: [None]
Workspace Config Directory: [None]
Workspace Properties: [None]

Account: [kusuma.seshavarapu@jda.com]
Project: [jdalabs-retail-me-dev01]

Current Properties:
  [core]
    project: [jdalabs-retail-me-dev01]
    account: [kusuma.seshavarapu@jda.com]
    disable_usage_reporting: [False]

Logs Directory: [/Users/J1008690/.config/gcloud/logs]
Last Log File: 
[/Users/J1008690/.config/gcloud/logs/2015.10.30/12.35.35.840237.log]

```

Original issue reported on code.google.com by `kusuma.s...@jda.com` on 30 Oct 2015 at 8:30

**Comment by GoogleCodeExporter** [comment]
```
This got resolved after adding the client-secret.json to web-inf. 

You can close this issue.
```

Original comment by `kusuma.s...@jda.com` on 30 Oct 2015 at 9:11

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the follow-up.
```

Original comment by `gsfow...@google.com` on 3 Nov 2015 at 8:30
- Changed state: **Done**
