### ISSUE TITLE
gcloud container clusters get-credentials cluster-1 command crashed

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#361]
```
What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "calliope/cli.py", line 598, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "calliope/backend.py", line 1216, in Run
    last_group = context_filter(tool_context, Http, args)
  File "calliope/backend.py", line 580, in ContextFilter
    group.Filter(context, args)
  File "surface/container/__init__.py", line 54, in Filter
    api_version, endpoint_url, self.Http())
  File "calliope/base.py", line 279, in Http
    return self._http_func(auth=auth, creds=creds, **kwargs)
  File "calliope/backend.py", line 1211, in Http
    **kwargs)
  File "core/cli.py", line 126, in Http
    creds = c_store.Load()
  File "core/credentials/store.py", line 237, in Load
    if account in c_gce.Metadata().Accounts():
  File "core/credentials/gce.py", line 189, in Metadata
    _metadata_lock.lock(function=_CreateMetadata, argument=None)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/mutex.py", line 44, in lock
    function(argument)
  File "core/credentials/gce.py", line 188, in _CreateMetadata
    _metadata = _GCEMetadata()
  File "core/credentials/gce.py", line 45, in __init__
    self.connected = gce_cache.GetOnGCE()
  File "core/credentials/gce_cache.py", line 91, in GetOnGCE
    return _SINGLETON_ON_GCE_CACHE.GetOnGCE(check_age)
  File "core/credentials/gce_cache.py", line 54, in GetOnGCE
    self._UpdateFileCache()
[output truncated]

```

Original issue reported on code.google.com by `ho.clare...@gmail.com` on 31 Oct 2015 at 6:06

**Comment by GoogleCodeExporter** [comment]
```
What is the gcloud command line that produced the traceback?
```

Original comment by `gsfow...@google.com` on 3 Nov 2015 at 8:28

**Comment by GoogleCodeExporter** [comment]
Original comment by `gsfow...@google.com` on 3 Nov 2015 at 8:28
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
Assuming the command line is the same as the issue subject.

Unfortunately the interesting part of the traceback was truncated by 'gcloud 
feedback' (we are working on that!). Can you run the command again, and then 
run gcloud feedback, and cut and paste the tail end of the traceback into the 
report?
thanks
```

Original comment by `gsfow...@google.com` on 10 Nov 2015 at 2:13

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 4 Jan 2016 at 2:20
- Changed state: **Invalid**
