### ISSUE TITLE
ValueError: path is on drive c:, start on drive E:

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#363]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?

Attempt to deploy custom Managed VM from drive other than C:


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "calliope\cli.py", line 598, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "calliope\backend.py", line 1226, in Run
    resources = command_instance.Run(args)
  File "appengine\app_commands\deploy.py", line 259, in Run
    remote_build)
  File "appengine\lib\deploy_command_util.py", line 143, in BuildAndPushDockerImages
    with docker_util.DockerHost(cli, version_id, remote) as docker_client:
  File "appengine\lib\images\docker_util.py", line 209, in __enter__
    self._vm = Provision(self._cli, self._name, self._zone)
  File "appengine\lib\images\docker_util.py", line 52, in Provision
    vm = _CreateVm(cli, name, zone)
  File "appengine\lib\images\docker_util.py", line 107, in _CreateVm
    return _Vm(cli, vm_info[0])
  File "appengine\lib\images\docker_util.py", line 126, in __init__
    self.cert_dir = os.path.relpath(tempfile.mkdtemp())
  File "C:\python27_x64\lib\ntpath.py", line 529, in relpath
    % (path_prefix, start_prefix))
ValueError: path is on drive c:, start on drive E:

Installation information:

Google Cloud SDK [0.9.84]

Platform: [Windows, x86_64]
Python Version: [2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit 
(AMD64)]]
Site Packages: [Disabled]

Installation Root: [C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk]
Installed Components:
  core: [2015.10.23]
  app-engine-python: [1.9.27]
[output]


My Project is on drive E:

```

Original issue reported on code.google.com by `bugahdug` on 1 Nov 2015 at 7:47
- Merged into: #258

**Comment by GoogleCodeExporter** [comment]
Original comment by `gsfow...@google.com` on 3 Nov 2015 at 7:55
- Changed state: **Duplicate**
