### ISSUE TITLE
cant ssh

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#364]
```
What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "calliope\cli.py", line 598, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "calliope\backend.py", line 1216, in Run
    last_group = context_filter(tool_context, Http, args)
  File "calliope\backend.py", line 580, in ContextFilter
    group.Filter(context, args)
  File "compute\subcommands\__init__.py", line 56, in Filter
    _DoFilter(context, self.Http(), 'v1', args)
  File "calliope\base.py", line 279, in Http
    return self._http_func(auth=auth, creds=creds, **kwargs)
  File "calliope\backend.py", line 1211, in Http
    **kwargs)
  File "core\cli.py", line 126, in Http
    creds = c_store.Load()
  File "core\credentials\store.py", line 237, in Load
    if account in c_gce.Metadata().Accounts():
  File "core\credentials\gce.py", line 189, in Metadata
    _metadata_lock.lock(function=_CreateMetadata, argument=None)
  File "C:\python27_x64\lib\mutex.py", line 44, in lock
    function(argument)
  File "core\credentials\gce.py", line 188, in _CreateMetadata
    _metadata = _GCEMetadata()
  File "core\credentials\gce.py", line 45, in __init__
    self.connected = gce_cache.GetOnGCE()
  File "core\credentials\gce_cache.py", line 91, in GetOnGCE
    return _SINGLETON_ON_GCE_CACHE.GetOnGCE(check_age)
  File "core\credentials\gce_cache.py", line 54, in GetOnGCE
    self._UpdateFileCache()
  File "core\credentials\gce_cache.py", line 71, in _UpdateFileCache
[output truncated]

```

Original issue reported on code.google.com by `azi...@1tube.my` on 2 Nov 2015 at 6:25

**Comment by GoogleCodeExporter** [comment]
```
What gcloud command line produced the traceback?
```

Original comment by `gsfow...@google.com` on 3 Nov 2015 at 8:27
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 4 Jan 2016 at 2:06
- Changed state: **Invalid**
