### ISSUE TITLE
Unable to deploy when App Engine Admin API is enabled in gcloud

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#365]
```
Issue running command [gcloud preview app deploy].

Running a `gcloud preview app deploy` with `gcloud config set 
app/use_appengine_api true` fails when handling *some* static images.

Traceback (most recent call last):
  File "calliope/cli.py", line 598, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "calliope/backend.py", line 1226, in Run
    resources = command_instance.Run(args)
  File "appengine/app_commands/deploy.py", line 274, in Run
    app_config.NonHermeticModules().items(), code_bucket)
  File "appengine/lib/deploy_app_command_util.py", line 43, in CopyFilesToCodeBucket
    log.status.Print('Copying files to Google Cloud Storage...')
  File "core/log.py", line 118, in Print
    self.write(message + '\n')
  File "core/log.py", line 139, in write
    self.__stream_wrapper.stream.write(stream_msg)
IOError: [Errno 11] Resource temporarily unavailable

Installation information:

Google Cloud SDK [0.9.84]

Platform: [Linux, x86_64]
Python Version: [2.7.6 (default, Jun 22 2015, 17:58:13)  [GCC 4.8.2]]
Site Packages: [Disabled]

Installation Root: [/home/zeapo/Deploy/google-cloud-sdk]
Installed Components:
  app-engine-python-extras: [1.9.21]
  core: [2015.10.23]
  app-engine-python: [1.9.27]
  core-nix: [2015.09.03]
  kubectl: []
  app-engine-java: [1.9.27]
  gcloud: [2015.10.23]
  gsutil-nix: [4.14]
  app-engine-php: [ ]
  beta: [2015.10.08]
  gsutil: [4.15]
  bq: [2.0.18]
  alpha: [2015.10.08]
  kubectl-linux-x86_64: [1.0.6]
  app: [2015.10.23]
  bq-nix: [2.0.18]
[output truncated]

```

Original issue reported on code.google.com by `moha...@lumapps.com` on 2 Nov 2015 at 9:44

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the report. I passed this on to the app team.
```

Original comment by `gsfow...@google.com` on 3 Nov 2015 at 8:26

**Comment by GoogleCodeExporter** [comment]
```
Thanks for reporting this, and sorry for the delay in response.

The line at which this is failing is a logging line. This shouldn't fail under 
normal circumstances, and has very little to do with which API is used for 
deployment. Is your disk full, perhaps? Are the permissions on your log file 
(~/.config/gcloud) writable? Are you deploying from an interactive terminal?
```

Original comment by `z...@google.com` on 24 Nov 2015 at 7:31
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
This issue is reproducible by another team member. The config folder is
writable and I am deploying from an interactive terminal. However, we are
no longer having the error in the first post but this one:

Updating module [default]...\DEBUG: Operation
[apps/<>/operations/c4d035f7-699d-43f8-ace7-37eb39260300] complete. Result:
{
    "metadata": {
        "target": "apps/<>/modules/default/versions/mo",
        "insertTime": "2015-11-25T08:33:12.899Z",
        "method": "google.appengine.v1beta4.Versions.CreateVersion",
        "user": "mohamed@lumapps.com",
        "operationType": "create_version",
        "endTime": "2015-11-25T08:34:47.014Z",
        "@type": "
type.googleapis.com/google.appengine.v1beta4.OperationMetadata"
    },
    "done": true,
    "name": "apps/<>/operations/c4d035f7-699d-43f8-ace7-37eb39260300",
    "error": {
        "message": "An internal error occurred.",
        "code": 13
    }
}
Updating module [default]...failed.
DEBUG: (gcloud.preview.app.deploy) Error Response: [13] An internal error
occurred.
Traceback (most recent call last):
  File
"/home/zeapo/Deploy/google-cloud-sdk/./lib/googlecloudsdk/calliope/cli.py",
line 609, in Execute
    result = args.cmd_func(cli=self, args=args)
  File
"/home/zeapo/Deploy/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py",
line 1228, in Run
    resources = command_instance.Run(args)
  File
"/home/zeapo/Deploy/google-cloud-sdk/./lib/googlecloudsdk/surface/preview/app/de
ploy.py",
line 296, in Run
    images.get(module))
  File
"/home/zeapo/Deploy/google-cloud-sdk/./lib/googlecloudsdk/api_lib/app/appengine_
api_client.py",
line 76, in DeployModule
    return operations.WaitForOperation(self.client.apps_operations,
operation)
  File
"/home/zeapo/Deploy/google-cloud-sdk/./lib/googlecloudsdk/api_lib/app/api/operat
ions.py",
line 54, in WaitForOperation
    encoding.MessageToPyValue(completed_operation.error)))
OperationError: Error Response: [13] An internal error occurred.
ERROR: (gcloud.preview.app.deploy) Error Response: [13] An internal error
occurred.


Strangely the application is accessible even after this error.
```

Original comment by `moha...@lumapps.com` on 25 Nov 2015 at 8:39

**Comment by GoogleCodeExporter** [comment]
```
Is this reproducible now? Internal errors like this are often transient.

I'll contact the backend team and see if they can look into this.
```

Original comment by `z...@google.com` on 26 Nov 2015 at 3:58

**Comment by GoogleCodeExporter** [comment]
```
Please re-open if you're still experiencing this.
```

Original comment by `z...@google.com` on 4 Jan 2016 at 2:08
- Changed state: **Invalid**
