### ISSUE TITLE
gcloud crash when I am using it in different drive other than C in windows 10

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#366]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "calliope\cli.py", line 598, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "calliope\backend.py", line 1226, in Run
    resources = command_instance.Run(args)
  File "appengine\app_commands\deploy.py", line 259, in Run
    remote_build)
  File "appengine\lib\deploy_command_util.py", line 143, in BuildAndPushDockerImages
    with docker_util.DockerHost(cli, version_id, remote) as docker_client:
  File "appengine\lib\images\docker_util.py", line 209, in __enter__
    self._vm = Provision(self._cli, self._name, self._zone)
  File "appengine\lib\images\docker_util.py", line 52, in Provision
    vm = _CreateVm(cli, name, zone)
  File "appengine\lib\images\docker_util.py", line 107, in _CreateVm
    return _Vm(cli, vm_info[0])
  File "appengine\lib\images\docker_util.py", line 126, in __init__
    self.cert_dir = os.path.relpath(tempfile.mkdtemp())
  File "C:\Python27\lib\ntpath.py", line 512, in relpath
    % (path_prefix, start_prefix))
ValueError: path is on drive c:, start on drive E:

Installation information:

Google Cloud SDK [0.9.84]

Platform: [Windows, x86_64]
Python Version: [2.7.3 (default, Apr 10 2012, 23:24:47) [MSC v.1500 64 bit 
(AMD64)]]
Site Packages: [Disabled]

Installation Root: [C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk]
Installed Components:
  core: [2015.10.23]
  bq-win: [2.0.18]
[output truncated]

```

Original issue reported on code.google.com by `jamesmwa...@gmail.com` on 2 Nov 2015 at 10:24
- Merged into: #258

**Comment by GoogleCodeExporter** [comment]
Original comment by `gsfow...@google.com` on 3 Nov 2015 at 7:56
- Changed state: **Duplicate**
