### ISSUE TITLE
Cannot activate service account

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#368]
```
Issue running command [gcloud auth activate].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\cli.py", line 592, in Execute
    command_path_string = '.'.join(args.command_path)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\backend.py", line 1223, in Run
    format_string=args.format or 'yaml')
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\surface\auth\activate_service_account.py", line 122, in Run
    c_store.Refresh(cred)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\core\credentials\store.py", line 267, in Refresh
    creds.refresh(http or _Http())
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\oauth2client\client.py", line 597, in refresh
    self._refresh(http.request)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\oauth2client\client.py", line 768, in _refresh
    self._do_refresh_request(http_request)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\oauth2client\client.py", line 794, in _do_refresh_request
    body = self._generate_refresh_request_body()
[output truncated]

```

Original issue reported on code.google.com by `hungandr...@gmail.com` on 4 Nov 2015 at 8:02

**Comment by GoogleCodeExporter** [comment]
```
Beside the traceback was there any other error message?
```

Original comment by `gsfow...@google.com` on 4 Nov 2015 at 1:54
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 4 Jan 2016 at 2:07
- Changed state: **Invalid**
