### ISSUE TITLE
reverse --sort-by combined with --format crashes

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#375]
```
Issue running command [gcloud compute snapshots list].

What steps will reproduce the problem?

gcloud compute snapshots list --limit=1 --format='value(name)' 
--sort-by='~creationTimestamp'

What is the expected output? What do you see instead?

I expect to see the name of the most recently created snapshot. Instead, I get:

ERROR: (gcloud.compute.snapshots.list) value not expected 
[value(name):(creationTimestamp:sort=1:reverse *HERE* =1)].


Please provide any additional information below.

Invoking --sort-by without '~' (nor reversed) does not cause error, and 
produces expected output; this works:

gcloud compute snapshots list --limit=1 --format='value(name)' 
--sort-by='creationTimestamp'

This has been working until I upgraded to Google Cloud SDK [0.9.85] (from .83) 
today. 



Traceback (most recent call last):
  File "calliope/cli.py", line 605, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "calliope/backend.py", line 1229, in Run
    display.Displayer(command_instance, args, resources).Display()
  File "calliope/display.py", line 352, in Display
    self._resources, fmt, defaults=self._defaults, out=log.out)
  File "core/resource/resource_printer.py", line 161, in Print
    printer = Printer(print_format, out=out, defaults=defaults)
  File "core/resource/resource_printer.py", line 128, in Printer
    symbols=resource_transform.GetTransforms())
  File "core/resource/resource_projector.py", line 393, in Compile
    symbols=symbols)
  File "core/resource/resource_projection_parser.py", line 477, in Parse
    return Parser(defaults=defaults, symbols=symbols).Parse(expression)
  File "core/resource/resource_projection_parser.py", line 449, in Parse
    self._ParseKeys()
  File "core/resource/resource_projection_parser.py", line 383, in _ParseKeys
    self._ParseKey()
  File "core/resource/resource_projection_parser.py", line 366, in _ParseKey
    self._ParseKeyAttributes(key, attribute)
  File "core/resource/resource_projection_parser.py", line 291, in _ParseKeyAttributes
    'value not expected [{0}].'.format(self._lex.Annotate(here)))
ExpressionSyntaxError: value not expected 
[value(name):(creationTimestamp:sort=1:reverse *HERE* =1)].

Installation information:

[output truncated]

```

Original issue reported on code.google.com by `mkocikow...@gmail.com` on 6 Nov 2015 at 8:21

**Comment by GoogleCodeExporter** [comment]
```
This is fixed in Cloud SDK 0.9.87, which is currently available.
```

Original comment by `z...@google.com` on 24 Nov 2015 at 7:15
- Changed state: **Fixed**
