### ISSUE TITLE
ERROR: gcloud crashed (ResponseNotReady):

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#377]
```
Issue running command [gcloud init].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk\calliope\cli.py", line 605, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk\calliope\backend.py", line 1228, in Run
    resources = command_instance.Run(args)
  File "googlecloudsdk\surface\init.py", line 85, in Run
    if not self._PickAccount(args.console_only):
  File "googlecloudsdk\surface\init.py", line 137, in _PickAccount
    disable_user_output=False):
  File "googlecloudsdk\surface\init.py", line 381, in _RunCmd
    result = self.cli.Execute(args)
  File "googlecloudsdk\calliope\cli.py", line 605, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk\calliope\backend.py", line 1228, in Run
    resources = command_instance.Run(args)
  File "googlecloudsdk\calliope\exceptions.py", line 98, in TryFunc
    return func(*args, **kwargs)
  File "googlecloudsdk\surface\auth\login.py", line 111, in Run
    creds = self.DoWebFlow(args.launch_browser)
  File "googlecloudsdk\surface\auth\login.py", line 176, in DoWebFlow
    return c_store.AcquireFromWebFlow(launch_browser=launch_browser)
  File "googlecloudsdk\core\credentials\store.py", line 383, in AcquireFromWebFlow
    http=_Http())
  File "googlecloudsdk\core\credentials\flow.py", line 156, in Run
    credential = flow.step2_exchange(code, http=http)
  File "oauth2client\util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
[output truncat

```

Original issue reported on code.google.com by `Rego.I...@gmail.com` on 9 Nov 2015 at 7:51

**Comment by GoogleCodeExporter** [comment]
```
Is this issue similar to 
https://code.google.com/p/google-cloud-sdk/issues/detail?id=309

Can you follow same workaround and let us know if it has worked for you?
```

Original comment by `che...@google.com` on 9 Nov 2015 at 12:03
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
I have the same error. Updated the thread: 
https://code.google.com/p/google-cloud-sdk/issues/detail?id=309
```

Original comment by `rset...@gmail.com` on 28 Dec 2015 at 7:22

**Comment by GoogleCodeExporter** [comment]
```
Please update if you're still experiencing this.
```

Original comment by `z...@google.com` on 4 Jan 2016 at 2:05
- Changed state: **Invalid**
