### ISSUE TITLE
Deploy fails for NVN

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#378]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "calliope/cli.py", line 605, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "calliope/backend.py", line 1228, in Run
    resources = command_instance.Run(args)
  File "surface/preview/app/deploy.py", line 267, in Run
    remote_build)
  File "api_lib/app/deploy_command_util.py", line 169, in BuildAndPushDockerImages
    info.file, docker_client, image_name)
  File "api_lib/app/deploy_command_util.py", line 241, in BuildAndPushDockerImage
    image.Push(docker_client)
  File "api_lib/app/docker_image.py", line 159, in Push
    _Retry(InnerPush)
  File "api_lib/app/docker_image.py", line 185, in _Retry
    raise e
APIError: 500 Server Error: Internal Server Error ("push 
appengine.gcr.io/gcloud/nozzle-app.rankings.republish is already in progress")

Installation information:

Google Cloud SDK [0.9.85]

Platform: [Mac OS X, x86_64]
Python Version: [2.7.10 (default, Aug 22 2015, 20:33:39)  [GCC 4.2.1 Compatible 
Apple LLVM 7.0.0 (clang-700.0.59.1)]]
Site Packages: [Disabled]

Installation Root: [/Users/derek/google-cloud-sdk]
Installed Components:
  core: [2015.10.30]
  app-engine-python: [1.9.28]
  core-nix: [2015.09.03]
  kubectl: []
  app-engine-java: [1.9.28]
  gcloud: [2015.10.30]
  gsutil-nix: [4.14]
  app-engine-python-extras: [1.9.21]
  beta: [2015.10.08]
  gsutil: [4.15]
  bq: [2.0.18]
  alpha: [2015.10.08]
  bq-nix: [2.0.18]
[output truncated]

```

Original issue reported on code.google.com by `de...@derekperkins.com` on 9 Nov 2015 at 10:08

**Comment by GoogleCodeExporter** [comment]
```
Is this a reproducible issue? The error message suggests that there are 
multiple deployments occurring at the same time.
```

Original comment by `z...@google.com` on 9 Nov 2015 at 1:53
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
Please re-open if you're still experiencing this.
```

Original comment by `z...@google.com` on 4 Jan 2016 at 2:07
- Changed state: **Invalid**
