### ISSUE TITLE
Managed VMs cannot be deployed if the "staging.appid.appspot.com" is accidentally deleted

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#379]
```
Observed results:
Copying files to Google Cloud Storage...
Synchronizing files to [gs://staging.i-digi-sign.appspot.com/].
ERROR: (gcloud.preview.app.deploy) Could not synchronize files. The gsutil 
command exited with status [1]. Command output is available in 
[/home/zilong.wzl/.config/gcloud/logs/2015.11.09/10.45.06.730729.log].

Log:
Building synchronization state...
Caught non-retryable exception while listing 
gs://staging.i-digi-sign.appspot.com/: BucketNotFoundException: 404 
gs://staging.i-digi-sign.appspot.com bucket does not exist.
CommandException: Caught non-retryable exception - aborting rsync

2015-11-09 10:46:29,423 DEBUG    root            (gcloud.preview.app.deploy) 
Could not synchronize files. The gsutil command exited with status [1]. Command 
output is available in 
[/home/zilong.wzl/.config/gcloud/logs/2015.11.09/10.45.06.730729.log].
Traceback (most recent call last):
  File "/home/zilong.wzl/google-cloud-sdk/./lib/googlecloudsdk/calliope/cli.py", line 605, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "/home/zilong.wzl/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 1228, in Run
    resources = command_instance.Run(args)
  File "/home/zilong.wzl/google-cloud-sdk/./lib/googlecloudsdk/surface/preview/app/deploy.py", line 282, in Run
    app_config.NonHermeticModules().items(), code_bucket)
  File "/home/zilong.wzl/google-cloud-sdk/./lib/googlecloudsdk/api_lib/app/deploy_app_command_util.py", line 51, in CopyFilesToCodeBucket
    s=exit_code, l=log.GetLogFilePath()))
ToolException: Could not synchronize files. The gsutil command exited with 
status [1]. Command output is available in 
[/home/zilong.wzl/.config/gcloud/logs/2015.11.09/10.45.06.730729.log].
2015-11-09 10:46:29,424 ERROR    root            (gcloud.preview.app.deploy) 
Could not synchronize files. The gsutil command exited with status [1]. Command 
output is available in 
[/home/zilong.wzl/.config/gcloud/logs/2015.11.09/10.45.06.730729.log].


I made the mistake of deleting the storage bucket entitled 
"staging.APPID.appspot.com" for my deployment as described in this report.


```

Original issue reported on code.google.com by `wzl198...@gmail.com` on 9 Nov 2015 at 11:07

Attachments:
- [10.45.06.730729.log](https://storage.googleapis.com/google-code-attachments/google-cloud-sdk/issue-379/comment-0/10.45.06.730729.log)

**Comment by GoogleCodeExporter** [comment]
```
Issue 321 has been merged into this issue.
```

Original comment by `z...@google.com` on 20 Nov 2015 at 11:20

**Comment by GoogleCodeExporter** [comment]
```
This is also tracked here: 
https://code.google.com/p/googleappengine/issues/detail?id=12502
```

Original comment by `deben...@gmail.com` on 21 Nov 2015 at 6:18

**Comment by GoogleCodeExporter** [comment]
```
For now, the workaround is to create a new Google Cloud Storage bucket and pass 
it in using the --bucket argument.

We're working on this on the backend.
```

Original comment by `z...@google.com` on 24 Nov 2015 at 7:12
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
FWIW following the instructions listed here 
https://docs.travis-ci.com/user/deployment/google-app-engine results in the 
error described in this issue.
```

Original comment by `sethladd@gmail.com` on 22 Dec 2015 at 12:17

**Comment by GoogleCodeExporter** [comment]
```
This is fixed on the backend; please let me know if you're still experiencing 
the issue.
```

Original comment by `z...@google.com` on 10 Mar 2016 at 3:17
- Changed state: **Fixed**
