### ISSUE TITLE
issue only issues

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#381]
```
Issue running command [gcloud deployment].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk\calliope\cli.py", line 605, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk\calliope\backend.py", line 1228, in Run
    resources = command_instance.Run(args)
  File "googlecloudsdk\surface\deployment_manager\deployments\create.py", line 112, in Run
    messages, args.config, args.properties),
  File "googlecloudsdk\api_lib\deployment_manager\importer.py", line 400, in BuildTargetConfig
    imports=_CreateImports(messages, config_object))
  File "googlecloudsdk\api_lib\deployment_manager\importer.py", line 308, in _CreateImports
    content=import_object.GetContent())
  File "protorpc\messages.py", line 747, in __init__
    setattr(self, name, value)
  File "protorpc\messages.py", line 926, in __setattr__
    object.__setattr__(self, name, value)
  File "protorpc\messages.py", line 1232, in __set__
    self.validate(value)
  File "protorpc\messages.py", line 1321, in validate
    self.__validate(value, self.validate_element)
  File "protorpc\messages.py", line 1287, in __validate
    validate_element(value)
  File "protorpc\messages.py", line 1452, in validate_element
    raise validation_error
ValidationError: Field content encountered non-ASCII string import 
helpers.common

def GenerateConfig(_):
  return 
resources: 
- name: %(name)s
  type: compute.v1.instance
  properties:
[output truncated]

```

Original issue reported on code.google.com by `banoafre...@gmail.com` on 10 Nov 2015 at 9:29

**Comment by GoogleCodeExporter** [comment]
```
Thanks for reporting this. Do you mind posting the exact command you were 
trying to run (scrubbed of any potentially sensitive information)? `gcloud 
deployment` is not a valid command.
```

Original comment by `z...@google.com` on 24 Nov 2015 at 5:56
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 4 Jan 2016 at 2:06
- Changed state: **Invalid**
