### ISSUE TITLE
Gcloud ssh crash

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#382]
```
Issue running command [gcloud compute ssh].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk/calliope/cli.py", line 592, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk/calliope/backend.py", line 1223, in Run
    resources = command_instance.Run(args)
  File "googlecloudsdk/compute/subcommands/ssh.py", line 113, in Run
    external_ip_address = self.GetInstanceExternalIpAddress(instance_ref)
  File "googlecloudsdk/shared/compute/ssh_utils.py", line 430, in GetInstanceExternalIpAddress
    custom_get_requests=None))
  File "googlecloudsdk/shared/compute/request_helper.py", line 135, in MakeRequests
    requests=requests, http=http, batch_url=batch_url)
  File "googlecloudsdk/shared/compute/batch_helper.py", line 30, in MakeRequests
    responses = batch.Execute(http)
  File "googlecloudsdk/third_party/apitools/base/py/batch.py", line 181, in Execute
    batch_http_request.Execute(http)
  File "googlecloudsdk/third_party/apitools/base/py/batch.py", line 423, in Execute
    self._Execute(http)
  File "googlecloudsdk/third_party/apitools/base/py/batch.py", line 386, in _Execute
    response = http_wrapper.MakeRequest(http, request)
  File "googlecloudsdk/third_party/apitools/base/py/http_wrapper.py", line 310, in MakeRequest
    retry_func(ExceptionRetryArgs(http, http_request, e, retry))
  File "googlecloudsdk/third_party/apitools/base/py/http_wrapper.py", line 302, in MakeRequest
    check_response_func=check_response_func)
[output truncated]

```

Original issue reported on code.google.com by `nick....@abracontrols.com` on 10 Nov 2015 at 5:16

**Comment by GoogleCodeExporter** [comment]
```
Thanks for reporting this. Do you mind posting the full traceback (should be in 
the output of the `gcloud feedback` command?

Also, is this a repeatable issue? Do you see it every time or just on occasion?
```

Original comment by `z...@google.com` on 24 Nov 2015 at 5:55
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
I beleave this is a permission issue

I had err same like you when I execute gustily

after I update my permission, it’s all ok

sudo chown -R xinzhouliu:xinzhouliu .config

Please try again
```

Original comment by `nick....@abracontrols.com` on 24 Nov 2015 at 6:00

**Comment by GoogleCodeExporter** [comment]
```
If you give us the full error message, we can look into reproducing and 
improving the messaging here.

If not, I'm happy to just close this out.
```

Original comment by `z...@google.com` on 24 Nov 2015 at 7:05

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 4 Jan 2016 at 2:19
- Changed state: **Invalid**
