### ISSUE TITLE
gcloud appl deploy crashes when gcloud installed on  Windows 7 drive other than C:

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#383]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?
Install gcloud on drive other than C: such as F:

What is the expected output? What do you see instead?
expected to work ?
Saw gcloud crashed (ValueError): path is on drive C:, start on drive F:

Please provide any additional information below.


Traceback (most recent call last):
  File "calliope\cli.py", line 605, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "calliope\backend.py", line 1228, in Run
    resources = command_instance.Run(args)
  File "surface\preview\app\deploy.py", line 267, in Run
    remote_build)
  File "api_lib\app\deploy_command_util.py", line 159, in BuildAndPushDockerImages
    with docker_util.DockerHost(cli, version_id, remote) as docker_client:
  File "api_lib\app\images\docker_util.py", line 208, in __enter__
    self._vm = Provision(self._cli, self._name, self._zone)
  File "api_lib\app\images\docker_util.py", line 51, in Provision
    vm = _CreateVm(cli, name, zone)
  File "api_lib\app\images\docker_util.py", line 106, in _CreateVm
    return _Vm(cli, vm_info[0])
  File "api_lib\app\images\docker_util.py", line 125, in __init__
    self.cert_dir = os.path.relpath(tempfile.mkdtemp())
  File "C:\python27_x64\lib\ntpath.py", line 529, in relpath
    % (path_prefix, start_prefix))
ValueError: path is on drive c:, start on drive F:

Installation information:

Google Cloud SDK [0.9.85]

Platform: [Windows, x86_64]
Python Version: [2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit 
(AMD64)]]
Site Packages: [Disabled]

Installation Root: [F:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk]
Installed Components:
  core: [2015.10.30]
  bq-win: [2.0.18]
[output truncated]

```

Original issue reported on code.google.com by `rgo...@ragould.com` on 10 Nov 2015 at 11:49

**Comment by GoogleCodeExporter** [comment]
```
This issue should be fixed as of the 0.9.87 Cloud SDK release from a couple of 
days ago. Please let us know if it's not.
```

Original comment by `z...@google.com` on 20 Nov 2015 at 10:26
- Changed state: **Fixed**
