### ISSUE TITLE
some issuse

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#384]
```
Issue running command [gcloud init].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk\calliope\cli.py", line 605, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk\calliope\backend.py", line 1228, in Run
    resources = command_instance.Run(args)
  File "googlecloudsdk\surface\init.py", line 91, in Run
    self._PickDefaultRegionAndZone()
  File "googlecloudsdk\surface\init.py", line 240, in _PickDefaultRegionAndZone
    project_info = self._RunCmd(['compute', 'project-info', 'describe'])
  File "googlecloudsdk\surface\init.py", line 381, in _RunCmd
    result = self.cli.Execute(args)
  File "googlecloudsdk\calliope\cli.py", line 605, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk\calliope\backend.py", line 1228, in Run
    resources = command_instance.Run(args)
  File "googlecloudsdk\api_lib\compute\base_classes.py", line 649, in Run
    resources = list(self.ComputeDynamicProperties(args, resources))
  File "googlecloudsdk\api_lib\compute\lister.py", line 40, in ProcessResults
    for resource in resources:
  File "googlecloudsdk\api_lib\compute\lister.py", line 12, in _ConvertProtobufsToDicts
    for resource in resources:
  File "googlecloudsdk\api_lib\compute\request_helper.py", line 134, in MakeRequests
    requests=requests, http=http, batch_url=batch_url)
  File "googlecloudsdk\api_lib\compute\batch_helper.py", line 30, in MakeRequests
    responses = batch.Execute(http)
[output truncated]

```

Original issue reported on code.google.com by `zuni5339...@gmail.com` on 11 Nov 2015 at 2:57
- Merged into: #323

**Comment by GoogleCodeExporter** [comment]
Original comment by `che...@google.com` on 11 Nov 2015 at 12:29
- Changed state: **Duplicate**
