### ISSUE TITLE
CRASH : gcloud auth login

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#386]
```
Issue running command [gcloud auth login].

What steps will reproduce the problem?
gcloud auth login --no-launch-browser

What is the expected output? What do you see instead?


Please provide any additional information below.
I am using VPN to login from a Windows 10 machine.

Traceback (most recent call last):
  File "googlecloudsdk\calliope\cli.py", line 605, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk\calliope\backend.py", line 1228, in Run
    resources = command_instance.Run(args)
  File "googlecloudsdk\calliope\exceptions.py", line 98, in TryFunc
    return func(*args, **kwargs)
  File "googlecloudsdk\surface\auth\login.py", line 111, in Run
    creds = self.DoWebFlow(args.launch_browser)
  File "googlecloudsdk\surface\auth\login.py", line 176, in DoWebFlow
    return c_store.AcquireFromWebFlow(launch_browser=launch_browser)
  File "googlecloudsdk\core\credentials\store.py", line 383, in AcquireFromWebFlow
    http=_Http())
  File "googlecloudsdk\core\credentials\flow.py", line 156, in Run
    credential = flow.step2_exchange(code, http=http)
  File "oauth2client\util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "oauth2client\client.py", line 1993, in step2_exchange
    headers=headers)
  File "httplib2\__init__.py", line 1608, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "httplib2\__init__.py", line 1350, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "httplib2\__init__.py", line 1306, in _conn_request
    response = conn.getresponse()
[output truncated]

```

Original issue reported on code.google.com by `Rego.I...@gmail.com` on 12 Nov 2015 at 6:41
- Merged into: #330

**Comment by GoogleCodeExporter** [comment]
```
Thanks for reporting! I'm marking this as a duplicate of a similar issue.

This message usually means that you're having some sort of network issues in 
between your machine and the Google API servers. Are you behind a 
proxy/firewall, or do you have any other unusual network settings?
```

Original comment by `z...@google.com` on 24 Nov 2015 at 5:53
- Changed state: **Duplicate**
