### ISSUE TITLE
cannot deploy rails app

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#389]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk\calliope\cli.py", line 605, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk\calliope\backend.py", line 1228, in Run
    resources = command_instance.Run(args)
  File "googlecloudsdk\surface\preview\app\deploy.py", line 267, in Run
    remote_build)
  File "googlecloudsdk\api_lib\app\deploy_command_util.py", line 169, in BuildAndPushDockerImages
    info.file, docker_client, image_name)
  File "googlecloudsdk\api_lib\app\deploy_command_util.py", line 240, in BuildAndPushDockerImage
    image.Build(docker_client)
  File "googlecloudsdk\api_lib\app\docker_image.py", line 98, in Build
    nocache=self._nocache, rm=self._rm, pull=False)
  File "docker\docker\client.py", line 394, in build
    timeout=timeout,
  File "docker\docker\client.py", line 103, in _post
    return self.post(url, **self._set_request_timeout(kwargs))
  File "requests\sessions.py", line 507, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "requests\sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "requests\sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "requests\adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
[output truncated]

```

Original issue reported on code.google.com by `binhthuong8290` on 13 Nov 2015 at 7:17

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Can you please post the full stack trace and give us a description of what you 
were trying to do?
```

Original comment by `svalen...@google.com` on 19 Nov 2015 at 6:55
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 4 Jan 2016 at 2:09
- Changed state: **Invalid**
