### ISSUE TITLE
 Bookshelf APP: Got errors at npm install

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#390]
```
What steps will reproduce the problem?
The Bookshelf App
After: (1) git clone 
https://github.com/GoogleCloudPlatform/nodejs-getting-started.git -b 6-pubsub 
6-pubsub
(2)cd 6-pubsub
(3)updated config.js and app.yaml
(4)npm install

What is the expected output? What do you see instead?
Expect dependencies installed. 
I got error:
zijihgo@sanguine-willow-112918:~/6-pubsub$ npm install

> sse4_crc32@4.1.1 install 
/home/zijihgo/6-pubsub/node_modules/gcloud/node_modules/hash-stream-
validation/node_modules/fast-crc32c/node_modules/sse4_crc32
> node-gyp rebuild
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at exports._errnoException (util.js:746:11)
gyp ERR! stack     at TCP.onread (net.js:559:26)
gyp ERR! System Linux 3.16.0-0.bpo.4-amd64
gyp ERR! command "node" 
"/usr/local/nvm/versions/node/v0.12.2/lib/node_modules/npm/node_modules
/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd 
/home/zijihgo/6-pubsub/node_modules/gcloud/node_modules/hash-stream-validation/n
od
e_modules/fast-crc32c/node_modules/sse4_crc32
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm WARN optional dep failed, continuing sse4_crc32@4.1.1
npm WARN peerDependencies The peer dependency kerberos@~0.0 included from 
mongodb-core will no
npm WARN peerDependencies longer be automatically installed to fulfill the 
peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it 
explicitly.

What is the output of 'gcloud info'?


Please provide any additional information below.
I followed steps at: 
https://cloud.google.com/nodejs/getting-started/using-pub-sub#download_app


```

Original issue reported on code.google.com by `ziji...@gmail.com` on 14 Nov 2015 at 9:48

**Comment by GoogleCodeExporter** [comment]
```
Thanks for reporting this! This issue tracker is for the Google Cloud SDK, so 
it's appropriate for problems specifically with the `gcloud` command and app 
deployment.

This looks to be an issue with the nodejs-getting-started project. Do you mind 
filing an issue over there? 
(https://github.com/GoogleCloudPlatform/nodejs-getting-started/issues).
```

Original comment by `z...@google.com` on 16 Nov 2015 at 12:31
- Changed state: **Invalid**
