### ISSUE TITLE
Cannot install Google Cloud SDK 0.9.87 via apt-get

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#393]
```
What steps will reproduce the problem?

sudo apt-get install google-cloud-sdk

What is the expected output? What do you see instead?

Success

What is the output of 'gcloud info'?

$ gcloud info
Traceback (most recent call last):
  File "/usr/bin/../lib/google-cloud-sdk/./lib/googlecloudsdk/gcloud/gcloud.py", line 86, in <module>
    from googlecloudsdk.calliope import base
  File "/usr/bin/../lib/google-cloud-sdk/./lib/googlecloudsdk/calliope/base.py", line 8, in <module>
    from googlecloudsdk.calliope import usage_text
  File "/usr/bin/../lib/google-cloud-sdk/./lib/googlecloudsdk/calliope/usage_text.py", line 12, in <module>
    from googlecloudsdk.calliope import arg_parsers
  File "/usr/bin/../lib/google-cloud-sdk/./lib/googlecloudsdk/calliope/arg_parsers.py", line 43, in <module>
    from googlecloudsdk.core import log
  File "/usr/bin/../lib/google-cloud-sdk/./lib/googlecloudsdk/core/log.py", line 12, in <module>
    from googlecloudsdk.core import properties
  File "/usr/bin/../lib/google-cloud-sdk/./lib/googlecloudsdk/core/properties.py", line 11, in <module>
    from googlecloudsdk.core import exceptions
  File "/usr/bin/../lib/google-cloud-sdk/./lib/googlecloudsdk/core/config.py", line 307, in <module>

  File "/usr/bin/../lib/google-cloud-sdk/./lib/googlecloudsdk/core/config.py", line 279, in Load
    directory name so that different release channels can have separate
TypeError: __init__() got an unexpected keyword argument 'revision'



Please provide any additional information below.

Ubuntu 14.04


This did not happen in the previous version I had: 0.9.86-20151106084643-0
```

Original issue reported on code.google.com by `vsi...@gmail.com` on 19 Nov 2015 at 2:06

**Comment by GoogleCodeExporter** [comment]
```
I am unable to reproduce the issue. You certainly should not be getting any 
errors when running sudo apt-get install google-cloud-sdk. That doesn't run any 
gcloud code.

Could you try:

sudo apt-get remove google-cloud-sdk
sudo apt-get install google-cloud-sdk

Also paste the output of apt-cache policy google-cloud-sdk
```

Original comment by `stephe...@google.com` on 19 Nov 2015 at 7:04
- Changed state: **NeedsMoreInfo**
- Added labels: **OpSys-Linux**

**Comment by GoogleCodeExporter** [comment]
```
Thanks, that helped. Here is apt-cache policy before & after. 

$ apt-cache policy google-cloud-sdk
google-cloud-sdk:
  Installed: 0.9.87.1-20151118121533-0
  Candidate: 0.9.87.1-20151118121533-0
  Version table:
 *** 0.9.87.1-20151118121533-0 0
        500 http://packages.cloud.google.com/apt/ cloud-sdk-trusty/main amd64 Packages
        100 /var/lib/dpkg/status

$ sudo apt-get remove google-cloud-sdk
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  google-cloud-sdk
0 upgraded, 0 newly installed, 1 to remove and 18 not upgraded.
After this operation, 32.3 MB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 137463 files and directories currently installed.)
Removing google-cloud-sdk (0.9.87.1-20151118121533-0) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...

$ sudo apt-get install google-cloud-sdk
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  google-cloud-sdk
0 upgraded, 1 newly installed, 0 to remove and 18 not upgraded.
Need to get 0 B/4,360 kB of archives.
After this operation, 32.3 MB of additional disk space will be used.
Selecting previously unselected package google-cloud-sdk.
(Reading database ... 133380 files and directories currently installed.)
Preparing to unpack .../google-cloud-sdk_0.9.87.1-20151118121533-0_all.deb ...
Unpacking google-cloud-sdk (0.9.87.1-20151118121533-0) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Setting up google-cloud-sdk (0.9.87.1-20151118121533-0) ...

$ apt-cache policy google-cloud-sdk
google-cloud-sdk:
  Installed: 0.9.87.1-20151118121533-0
  Candidate: 0.9.87.1-20151118121533-0
  Version table:
 *** 0.9.87.1-20151118121533-0 0
        500 http://packages.cloud.google.com/apt/ cloud-sdk-trusty/main amd64 Packages
        100 /var/lib/dpkg/status

```

Original comment by `vsi...@gmail.com` on 19 Nov 2015 at 7:25

**Comment by GoogleCodeExporter** [comment]
```
That was a very odd error, glad reinstalling fixed it for you.
```

Original comment by `stephe...@google.com` on 19 Nov 2015 at 7:43
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Workaround, in case anyone experiences this in the meantime:

    sudo apt-get remove google-cloud-sdk
    sudo rm -rf /usr/lib/google-cloud-sdk
    sudo apt-get install google-cloud-sdk
```

Original comment by `z...@google.com` on 24 Nov 2015 at 2:48

**Comment by GoogleCodeExporter** [comment]
```
Actually, it has already been fixed. Just update to the latest version and this 
problem should go away.
```

Original comment by `stephe...@google.com` on 24 Nov 2015 at 3:18
