### ISSUE TITLE
gcloud docker push falls time to time

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#398]
```
Issue running command [gcloud docker].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk/calliope/cli.py", line 609, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk/calliope/backend.py", line 1228, in Run
    resources = command_instance.Run(args)
  File "googlecloudsdk/surface/docker.py", line 99, in Run
    docker.UpdateDockerCredentials(server)
  File "googlecloudsdk/core/docker/docker.py", line 133, in UpdateDockerCredentials
    store.Refresh(cred)
  File "googlecloudsdk/core/credentials/store.py", line 267, in Refresh
    creds.refresh(http or _Http())
  File "oauth2client/client.py", line 597, in refresh
    self._refresh(http.request)
  File "oauth2client/client.py", line 780, in _refresh
    self._do_refresh_request(http_request)
  File "oauth2client/client.py", line 799, in _do_refresh_request
    self.token_uri, method='POST', body=body, headers=headers)
  File "httplib2/__init__.py", line 1608, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "httplib2/__init__.py", line 1350, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "httplib2/__init__.py", line 1272, in _conn_request
    conn.connect()
  File "httplib2/__init__.py", line 1036, in connect
    self.disable_ssl_certificate_validation, self.ca_certs)
  File "httplib2/__init__.py", line 80, in _ssl_wrap_socket
[output truncated]

```

Original issue reported on code.google.com by `vic...@zagorski.ru` on 23 Nov 2015 at 7:43

**Comment by GoogleCodeExporter** [comment]
```
This traceback looks to indicate network issues. Are you on a network with 
limited connectivity?

We have work under way to improve the error message in such circumstances.
```

Original comment by `z...@google.com` on 24 Nov 2015 at 4:47
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
Yes, it seems that there were problems at my ISP. We resolved it, and I didn't 
have 
this issue again.

Thank you
```

Original comment by `vic...@zagorski.ru` on 24 Nov 2015 at 4:50

**Comment by GoogleCodeExporter** [comment]
```
Thanks for following up!
```

Original comment by `z...@google.com` on 24 Nov 2015 at 11:18
- Changed state: **Invalid**
