### ISSUE TITLE
login auth failed

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#40]
```
What steps will reproduce the problem?

I use command：gcloud auth login

What is the expected output? What do you see instead?
the output：
Go to the following link in your browser:

    https://accounts.google.com/o/oauth2/auth?redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&prompt=select_account&response_type=code&client_id=32555940559.apps.googleusercontent.com&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fappengine.admin+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fbigquery+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcompute+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.full_control+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fndev.cloudman+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatform+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fsqlservice.admin+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fprediction+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fprojecthosting&access_type=offline

Traceback (most recent call last):
  File "/home/c2485/google-cloud-sdk/bin/../lib/google/cloud/sdk/gcloud/gcloud.py", line 78, in <module>
    main()
  File "/home/c2485/google-cloud-sdk/bin/../lib/google/cloud/sdk/gcloud/gcloud.py", line 75, in main
    _loader.Execute()
  File "/home/c2485/google-cloud-sdk/bin/../lib/google/cloud/sdk/calliope/__init__.py", line 1270, in Execute
    cur._Execute(cli_mode=True, kwargs=kwargs)
  File "/home/c2485/google-cloud-sdk/bin/../lib/google/cloud/sdk/calliope/__init__.py", line 933, in _Execute
    cli_mode=cli_mode)
  File "/home/c2485/google-cloud-sdk/bin/../lib/google/cloud/sdk/calliope/__init__.py", line 665, in Run
    result = command_instance.Run(args)
  File "/home/c2485/google-cloud-sdk/bin/../lib/google/cloud/sdk/calliope/exceptions.py", line 84, in TryFunc
    return func(*args, **kwargs)
  File "/home/c2485/google-cloud-sdk/bin/../lib/google/cloud/sdk/gcloud/sdktools/auth/login.py", line 46, in Run
    launch_browser=args.launch_browser and not c_gce.IsOnGCE())
  File "/home/c2485/google-cloud-sdk/bin/../lib/google/cloud/sdk/core/credentials/__init__.py", line 290, in AcquireFromWebFlow
    cred = flow.Run(webflow, launch_browser=launch_browser)
  File "/home/c2485/google-cloud-sdk/bin/../lib/google/cloud/sdk/core/credentials/flow.py", line 152, in Run
    credential = flow.step2_exchange(code, http=http)
  File "/home/c2485/google-cloud-sdk/bin/../lib/oauth2client/util.py", line 132, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/c2485/google-cloud-sdk/bin/../lib/oauth2client/client.py", line 1283, in step2_exchange
    headers=headers)
  File "/home/c2485/google-cloud-sdk/bin/../lib/httplib2/__init__.py", line 1586, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/home/c2485/google-cloud-sdk/bin/../lib/httplib2/__init__.py", line 1333, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/home/c2485/google-cloud-sdk/bin/../lib/httplib2/__init__.py", line 1289, in _conn_request
    response = conn.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1018, in getresponse
    raise ResponseNotReady()
httplib.ResponseNotReady

What is the output of 'gcloud version'?

app-engine-python 1.9.5
app-engine-python-extras 1.9.4
bq 2.0.18
bq-win 2.0.17
compute 2014.05.22
core 2014.05.22
core-win 2014.05.20
dns 2014.04.30
gae-python 2014.05.06
gae-python-launcher-win 1.9.5
gcutil 1.15.0
gcutil-win 1.15.0
gsutil 3.42
gsutil-win 3.42
sql 2014.05.06

Please provide any additional information below.


```

Original issue reported on code.google.com by `joeyhe...@gmail.com` on 29 May 2014 at 8:08
- Merged into: #14

**Comment by GoogleCodeExporter** [comment]
```
That was not me & nobody else uses
My accounts.
```

Original comment by `JBo...@gmail.com` on 15 Jun 2014 at 10:56

**Comment by GoogleCodeExporter** [comment]
Original comment by `alockw...@google.com` on 12 Aug 2014 at 4:14
- Changed state: **Duplicate**
