### ISSUE TITLE
Issue running command [gcloud preview app deploy]

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#400]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?

Was following the NodeJS tutorial:
https://cloud.google.com/nodejs/getting-started/using-cloud-datastore


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "calliope/cli.py", line 609, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "calliope/backend.py", line 1228, in Run
    resources = command_instance.Run(args)
  File "surface/preview/app/deploy.py", line 216, in Run
    if (bs.get('use_endpoints_api_management') and
AttributeError: 'NoneType' object has no attribute 'get'

Installation information:

Google Cloud SDK [0.9.87]

Platform: [Linux, x86_64]
Python Version: [2.7.6 (default, Jun 22 2015, 17:58:13)  [GCC 4.8.2]]
Python Location: [/usr/bin/python2]
Site Packages: [Disabled]

Installation Root: [/usr/local/google/home/wesleywong/google-cloud-sdk]
Additional Repositories:
  https://storage.googleapis.com/endpoints-gcloud/components-2.json
Installed Components:
  core: [2015.11.18]
  core-nix: [2015.11.18]
  gcloud: [2015.11.18]
  gsutil-nix: [4.15]
  gsutil: [4.15]
  bq: [2.0.18]
  alpha: [2015.10.08]
  bq-nix: [2.0.18]
System PATH: 
[/usr/local/google/home/wesleywong/google-cloud-sdk/bin:/usr/local/google/home/w
esleywong/google-cloud-sdk/bin:/usr/local/google/home/wesleywong/google-cloud-sd
k/bin:/usr/lib/google-golang/bin:/usr/local/buildtools/java/jdk/bin:/usr/local/s
bin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/google/home/wesleywo
ng/local/appengine-java-sdk-1.9.28/bin]
Cloud SDK on PATH: [True]

[output truncated]

```

Original issue reported on code.google.com by `wesleyw...@google.com` on 23 Nov 2015 at 8:23

**Comment by GoogleCodeExporter** [comment]
```
It looks as though this is a corrupted Cloud SDK isntallation; the 
corresponding file in the latest version makes no reference to 
"use_endpoints_api_management":

    > /tmp/google-cloud-sdk/bin/gcloud version | head -n 1
    Google Cloud SDK 0.9.87
    > grep use_endpoints_api_management /tmp/google-cloud-sdk/lib/googlecloudsdk/surface/preview/app/deploy.py
    >

Can you run `gcloud components reinstall` or remove the directory 
`/usr/local/google/home/wesleywong/google-cloud-sdk` and install again? This 
will preserve any existing configuration.
```

Original comment by `z...@google.com` on 23 Nov 2015 at 8:40
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
Re-install didn't work, but removing the directly and installing a fresh copy 
worked. Thanks!
```

Original comment by `wesleyw...@google.com` on 23 Nov 2015 at 10:27

**Comment by GoogleCodeExporter** [comment]
```
Thanks! We have some other features coming along to detect corruption such as 
this as it happens. Glad you have a work-around for now.
```

Original comment by `z...@google.com` on 23 Nov 2015 at 10:29
- Changed state: **WontFix**
