### ISSUE TITLE
WINDOWS 10 Reinstall Issues

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#405]
```
Issue running command [gcloud compute ssh].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk\calliope\cli.py", line 609, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk\calliope\backend.py", line 1228, in Run
    resources = command_instance.Run(args)
  File "googlecloudsdk\surface\compute\ssh.py", line 113, in Run
    external_ip_address = self.GetInstanceExternalIpAddress(instance_ref)
  File "googlecloudsdk\api_lib\compute\ssh_utils.py", line 448, in GetInstanceExternalIpAddress
    custom_get_requests=None))
  File "googlecloudsdk\api_lib\compute\request_helper.py", line 134, in MakeRequests
    requests=requests, http=http, batch_url=batch_url)
  File "googlecloudsdk\api_lib\compute\batch_helper.py", line 30, in MakeRequests
    responses = batch.Execute(http)
  File "googlecloudsdk\third_party\apitools\base\py\batch.py", line 181, in Execute
    batch_http_request.Execute(http)
  File "googlecloudsdk\third_party\apitools\base\py\batch.py", line 423, in Execute
    self._Execute(http)
  File "googlecloudsdk\third_party\apitools\base\py\batch.py", line 386, in _Execute
    response = http_wrapper.MakeRequest(http, request)
  File "googlecloudsdk\third_party\apitools\base\py\http_wrapper.py", line 302, in MakeRequest
    check_response_func=check_response_func)
  File "googlecloudsdk\third_party\apitools\base\py\http_wrapper.py", line 349, in _MakeRequestNoRetry
    redirections=redirections, connection_type=connection_type)
[output truncated]

```

Original issue reported on code.google.com by `RuaanVan...@gmail.com` on 26 Nov 2015 at 9:22

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the report.
In the subject you mention that "reinstall" issues. Can you describe how you 
reinstalled google cloud sdk?

Are you able to run any command like [gcloud info] or [gcloud compute instances 
list]?

Can you include output of [gcloud info] ?

```

Original comment by `che...@google.com` on 26 Nov 2015 at 9:55
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 4 Jan 2016 at 2:08
- Changed state: **Invalid**
