### ISSUE TITLE
Tried to push local docker image to GCE and it crashe

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#409]
```
Issue running command [gcloud docker].

What steps will reproduce the problem?

gcloud docker push us.gcr.io/direct-disk-101619/egs-rc-4372

What is the expected output? What do you see instead?

Should be ok

instead I got:
ERROR: gcloud crashed (SSLEOFError): EOF occurred in violation of protocol 
(_ssl.c:590)

Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk/calliope/cli.py", line 609, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk/calliope/backend.py", line 1228, in Run
    resources = command_instance.Run(args)
  File "googlecloudsdk/surface/docker.py", line 99, in Run
    docker.UpdateDockerCredentials(server)
  File "googlecloudsdk/core/docker/docker.py", line 133, in UpdateDockerCredentials
    store.Refresh(cred)
  File "googlecloudsdk/core/credentials/store.py", line 267, in Refresh
    creds.refresh(http or _Http())
  File "oauth2client/client.py", line 597, in refresh
    self._refresh(http.request)
  File "oauth2client/client.py", line 780, in _refresh
    self._do_refresh_request(http_request)
  File "oauth2client/client.py", line 799, in _do_refresh_request
    self.token_uri, method='POST', body=body, headers=headers)
  File "httplib2/__init__.py", line 1608, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "httplib2/__init__.py", line 1350, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "httplib2/__init__.py", line 1272, in _conn_request
    conn.connect()
  File "httplib2/__init__.py", line 1036, in connect
    self.disable_ssl_certificate_validation, self.ca_certs)
  File "httplib2/__init__.py", line 80, in _ssl_wrap_socket
[output truncated]

```

Original issue reported on code.google.com by `oleg.kri...@xcision.com` on 2 Dec 2015 at 5:09

**Comment by GoogleCodeExporter** [comment]
```
Thanks for reporting!

Is this reproducible? The error that occurs indicates network problems.

Are you behind a firewall, or do you have any other unusual network settings?
```

Original comment by `z...@google.com` on 2 Dec 2015 at 1:32
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
No, it is not reproducible

happens once, I repeated command again and everything went ok.

> Are you behind a firewall, or do you have any other unusual network settings?

no, nothing unusual in my network setup - Comcast, modem, router, DHCP
```

Original comment by `oleg.kri...@xcision.com` on 2 Dec 2015 at 9:46

**Comment by GoogleCodeExporter** [comment]
```
I'm going to close this out then. It looks as though it was caused by a network 
hiccup.

We're already tracking work to make the error messaging cleaner here.

I appreciate the follow-up.
```

Original comment by `z...@google.com` on 2 Dec 2015 at 9:48
- Changed state: **WontFix**
