### ISSUE TITLE
gcloud preview app deploy not working with node.js application

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#418]
```
Issue running command [gcloud preview app deploy].
gcloud preview app deploy app.yaml --project=instant-kegs-dashboard --promote 
--verbosity debug

What steps will reproduce the problem?
command above


What is the expected output? What do you see instead?
deployment. errors.


Please provide any additional information below.


Traceback (most recent call last):
  File "calliope/cli.py", line 609, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "calliope/backend.py", line 1228, in Run
    resources = command_instance.Run(args)
  File "surface/preview/app/deploy.py", line 256, in Run
    remote_build)
  File "api_lib/app/deploy_command_util.py", line 177, in BuildAndPushDockerImages
    info.file, docker_client, image_name)
  File "api_lib/app/deploy_command_util.py", line 249, in BuildAndPushDockerImage
    image.Push(docker_client)
  File "api_lib/app/docker_image.py", line 159, in Push
    _Retry(InnerPush)
  File "api_lib/app/docker_image.py", line 185, in _Retry
    raise e
APIError: 500 Server Error: Internal Server Error ("push 
appengine.gcr.io/gcloud/instant-kegs-dashboard.default.20151208t112534 is 
already in progress")

Installation information:

Google Cloud SDK [0.9.89]

Platform: [Mac OS X, x86_64]
Python Version: [2.7.10 (default, Aug 22 2015, 20:33:39)  [GCC 4.2.1 Compatible 
Apple LLVM 7.0.0 (clang-700.0.59.1)]]
Python Location: [/usr/bin/python]
Site Packages: [Disabled]

Installation Root: [/Users/tmaloney/Applications/google-cloud-sdk]
Installed Components:
  core: [2015.11.30]
  app-engine-python: [1.9.28]
  core-nix: [2015.11.24]
  app-engine-php: [ ]
  app-engine-java: [1.9.28]
  gcloud: []
  gsutil-nix: [4.15]
  app-engine-python-extras: [1.9.21]
  gsutil: [4.16]
  bq: [2.0.18]
[output truncated]

```

Original issue reported on code.google.com by `tmalo...@gmail.com` on 8 Dec 2015 at 5:38
- Merged into: #416

**Comment by GoogleCodeExporter** [comment]
```
This looks like a transient error, caused by two deployment attempts very close 
together. Can you reproduce this if you try it again?
```

Original comment by `z...@google.com` on 8 Dec 2015 at 5:40
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
I get the same issue trying 20 minutes later:


Traceback (most recent call last):
  File "calliope/cli.py", line 609, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "calliope/backend.py", line 1228, in Run
    resources = command_instance.Run(args)
  File "surface/preview/app/deploy.py", line 256, in Run
    remote_build)
  File "api_lib/app/deploy_command_util.py", line 177, in BuildAndPushDockerImages
    info.file, docker_client, image_name)
  File "api_lib/app/deploy_command_util.py", line 249, in BuildAndPushDockerImage
    image.Push(docker_client)
  File "api_lib/app/docker_image.py", line 159, in Push
    _Retry(InnerPush)
  File "api_lib/app/docker_image.py", line 185, in _Retry
    raise e
APIError: 500 Server Error: Internal Server Error ("push 
appengine.gcr.io/gcloud/instant-kegs-dashboard.default.20151208t114154 is 
already in progress")

Installation information:

Google Cloud SDK [0.9.89]

Platform: [Mac OS X, x86_64]
Python Version: [2.7.10 (default, Aug 22 2015, 20:33:39)  [GCC 4.2.1 Compatible 
Apple LLVM 7.0.0 (clang-700.0.59.1)]]
Python Location: [/usr/bin/python]
Site Packages: [Disabled]

Installation Root: [/Users/tmaloney/Applications/google-cloud-sdk]
Installed Components:
  core: [2015.11.30]
  app-engine-python: [1.9.28]
  core-nix: [2015.11.24]
  app-engine-php: [ ]
  app-engine-java: [1.9.28]
  gcloud: []
  gsutil-nix: [4.15]
  app-engine-python-extras: [1.9.21]
  gsutil: [4.16]
  bq: [2.0.18]
[output truncated]

```

Original comment by `tmalo...@gmail.com` on 8 Dec 2015 at 5:52

**Comment by GoogleCodeExporter** [comment]
Original comment by `vil...@google.com` on 8 Dec 2015 at 6:37
- Changed state: **Duplicate**
