### ISSUE TITLE
gcloud init stack trace for clone repo 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#421]
```
Issue running command [gcloud init].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "calliope\cli.py", line 609, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "calliope\backend.py", line 1228, in Run
    resources = command_instance.Run(args)
  File "surface\init.py", line 94, in Run
    self._PickRepo()
  File "surface\init.py", line 326, in _PickRepo
    self._CloneRepo(repo_name)
  File "surface\init.py", line 351, in _CloneRepo
    self._RunCmd(['source', 'repos', 'clone'], [repo_name, clone_path])
  File "surface\init.py", line 401, in _RunCmd
    raise c_exc.FailedSubCommand(cmd + params, exc.code)
FailedSubCommand: Failed command: [source repos clone default C:\Program Files 
(x86)\Google\Cloud SDK\default] with exit code [1]

Installation information:

Google Cloud SDK [0.9.89]

Platform: [Windows, x86_64]
Python Version: [2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit 
(AMD64)]]
Python Location: [C:\python27_x64\python.exe]
Site Packages: [Disabled]

Installation Root: [C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk]
Installed Components:
  core: [2015.11.30]
  bq-win: [2.0.18]
  core-win: [2015.11.24]
  gcloud: []
  windows-ssh-tools: [2015.09.21]
  gsutil: [4.16]
  gsutil-win: [4.15]
  bq: [2.0.18]
[output truncated]

```

Original issue reported on code.google.com by `alejandr...@fandeal.com.mx` on 9 Dec 2015 at 5:23

**Comment by GoogleCodeExporter** [comment]
```
Thanks for reporting the issue.

How did you invoke gcloud init. Was it part of installation process?

Note that you can ignore this error, unless you care about using your cloud 
project git repo.

Does [gcloud source repos clone default] work for you?


```

Original comment by `che...@google.com` on 9 Dec 2015 at 1:02
- Changed title: *_gcloud init stack trace for clone repo *_
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
Closing, as there is not enough information to properly diagnose this issue.

Please reopen if you can provide the logs.
```

Original comment by `z...@google.com` on 9 Feb 2016 at 2:07
