### ISSUE TITLE
Problems to initialize a Google Cloud Project [new project] using gcloud init

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#423]
```
Issue running command [gcloud init].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "calliope/cli.py", line 609, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "calliope/backend.py", line 1228, in Run
    resources = command_instance.Run(args)
  File "surface/init.py", line 94, in Run
    self._PickRepo()
  File "surface/init.py", line 326, in _PickRepo
    self._CloneRepo(repo_name)
  File "surface/init.py", line 346, in _CloneRepo
    files.MakeDir(parent_dir)
  File "core/util/files.py", line 47, in MakeDir
    os.makedirs(path, mode=mode)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 2] No such file or directory: ''

Installation information:

Google Cloud SDK [90.0.0]

Platform: [Mac OS X, x86_64]
Python Version: [2.7.10 (default, Oct 23 2015, 18:05:06)  [GCC 4.2.1 Compatible 
Apple LLVM 7.0.0 (clang-700.0.59.5)]]
Python Location: [/usr/bin/python]
Site Packages: [Disabled]

Installation Root: [/Users/odan/google-cloud-sdk]
Installed Components:
  core: [2015.12.07]
  core-nix: [2015.11.24]
  gcloud: []
  gsutil-nix: [4.15]
  gsutil: [4.16]
  bq: [2.0.18]
  bq-nix: [2.0.18]
System PATH: 
[/Library/Frameworks/Python.framework/Versions/3.5/bin:/Library/Frameworks/Pytho
n.framework/Versions/3.5/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin]
Cloud SDK on PATH: [False]

[output truncated]

```

Original issue reported on code.google.com by `diogo.hi...@gmail.com` on 13 Dec 2015 at 1:16

**Comment by GoogleCodeExporter** [comment]
```
Trunced info:


============== TRUNCATED INFORMATION (PLEASE CONSIDER INCLUDING) ===============
Installation Properties: [/Users/odan/google-cloud-sdk/properties]
User Config Directory: [/Users/odan/.config/gcloud]
User Properties: [/Users/odan/.config/gcloud/properties]
Current Workspace: [None]
Workspace Config Directory: [None]
Workspace Properties: [None]

Account: [diogo.hideo@gmail.com]
Project: [projectcureable]

Current Properties:
  [core]
    project: [projectcureable]
    account: [diogo.hideo@gmail.com]
    disable_usage_reporting: [False]

Logs Directory: [/Users/odan/.config/gcloud/logs]
Last Log File: [/Users/odan/.config/gcloud/logs/2015.12.13/11.14.33.197049.log]
============ END TRUNCATED INFORMATION (PLEASE CONSIDER INCLUDING) =============
WARNING: The output of gcloud info is too long to pre-populate the new issue 
form.
WARNING: Please consider including the remainder (above).
Opening your browser to a new Google Cloud SDK issue.
```

Original comment by `diogo.hi...@gmail.com` on 13 Dec 2015 at 1:19

**Comment by GoogleCodeExporter** [comment]
```
Thanks for reporting the issue.

It looks like you chose to clone associated project repo. When you were asked 
to enter a directory to clone it to, did you enter anything or did you choose 
default?
```

Original comment by `che...@google.com` on 14 Dec 2015 at 1:17
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
Issue 447 has been merged into this issue.
```

Original comment by `z...@google.com` on 4 Jan 2016 at 12:58

**Comment by GoogleCodeExporter** [comment]
```
Issue 454 has been merged into this issue.
```

Original comment by `z...@google.com` on 4 Jan 2016 at 12:58

**Comment by GoogleCodeExporter** [comment]
```
We should have a fix for this available in the next gcloud release (version 
92.0.0).
```

Original comment by `z...@google.com` on 4 Jan 2016 at 1:01
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
Issue 426 has been merged into this issue.
```

Original comment by `z...@google.com` on 4 Jan 2016 at 2:03

**Comment by GoogleCodeExporter** [comment]
```
Issue 465 has been merged into this issue.
```

Original comment by `z...@google.com` on 12 Jan 2016 at 10:49

**Comment by GoogleCodeExporter** [comment]
```
The 92.0.0 release is available. Please re-open if you're still experiencing 
this issue.
```

Original comment by `z...@google.com` on 18 Feb 2016 at 8:17
- Changed state: **Fixed**
