### ISSUE TITLE
transer our Project ID rotlein-1149 to europe-east1-b

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#425]
```
Issue running command [gcloud init].

What steps will reproduce the problem?

$ gcloud compute instances move ritsrv \
    --zone asia-east1-a --destination-zone europe-east1-b


What is the expected output? What do you see instead?
new zone  europe-east1-b

Please provide any additional information below.
transer our Project ID rotlein-1149 to europe-east1-b

Traceback (most recent call last):
  File "calliope\cli.py", line 609, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "calliope\backend.py", line 1228, in Run
    resources = command_instance.Run(args)
  File "surface\init.py", line 94, in Run
    self._PickRepo()
  File "surface\init.py", line 326, in _PickRepo
    self._CloneRepo(repo_name)
  File "surface\init.py", line 346, in _CloneRepo
    files.MakeDir(parent_dir)
  File "core\util\files.py", line 47, in MakeDir
    os.makedirs(path, mode=mode)
  File "C:\python27_x64\lib\os.py", line 157, in makedirs
    mkdir(name, mode)
WindowsError: [Error 3] : ''

Installation information:

Google Cloud SDK [90.0.0]

Platform: [Windows, x86_64]
Python Version: [2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit 
(AMD64)]]
Python Location: [C:\python27_x64\python.exe]
Site Packages: [Disabled]

Installation Root: [C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk]
Installed Components:
  core: [2015.12.07]
  bq-win: [2.0.18]
  core-win: [2015.11.24]
  gcloud: []
  windows-ssh-tools: [2015.09.21]
  gsutil: [4.16]
  gsutil-win: [4.15]
  bq: [2.0.18]
[output truncated]

```

Original issue reported on code.google.com by `Vit...@rotlein.co.il` on 14 Dec 2015 at 1:31
- Merged into: #426

**Comment by GoogleCodeExporter** [comment]
```
It looks like you may have attached a log file for a different gcloud command. 
Try the failed command again, and then this command will print the last log 
file path:

gcloud info --format="value(logs.last_log)"

Running and gcloud command, including gcloud info, writes a new log file. So be 
sure tp save the log file path immediately after the command that fails.
```

Original comment by `gsfow...@google.com` on 16 Dec 2015 at 8:35
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
Original comment by `che...@google.com` on 17 Dec 2015 at 12:52
- Changed state: **Duplicate**
