### ISSUE TITLE
error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#426]
```
Issue running command [gcloud init].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "calliope\cli.py", line 609, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "calliope\backend.py", line 1228, in Run
    resources = command_instance.Run(args)
  File "surface\init.py", line 94, in Run
    self._PickRepo()
  File "surface\init.py", line 326, in _PickRepo
    self._CloneRepo(repo_name)
  File "surface\init.py", line 346, in _CloneRepo
    files.MakeDir(parent_dir)
  File "core\util\files.py", line 47, in MakeDir
    os.makedirs(path, mode=mode)
  File "C:\python27_x64\lib\os.py", line 157, in makedirs
    mkdir(name, mode)
WindowsError: [Error 3] : ''

Installation information:

Google Cloud SDK [90.0.0]

Platform: [Windows, x86_64]
Python Version: [2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit 
(AMD64)]]
Python Location: [C:\python27_x64\python.exe]
Site Packages: [Disabled]

Installation Root: [C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk]
Installed Components:
  core: [2015.12.07]
  bq-win: [2.0.18]
  core-win: [2015.11.24]
  gcloud: []
  windows-ssh-tools: [2015.09.21]
  beta: [2015.10.08]
  gsutil: [4.16]
  bq: [2.0.18]
  gsutil-win: [4.15]
[output truncated]

```

Original issue reported on code.google.com by `bluehosu...@gmail.com` on 15 Dec 2015 at 12:59
- Merged into: #423

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the report. That is definitely not a useful error message.

Were your prompted for a directory path to clone to? If so, did you have 
permission to create files in that directory?
```

Original comment by `gsfow...@google.com` on 16 Dec 2015 at 8:49
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
It appears the issue happens when:

Where would you like to clone [default] repository to 
[/home/sampleuser/default]:myrepo
No such directory []
Would you like to create it (Y/n)?  y

Here absolute path was expected for the destination, but only a name was given.

We will add extra validation here.
```

Original comment by `che...@google.com` on 17 Dec 2015 at 12:52
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
Issue 425 has been merged into this issue.
```

Original comment by `che...@google.com` on 17 Dec 2015 at 12:52

**Comment by GoogleCodeExporter** [comment]
```
Issue 451 has been merged into this issue.
```

Original comment by `che...@google.com` on 30 Dec 2015 at 1:49

**Comment by GoogleCodeExporter** [comment]
```
Next planned release (around Jan 13) will have a fix to support relative paths.
```

Original comment by `che...@google.com` on 30 Dec 2015 at 1:51

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 4 Jan 2016 at 2:03
- Changed state: **Duplicate**
