### ISSUE TITLE
gcloud crashed (SSLHandshakeError): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#427]
```
Issue running command [gcloud auth login].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "lib\googlecloudsdk\calliope\cli.py", line 609, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "lib\googlecloudsdk\calliope\backend.py", line 1228, in Run
    resources = command_instance.Run(args)
  File "lib\googlecloudsdk\calliope\exceptions.py", line 98, in TryFunc
    return func(*args, **kwargs)
  File "lib\googlecloudsdk\surface\auth\login.py", line 114, in Run
    creds = self.DoWebFlow(args.launch_browser)
  File "lib\googlecloudsdk\surface\auth\login.py", line 179, in DoWebFlow
    return c_store.AcquireFromWebFlow(launch_browser=launch_browser)
  File "lib\googlecloudsdk\core\credentials\store.py", line 383, in AcquireFromWebFlow
    http=_Http())
  File "lib\googlecloudsdk\core\credentials\flow.py", line 158, in Run
    credential = flow.step2_exchange(code, http=http)
  File "bin\..\./lib\third_party\oauth2client\util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "bin\..\./lib\third_party\oauth2client\client.py", line 1993, in step2_exchange
    headers=headers)
  File "bin\..\./lib\third_party\httplib2\__init__.py", line 1608, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "bin\..\./lib\third_party\httplib2\__init__.py", line 1350, in _request
[output truncated]

```

Original issue reported on code.google.com by `rakesh.s...@dagrofa.dk` on 16 Dec 2015 at 3:37

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the report.

Can you post the full stack trace from the log file for the failed command? 
This command prints the log file directory:

gcloud info --format="value(logs.logs_dir)"

or you can run the failed command again and post the file named by this command:

gcloud info --format="value(logs.last_log)"
```

Original comment by `gsfow...@google.com` on 16 Dec 2015 at 8:54
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
Attached the latest log file directory "2015.12.17.zip" & last log file 
"09.54.55.001000" for your reference.
```

Original comment by `rakesh.s...@dagrofa.dk` on 17 Dec 2015 at 4:32

Attachments:
- [2015.12.17.zip](https://storage.googleapis.com/google-code-attachments/google-cloud-sdk/issue-427/comment-2/2015.12.17.zip)
- [09.54.55.001000.log](https://storage.googleapis.com/google-code-attachments/google-cloud-sdk/issue-427/comment-2/09.54.55.001000.log)
