### ISSUE TITLE
gcloud error during gcloud init on windows 10

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#429]
```
Issue running command [gcloud init].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "calliope\cli.py", line 609, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "calliope\backend.py", line 1228, in Run
    resources = command_instance.Run(args)
  File "surface\init.py", line 94, in Run
    self._PickRepo()
  File "surface\init.py", line 326, in _PickRepo
    self._CloneRepo(repo_name)
  File "surface\init.py", line 351, in _CloneRepo
    self._RunCmd(['source', 'repos', 'clone'], [repo_name, clone_path])
  File "surface\init.py", line 401, in _RunCmd
    raise c_exc.FailedSubCommand(cmd + params, exc.code)
FailedSubCommand: Failed command: [source repos clone default 
C:\Users\patrick\AppData\Local\Google\Cloud SDK\default] with exit code [1]

Installation information:

Google Cloud SDK [91.0.1]

Platform: [Windows, x86_64]
Python Version: [2.7.6 (default, Nov 10 2013, 19:24:24) [MSC v.1500 64 bit 
(AMD64)]]
Python Location: [C:\python27_x64\python.exe]
Site Packages: [Disabled]

Installation Root: [C:\Users\patrick\AppData\Local\Google\Cloud 
SDK\google-cloud-sdk]
Installed Components:
  core: [2015.12.16]
  bq-win: [2.0.18]
  core-win: [2015.11.24]
  gcloud: []
  windows-ssh-tools: [2015.09.21]
  beta: [2015.10.08]
  gsutil: [4.16]
  bq: [2.0.18]
  gsutil-win: [4.15]
[output truncated]

```

Original issue reported on code.google.com by `big....@gmail.com` on 17 Dec 2015 at 7:39

**Comment by GoogleCodeExporter** [comment]
```
This wasn't actually the error I was trying to report.  The error I got before 
this was:

[beta projects list] has failed
Unexpected failure while executing [beta projects list]: [<class 
'googlecloudsdk.calliope.exceptions.FailedSubCommand'>: Failed command: [beta 
projects list] with exit code [1]]
Please report by running `gcloud feedback`.

All I did was run the latest cloud SDK installer and told it to run gcloud init 
on completion.
```

Original comment by `big....@gmail.com` on 17 Dec 2015 at 7:42

**Comment by GoogleCodeExporter** [comment]
```
Thanks for reporting the issue.

Do you have beta commands installed. Can you run [gcloud beta projects list] by 
itself?

Anyway you can copy paste the screen session you had with [gcloud init] ?
```

Original comment by `che...@google.com` on 17 Dec 2015 at 7:45
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
I did select to install the beta commands in the installer.

This is what I try the suggested command I see the following error:
C:\Users\patrick\AppData\Local\Google\Cloud SDK>gcloud beta projects list
--verbosity debug
INFO: Refreshing access_token
INFO: Failed to retrieve access token: {
  "error" : "internal_failure"
}
DEBUG: (gcloud.beta.projects.list) internal_failure
Traceback (most recent call last):
  File "C:\Users\patrick\AppData\Local\Google\Cloud
SDK\google-cloud-sdk\lib\googlecloudsdk\calliope\cli.py", line 609, in
Execute
    result = args.cmd_func(cli=self, args=args)
  File "C:\Users\patrick\AppData\Local\Google\Cloud
SDK\google-cloud-sdk\lib\googlecloudsdk\calliope\backend.py", line 1218, in
Run
    last_group = context_filter(tool_context, Http, args)
  File "C:\Users\patrick\AppData\Local\Google\Cloud
SDK\google-cloud-sdk\lib\googlecloudsdk\calliope\backend.py", line 580, in
ContextFilter
    group.Filter(context, args)
  File "C:\Users\patrick\AppData\Local\Google\Cloud
SDK\google-cloud-sdk\lib\googlecloudsdk\surface\projects\__init__.py", line
25, in Filter
    http=self.Http())
  File "C:\Users\patrick\AppData\Local\Google\Cloud
SDK\google-cloud-sdk\lib\googlecloudsdk\calliope\base.py", line 283, in Http
    return self._http_func(auth=auth, creds=creds, **kwargs)
  File "C:\Users\patrick\AppData\Local\Google\Cloud
SDK\google-cloud-sdk\lib\googlecloudsdk\calliope\backend.py", line 1213, in
Http
    **kwargs)
  File "C:\Users\patrick\AppData\Local\Google\Cloud
SDK\google-cloud-sdk\lib\googlecloudsdk\core\cli.py", line 127, in Http
    creds = c_store.Load()
  File "C:\Users\patrick\AppData\Local\Google\Cloud
SDK\google-cloud-sdk\lib\googlecloudsdk\core\credentials\store.py", line
249, in Load
    Refresh(cred)
  File "C:\Users\patrick\AppData\Local\Google\Cloud
SDK\google-cloud-sdk\lib\googlecloudsdk\core\credentials\store.py", line
269, in Refresh
    raise RefreshError(e)
RefreshError: internal_failure
ERROR: (gcloud.beta.projects.list) internal_failure

C:\Users\patrick\AppData\Local\Google\Cloud SDK>
```

Original comment by `big....@gmail.com` on 17 Dec 2015 at 7:50

**Comment by GoogleCodeExporter** [comment]
```
Thanks! This is helpful.

Have you already logged in? You can do that via [gcloud auth login].

Do other commands work for you like [gcloud compute instances list]?

```

Original comment by `che...@google.com` on 17 Dec 2015 at 8:02

**Comment by GoogleCodeExporter** [comment]
```
I had a user from a previous old cloud SDK install that I had just removed,
that was detected during gcloud init and which I selected as the active
user.

If I run gcloud auth login things start working again.
```

Original comment by `big....@gmail.com` on 17 Dec 2015 at 8:05
