### ISSUE TITLE
crushed deployment

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#433]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "lib\googlecloudsdk\calliope\cli.py", line 609, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "lib\googlecloudsdk\calliope\backend.py", line 1228, in Run
    resources = command_instance.Run(args)
  File "lib\googlecloudsdk\surface\preview\app\deploy.py", line 256, in Run
    remote_build)
  File "lib\googlecloudsdk\api_lib\app\deploy_command_util.py", line 177, in BuildAndPushDockerImages
    info.file, docker_client, image_name)
  File "lib\googlecloudsdk\api_lib\app\deploy_command_util.py", line 248, in BuildAndPushDockerImage
    image.Build(docker_client)
  File "lib\googlecloudsdk\api_lib\app\docker_image.py", line 98, in Build
    nocache=self._nocache, rm=self._rm, pull=False)
  File "bin\..\./lib\third_party\docker\docker\api\build.py", line 49, in build
    context = utils.tar(path, exclude=exclude, dockerfile=dockerfile)
  File "bin\..\./lib\third_party\docker\docker\utils\utils.py", line 86, in tar
    t.add(os.path.join(root, path), arcname=path, recursive=False)
  File "C:\python27_x64\lib\tarfile.py", line 2000, in add
    tarinfo = self.gettarinfo(name, arcname)
  File "C:\python27_x64\lib\tarfile.py", line 1872, in gettarinfo
    statres = os.lstat(name)
[output truncated]

```

Original issue reported on code.google.com by `bex...@gmail.com` on 19 Dec 2015 at 8:32

**Comment by GoogleCodeExporter** [comment]
```
Hi there - I'm sorry that you're running into this issue.

Any chance you could provide the output of 'gcloud info'?

```

Original comment by `rdayal@google.com` on 19 Dec 2015 at 9:42

**Comment by GoogleCodeExporter** [comment]
Original comment by `rdayal@google.com` on 19 Dec 2015 at 9:42
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
Also, could you provide the full stack trace? It should be printed to your 
screen when you run `gcloud feedback` (there's a character limit in Google 
code, so we can't automatically populate the whole thing).
```

Original comment by `z...@google.com` on 20 Dec 2015 at 4:16

**Comment by GoogleCodeExporter** [comment]
```
Please reopen when you provide the full stack trace.
```

Original comment by `z...@google.com` on 9 Feb 2016 at 2:06
- Changed state: **Invalid**
