### ISSUE TITLE
Get SSLHandshakeError when running either "gcloud init" or "gcloud auth login"

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#435]
```
Issue running command [gcloud init].

What steps will reproduce the problem?

Everytime I run gcloud init or gcloud auth login I get ERROR: gcloud crashed 
(SSLHandshakeError): [Errno 1] _ssl.c:480: error:14090086:SSL 
routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed 

What is the expected output? What do you see instead?

I don't know what the expected output is, as gcloud init and gcloud auth login 
have not successfully ran. 

Please provide any additional information below.

I am new to google cloud and app development in general so I am sorry if I am 
not providing the necessary information to help solve this problem. 

Traceback (most recent call last):
  File "googlecloudsdk/calliope/cli.py", line 609, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk/calliope/backend.py", line 1228, in Run
    resources = command_instance.Run(args)
  File "googlecloudsdk/surface/init.py", line 86, in Run
    if not self._PickAccount(args.console_only):
  File "googlecloudsdk/surface/init.py", line 138, in _PickAccount
    disable_user_output=False):
  File "googlecloudsdk/surface/init.py", line 391, in _RunCmd
    result = self.cli.Execute(args)
  File "googlecloudsdk/calliope/cli.py", line 609, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk/calliope/backend.py", line 1228, in Run
    resources = command_instance.Run(args)
  File "googlecloudsdk/calliope/exceptions.py", line 98, in TryFunc
    return func(*args, **kwargs)
  File "googlecloudsdk/surface/auth/login.py", line 114, in Run
    creds = self.DoWebFlow(args.launch_browser)
  File "googlecloudsdk/surface/auth/login.py", line 179, in DoWebFlow
    return c_store.AcquireFromWebFlow(launch_browser=launch_browser)
  File "googlecloudsdk/core/credentials/store.py", line 383, in AcquireFromWebFlow
    http=_Http())
  File "googlecloudsdk/core/credentials/flow.py", line 158, in Run
    credential = flow.step2_exchange(code, http=http)
  File "third_party/oauth2client/util.py", line 137, in positional_wrapper
[output truncated]

```

Original issue reported on code.google.com by `alekBini...@gmail.com` on 19 Dec 2015 at 9:29

**Comment by GoogleCodeExporter** [comment]
```
Hi there. Sorry you're running into this. Could you provide me with the output 
of 'gcloud info'?
```

Original comment by `rdayal@google.com` on 19 Dec 2015 at 9:46
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
alex , upgrade your python to 2.7.11 fix the problem
```

Original comment by `second.c...@gmail.com` on 28 Jan 2016 at 12:52

**Comment by GoogleCodeExporter** [comment]
```
Please reopen with more information if you're still experiencing this.
```

Original comment by `z...@google.com` on 18 Feb 2016 at 7:19
- Changed state: **Invalid**
