### ISSUE TITLE
i faced this problem when deploying to cloud

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#441]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\cli.py", line 591, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\calliope\backend.py", line 1191, in Run
    resources = command_instance.Run(args)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\appengine\app_commands\deploy.py", line 208, in Run
    implicit_remote_build)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\appengine\lib\deploy_command_util.py", line 137, in BuildAndPushDockerImages
    with docker_util.DockerHost(cli, version_id, remote) as docker_client:
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\appengine\lib\images\docker_util.py", line 208, in __enter__
    self._vm = Provision(self._cli, self._name, self._zone)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\appengine\lib\images\docker_util.py", line 51, in Provision
    vm = _CreateVm(cli, name, zone)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\..\./lib\googlecloudsdk\appengine\lib\images\docker_util.py", line 106, in _CreateVm
    return _Vm(cli, vm_info[0])
[output truncated]

```

Original issue reported on code.google.com by `m.rajase...@virtualgodown.com` on 21 Dec 2015 at 5:41

**Comment by GoogleCodeExporter** [comment]
```
We need a full stack trace and gcloud info to debug this issue.
```

Original comment by `stephe...@google.com` on 21 Dec 2015 at 7:38
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 9 Feb 2016 at 2:04
- Changed state: **Invalid**
