### ISSUE TITLE
Crash while deploying to Managed VMs.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#444]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "calliope/cli.py", line 609, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "calliope/backend.py", line 1228, in Run
    resources = command_instance.Run(args)
  File "surface/preview/app/deploy.py", line 365, in Run
    app_config.NonHermeticModules().items(), code_bucket, source_contexts)
  File "api_lib/app/deploy_app_command_util.py", line 43, in CopyFilesToCodeBucket
    source_contexts)
  File "api_lib/app/deploy_app_command_util.py", line 170, in _BuildStagingDirectory
    staging_dir, source_contexts, overwrite=True, source_dir=source_dir)
  File "api_lib/source/context_util.py", line 257, in CreateContextFiles
    log.warn('Could not generate [{0}]: {1}', context_filename, e)
UnboundLocalError: local variable 'context_filename' referenced before 
assignment

Installation information:

Google Cloud SDK [91.0.0]

Platform: [Linux, x86_64]
Python Version: [2.7.6 (default, Jun 22 2015, 17:58:13)  [GCC 4.8.2]]
Python Location: [/usr/bin/python2]
Site Packages: [Disabled]

Installation Root: [/usr/local/google/home/swast/google-cloud-sdk]
Installed Components:
  core: [2015.12.10]
  app-engine-python: [1.9.30]
  core-nix: [2015.11.24]
  kubectl: []
  app-engine-java: [1.9.30]
  gcloud: []
  gsutil-nix: [4.15]
  gsutil: [4.16]
  bq: [2.0.18]
  alpha: [2015.10.08]
  kubectl-linux-x86_64: [1.1.3]
[output truncated]

```

Original issue reported on code.google.com by `sw...@google.com` on 23 Dec 2015 at 12:15

**Comment by GoogleCodeExporter** [comment]
```
Issue 445 has been merged into this issue.
```

Original comment by `z...@google.com` on 26 Dec 2015 at 4:34
