### ISSUE TITLE
"Gcloud init" false to setup a default directory

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#447]
```
Issue running command [gcloud init].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "calliope/cli.py", line 609, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "calliope/backend.py", line 1228, in Run
    resources = command_instance.Run(args)
  File "surface/init.py", line 94, in Run
    self._PickRepo()
  File "surface/init.py", line 326, in _PickRepo
    self._CloneRepo(repo_name)
  File "surface/init.py", line 346, in _CloneRepo
    files.MakeDir(parent_dir)
  File "core/util/files.py", line 47, in MakeDir
    os.makedirs(path, mode=mode)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 2] No such file or directory: ''

Installation information:

Google Cloud SDK [91.0.1]

Platform: [Linux, x86]
Python Version: [2.7.6 (default, Jun 22 2015, 18:00:18)  [GCC 4.8.2]]
Python Location: [/usr/bin/python2]
Site Packages: [Disabled]

Installation Root: [/home/liem/google-cloud-sdk]
Installed Components:
  core: [2015.12.16]
  core-nix: [2015.11.24]
  gcloud: []
  gsutil-nix: [4.15]
  gsutil: [4.16]
  bq: [2.0.18]
  bq-nix: [2.0.18]
System PATH: 
[/home/liem/google-cloud-sdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/b
in:/sbin:/bin:/usr/games:/usr/local/games]
Cloud SDK on PATH: [True]

Installation Properties: [/home/liem/google-cloud-sdk/properties]
User Config Directory: [/home/liem/.config/gcloud]
[output truncated]

```

Original issue reported on code.google.com by `thanhlie...@gmail.com` on 25 Dec 2015 at 2:23
- Merged into: #423

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the report, we'll take a look!
```

Original comment by `svalen...@google.com` on 26 Dec 2015 at 1:02

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 4 Jan 2016 at 12:58
- Changed state: **Duplicate**
