### ISSUE TITLE
gcloud login crash

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#448]
```
Issue running command [gcloud auth login].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "calliope\cli.py", line 609, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "calliope\backend.py", line 1228, in Run
    resources = command_instance.Run(args)
  File "calliope\exceptions.py", line 98, in TryFunc
    return func(*args, **kwargs)
  File "surface\auth\login.py", line 126, in Run
    c_store.Store(creds, account)
  File "core\credentials\store.py", line 297, in Store
    _GetLegacyGen(account, creds).WriteTemplate()
  File "core\credentials\store.py", line 302, in _GetLegacyGen
    multistore_path=config.Paths().LegacyCredentialsMultistorePath(account),
  File "core\config.py", line 615, in LegacyCredentialsMultistorePath
    return os.path.join(self.LegacyCredentialsDir(account), 'multistore.json')
  File "core\config.py", line 604, in LegacyCredentialsDir
    return os.path.join(self.global_config_dir, 'legacy_credentials', account)
  File "C:\python27\lib\ntpath.py", line 85, in join
    result_path = result_path + p_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 8: ordinal 
not in range(128)

Installation information:

Google Cloud SDK [91.0.1]

Platform: [Windows, x86_64]
Python Version: [2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC 
v.1500 32 bit (Intel)]]
Python Location: [C:\python27\python.exe]
Site Packages: [Disabled]

[output truncated]

```

Original issue reported on code.google.com by `cesgu...@gmail.com` on 26 Dec 2015 at 8:27
- Merged into: #145

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 4 Jan 2016 at 5:03
- Changed state: **Duplicate**
