### ISSUE TITLE
Google Cloud Deployment Error Response: [13] Could not pick a region and/or zone

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#452]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "calliope/cli.py", line 609, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "calliope/backend.py", line 1228, in Run
    resources = command_instance.Run(args)
  File "surface/preview/app/deploy.py", line 285, in Run
    images.get(module))
  File "api_lib/app/appengine_api_client.py", line 76, in DeployModule
    return operations.WaitForOperation(self.client.apps_operations, operation)
  File "api_lib/app/api/operations.py", line 54, in WaitForOperation
    encoding.MessageToPyValue(completed_operation.error)))
OperationError: Error Response: [13] Could not pick a region and/or zone. 
Version: 20151230t172615.389637987281283257

Installation information:

Google Cloud SDK [91.0.1]

Platform: [Mac OS X, x86_64]
Python Version: [2.7.10 (default, Oct 23 2015, 18:05:06)  [GCC 4.2.1 Compatible 
Apple LLVM 7.0.0 (clang-700.0.59.5)]]
Python Location: 
[/Users/lindauson/Development/python/fourth-gen-recycling/getting-started-python
/6-pubsub/env/bin/python2]
Site Packages: [Enabled]

Installation Root: 
[/Users/lindauson/Development/python/fourth-gen-recycling/getting-started-python
/6-pubsub/Y/google-cloud-sdk]
Installed Components:
  core: [2015.12.16]
  core-nix: [2015.11.24]
  gcloud: []
  gsutil-nix: [4.15]
  gsutil: [4.16]
  bq: [2.0.18]
  bq-nix: [2.0.18]
[output truncated]

```

Original issue reported on code.google.com by `lindauso...@gmail.com` on 30 Dec 2015 at 10:35

Attachments:
- [17.31.48.900324.log](https://storage.googleapis.com/google-code-attachments/google-cloud-sdk/issue-452/comment-0/17.31.48.900324.log)

**Comment by GoogleCodeExporter** [comment]
```
Extra information here: 
http://stackoverflow.com/questions/34533783/google-cloud-deployment-error-respon
se-13-could-not-pick-a-region-and-or-zone/34535566

gcloud info response:

Google Cloud SDK [90.0.0]

Platform: [Mac OS X, x86_64]
Python Version: [2.7.10 (default, Oct 23 2015, 18:05:06)  [GCC 4.2.1 Compatible 
Apple LLVM 7.0.0 (clang-700.0.59.5)]]
Python Location: [/Users/.../getting-started-python/6-pubsub/env/bin/python2]
Site Packages: [Enabled]

Installation Root: [/Users/user/google-cloud-sdk]
Installed Components:
  core: [2015.12.07]
  core-nix: [2015.11.24]
  gcloud: []
  gsutil-nix: [4.15]
  gsutil: [4.16]
  bq: [2.0.18]
  bq-nix: [2.0.18]
System PATH: [...]
Cloud SDK on PATH: [True]

Installation Properties: [/Users/user/google-cloud-sdk/properties]
User Config Directory: [/Users/user/.config/gcloud]
User Properties: [/Users/user/.config/gcloud/properties]
Current Workspace: [None]
Workspace Config Directory: [None]
Workspace Properties: [None]

Account: [*******]
Project: [*******]

Current Properties:
  [core]
    project: [*******]
    account: [*******]
    disable_usage_reporting: [True]
  [app]
    use_appengine_api: [true]
    suppress_change_warning: [true]
  [compute]
    region: [us-central1]
    zone: [us-central1-f]

Logs Directory: [/Users/user/.config/gcloud/logs]
Last Log File: [/Users/user/.config/gcloud/logs/2015.12.30/14.29.56.415916.log]
```

Original comment by `svalen...@google.com` on 30 Dec 2015 at 11:18

**Comment by GoogleCodeExporter** [comment]
```
Thanks for reporting this issue! I'll check in with the backend team and see 
why you may be experiencing this.
```

Original comment by `z...@google.com` on 2 Jan 2016 at 9:54
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
This occurs when your project winds up in an unusual state–I know it's 
annoying, but can you try again with a new project and see if the issue 
persists?

If that fixes it, we should have a fix out soon for the original issue (it's a 
problem on the backend, not with gcloud).
```

Original comment by `z...@google.com` on 4 Jan 2016 at 1:04
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
Hi, I have the same issue. Tried to create a new project and upload with gcloud 
but got the same error. 
Hope there will be a fix soon as I cannot upload my project anymore.
```

Original comment by `supp...@mentionlytics.com` on 4 Jan 2016 at 12:12

**Comment by GoogleCodeExporter** [comment]
```
Issue 457 has been merged into this issue.
```

Original comment by `z...@google.com` on 4 Jan 2016 at 1:45

**Comment by GoogleCodeExporter** [comment]
```
We were able to avoid the issue by creating a new project. No other changes 
(except name), and then it just started working.
```

Original comment by `bengtric...@gmail.com` on 4 Jan 2016 at 1:53

**Comment by GoogleCodeExporter** [comment]
```
Recreating the project worked for me as well.
```

Original comment by `lindauso...@gmail.com` on 4 Jan 2016 at 3:18

**Comment by GoogleCodeExporter** [comment]
```
Glad to hear that new projects are helping for a lot of folks.

If you're still running into this after creating a new project or need to be 
able to deploy to your old project (ex. the URL is important) before we're able 
to roll out a fix, please email me: zjn@...
```

Original comment by `z...@google.com` on 4 Jan 2016 at 4:20
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
Please comment if you're still seeing this.
```

Original comment by `z...@google.com` on 10 Mar 2016 at 2:08
- Changed state: **Fixed**
