### ISSUE TITLE
gcloud components update fails with error "connection reset by peer"

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#453]
```
Issue running command [gcloud components update].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "calliope/cli.py", line 609, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "calliope/backend.py", line 1228, in Run
    resources = command_instance.Run(args)
  File "surface/components/update.py", line 81, in Run
    version=args.version)
  File "core/updater/update_manager.py", line 720, in Update
    command_path='components.update')
  File "core/updater/update_manager.py", line 412, in _GetStateAndDiff
    command_path=command_path)
  File "core/updater/update_manager.py", line 395, in _GetLatestSnapshot
    *effective_url.split(','), command_path=command_path)
  File "core/updater/snapshots.py", line 153, in FromURLs
    for url in urls]
  File "core/updater/snapshots.py", line 174, in _DictFromURL
    response = installers.ComponentInstaller.MakeRequest(url, command_path)
  File "core/updater/installers.py", line 265, in MakeRequest
    return urlopen_with_cacerts.urlopen(req, timeout=TIMEOUT_IN_SEC)
  File "core/util/urlopen_with_cacerts.py", line 27, in urlopen
    return orig_urlopen(*args, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
[output truncated]

```

Original issue reported on code.google.com by `vineeth...@google.com` on 30 Dec 2015 at 11:54

**Comment by GoogleCodeExporter** [comment]
```
"connection reset by peer" usually indicates an issue with network 
connectivity–are you on WiFi or an unreliable internet connection?
```

Original comment by `z...@google.com` on 2 Jan 2016 at 9:53
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
Please re-open if you're still experiencing this.
```

Original comment by `z...@google.com` on 16 Feb 2016 at 11:14
- Changed state: **Invalid**
