### ISSUE TITLE
"No such file or directory:" when trying to clone [default] repository to [/default]

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#454]
```
Issue running command [gcloud init].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "calliope/cli.py", line 609, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "calliope/backend.py", line 1228, in Run
    resources = command_instance.Run(args)
  File "surface/init.py", line 94, in Run
    self._PickRepo()
  File "surface/init.py", line 326, in _PickRepo
    self._CloneRepo(repo_name)
  File "surface/init.py", line 346, in _CloneRepo
    files.MakeDir(parent_dir)
  File "core/util/files.py", line 47, in MakeDir
    os.makedirs(path, mode=mode)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 2] No such file or directory: ''

Installation information:

Google Cloud SDK [91.0.1]

Platform: [Mac OS X, x86_64]
Python Version: [2.7.10 (default, Oct 23 2015, 18:05:06)  [GCC 4.2.1 Compatible 
Apple LLVM 7.0.0 (clang-700.0.59.5)]]
Python Location: [/usr/bin/python]
Site Packages: [Disabled]

Installation Root: [/Users/hezumartin/google-cloud-sdk]
Installed Components:
  core: [2015.12.16]
  core-nix: [2015.11.24]
  gcloud: []
  gsutil-nix: [4.15]
  gsutil: [4.16]
  bq: [2.0.18]
  bq-nix: [2.0.18]
System PATH: 
[/Users/hezumartin/google-cloud-sdk/bin:/Users/hezumartin/anaconda/bin:/usr/loca
l/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin:/Library/TeX/texbin]
[output truncated]

```

Original issue reported on code.google.com by `hezumar...@gmail.com` on 3 Jan 2016 at 2:07
- Merged into: #423

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 4 Jan 2016 at 12:58
- Changed state: **Duplicate**
