### ISSUE TITLE
Can't deploy Managed VM module

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#457]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?
1. Create project in console
2. Deploy regular GAE module
3. Try to deploy Managed VM module using gcloud preview app deploy --promote 
mymodule/mymodule.yaml

What is the expected output? What do you see instead?
The Docker image is built correctly and the deploy only fails once everything 
seems to be complete, with the error message "Error Response: [13] Could not 
pick a region and/or zone". 


Please provide any additional information below.

Traceback (most recent call last):
  File "calliope/cli.py", line 609, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "calliope/backend.py", line 1228, in Run
    resources = command_instance.Run(args)
  File "surface/preview/app/deploy.py", line 285, in Run
    images.get(module))
  File "api_lib/app/appengine_api_client.py", line 76, in DeployModule
    return operations.WaitForOperation(self.client.apps_operations, operation)
  File "api_lib/app/api/operations.py", line 54, in WaitForOperation
    encoding.MessageToPyValue(completed_operation.error)))
OperationError: Error Response: [13] Could not pick a region and/or zone. 
Version: conversion:20160104t101005.389741105095154641

Installation information:

Google Cloud SDK [91.0.1]

Platform: [Mac OS X, x86_64]
Python Version: [2.7.10 (default, Aug 22 2015, 20:33:39)  [GCC 4.2.1 Compatible 
Apple LLVM 7.0.0 (clang-700.0.59.1)]]
Python Location: [/usr/bin/python]
Site Packages: [Disabled]

Installation Root: [/Users/richardolsson/google-cloud-sdk]
Installed Components:
  core: [2015.12.16]
  core-nix: [2015.11.24]
  gcloud: []
  gsutil-nix: [4.15]
  gsutil: [4.16]
  bq: [2.0.18]
  bq-nix: [2.0.18]
[output truncated]

```

Original issue reported on code.google.com by `richard....@b-reel.com` on 4 Jan 2016 at 9:27
- Merged into: #452

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 4 Jan 2016 at 1:45
- Changed state: **Duplicate**
