### ISSUE TITLE
Connection error when running [gcloud auth login]

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#461]
```
Issue running command [gcloud auth login].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "lib/googlecloudsdk/calliope/cli.py", line 609, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "lib/googlecloudsdk/calliope/backend.py", line 1228, in Run
    resources = command_instance.Run(args)
  File "lib/googlecloudsdk/calliope/exceptions.py", line 98, in TryFunc
    return func(*args, **kwargs)
  File "lib/googlecloudsdk/surface/auth/login.py", line 114, in Run
    creds = self.DoWebFlow(args.launch_browser)
  File "lib/googlecloudsdk/surface/auth/login.py", line 179, in DoWebFlow
    return c_store.AcquireFromWebFlow(launch_browser=launch_browser)
  File "lib/googlecloudsdk/core/credentials/store.py", line 383, in AcquireFromWebFlow
    http=_Http())
  File "lib/googlecloudsdk/core/credentials/flow.py", line 158, in Run
    credential = flow.step2_exchange(code, http=http)
  File "./lib/third_party/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "./lib/third_party/oauth2client/client.py", line 1993, in step2_exchange
    headers=headers)
  File "./lib/third_party/httplib2/__init__.py", line 1608, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "./lib/third_party/httplib2/__init__.py", line 1350, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
[output truncated]

```

Original issue reported on code.google.com by `ca.varg...@gmail.com` on 7 Jan 2016 at 3:02

**Comment by GoogleCodeExporter** [comment]
```
Thanks for reporting the issue.

By any chance you are behind some proxy/firewall.

Can you use
  gcloud auth login --no-launch-browser
and manually copy paste the link and then the code back.

To help diagnose the issue, can you include output of
  gcloud info
```

Original comment by `che...@google.com` on 7 Jan 2016 at 3:23
- Changed title: **Connection error when running [gcloud auth login]**
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
Please reopen if you are still experiencing this.
```

Original comment by `z...@google.com` on 18 Feb 2016 at 7:08
- Changed state: **Invalid**
