### ISSUE TITLE
Error when using relative path to clone in gcloud init

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#463]
```
Issue running command [gcloud init].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "calliope\cli.py", line 609, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "calliope\backend.py", line 1228, in Run
    resources = command_instance.Run(args)
  File "surface\init.py", line 94, in Run
    self._PickRepo()
  File "surface\init.py", line 326, in _PickRepo
    self._CloneRepo(repo_name)
  File "surface\init.py", line 346, in _CloneRepo
    files.MakeDir(parent_dir)
  File "core\util\files.py", line 47, in MakeDir
    os.makedirs(path, mode=mode)
  File "C:\python27_x64\lib\os.py", line 157, in makedirs
    mkdir(name, mode)
WindowsError: [Error 3] The system cannot find the path specified: ''

Installation information:

Google Cloud SDK [0.9.89]

Platform: [Windows, x86_64]
Python Version: [2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit 
(AMD64)]]
Python Location: [C:\python27_x64\python.exe]
Site Packages: [Disabled]

Installation Root: [C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk]
Installed Components:
  core: [2015.11.30]
  bq-win: [2.0.18]
  core-win: [2015.11.24]
  gcloud: []
  windows-ssh-tools: [2015.09.21]
  beta: [2015.10.08]
  gsutil: [4.16]
  bq: [2.0.18]
  gsutil-win: [4.15]
[output truncated]

```

Original issue reported on code.google.com by `sirisak....@gmail.com` on 7 Jan 2016 at 11:41

**Comment by GoogleCodeExporter** [comment]
```
Thanks for reporting the issue.

This has been addressed to in release 90.0.0, so if you update gcloud to latest
  gcloud components update
you will be able to enter relative path to clone repository.

Alternatively you can enter absolute path for destination git repo, or change 
to the destination directory and run git init accepting default path when 
cloning.
```

Original comment by `che...@google.com` on 8 Jan 2016 at 1:55
- Changed title: **Error when using relative path to clone in gcloud init**
- Changed state: **Fixed**
