### ISSUE TITLE
Error gcloud preview app deploy app.yaml --promote

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#468]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?
Download the example project,
Run >gcloud preview app deploy app.yaml --promote
Fails!

What is the expected output? What do you see instead?
It never worked, but I spect that works...

Please provide any additional information below.
WindowsError: [Error 3] El sistema no puede encontrar la ruta especificada: 
'C:\\Develop\\NodeJS\\hello\\node_modules\\gcloud\\node_modules\\gce-images\\nod
e_modules\\google-auto-auth\\node_modules\\google-auth-library\\node_modules\\jw
s\\node_modules\\base64url\\node_modules\\concat-stream\\node_modules\\readable-
stream\\node_modules\\core-util-is\\LICENSE'

Installation information:

Google Cloud SDK [91.0.1]

Platform: [Windows, x86_64]
Python Version: [2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit 
(AMD64)]]
Python Location: [C:\python27_x64\python.exe]
Site Packages: [Disabled]

Installation Root: [C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk]
Installed Components:
  core: [2015.12.16]
  bq-win: [2.0.18]
  core-win: [2015.11.24]
  gcloud: []
  windows-ssh-tools: [2015.09.21]
  gsutil: [4.16]
  gsutil-win: [4.15]
  bq: [2.0.18]
System PATH: [C:\Program Files (x86)\Google\Cloud 
SDK\google-cloud-sdk\bin\..\bin\sdk;C:\python27_x64\;C:\python27_x64\Scripts;C:\
WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\Windows
PowerShell\v1.0\;C:\Program Files (x86)\ATI 
Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\Common 
Files\lenovo\easyplussdk\bin;C:\Program Files\nodejs\;C:\Program 
Files\Java\jdk1.7.0_79\bin;C:\Program Files 
(x86)\Skype\Phone\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files 
(x86)\Google\Cloud SDK\google-cloud-sdk\bin;C:\Program 
Files\Java\jdk1.7.0_79\bin;C:\RailsInstaller\Git\cmd;C:\RailsInstaller\Ruby2.1.0
\bin;C:\RailsInstaller\Ruby2.0.0\bin;C:\Users\carlos\AppData\Roaming\npm;C:\Deve
lop\DevTools\bin;C:\Develop\DevTools;C:\Develop\DevTools\mingw\bin;C:\Users\carl
os\android-sdks\tools;C:\Users\carlos\android-sdks\platform-tools;C:\Develop\sts
-bundle\sts-3.6.4.RELEASE\plugins\appengine-java-sdk-1.9.27\bin;C:\Program 
Files (x86)\Microsoft Visual Studio 8\]
Cloud SDK on PATH: [True]

Installation Properties: [C:\Program Files (x86)\Google\Cloud 
SDK\google-cloud-sdk\properties]
User Config Directory: [C:\Users\carlos\AppData\Roaming\gcloud]
User Properties: [C:\Users\carlos\AppData\Roaming\gcloud\properties]
Current Workspace: [None]
Workspace Config Directory: [None]
Workspace Properties: [None]

Account: [ccorona@overcome.mx]
Project: [caduceusexp]

Current Properties:
  [core]
    project: [caduceusexp]
    account: [ccorona@overcome.mx]
    disable_usage_reporting: [False]
  [app]
    suppress_change_warning: [true]

Traceback (most recent call last):
  File "lib\googlecloudsdk\calliope\cli.py", line 609, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "lib\googlecloudsdk\calliope\backend.py", line 1228, in Run
    resources = command_instance.Run(args)
  File "lib\googlecloudsdk\surface\preview\app\deploy.py", line 256, in Run
    remote_build)
  File "lib\googlecloudsdk\api_lib\app\deploy_command_util.py", line 177, in BuildAndPushDockerImages
    info.file, docker_client, image_name)
  File "lib\googlecloudsdk\api_lib\app\deploy_command_util.py", line 248, in BuildAndPushDockerImage
    image.Build(docker_client)
  File "lib\googlecloudsdk\api_lib\app\docker_image.py", line 98, in Build
    nocache=self._nocache, rm=self._rm, pull=False)
  File "bin\..\./lib\third_party\docker\docker\api\build.py", line 49, in build
    context = utils.tar(path, exclude=exclude, dockerfile=dockerfile)
  File "bin\..\./lib\third_party\docker\docker\utils\utils.py", line 86, in tar
    t.add(os.path.join(root, path), arcname=path, recursive=False)
  File "C:\python27_x64\lib\tarfile.py", line 2000, in add
    tarinfo = self.gettarinfo(name, arcname)
  File "C:\python27_x64\lib\tarfile.py", line 1872, in gettarinfo
    statres = os.lstat(name)


```

Original issue reported on code.google.com by `ccor...@overcome.mx` on 13 Jan 2016 at 9:35

**Comment by GoogleCodeExporter** [comment]
```
Can you take a look at the mentioned license file and verify that you can read 
it?

Does this work? -->

python -c "import os; print 
os.lstat('C:\\Develop\\NodeJS\\hello\\node_modules\\gcloud\\node_modules\\gce-im
ages\\node_modules\\google-auto-auth\\node_modules\\google-auth-library\\node_mo
dules\\jws\\node_modules\\base64url\\node_modules\\concat-stream\\node_modules\\
readable-stream\\node_modules\\core-util-is\\LICENSE')"
```

Original comment by `mmul...@google.com` on 14 Jan 2016 at 1:08

**Comment by GoogleCodeExporter** [comment]
Original comment by `vil...@google.com` on 14 Jan 2016 at 4:21
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
I've tried the command that you send me but it doesn't work... The output is:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
WindowsError: [Error 3] El sistema no puede encontrar la ruta especificada: 
'C:\\Develop\\NodeJS\\hello\\node_modules\\gcloud\\node_modules\\gce-images\\nod
e_modules\\google-auto-auth\\node_modules\\google-auth-library\\node_modules\\jw
s\\node_modules\\base64url\\node_modules\\concat-stream\\node_modules\\readable-
stream\\node_modules\\core-util-is\\LICENSE'

Still, I've already looked back for the same file on the WindowsExplorer and I 
found it on the correct place... So I think it's possible a long path error... 
in fact, I renamed my project's folder to "C:\h\", and tried again, with same 
error on different file...

Beginning deployment...
Verifying that Managed VMs are enabled and ready.

Provisioning remote build service.
Copying certificates for secure access. You may be prompted to create an SSH 
keypair.
Building and pushing image for module [books]
----------------------------- DOCKER BUILD OUTPUT ------------------------------
Beginning teardown of remote build environment (this may take a few seconds).
ERROR: gcloud crashed (WindowsError): [Error 3] El sistema no puede encontrar 
la ruta especificada: 
'C:\\h\\node_modules\\gcloud\\node_modules\\gce-images\\node_modules\\google-aut
o-auth\\node_modules\\google-auth-library\\node_modules\\jws\\node_modules\\base
64url\\node_modules\\meow\\node_modules\\indent-string\\node_modules\\repeating\
\node_modules\\is-finite\\node_modules\\number-is-nan' 

Again, the file exists on the path but for some reason this fails... 


```

Original comment by `ccor...@overcome.mx` on 14 Jan 2016 at 9:14

Attachments:
- [File Licese Exists.jpg](https://storage.googleapis.com/google-code-attachments/google-cloud-sdk/issue-468/comment-3/File Licese Exists.jpg)

**Comment by GoogleCodeExporter** [comment]
```
This could be a path length issue. Even with the C:\h change, that string comes 
in at 269 characters because of the escaping of the '\' characters. I believe 
Windows has a limit of 260 characters.
```

Original comment by `dlor...@google.com` on 14 Jan 2016 at 9:30

**Comment by GoogleCodeExporter** [comment]
```
Yes... I think so... but Windows can handle more than 32K chars on the path if 
the string starts with the prefix "\\C:" 

Now... how I can solve this? I cant find where the process invoques this path 
to change it...
```

Original comment by `ccor...@overcome.mx` on 14 Jan 2016 at 10:18
