### ISSUE TITLE
When Deploying Ruby Application

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#469]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?
See:
https://cloud.google.com/ruby/getting-started/hello-world

Instead of using a Hello World rails application, I was trying to do a Sinatra 
Hello World Application.

What is the expected output? What do you see instead?

not crash.


Please provide any additional information below.


Traceback (most recent call last):
  File "lib/googlecloudsdk/gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  File "lib/googlecloudsdk/calliope/cli.py", line 643, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "lib/googlecloudsdk/calliope/backend.py", line 1401, in Run
    resources = command_instance.Run(args)
  File "lib/surface/preview/app/deploy.py", line 369, in Run
    config_cleanup)
  File "lib/googlecloudsdk/api_lib/app/deploy_command_util.py", line 193, in BuildAndPushDockerImages
    cli, version_id, remote, project) as docker_client:
  File "lib/googlecloudsdk/api_lib/app/images/docker_util.py", line 243, in __enter__
    return containers.NewDockerClient(local=(not self._remote), **kwargs)
  File "lib/googlecloudsdk/api_lib/app/containers.py", line 139, in NewDockerClient
    client = NewDockerClientNoCheck(**kwargs)
  File "lib/googlecloudsdk/api_lib/app/containers.py", line 122, in NewDockerClientNoCheck
    return docker.Client(**kwargs)
  File "./lib/third_party/docker/docker/client.py", line 77, in __init__
    self._version = self._retrieve_server_version()
  File "./lib/third_party/docker/docker/client.py", line 97, in _retrieve_server_version
    'Error while fetching server API version: {0}'.format(e)
DockerException: Error while fetching server API version: ('Connection 
aborted.', error(61, 'Connection refused'))

Installation information:

[output truncated]
```

Original issue reported on code.google.com by `henr...@gmail.com` on 14 Jan 2016 at 9:33

**Comment by GoogleCodeExporter** [comment]
```
WARNING: Truncating included information. Please consider including the 
remainder:
=============================================================== TRUNCATED 
INFORMATION (PLEASE CONSIDER INCLUDING) 
================================================================
Google Cloud SDK [92.0.0]

Platform: [Mac OS X, x86_64]
Python Version: [2.7.10 (default, Oct 23 2015, 18:05:06)  [GCC 4.2.1 Compatible 
Apple LLVM 7.0.0 (clang-700.0.59.5)]]
Python Location: [/usr/bin/python]
Site Packages: [Disabled]

Installation Root: [/Users/henry/Downloads/google-cloud-sdk]
Installed Components:
  core: [2016.01.12]
  core-nix: [2015.12.16]
  kubectl: []
  gcloud: []
  gsutil-nix: [4.16]
  gsutil: [4.16]
  bq: [2.0.18]
  bq-nix: [2.0.18]
  kubectl-darwin-x86_64: [1.1.3]
System PATH: 
[/Users/henry/Downloads/google-cloud-sdk/bin:/Users/henry/.rvm/gems/ruby-2.2.3/b
in:/Users/henry/.rvm/gems/ruby-2.2.3@global/bin:/Users/henry/.rvm/rubies/ruby-2.
2.3/bin:/Users/henry/pebble-dev/PebbleSDK-2.2/bin:/Users/henry/pebble-dev/Pebble
SDK-current/bin:/usr/local/apache-maven/apache-maven-3.2.1/bin:/usr/local/heroku
/bin:/usr/local/bin:/opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbi
n:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/henry/Downloads/google-clo
ud-sdk/bin:/Users/henry/.rvm/gems/ruby-2.2.3/bin:/Users/henry/.rvm/gems/ruby-2.2
.3@global/bin:/Users/henry/.rvm/rubies/ruby-2.2.3/bin:/Users/henry/pebble-dev/Pe
bbleSDK-2.2/bin:/Users/henry/pebble-dev/PebbleSDK-current/bin:/usr/local/apache-
maven/apache-maven-3.2.1/bin:/usr/local/heroku/bin:/opt/local/bin:/opt/local/sbi
n:/Users/henry/.rvm/bin]
Cloud SDK on PATH: [True]

Installation Properties: [/Users/henry/Downloads/google-cloud-sdk/properties]
User Config Directory: [/Users/henry/.config/gcloud]
User Properties: [/Users/henry/.config/gcloud/properties]
Current Workspace: [None]
Workspace Config Directory: [None]
Workspace Properties: [None]

Account: [henryse@gmail.com]
Project: [ringed-metric-117718]

Current Properties:
  [core]
    project: [ringed-metric-117718]
    account: [henryse@gmail.com]
    disable_usage_reporting: [False]
  [app]
    suppress_change_warning: [true]
  [compute]
    zone: [us-central1-b]

Logs Directory: [/Users/henry/.config/gcloud/logs]
Last Log File: [/Users/henry/.config/gcloud/logs/2016.01.14/13.29.42.122753.log]
============================================================= END TRUNCATED 
INFORMATION (PLEASE CONSIDER INCLUDING) 
==============================================================
WARNING: The output of gcloud info is too long to pre-populate the new issue 
form.
WARNING: Please consider including the remainder (above).
Opening your browser to a new Google Cloud SDK issue.
If your browser doesn't open, please file an issue: 
https://code.google.com/p/google-cloud-sdk/issues
```

Original comment by `henr...@gmail.com` on 14 Jan 2016 at 9:34

**Comment by GoogleCodeExporter** [comment]
```
I wish ruby worked on google cloud....
```

Original comment by `henr...@gmail.com` on 14 Jan 2016 at 9:37

**Comment by GoogleCodeExporter** [comment]
```
I will try to use Heroku for now.  I have also trie dot use docker images with 
the ruby application inside of it with no luck.
```

Original comment by `henr...@gmail.com` on 14 Jan 2016 at 9:41

**Comment by GoogleCodeExporter** [comment]
```
Can you provide the command you used and the app.yaml file?
```

Original comment by `dlor...@google.com` on 14 Jan 2016 at 9:51

**Comment by GoogleCodeExporter** [comment]
```
This appears to be a Firewall issue, you tool should do a better job when it 
"crashes" because of a fire wall issue.  :-)
```

Original comment by `henr...@gmail.com` on 14 Jan 2016 at 10:05

**Comment by GoogleCodeExporter** [comment]
Original comment by `vil...@google.com` on 14 Jan 2016 at 10:37
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
Original comment by `vil...@google.com` on 14 Jan 2016 at 10:40
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
Issue 578 has been merged into this issue.
```

Original comment by `z...@google.com` on 24 Feb 2016 at 7:21

**Comment by GoogleCodeExporter** [comment]
```
Issue 507 has been merged into this issue.
```

Original comment by `z...@google.com` on 24 Feb 2016 at 7:22

**Comment by GoogleCodeExporter** [comment]
```
Issue 606 has been merged into this issue.
```

Original comment by `z...@google.com` on 29 Feb 2016 at 9:06
