### ISSUE TITLE
Error when run gcutil

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#47]
```
What steps will reproduce the problem?
C:\Program Files\Google\Cloud SDK>gcutil --service_version="v1" 
--project="excellent-well-614" ssh --zone="europe-west1-
b" "phpdemo"


What is the expected output? What do you see instead?
Traceback (most recent call last):
  File "C:\Program Files\Google\Cloud SDK\bootstrapping\gcutil.py", line 10, in <module>
    import bootstrapping
  File "C:\Program Files\Google\Cloud SDK\bootstrapping\bootstrapping.py", line 9, in <module>
    import setup
  File "C:\Program Files\Google\Cloud SDK\bootstrapping\setup.py", line 44, in <module>
    from googlecloudsdk.core.util import platforms

What is the output of 'gcloud version'?
'gcloud' n'est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.

Please provide any additional information below.
run windows 7

```

Original issue reported on code.google.com by `n-...@3-ow.in` on 19 Jun 2014 at 10:42

**Comment by GoogleCodeExporter** [comment]
```
This is obsolete, now that 'gcutil' is deprecated. Please use 'gcloud compute' 
instead.
```

Original comment by `z...@google.com` on 13 Jul 2015 at 2:06
- Changed state: **Obsolete**
