### ISSUE TITLE
Not enough VMs ready

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#470]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?
Deploying with our repository

What is the expected output? What do you see instead?
Successful deploy logs

Please provide any additional information below.
Crash log did not seem to reveal issues on our side

Traceback (most recent call last):
  File "calliope/cli.py", line 609, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "calliope/backend.py", line 1228, in Run
    resources = command_instance.Run(args)
  File "surface/preview/app/deploy.py", line 285, in Run
    images.get(module))
  File "api_lib/app/appengine_api_client.py", line 76, in DeployModule
    return operations.WaitForOperation(self.client.apps_operations, operation)
  File "api_lib/app/api/operations.py", line 54, in WaitForOperation
    encoding.MessageToPyValue(completed_operation.error)))
OperationError: Error Response: [13] Not enough VMs ready (0/1 ready, 1 still 
deploying). Version: partner-docs-gce:20160114t181614.389986792629975875

Installation information:

Google Cloud SDK [0.9.89]

Platform: [Mac OS X, x86_64]
Python Version: [2.7.10 (default, Jul 14 2015, 19:46:27)  [GCC 4.2.1 Compatible 
Apple LLVM 6.0 (clang-600.0.39)]]
Python Location: [/src/tmvenv/bin/python2]
Site Packages: [Enabled]

Installation Root: [/Users/mcavalli-sforza/google-cloud-sdk]
Installed Components:
  core: [2015.11.30]
  app-engine-python: [1.9.28]
  core-nix: [2015.11.24]
  app-engine-java: [1.9.28]
  gcloud: []
  gsutil-nix: [4.15]
  app-engine-php: [ ]
  gsutil: [4.16]
  bq: [2.0.18]
  app-engine-php-darwin: [2015.11.16]
  bq-nix: [2.0.18]
[output truncated]

```

Original issue reported on code.google.com by `ma...@triggermail.io` on 15 Jan 2016 at 12:16

**Comment by GoogleCodeExporter** [comment]
```
Thank you for reporting this. 

The error may be caused by your app not passing health checks. You should check 
your logs to see what is happening. You should be able to see your logs at: 
https://cloud.google.com/logs?project=YOUR_PROJECT_NAME&service=appengine.google
apis.com.

We will look into improving this error message.
```

Original comment by `vil...@google.com` on 15 Jan 2016 at 9:16
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
This can also happen if your application process crashes on startup.  In Cloud 
Logging, can you look for a crash.log?   Here's a screenshot of where you find 
it:

http://i.imgur.com/eazjr1K.png?1

If you find crash.log in that dropdown, take a look at the output.  It will 
usually have the stack trace for the crash.  

Hope this helps!
```

Original comment by `beckw...@google.com` on 15 Jan 2016 at 9:22

**Comment by GoogleCodeExporter** [comment]
```
Please re-open if the suggestions in #1 and #2 did not help.
```

Original comment by `z...@google.com` on 16 Feb 2016 at 11:13
- Changed state: **Invalid**
