### ISSUE TITLE
error auth login

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#472]
```
Issue running command [gcloud auth login].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk/gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  File "googlecloudsdk/calliope/cli.py", line 643, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk/calliope/backend.py", line 1401, in Run
    resources = command_instance.Run(args)
  File "googlecloudsdk/calliope/exceptions.py", line 110, in TryFunc
    return func(*args, **kwargs)
  File "surface/auth/login.py", line 97, in Run
    elif c_gce.Metadata().connected:
  File "googlecloudsdk/core/credentials/gce.py", line 201, in Metadata
    _metadata_lock.lock(function=_CreateMetadata, argument=None)
  File "/usr/lib/python2.7/mutex.py", line 44, in lock
    function(argument)
  File "googlecloudsdk/core/credentials/gce.py", line 200, in _CreateMetadata
    _metadata = _GCEMetadata()
  File "googlecloudsdk/core/credentials/gce.py", line 57, in __init__
    self.connected = gce_cache.GetOnGCE()
  File "googlecloudsdk/core/credentials/gce_cache.py", line 104, in GetOnGCE
    return _SINGLETON_ON_GCE_CACHE.GetOnGCE(check_age)
  File "googlecloudsdk/core/credentials/gce_cache.py", line 67, in GetOnGCE
    self._UpdateFileCache()
  File "googlecloudsdk/core/credentials/gce_cache.py", line 84, in _UpdateFileCache
    on_gce = self._CheckServer()
  File "googlecloudsdk/core/credentials/gce_cache.py", line 92, in _CheckServer
    gce_read.GOOGLE_GCE_METADATA_NUMERIC_PROJECT_URI)
[output truncated]

```

Original issue reported on code.google.com by `rizky281...@gmail.com` on 15 Jan 2016 at 12:51

**Comment by GoogleCodeExporter** [comment]
```
Thank you for reporting this. Could you provide the output of `gcloud info` 
(after redacting any private info), and also the full stack trace?
```

Original comment by `vil...@google.com` on 15 Jan 2016 at 3:46
- Changed state: **NeedsMoreInfo**
