### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#474]
```
Issue running command [gcloud init].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  File "calliope\cli.py", line 643, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "calliope\backend.py", line 1401, in Run
    resources = command_instance.Run(args)
  File "surface\init.py", line 94, in Run
    self._PickRepo()
  File "surface\init.py", line 326, in _PickRepo
    self._CloneRepo(repo_name)
  File "surface\init.py", line 346, in _CloneRepo
    files.MakeDir(parent_dir)
  File "core\util\files.py", line 59, in MakeDir
    os.makedirs(path, mode=mode)
  File "C:\python27\lib\os.py", line 157, in makedirs
    mkdir(name, mode)
WindowsError: [Error 3] The system cannot find the path specified: ''

Installation information:

Google Cloud SDK [92.0.0]

Platform: [Windows, x86_64]
Python Version: [2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC 
v.1500 32 bit (Intel)]]
Python Location: [C:\python27\python.exe]
Site Packages: [Disabled]

Installation Root: [C:\Users\Rockstar\AppData\Local\Google\Cloud 
SDK\google-cloud-sdk]
Installed Components:
  core: [2016.01.12]
  bq-win: [2.0.18]
  core-win: [2016.01.12]
  gcloud: []
  windows-ssh-tools: [2015.09.21]
  gsutil: [4.16]
  gsutil-win: [4.16]
  bq: [2.0.18]
[output truncated]

```

Original issue reported on code.google.com by `computer...@gmail.com` on 16 Jan 2016 at 4:14

**Comment by GoogleCodeExporter** [comment]
```
Thank you for the feedback. To help us better understand what is happening 
could you:

- Provide the full output of gcloud info (after redacting any personal info)
- Describe at what point during `gcloud init` you encountered this error


```

Original comment by `vil...@google.com` on 19 Jan 2016 at 3:56
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
Please reopen with more information if you're still experiencing this.
```

Original comment by `z...@google.com` on 18 Feb 2016 at 7:17
- Changed state: **Invalid**
