### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\xd7' in position 118: ordinal not in range(128)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#475]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?

running gcloud preview app deploy app.yaml

What is the expected output? What do you see instead?

app should have been deployed. error was returned instead.

Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk/gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  File "googlecloudsdk/calliope/cli.py", line 643, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk/calliope/backend.py", line 1401, in Run
    resources = command_instance.Run(args)
  File "surface/preview/app/deploy.py", line 387, in Run
    images.get(module))
  File "googlecloudsdk/api_lib/app/appengine_api_client.py", line 90, in DeployModule
    return operations.WaitForOperation(self.client.apps_operations, operation)
  File "googlecloudsdk/api_lib/app/api/operations.py", line 66, in WaitForOperation
    encoding.MessageToPyValue(completed_operation.error)))
  File "googlecloudsdk/api_lib/app/api/requests.py", line 69, in ExtractErrorMessage
    message=error_details.get('message', '')))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xd7' in position 
118: ordinal not in range(128)

Installation information:

Google Cloud SDK [92.0.0]

Platform: [Linux, x86_64]
Python Version: [2.7.10 (default, Jun 30 2015, 17:20:49)  [GCC 4.9.2]]
Python Location: [/usr/bin/python2]
Site Packages: [Disabled]

Installation Root: [/home/dalla/sdks/google-cloud-sdk]
Installed Components:
  core: [2016.01.12]
  app-engine-python: [1.9.30]
  core-nix: [2015.11.24]
  gcloud: []
  gsutil-nix: [4.15]
  gsutil: [4.16]
  bq: [2.0.18]
[output truncated]

```

Original issue reported on code.google.com by `dallar...@gmail.com` on 17 Jan 2016 at 11:48
- Merged into: #471

**Comment by GoogleCodeExporter** [comment]
```
Thank you for the feedback. We are aware of this issue and hope to fix it soon 
in a future release.
```

Original comment by `vil...@google.com` on 19 Jan 2016 at 3:58
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
Original comment by `vil...@google.com` on 19 Jan 2016 at 3:59
- Changed state: **Duplicate**
