### ISSUE TITLE
Couldn't deploy the hellow world node js app 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#476]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "lib\googlecloudsdk\gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  File "lib\googlecloudsdk\calliope\cli.py", line 643, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "lib\googlecloudsdk\calliope\backend.py", line 1401, in Run
    resources = command_instance.Run(args)
  File "lib\surface\preview\app\deploy.py", line 369, in Run
    config_cleanup)
  File "lib\googlecloudsdk\api_lib\app\deploy_command_util.py", line 193, in BuildAndPushDockerImages
    cli, version_id, remote, project) as docker_client:
  File "lib\googlecloudsdk\api_lib\app\images\docker_util.py", line 243, in __enter__
    return containers.NewDockerClient(local=(not self._remote), **kwargs)
  File "lib\googlecloudsdk\api_lib\app\containers.py", line 139, in NewDockerClient
    client = NewDockerClientNoCheck(**kwargs)
  File "lib\googlecloudsdk\api_lib\app\containers.py", line 122, in NewDockerClientNoCheck
    return docker.Client(**kwargs)
  File "bin\..\./lib\third_party\docker\docker\client.py", line 77, in __init__
    self._version = self._retrieve_server_version()
  File "bin\..\./lib\third_party\docker\docker\client.py", line 97, in _retrieve_server_version
    'Error while fetching server API version: {0}'.format(e)
DockerException: Error while fetching server API version: [SSL: 
CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

[output truncated]

```

Original issue reported on code.google.com by `Mark.O...@mysteryshoppa.com` on 18 Jan 2016 at 11:46

**Comment by GoogleCodeExporter** [comment]
```
Hi,

Can you try again with this setting:

gcloud config set app/use_cloud_build true

then deploy.
```

Original comment by `dlor...@google.com` on 18 Jan 2016 at 7:19

**Comment by GoogleCodeExporter** [comment]
Original comment by `vil...@google.com` on 19 Jan 2016 at 4:03
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
Issue 486 has been merged into this issue.
```

Original comment by `z...@google.com` on 21 Jan 2016 at 2:24

**Comment by GoogleCodeExporter** [comment]
```
Issue 473 has been merged into this issue.
```

Original comment by `z...@google.com` on 21 Jan 2016 at 2:25

**Comment by GoogleCodeExporter** [comment]
```
Issue 485 has been merged into this issue.
```

Original comment by `z...@google.com` on 21 Jan 2016 at 5:20

**Comment by GoogleCodeExporter** [comment]
```
Issue 491 has been merged into this issue.
```

Original comment by `z...@google.com` on 21 Jan 2016 at 5:21

**Comment by GoogleCodeExporter** [comment]
```
POssible proble (solved for me)
If you are in a virtual machine change your network mode from NAT
to Bridged so you will get an IP directly from your router and not create a sub 
network between your guest and your host. The NAT configuration creates a man 
in the middle situation
```

Original comment by `RavenX86...@gmail.com` on 23 Jan 2016 at 8:58

**Comment by GoogleCodeExporter** [comment]
```
Issue 621 has been merged into this issue.
```

Original comment by `vil...@google.com` on 5 Mar 2016 at 2:26

**Comment by GoogleCodeExporter** [comment]
```
Issue 622 has been merged into this issue.
```

Original comment by `vil...@google.com` on 5 Mar 2016 at 2:26

**Comment by GoogleCodeExporter** [comment]
```
Issue 636 has been merged into this issue.
```

Original comment by `z...@google.com` on 9 Mar 2016 at 6:04

**Comment by GoogleCodeExporter** [comment]
```
Issue 637 has been merged into this issue.
```

Original comment by `z...@google.com` on 9 Mar 2016 at 7:25

**Comment by GoogleCodeExporter** [comment]
```
Issue 646 has been merged into this issue.
```

Original comment by `z...@google.com` on 14 Mar 2016 at 12:01
