### ISSUE TITLE
ASCII/Unicode error when generating ssh keys

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#477]
```
Issue running command [gcloud compute ssh].

What steps will reproduce the problem?
I'm performing  step by step from this tutorial: Setting up secure FTP on 
Google Compute Engine -> Part "Setting up secure FTP on Google Compute Engine", 
step 2. When Im generating ssh keys in cmd (with admin rights):

gcloud compute ssh [MY-ACTIVE-INSTANCE]


What is the expected output? What do you see instead?

I see this error msg:
"ERROR: gcloud crashed (UnicodeDecodeError): 'ascii' codec can't decode byte 
0xb3 in position 5: ordinal not in range(128)"

Please provide any additional information below.

My paths are as simple as possible, without special chars.

Traceback (most recent call last):
  File "googlecloudsdk\gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  File "googlecloudsdk\calliope\cli.py", line 643, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk\calliope\backend.py", line 1401, in Run
    resources = command_instance.Run(args)
  File "surface\compute\ssh.py", line 141, in Run
    ssh_args.append(ssh_utils.UserHost(user, external_ip_address))
  File "googlecloudsdk\api_lib\compute\ssh_utils.py", line 71, in UserHost
    return user + '@' + host
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb3 in position 5: ordinal 
not in range(128)

Installation information:

Google Cloud SDK [92.0.0]

Platform: [Windows, x86_64]
Python Version: [2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit 
(AMD64)]]
Python Location: [C:\python27\python.exe]
Site Packages: [Disabled]

Installation Root: [c:\GoogleCloudSDK\google-cloud-sdk]
Installed Components:
  core: [2016.01.12]
  bq-win: [2.0.18]
  core-win: [2016.01.12]
  gcloud: []
  windows-ssh-tools: [2015.09.21]
  gsutil: [4.16]
  gsutil-win: [4.16]
  bq: [2.0.18]
[output truncated]

```

Original issue reported on code.google.com by `deloitte...@gmail.com` on 18 Jan 2016 at 12:18

**Comment by GoogleCodeExporter** [comment]
```
Does your Windows user name have any non-ASCII characters in it, by any chance?

Try `gcloud compute ssh testuser@[MY ACTIVE INSTANCE]`--does that work?
```

Original comment by `z...@google.com` on 19 Jan 2016 at 2:40
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
Issue 140 has been merged into this issue.
```

Original comment by `z...@google.com` on 19 Jan 2016 at 3:40

**Comment by GoogleCodeExporter** [comment]
```
Yes, that was the problem. My windows user name was using a non-ASCII character.
```

Original comment by `Yuri.c.r...@gmail.com` on 19 Jan 2016 at 3:58

**Comment by GoogleCodeExporter** [comment]
```
We'll look into this.
```

Original comment by `z...@google.com` on 19 Jan 2016 at 8:53
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
This should be fixed in the 97.0.0 Cloud SDK release.
```

Original comment by `z...@google.com` on 9 Feb 2016 at 2:32
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
Issue 542 has been merged into this issue.
```

Original comment by `z...@google.com` on 12 Feb 2016 at 11:33

**Comment by GoogleCodeExporter** [comment]
```
The 97.0.0 release is out. Please re-open if you're still experiencing this 
issue.
```

Original comment by `z...@google.com` on 18 Feb 2016 at 8:15
- Changed state: **Fixed**
