### ISSUE TITLE
gcloud auth login crashes

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#479]
```
Issue running command [gcloud auth login].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "lib/google-cloud-sdk/lib/googlecloudsdk/gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  File "lib/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 643, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "lib/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 1401, in Run
    resources = command_instance.Run(args)
  File "lib/google-cloud-sdk/lib/googlecloudsdk/calliope/exceptions.py", line 110, in TryFunc
    return func(*args, **kwargs)
  File "lib/google-cloud-sdk/lib/surface/auth/login.py", line 126, in Run
    creds = self.DoWebFlow(args.launch_browser)
  File "lib/google-cloud-sdk/lib/surface/auth/login.py", line 191, in DoWebFlow
    return c_store.AcquireFromWebFlow(launch_browser=launch_browser)
  File "lib/google-cloud-sdk/lib/googlecloudsdk/core/credentials/store.py", line 401, in AcquireFromWebFlow
    http=_Http())
  File "lib/google-cloud-sdk/lib/googlecloudsdk/core/credentials/flow.py", line 170, in Run
    credential = flow.step2_exchange(code, http=http)
  File "bin/../lib/google-cloud-sdk/./lib/third_party/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "bin/../lib/google-cloud-sdk/./lib/third_party/oauth2client/client.py", line 1993, in step2_exchange
    headers=headers)
[output truncated]

```

Original issue reported on code.google.com by `awwsa...@gmail.com` on 19 Jan 2016 at 2:47

**Comment by GoogleCodeExporter** [comment]
```
Thank you for reporting this. 

Please provide the following to help us better understand what may be 
happening: 

- The output of `gcloud info` (after redacting any private info)
- The full stack trace.
```

Original comment by `vil...@google.com` on 19 Jan 2016 at 4:06
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
Please reopen with more information if you're still experiencing this.
```

Original comment by `z...@google.com` on 18 Feb 2016 at 7:17
- Changed state: **Invalid**
