### ISSUE TITLE
Trying run bookshelf app 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#480]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "lib\googlecloudsdk\gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  File "lib\googlecloudsdk\calliope\cli.py", line 643, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "lib\googlecloudsdk\calliope\backend.py", line 1401, in Run
    resources = command_instance.Run(args)
  File "lib\surface\preview\app\deploy.py", line 369, in Run
    config_cleanup)
  File "lib\googlecloudsdk\api_lib\app\deploy_command_util.py", line 204, in BuildAndPushDockerImages
    info.file, docker_client, image_name)
  File "lib\googlecloudsdk\api_lib\app\deploy_command_util.py", line 278, in BuildAndPushDockerImage
    image.Build(docker_client)
  File "lib\googlecloudsdk\api_lib\app\docker_image.py", line 110, in Build
    nocache=self._nocache, rm=self._rm, pull=False)
  File "bin\..\./lib\third_party\docker\docker\api\build.py", line 49, in build
    context = utils.tar(path, exclude=exclude, dockerfile=dockerfile)
  File "bin\..\./lib\third_party\docker\docker\utils\utils.py", line 86, in tar
    t.add(os.path.join(root, path), arcname=path, recursive=False)
  File "C:\python27_x64\lib\tarfile.py", line 2000, in add
    tarinfo = self.gettarinfo(name, arcname)
  File "C:\python27_x64\lib\tarfile.py", line 1872, in gettarinfo
    statres = os.lstat(name)
[output truncated]

```

Original issue reported on code.google.com by `edygalan...@gmail.com` on 19 Jan 2016 at 6:03

**Comment by GoogleCodeExporter** [comment]
```
Thank you for reporting this. To help us better understand what may be 
happening can you please provide:

- The full stack trace from the logs
- The output of `gcloud info` (after redacting personal info)
```

Original comment by `vil...@google.com` on 20 Jan 2016 at 6:41
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
Please reopen with more information if you're still experiencing this.
```

Original comment by `z...@google.com` on 18 Feb 2016 at 7:17
- Changed state: **Invalid**
