### ISSUE TITLE
Gcloud crashed on exit

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#481]
```
Issue running command [gcloud compute ssh].

What steps will reproduce the problem?
I logged into a VM, used it and logged it with either exit or Ctrl+D.

What is the expected output? What do you see instead?
I expect a clean logout, instead the logs showed that Gcloud crashed. 

Please provide any additional information below.
I have used a similar method earlier several times. So this could be an issue 
with more recent updates.

Traceback (most recent call last):
  File "googlecloudsdk/gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  File "googlecloudsdk/calliope/cli.py", line 643, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk/calliope/backend.py", line 1401, in Run
    resources = command_instance.Run(args)
  File "surface/compute/ssh.py", line 165, in Run
    use_account_service=self._use_accounts_service)
  File "googlecloudsdk/api_lib/compute/ssh_utils.py", line 527, in ActuallyRun
    return _RunExecutable(cmd_args, strict_error_checking=strict_error_checking)
  File "googlecloudsdk/api_lib/compute/ssh_utils.py", line 136, in _RunExecutable
    subprocess.check_call(cmd_args, stdout=stdout, stderr=stderr)
  File "/usr/lib64/python2.6/subprocess.py", line 505, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['/usr/bin/ssh', '-i', 
'/home/biswass/.ssh/google_compute_engine', '-o', 
'UserKnownHostsFile=/dev/null', '-o', 'IdentitiesOnly=yes', '-o', 
'CheckHostIP=no', '-o', 'StrictHostKeyChecking=no', u'biswass@104.197.130.26']' 
returned non-zero exit status 130

Installation information:

Google Cloud SDK [92.0.0]

Platform: [Linux, x86_64]
Python Version: [2.6.6 (r266:84292, May 22 2015, 08:34:51)  [GCC 4.4.7 20120313 
(Red Hat 4.4.7-15)]]
Python Location: [/usr/bin/python2]
Site Packages: [Disabled]

[output truncated]

```

Original issue reported on code.google.com by `swarnendu.biswas` on 19 Jan 2016 at 9:26

**Comment by GoogleCodeExporter** [comment]
```
Thank you for reporting this. 

Does this happen every time you use `gcloud compute ssh`?

If possible, can you try this with Python 2.7+?
```

Original comment by `vil...@google.com` on 20 Jan 2016 at 6:55
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
Looking into this further, this seems to be an issue that only affects Python 
2.6 users. We will investigate this and hope to fix it soon in a future release.
```

Original comment by `vil...@google.com` on 20 Jan 2016 at 7:49
- Changed state: **Accepted**
