### ISSUE TITLE
gcloud preview app deploy app.yaml --promote crashed

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#482]
```
2016-01-19 23:20:59,526 DEBUG    root            Loaded Command Group: 
['gcloud', 'preview']
2016-01-19 23:20:59,528 DEBUG    root            Loaded Command Group: 
['gcloud', 'preview', 'app']
2016-01-19 23:20:59,983 DEBUG    root            Loaded Command Group: 
['gcloud', 'preview', 'app', 'deploy']
2016-01-19 23:20:59,986 WARNING  root            The `gcloud preview app` 
surface is rapidly improving. Look out for
changing flags and new commands before the transition out of the `preview`
component. These changes will be documented in the Cloud SDK release notes
<https://goo.gl/X8apDJ> and via deprecation notices for changing commands.

If you would like to avoid changing behavior, please pin to a fixed version of
the Google Cloud SDK as described under the "Alternative Methods" section of the
Cloud SDK web site: <https://cloud.google.com/sdk/#alternative>.

2016-01-19 23:20:59,988 DEBUG    root            Running 
gcloud.preview.app.deploy with 
Namespace(__calliope_internal_deepest_parser=ArgumentParser(prog='gcloud.preview
.app.deploy', usage=None, description="*(BETA)* This command is used to deploy 
both code and configuration to the App Engine\nserver.  As an input it takes 
one or more ``DEPLOYABLES'' that should be\nuploaded.  A ``DEPLOYABLE'' can be 
a module's .yaml file or a configuration's\n.yaml file.", version=None, 
formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', 
add_help=False), account=None, authority_selector=None, 
authorization_token_file=None, bucket=None, cmd_func=<bound method Command.Run 
of <googlecloudsdk.calliope.backend.Command object at 0x24e0350>>, 
command_path=['gcloud', 'preview', 'app', 'deploy'], configuration=None, 
deployables=['app.yaml'], docker_build=None, document=None, force=False, 
format=None, h=None, help=None, http_timeout=None, image_url=None, 
log_http=None, project=None, promote='true', quiet=None, repo_info_file=None, 
server=None, stop_previous_version=None, trace_email=None, trace_log=False, 
trace_token=None, user_output_enabled=None, verbosity=None, version=None).
2016-01-19 23:21:00,002 DEBUG    root            API endpoint: 
[https://appengine.googleapis.com/], API version: [v1beta4]
2016-01-19 23:21:00,004 INFO     ___FILE_ONLY___ You are about to deploy the 
following modules:

2016-01-19 23:21:00,005 INFO     ___FILE_ONLY___  - 
hotelapplicationversion1/default (from 
[/home/ivarghis/googleAppEngine/nodejs-getting-started/1-hello-world/app.yaml])
     Deployed URL: [https://hotelapplicationversion1.appspot.com]


2016-01-19 23:21:06,349 INFO     ___FILE_ONLY___ Beginning deployment...

2016-01-19 23:21:06,350 DEBUG    root            Host: appengine.google.com
2016-01-19 23:21:06,352 DEBUG    
googlecloudsdk.third_party.appengine.tools.appengine_rpc _Authenticate 
configuring auth; needs_auth=False
2016-01-19 23:21:06,352 DEBUG    
googlecloudsdk.third_party.appengine.tools.appengine_rpc Sending request to 
https://appengine.google.com/api/vms/prepare?app_id=hotelapplicationversion1 
headers={'X-appcfg-api-version': '1', 'content-length': '0', 'Content-Type': 
'application/octet-stream'} body=
2016-01-19 23:21:06,352 INFO     oauth2client.client Attempting refresh to 
obtain initial access_token
2016-01-19 23:21:06,352 INFO     oauth2client.client Refreshing access_token
2016-01-19 23:21:21,396 INFO     ___FILE_ONLY___ If this is your first 
deployment, this may take a while...
2016-01-19 23:21:21,399 DEBUG    root            Unable to find the server at 
accounts.google.com
Traceback (most recent call last):
  File "/home/ivarghis/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 643, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "/home/ivarghis/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 1401, in Run
    resources = command_instance.Run(args)
  File "/home/ivarghis/google-cloud-sdk/lib/surface/preview/app/deploy.py", line 350, in Run
    deploy_command_util.DoPrepareManagedVms(gae_client)
  File "/home/ivarghis/google-cloud-sdk/lib/googlecloudsdk/api_lib/app/deploy_command_util.py", line 250, in DoPrepareManagedVms
    gae_client.PrepareVmRuntime()
  File "/home/ivarghis/google-cloud-sdk/lib/googlecloudsdk/api_lib/app/appengine_client.py", line 198, in PrepareVmRuntime
    rpcserver.Send('/api/vms/prepare', app_id=self.project)
  File "/home/ivarghis/google-cloud-sdk/lib/googlecloudsdk/api_lib/app/util.py", line 370, in Send
    response = self._server.Send(*args, **kwargs)
  File "/home/ivarghis/google-cloud-sdk/lib/googlecloudsdk/third_party/appengine/tools/appengine_rpc_httplib2.py", line 230, in Send
    url, method=method, body=payload, headers=headers)
  File "/home/ivarghis/googleAppEngine/nodejs-getting-started/1-hello-world/../../../google-cloud-sdk/./lib/third_party/oauth2client/client.py", line 540, in new_request
    self._refresh(request_orig)
  File "/home/ivarghis/googleAppEngine/nodejs-getting-started/1-hello-world/../../../google-cloud-sdk/./lib/third_party/oauth2client/client.py", line 768, in _refresh
    self._do_refresh_request(http_request)
  File "/home/ivarghis/googleAppEngine/nodejs-getting-started/1-hello-world/../../../google-cloud-sdk/./lib/third_party/oauth2client/client.py", line 799, in _do_refresh_request
    self.token_uri, method='POST', body=body, headers=headers)
  File "/home/ivarghis/googleAppEngine/nodejs-getting-started/1-hello-world/../../../google-cloud-sdk/./lib/third_party/httplib2/__init__.py", line 1608, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/home/ivarghis/googleAppEngine/nodejs-getting-started/1-hello-world/../../../google-cloud-sdk/./lib/third_party/httplib2/__init__.py", line 1350, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/home/ivarghis/googleAppEngine/nodejs-getting-started/1-hello-world/../../../google-cloud-sdk/./lib/third_party/httplib2/__init__.py", line 1278, in _conn_request
    raise ServerNotFoundError("Unable to find the server at %s" % conn.host)
ServerNotFoundError: Unable to find the server at accounts.google.com
2016-01-19 23:21:21,412 ERROR    ___FILE_ONLY___ BEGIN CRASH STACKTRACE
Traceback (most recent call last):
  File "/home/ivarghis/google-cloud-sdk/lib/googlecloudsdk/gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  File "/home/ivarghis/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 643, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "/home/ivarghis/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 1401, in Run
    resources = command_instance.Run(args)
  File "/home/ivarghis/google-cloud-sdk/lib/surface/preview/app/deploy.py", line 350, in Run
    deploy_command_util.DoPrepareManagedVms(gae_client)
  File "/home/ivarghis/google-cloud-sdk/lib/googlecloudsdk/api_lib/app/deploy_command_util.py", line 250, in DoPrepareManagedVms
    gae_client.PrepareVmRuntime()
  File "/home/ivarghis/google-cloud-sdk/lib/googlecloudsdk/api_lib/app/appengine_client.py", line 198, in PrepareVmRuntime
    rpcserver.Send('/api/vms/prepare', app_id=self.project)
  File "/home/ivarghis/google-cloud-sdk/lib/googlecloudsdk/api_lib/app/util.py", line 370, in Send
    response = self._server.Send(*args, **kwargs)
  File "/home/ivarghis/google-cloud-sdk/lib/googlecloudsdk/third_party/appengine/tools/appengine_rpc_httplib2.py", line 230, in Send
    url, method=method, body=payload, headers=headers)
  File "/home/ivarghis/googleAppEngine/nodejs-getting-started/1-hello-world/../../../google-cloud-sdk/./lib/third_party/oauth2client/client.py", line 540, in new_request
    self._refresh(request_orig)
  File "/home/ivarghis/googleAppEngine/nodejs-getting-started/1-hello-world/../../../google-cloud-sdk/./lib/third_party/oauth2client/client.py", line 768, in _refresh
    self._do_refresh_request(http_request)
  File "/home/ivarghis/googleAppEngine/nodejs-getting-started/1-hello-world/../../../google-cloud-sdk/./lib/third_party/oauth2client/client.py", line 799, in _do_refresh_request
    self.token_uri, method='POST', body=body, headers=headers)
  File "/home/ivarghis/googleAppEngine/nodejs-getting-started/1-hello-world/../../../google-cloud-sdk/./lib/third_party/httplib2/__init__.py", line 1608, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/home/ivarghis/googleAppEngine/nodejs-getting-started/1-hello-world/../../../google-cloud-sdk/./lib/third_party/httplib2/__init__.py", line 1350, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/home/ivarghis/googleAppEngine/nodejs-getting-started/1-hello-world/../../../google-cloud-sdk/./lib/third_party/httplib2/__init__.py", line 1278, in _conn_request
    raise ServerNotFoundError("Unable to find the server at %s" % conn.host)
ServerNotFoundError: Unable to find the server at accounts.google.com
2016-01-19 23:21:21,413 ERROR    root            gcloud crashed 
(ServerNotFoundError): Unable to find the server at accounts.google.com
2016-01-19 23:21:21,413 INFO     ___FILE_ONLY___ 
If you would like to report this issue, please run the following command:

2016-01-19 23:21:21,413 INFO     ___FILE_ONLY___   gcloud feedback
```

Original issue reported on code.google.com by `iva...@gmail.com` on 20 Jan 2016 at 4:23

**Comment by GoogleCodeExporter** [comment]
```
Thank you for reporting this. To help us understand what may be happening, can 
you please provide the output of `gcloud info` (redacting any private info).
```

Original comment by `vil...@google.com` on 20 Jan 2016 at 6:57
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
Please reopen with more information if you're still experiencing this.
```

Original comment by `z...@google.com` on 18 Feb 2016 at 7:18
- Changed state: **Invalid**
