### ISSUE TITLE
I already had an app.yaml

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#488]
```
Issue running command [gcloud preview app gen].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk/gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  File "googlecloudsdk/calliope/cli.py", line 643, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk/calliope/backend.py", line 1401, in Run
    resources = command_instance.Run(args)
  File "surface/preview/app/gen_config.py", line 98, in Run
    fingerprinting.Params(appinfo=config, custom=args.custom))
  File "googlecloudsdk/api_lib/app/runtimes/fingerprinter.py", line 114, in GenerateConfigs
    module = IdentifyDirectory(path, params)
  File "googlecloudsdk/api_lib/app/runtimes/fingerprinter.py", line 89, in IdentifyDirectory
    configurator = runtime.Fingerprint(path, params)
  File "googlecloudsdk/api_lib/app/runtimes/java.py", line 228, in Fingerprint
    for filename in os.listdir(path):
OSError: [Errno 20] Not a directory: 'app.yaml'

Installation information:

Google Cloud SDK [92.0.0]

Platform: [Mac OS X, x86_64]
Python Version: [2.7.10 (default, Aug 22 2015, 20:33:39)  [GCC 4.2.1 Compatible 
Apple LLVM 7.0.0 (clang-700.0.59.1)]]
Python Location: [/usr/bin/python]
Site Packages: [Disabled]

Installation Root: [/Users/francesco/google-cloud-sdk]
Installed Components:
  core: [2016.01.12]
  core-nix: [2015.11.24]
  gcloud: []
  gsutil-nix: [4.15]
  gsutil: [4.16]
  bq: [2.0.18]
  bq-nix: [2.0.18]
[output truncated]

```

Original issue reported on code.google.com by `francesc...@gmail.com` on 20 Jan 2016 at 8:54

**Comment by GoogleCodeExporter** [comment]
```
Thank you for this feedback.

Can you please provide the full command that you executed (redacting any 
personal info)?

Looks like you may have provided 'app.yaml' as the value for the SOURCE_DIR 
parameter...
```

Original comment by `vil...@google.com` on 20 Jan 2016 at 10:07
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
Please reopen with more information if you're still experiencing this.
```

Original comment by `z...@google.com` on 18 Feb 2016 at 7:18
- Changed state: **Invalid**
