### ISSUE TITLE
ssh key crashed

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#489]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "lib\googlecloudsdk\gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  File "lib\googlecloudsdk\calliope\cli.py", line 643, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "lib\googlecloudsdk\calliope\backend.py", line 1401, in Run
    resources = command_instance.Run(args)
  File "lib\surface\preview\app\deploy.py", line 369, in Run
    config_cleanup)
  File "lib\googlecloudsdk\api_lib\app\deploy_command_util.py", line 193, in BuildAndPushDockerImages
    cli, version_id, remote, project) as docker_client:
  File "lib\googlecloudsdk\api_lib\app\images\docker_util.py", line 236, in __enter__
    self._vm = Provision(self._cli, self._name, self._zone, self._project)
  File "lib\googlecloudsdk\api_lib\app\images\docker_util.py", line 67, in Provision
    vm.CopyCerts()
  File "lib\googlecloudsdk\api_lib\app\images\docker_util.py", line 170, in CopyCerts
    _REMOTE_CERT_FORMAT.format(name=self._name), self.cert_dir])
  File "lib\googlecloudsdk\calliope\cli.py", line 643, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "lib\googlecloudsdk\calliope\backend.py", line 1401, in Run
    resources = command_instance.Run(args)
  File "lib\surface\compute\copy_files.py", line 122, in Run
    instance = self.GetInstance(instance_ref)
  File "lib\googlecloudsdk\api_lib\compute\ssh_utils.py", line 561, in GetInstance
[output truncated]

```

Original issue reported on code.google.com by `cd.uye...@gmail.com` on 21 Jan 2016 at 7:02

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the report. Can you run the command again, then run [gcloud info 
--show-log], and cut&oaste the full stack trace.
```

Original comment by `gsfow...@google.com` on 23 Jan 2016 at 3:30
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
Please reopen with more information if you're still experiencing this.
```

Original comment by `z...@google.com` on 18 Feb 2016 at 7:18
- Changed state: **Invalid**
