### ISSUE TITLE
gcloud crashed

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#492]
```
What steps will reproduce the problem?
use 'gcloud' to connect the remote nodes

What is the expected output? What do you see instead?


Please provide any additional information below.
ERROR: gcloud crashed (SSLHandshakeError): [Errno 1] _ssl.c:499: 
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify 
failed

If you would like to report this issue, please run the following command:
  gcloud feedback

Traceback (most recent call last):
  File "lib/googlecloudsdk/calliope/cli.py", line 609, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "lib/googlecloudsdk/calliope/backend.py", line 1218, in Run
    last_group = context_filter(tool_context, Http, args)
  File "lib/googlecloudsdk/calliope/backend.py", line 580, in ContextFilter
    group.Filter(context, args)
  File "lib/googlecloudsdk/surface/compute/__init__.py", line 53, in Filter
    _DoFilter(context, self.Http(), 'v1', args)
  File "lib/googlecloudsdk/calliope/base.py", line 283, in Http
    return self._http_func(auth=auth, creds=creds, **kwargs)
  File "lib/googlecloudsdk/calliope/backend.py", line 1213, in Http
    **kwargs)
  File "lib/googlecloudsdk/core/cli.py", line 127, in Http
    creds = c_store.Load()
  File "lib/googlecloudsdk/core/credentials/store.py", line 249, in Load
    Refresh(cred)
  File "lib/googlecloudsdk/core/credentials/store.py", line 267, in Refresh
    creds.refresh(http or _Http())
  File "./lib/third_party/oauth2client/client.py", line 597, in refresh
    self._refresh(http.request)
  File "./lib/third_party/oauth2client/client.py", line 780, in _refresh
    self._do_refresh_request(http_request)
  File "./lib/third_party/oauth2client/client.py", line 799, in _do_refresh_request
    self.token_uri, method='POST', body=body, headers=headers)
  File "./lib/third_party/httplib2/__init__.py", line 1608, in request
[output truncated]

```

Original issue reported on code.google.com by `lin....@gmail.com` on 21 Jan 2016 at 8:08

**Comment by GoogleCodeExporter** [comment]
```
solved the issue, after upgrade python to 2.7.11
```

Original comment by `lin....@gmail.com` on 21 Jan 2016 at 8:33

**Comment by GoogleCodeExporter** [comment]
```
Thanks for reporting the solution. What Python version produced the error?
```

Original comment by `gsfow...@google.com` on 23 Jan 2016 at 3:35
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Python 2.7
```

Original comment by `lin....@gmail.com` on 23 Jan 2016 at 4:21
