### ISSUE TITLE
Crashed while creating a dataproc cluster

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#494]
```
Issue running command [gcloud beta dataproc clusters create].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk/calliope/cli.py", line 609, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk/calliope/backend.py", line 1228, in Run
    resources = command_instance.Run(args)
  File "googlecloudsdk/api_lib/dataproc/util.py", line 61, in CatchHTTPErrorRaiseHTTPException
    return func(*args, **kwargs)
  File "googlecloudsdk/surface/dataproc/clusters/create.py", line 208, in Run
    operation = client.projects_clusters.Create(cluster)
  File "googlecloudsdk/third_party/apis/dataproc/v1beta1/dataproc_v1beta1_client.py", line 490, in Create
    config, request, global_params=global_params)
  File "googlecloudsdk/third_party/apitools/base/py/base_api.py", line 650, in _RunMethod
    http_response = http_wrapper.MakeRequest(http, http_request, **opts)
  File "googlecloudsdk/third_party/apitools/base/py/http_wrapper.py", line 302, in MakeRequest
    check_response_func=check_response_func)
  File "googlecloudsdk/third_party/apitools/base/py/http_wrapper.py", line 349, in _MakeRequestNoRetry
    redirections=redirections, connection_type=connection_type)
  File "googlecloudsdk/core/cli.py", line 296, in RequestWithErrHandling
    return orig_request(*args, **kwargs)
  File "oauth2client/client.py", line 562, in new_request
    redirections, connection_type)
  File "googlecloudsdk/core/cli.py", line 264, in RequestWithUserAgentAndTracing
[output truncated]

```

Original issue reported on code.google.com by `mobilepa...@gmail.com` on 23 Jan 2016 at 2:55

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the report. Can you post the error message? 
Also, it would help to see the full stack trace.
Run the command again and cut&paste the stack trace from [gcloud info 
--show-log].
```

Original comment by `gsfow...@google.com` on 23 Jan 2016 at 4:00
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
Please reopen with more information if you're still experiencing this.
```

Original comment by `z...@google.com` on 18 Feb 2016 at 7:19
- Changed state: **Invalid**
