### ISSUE TITLE
Gcloud crashing

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#495]
```
Issue running command [gcloud init].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "lib\googlecloudsdk\gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  File "lib\googlecloudsdk\calliope\cli.py", line 643, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "lib\googlecloudsdk\calliope\backend.py", line 1401, in Run
    resources = command_instance.Run(args)
  File "lib\surface\init.py", line 107, in Run
    self._PickDefaultRegionAndZone()
  File "lib\surface\init.py", line 260, in _PickDefaultRegionAndZone
    project_info = self._RunCmd(['compute', 'project-info', 'describe'])
  File "lib\surface\init.py", line 427, in _RunCmd
    result = self.cli.Execute(args)
  File "lib\googlecloudsdk\calliope\cli.py", line 643, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "lib\googlecloudsdk\calliope\backend.py", line 1391, in Run
    last_group = context_filter(tool_context, Http, args)
  File "lib\googlecloudsdk\calliope\backend.py", line 752, in ContextFilter
    group.Filter(context, args)
  File "lib\surface\compute\__init__.py", line 65, in Filter
    _DoFilter(context, self.Http(), 'v1', args)
  File "lib\googlecloudsdk\calliope\base.py", line 295, in Http
    return self._http_func(auth=auth, creds=creds, **kwargs)
  File "lib\googlecloudsdk\calliope\backend.py", line 1386, in Http
    **kwargs)
  File "lib\googlecloudsdk\core\cli.py", line 139, in Http
    creds = c_store.Load()
[output trunca

```

Original issue reported on code.google.com by `slamdunq...@gmail.com` on 25 Jan 2016 at 10:09
- Merged into: #535

**Comment by GoogleCodeExporter** [comment]
```
Please post the error message and full stack trace from [gcloud info 
--show-log].
```

Original comment by `gsfow...@google.com` on 26 Jan 2016 at 1:08
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
Original comment by `che...@google.com` on 12 Feb 2016 at 2:33
- Changed state: **Duplicate**
