### ISSUE TITLE
gcloud crashed (UnknownRdatatype)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#499]
```
Issue running command [gcloud dns record].

What steps will reproduce the problem?
gcloud dns record-sets transaction remove "123.456.789.012" --name 
"somewhere.jp." --ttl 300 --type "A" --zone zonename --transaction-file 
/tmp/tmp.hlGliGLjbN/transaction.yaml


What is the expected output? What do you see instead?
Expected output:
Not sure, but at least it shouldn't crash

Actual output:
ERROR: gcloud crashed (UnknownRdatatype): 

If you would like to report this issue, please run the following command:
  gcloud feedback

  error: exit status 1

Please provide any additional information below.


Traceback (most recent call last):
  File "lib/google-cloud-sdk/lib/googlecloudsdk/gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  File "lib/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 643, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "lib/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 1401, in Run
    resources = command_instance.Run(args)
  File "lib/google-cloud-sdk/lib/googlecloudsdk/api_lib/dns/util.py", line 58, in CatchHTTPErrorRaiseHTTPException
    return func(*args, **kwargs)
  File "lib/google-cloud-sdk/lib/surface/dns/record_sets/transaction/remove.py", line 71, in Run
    record_to_remove = trans_util.CreateRecordSetFromArgs(args)
  File "lib/google-cloud-sdk/lib/googlecloudsdk/api_lib/dns/transaction_util.py", line 91, in CreateRecordSetFromArgs
    rd_type = rdatatype.from_text(args.type)
  File "bin/../lib/google-cloud-sdk/./lib/third_party/dns/rdatatype.py", line 198, in from_text
    raise UnknownRdatatype
UnknownRdatatype

Installation information:

Google Cloud SDK [93.0.0]

Platform: [Linux, x86_64]
Python Version: [2.7.6 (default, Jun 22 2015, 17:58:13)  [GCC 4.8.2]]
Python Location: [/usr/bin/python2]
Site Packages: [Disabled]

Installation Root: [/usr/lib/google-cloud-sdk]
Installed Components:
  core: [2016.01.14]
  core-nix: [2016.01.14]
  gcloud: []
  gsutil-nix: [4.16]
  beta: [2016.01.14]
[output truncated]

```

Original issue reported on code.google.com by `og...@growaspeople.org` on 27 Jan 2016 at 5:18

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the report. At first glance it looks like its complaining about the 
--type "A" flag. To rule out quoting issues, did you run the command line from 
a shell prompt?
```

Original comment by `gsfow...@google.com` on 27 Jan 2016 at 1:18
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
Please reopen with more information if you're still experiencing this.
```

Original comment by `z...@google.com` on 18 Feb 2016 at 7:19
- Changed state: **Invalid**
