### ISSUE TITLE
proxy authentication failed

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#50]
```
$ gcloud auth login 

Traceback (most recent call last):
  File "/opt/google/google-cloud-sdk/./lib/googlecloudsdk/gcloud/gcloud.py", line 163, in <module>
    main()
  File "/opt/google/google-cloud-sdk/./lib/googlecloudsdk/gcloud/gcloud.py", line 159, in main
    _cli.Execute()
  File "/opt/google/google-cloud-sdk/./lib/googlecloudsdk/calliope/__init__.py", line 1601, in Execute
    post_run_hooks=self.__post_run_hooks, kwargs=kwargs)
  File "/opt/google/google-cloud-sdk/./lib/googlecloudsdk/calliope/__init__.py", line 1152, in _Execute
    pre_run_hooks=pre_run_hooks, post_run_hooks=post_run_hooks)
  File "/opt/google/google-cloud-sdk/./lib/googlecloudsdk/calliope/__init__.py", line 871, in Run
    result = command_instance.Run(args)
  File "/opt/google/google-cloud-sdk/./lib/googlecloudsdk/calliope/exceptions.py", line 78, in TryFunc
    return func(*args, **kwargs)
  File "/opt/google/google-cloud-sdk/lib/googlecloudsdk/gcloud/sdktools/auth/login.py", line 61, in Run
    creds = self.DoWebFlow(args.launch_browser)
  File "/opt/google/google-cloud-sdk/lib/googlecloudsdk/gcloud/sdktools/auth/login.py", line 104, in DoWebFlow
    return c_store.AcquireFromWebFlow(launch_browser=launch_browser)
  File "/opt/google/google-cloud-sdk/./lib/googlecloudsdk/core/credentials/store.py", line 335, in AcquireFromWebFlow
    http=httplib2.Http(disable_ssl_certificate_validation=no_validate))
  File "/opt/google/google-cloud-sdk/./lib/googlecloudsdk/core/credentials/flow.py", line 156, in Run
    credential = flow.step2_exchange(code, http=http)
  File "/opt/google/google-cloud-sdk/./lib/oauth2client/util.py", line 132, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/opt/google/google-cloud-sdk/./lib/oauth2client/client.py", line 1283, in step2_exchange
    headers=headers)
  File "/opt/google/google-cloud-sdk/./lib/httplib2/__init__.py", line 1586, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/opt/google/google-cloud-sdk/./lib/httplib2/__init__.py", line 1333, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/opt/google/google-cloud-sdk/./lib/httplib2/__init__.py", line 1255, in _conn_request
    conn.connect()
  File "/opt/google/google-cloud-sdk/./lib/httplib2/__init__.py", line 1018, in connect
    sock.connect((self.host, self.port))
  File "/opt/google/google-cloud-sdk/./lib/socks/__init__.py", line 431, in connect
    self.__negotiatehttp(destpair[0], destpair[1])
  File "/opt/google/google-cloud-sdk/./lib/socks/__init__.py", line 395, in __negotiatehttp
    raise HTTPError((statuscode, statusline[2]))
socks.HTTPError: (407, 'Proxy Authentication Required')
root@vispmc4791pcx:/home/visfj# gcloud version
Google Cloud SDK 0.9.27

app-engine-go-linux-x86_64 1.9.6
app-engine-python 1.9.6
app-engine-python-extras 1.9.6
bq 2.0.18
bq-nix 2.0.18
compute 2014.06.17
core 2014.06.17
core-nix 2014.06.17
dns 2014.04.30
gae-go 
gae-python 2014.05.06
gcutil 1.16.1
gcutil-nix 1.16.1
gsutil 4.3
gsutil-nix 4.3
sql 2014.06.17


I tried it on Ubuntu 64-bit 14.04. At the company we using a http proxy.
```

Original issue reported on code.google.com by `jfreder...@gmail.com` on 27 Jun 2014 at 1:18

**Comment by GoogleCodeExporter** [comment]
```
The proxy has been configured over export http_proxy=... and https_proxy.
```

Original comment by `jfreder...@gmail.com` on 27 Jun 2014 at 1:19

**Comment by GoogleCodeExporter** [comment]
```
jfrederich,  Thanks for your report.  This does indeed look a like a bug, both 
in terms of functionality and error reporting.  This also appears to have 
something to do with you particular proxy settings.  As a first step,  can you 
check to see if you're still encountering errors with the current release of 
glcoud?
```

Original comment by `jeffvaughan@google.com` on 18 Aug 2014 at 1:53
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
I had same problem.
This patch seems work for me.

```

Original comment by `yoshint2...@gmail.com` on 20 Aug 2014 at 7:01

Attachments:
- [**init**.py.diff](https://storage.googleapis.com/google-code-attachments/google-cloud-sdk/issue-50/comment-3/__init__.py.diff)

**Comment by GoogleCodeExporter** [comment]
```
Yes, that patch is great
```

Original comment by `helmar.c...@gmail.com` on 23 Dec 2014 at 11:02

**Comment by GoogleCodeExporter** [comment]
Original comment by `rdayal@google.com` on 23 Dec 2014 at 5:28
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
The issue is fixed as of latest release.
Use 'gcloud components update' to get the patch.
```

Original comment by `che...@google.com` on 27 Feb 2015 at 7:58
- Changed state: **Fixed**
