### ISSUE TITLE
Google cloud sdk setup help

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#501]
```
Issue running command [gcloud compute ssh].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  File "calliope\cli.py", line 643, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "calliope\backend.py", line 1401, in Run
    resources = command_instance.Run(args)
  File "surface\compute\ssh.py", line 113, in Run
    external_ip_address = self.GetInstanceExternalIpAddress(instance_ref)
AttributeError: 'SshGA' object has no attribute 'GetInstanceExternalIpAddress'

Installation information:

Google Cloud SDK [93.0.0]

Platform: [Windows, x86_64]
Python Version: [2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit 
(Intel)]]
Python Location: [C:\Program Files (x86)\Google\Cloud SDK\python\python.exe]
Site Packages: [Disabled]

Installation Root: [C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk]
Installed Components:
  core: [2016.01.14]
  bq-win: [2.0.18]
  core-win: [2016.01.12]
  gcloud: []
  windows-ssh-tools: [2015.09.21]
  beta: [2016.01.12]
  gsutil: [4.16]
  bq: [2.0.18]
  gsutil-win: [4.16]
[output truncated]

```

Original issue reported on code.google.com by `aamdata2...@gmail.com` on 27 Jan 2016 at 11:55

**Comment by GoogleCodeExporter** [comment]
```
It looks like your gcloud installation may have some out of date or 
incompatible files. Run [gcloud components update] and try again.
```

Original comment by `gsfow...@google.com` on 27 Jan 2016 at 1:33
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
Please reopen with more information if you're still experiencing this.
```

Original comment by `z...@google.com` on 18 Feb 2016 at 7:19
- Changed state: **Invalid**
