### ISSUE TITLE
Crash on login

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#502]
```
Issue running command [gcloud auth login].

What steps will reproduce the problem?

Issue the above command


What is the expected output? What do you see instead?

Expected to log in, instead get and error.

Please provide any additional information below.

My Username contains non ascii characters, I think this will be the error. 
(it's 2016...)


Traceback (most recent call last):
  File "googlecloudsdk\gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  File "googlecloudsdk\calliope\cli.py", line 643, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk\calliope\backend.py", line 1401, in Run
    resources = command_instance.Run(args)
  File "googlecloudsdk\calliope\exceptions.py", line 110, in TryFunc
    return func(*args, **kwargs)
  File "surface\auth\login.py", line 138, in Run
    c_store.Store(creds, account)
  File "googlecloudsdk\core\credentials\store.py", line 309, in Store
    _GetLegacyGen(account, creds).WriteTemplate()
  File "googlecloudsdk\core\credentials\store.py", line 314, in _GetLegacyGen
    multistore_path=config.Paths().LegacyCredentialsMultistorePath(account),
  File "googlecloudsdk\core\config.py", line 639, in LegacyCredentialsMultistorePath
    return os.path.join(self.LegacyCredentialsDir(account), 'multistore.json')
  File "googlecloudsdk\core\config.py", line 628, in LegacyCredentialsDir
    return os.path.join(self.global_config_dir, 'legacy_credentials', account)
  File "C:\python27_x64\lib\ntpath.py", line 85, in join
    result_path = result_path + p_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc1 in position 7: ordinal 
not in range(128)

Installation information:

Google Cloud SDK [93.0.0]

Platform: [Windows, x86_64]
[output truncated]

```

Original issue reported on code.google.com by `jakabada...@gmail.com` on 27 Jan 2016 at 4:09

**Comment by GoogleCodeExporter** [comment]
```
Temp solution is to add "sys.setdefaultencoding('ISO-8859-1')" to the 
python/Lib/ntpath.py file
```

Original comment by `jakabada...@gmail.com` on 27 Jan 2016 at 4:29

**Comment by GoogleCodeExporter** [comment]
```
Issue 569 has been merged into this issue.
```

Original comment by `z...@google.com` on 22 Feb 2016 at 3:49

**Comment by GoogleCodeExporter** [comment]
```
Looks like there's an issue with the fact that the path to your configuration 
directory has non-ASCII characters in it.

To work around, set the CLOUDSDK_CONFIG environment variable to a path that 
contains only ASCII characters.

We'll look into fixing this.
```

Original comment by `z...@google.com` on 22 Feb 2016 at 3:51
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
Issue 580 has been merged into this issue.
```

Original comment by `z...@google.com` on 24 Feb 2016 at 4:27
