### ISSUE TITLE
'gcloud compute config-ssh' crash due to UnicodeDecodeError

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#503]
```
What steps will reproduce the problem?
I'm trying to run 'gcloud compute config-ssh' on a compute engine VM.

What is the expected output? What do you see instead?
I receive the following error message:
ERROR: gcloud crashed (UnicodeDecodeError): 'ascii' codec can't decode byte 
0xe2 in position 1438: ordinal not in range(128)

my username & config directory do not contain non-ascii characters. Any 
suggestions would be appreciated.

What is the output of 'gcloud info'?
Google Cloud SDK [94.0.0]

Platform: [Linux, x86_64]
Python Version: [2.7.11 |Anaconda 2.4.1 (64-bit)| (default, Dec  6 2015, 
18:08:32)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]]
Python Location: [/home/amster_guy/anaconda2/bin/python2]
Site Packages: [Disabled]
Installation Root: [/usr/local/share/google/google-cloud-sdk]
Installed Components:
  core: [2016.01.22]
  core-nix: [2015.11.24]
  gcloud: []
  gsutil-nix: [4.15]
  gsutil: [4.16]
  bq: [2.0.18]
  bq-nix: [2.0.18]
System PATH: 
[/home/amster_guy/anaconda2/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/u
sr/games]
Cloud SDK on PATH: [False]
Installation Properties: [/usr/local/share/google/google-cloud-sdk/properties]
User Config Directory: [/home/amster_guy/.config/gcloud]
User Properties: [/home/amster_guy/.config/gcloud/properties]
Current Workspace: [None]
Workspace Config Directory: [None]
Workspace Properties: [None]
Account: [647333264477-compute@developer.gserviceaccount.com]
Project: [trial1-1135]
Current Properties:
  [core]
    project: [trial1-1135]
    account: [647333264477-compute@developer.gserviceaccount.com]
    disable_usage_reporting: [True]
Logs Directory: [/home/amster_guy/.config/gcloud/logs]
Last Log File: 
[/home/amster_guy/.config/gcloud/logs/2016.01.28/00.37.11.168479.log]

Please provide any additional information below.


```

Original issue reported on code.google.com by `amster....@gmail.com` on 28 Jan 2016 at 12:41

**Comment by GoogleCodeExporter** [comment]
```
I'm adding the information from the log file :

2016-01-28 00:37:11,170 DEBUG    root            Loaded Command Group: 
['gcloud', 'compute']
2016-01-28 00:37:11,302 DEBUG    root            Loaded Command Group: 
['gcloud', 'compute', 'config_ssh']
2016-01-28 00:37:11,322 ERROR    ___FILE_ONLY___ BEGIN CRASH STACKTRACE
Traceback (most recent call last):
  File "/usr/local/share/google/google-cloud-sdk/lib/googlecloudsdk/gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  File "/usr/local/share/google/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 655, in Execute
    print_error=True)
  File "/usr/local/share/google/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 705, in _HandleKnownError
    msg = u'({0}) {1} {2}'.format(command_path_string, unicode(exc),
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1438: 
ordinal not in range(128)
2016-01-28 00:37:11,323 ERROR    root            gcloud crashed 
(UnicodeDecodeError): 'ascii' codec can't decode byte 0xe
2 in position 1438: ordinal not in range(128)
2016-01-28 00:37:11,323 INFO     ___FILE_ONLY___ 
If you would like to report this issue, please run the following command:
2016-01-28 00:37:11,323 INFO     ___FILE_ONLY___   gcloud feedback
```

Original comment by `amster....@gmail.com` on 28 Jan 2016 at 12:49
