### ISSUE TITLE
Unable to deploy

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#504]
```
Issue running command [gcloud preview app deploy].

Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk/gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  File "googlecloudsdk/calliope/cli.py", line 643, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk/calliope/backend.py", line 1402, in Run
    resources = command_instance.Run(args)
  File "surface/preview/app/deploy.py", line 387, in Run
    images.get(module))
  File "googlecloudsdk/api_lib/app/appengine_api_client.py", line 90, in DeployModule
    return operations.WaitForOperation(self.client.apps_operations, operation)
  File "googlecloudsdk/api_lib/app/api/operations.py", line 66, in WaitForOperation
    encoding.MessageToPyValue(completed_operation.error)))
  File "googlecloudsdk/api_lib/app/api/requests.py", line 69, in ExtractErrorMessage
    message=error_details.get('message', '')))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xd7' in position 
118: ordinal not in range(128)

Installation information:

Google Cloud SDK [94.0.0]

Platform: [Mac OS X, x86_64]
Python Version: [2.7.10 (default, Oct 23 2015, 18:05:06)  [GCC 4.2.1 Compatible 
Apple LLVM 7.0.0 (clang-700.0.59.5)]]
Python Location: [/usr/bin/python]
Site Packages: [Disabled]

Installation Root: [/Users/baruch/development/google-cloud-sdk]
Installed Components:
  core: [2016.01.22]
  core-nix: [2015.11.24]
  gcloud: []
  gsutil-nix: [4.15]
  gsutil: [4.16]
[output truncated]

```

Original issue reported on code.google.com by `bar...@hyraxbio.co.za` on 28 Jan 2016 at 10:45

**Comment by GoogleCodeExporter** [comment]
```
Issue 534 has been merged into this issue.
```

Original comment by `z...@google.com` on 10 Feb 2016 at 8:51

**Comment by GoogleCodeExporter** [comment]
```
This will likely be fixed when #509 is fixed, which should be soon.
```

Original comment by `z...@google.com` on 10 Feb 2016 at 8:52
