### ISSUE TITLE
Issue running command [gcloud container clusters get].

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#506]
```
Issue running command [gcloud container clusters get].

What steps will reproduce the problem?
running the command

What is the expected output? What do you see instead?
the credentials

Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk/gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  File "googlecloudsdk/calliope/cli.py", line 643, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk/calliope/backend.py", line 1402, in Run
    resources = command_instance.Run(args)
  File "surface/container/clusters/get_credentials.py", line 65, in Run
    util.ClusterConfig.Persist(cluster, cluster_ref.projectId, self.cli)
  File "googlecloudsdk/api_lib/container/util.py", line 283, in Persist
    if auth.clientCertificate and auth.clientKey and auth.clusterCaCertificate:
AttributeError: 'NoneType' object has no attribute 'clientCertificate'

Installation information:

Google Cloud SDK [94.0.0]

Platform: [Linux, x86_64]
Python Version: [2.7.6 (default, Jun 22 2015, 17:58:13)  [GCC 4.8.2]]
Python Location: [/usr/bin/python2]
Site Packages: [Disabled]

Installation Root: [/home/daniel/google-cloud-sdk]
Installed Components:
  kubectl: []
  core-nix: [2015.11.24]
  core: [2016.01.22]
  gcloud: []
  gsutil-nix: [4.15]
  gsutil: [4.16]
  bq: [2.0.18]
  kubectl-linux-x86_64: [1.1.4]
  bq-nix: [2.0.18]
System PATH: 
[/home/daniel/google-cloud-sdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr
/bin:/sbin:/bin:/usr/games:/usr/local/games]
Cloud SDK on PATH: [True]

[output truncated]

```

Original issue reported on code.google.com by `dd...@learnerator.com` on 28 Jan 2016 at 7:17

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the report. I've opened an internal issue to track this.
```

Original comment by `dlor...@google.com` on 28 Jan 2016 at 7:28
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
Thanks! We've identified the issue and are working on a fix.
```

Original comment by `dlor...@google.com` on 29 Jan 2016 at 7:13
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
We have a fix ready that should go out in the next release. In the meantime, 
this error is caused by
running the command from a client that does not have edit permission on the 
project. Fix the permission and the error will go away.
```

Original comment by `dlor...@google.com` on 1 Feb 2016 at 9:21

**Comment by GoogleCodeExporter** [comment]
```
The fix should be out. Please re-open if you're still experiencing.
```

Original comment by `z...@google.com` on 18 Feb 2016 at 8:15
- Changed state: **Fixed**
