### ISSUE TITLE
Node JS integration keeps crashing

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#507]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "lib/googlecloudsdk/gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  File "lib/googlecloudsdk/calliope/cli.py", line 643, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "lib/googlecloudsdk/calliope/backend.py", line 1402, in Run
    resources = command_instance.Run(args)
  File "lib/surface/preview/app/deploy.py", line 369, in Run
    config_cleanup)
  File "lib/googlecloudsdk/api_lib/app/deploy_command_util.py", line 193, in BuildAndPushDockerImages
    cli, version_id, remote, project) as docker_client:
  File "lib/googlecloudsdk/api_lib/app/images/docker_util.py", line 243, in __enter__
    return containers.NewDockerClient(local=(not self._remote), **kwargs)
  File "lib/googlecloudsdk/api_lib/app/containers.py", line 139, in NewDockerClient
    client = NewDockerClientNoCheck(**kwargs)
  File "lib/googlecloudsdk/api_lib/app/containers.py", line 122, in NewDockerClientNoCheck
    return docker.Client(**kwargs)
  File "./lib/third_party/docker/docker/client.py", line 77, in __init__
    self._version = self._retrieve_server_version()
  File "./lib/third_party/docker/docker/client.py", line 97, in _retrieve_server_version
    'Error while fetching server API version: {0}'.format(e)
DockerException: Error while fetching server API version: ('Connection 
aborted.', error(60, 'Operation timed out'))

Installation information:

[output truncated]

```

Original issue reported on code.google.com by `nedmi...@mdsol.com` on 28 Jan 2016 at 8:06
- Merged into: #469

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 24 Feb 2016 at 7:22
- Changed state: **Duplicate**
