### ISSUE TITLE
Tried to follow tutorial

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#508]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?
I followed the steps in this tutorial:
https://cloud.google.com/nodejs/getting-started/using-cloud-sql

The hello world tutorial I did first was doing as expected.
https://cloud.google.com/nodejs/getting-started/hello-world


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "lib\googlecloudsdk\gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  File "lib\googlecloudsdk\calliope\cli.py", line 643, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "lib\googlecloudsdk\calliope\backend.py", line 1402, in Run
    resources = command_instance.Run(args)
  File "lib\surface\preview\app\deploy.py", line 369, in Run
    config_cleanup)
  File "lib\googlecloudsdk\api_lib\app\deploy_command_util.py", line 204, in BuildAndPushDockerImages
    info.file, docker_client, image_name)
  File "lib\googlecloudsdk\api_lib\app\deploy_command_util.py", line 278, in BuildAndPushDockerImage
    image.Build(docker_client)
  File "lib\googlecloudsdk\api_lib\app\docker_image.py", line 110, in Build
    nocache=self._nocache, rm=self._rm, pull=False)
  File "bin\..\./lib\third_party\docker\docker\api\build.py", line 49, in build
    context = utils.tar(path, exclude=exclude, dockerfile=dockerfile)
  File "bin\..\./lib\third_party\docker\docker\utils\utils.py", line 86, in tar
    t.add(os.path.join(root, path), arcname=path, recursive=False)
  File "C:\python27_x64\lib\tarfile.py", line 2000, in add
    tarinfo = self.gettarinfo(name, arcname)
  File "C:\python27_x64\lib\tarfile.py", line 1872, in gettarinfo
    statres = os.lstat(name)
[output truncated]

```

Original issue reported on code.google.com by `OddPaa...@gmail.com` on 29 Jan 2016 at 12:24

**Comment by GoogleCodeExporter** [comment]
```
I think this is an unfortunate problem caused by the way node.js vendors 
dependencies and the Windows max file length path. Basically, node.js installs 
dependencies in very long folder structures which can get too long to be 
addressed.

Can you try this?
npm install -g npm@3.7

The new version of npm vendors packages differently, which might help here.
```

Original comment by `dlor...@google.com` on 1 Feb 2016 at 4:48

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the suggestion!

I had a bad feeling about that file length myself, but I don't really know what 
to change to pack in a less complicated structure :-(

The 3.7 version didn't help

-----

So you want to continue (Y/n)?  y

Beginning deployment...

Verifying that Managed VMs are enabled and ready.
Provisioning remote build service.
Copying certificates for secure access. You may be prompted to create an SSH 
keypair.
Building and pushing image for module [default]
----------------------------------------------------- DOCKER BUILD OUTPUT 
------------------------------------------------------
Beginning teardown of remote build environment (this may take a few seconds).
ERROR: gcloud crashed (WindowsError): [Error 3] Systemet finner ikke angitt 
bane: 
'C:\\Users\\Odd\\Dropbox\\cola\\nodejs-getting-started\\2-structured-data\\node_
modules\\gcloud\\node_modules\\gce-images\\node_modules\\google-auto-auth\\node_
modules\\google-auth-library\\node_modules\\gtoken\\node_modules\\google-p12-pem
\\node_modules\\node-forge\\build-flash.xml'

If you would like to report this issue, please run the following command:
  gcloud feedback
Deleted 
[https://www.googleapis.com/compute/v1/projects/skilled-fulcrum-120422/zones/us-
central1-f/instances/gae-builder-vm-20160201t180417].
```

Original comment by `OddPaa...@gmail.com` on 1 Feb 2016 at 5:09

**Comment by GoogleCodeExporter** [comment]
```
The Norwegian text "Systemet finner ikke angitt bane:" translates to "System 
cannot find path:"
```

Original comment by `OddPaa...@gmail.com` on 1 Feb 2016 at 5:10
