### ISSUE TITLE
gcloud crash!! Not able to clone.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#510]
```
Issue running command [gcloud beta init].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk/gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  File "googlecloudsdk/calliope/cli.py", line 643, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk/calliope/backend.py", line 1402, in Run
    resources = command_instance.Run(args)
  File "surface/init.py", line 109, in Run
    self._PickRepo(project_id)
  File "surface/init.py", line 361, in _PickRepo
    self._CloneRepo(repo_name)
  File "surface/init.py", line 387, in _CloneRepo
    self._RunCmd(['source', 'repos', 'clone'], [repo_name, clone_path])
  File "surface/init.py", line 427, in _RunCmd
    result = self.cli.Execute(args)
  File "googlecloudsdk/calliope/cli.py", line 643, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk/calliope/backend.py", line 1402, in Run
    resources = command_instance.Run(args)
  File "googlecloudsdk/calliope/exceptions.py", line 110, in TryFunc
    return func(*args, **kwargs)
  File "surface/source/repos/clone.py", line 92, in Run
    dry_run=args.dry_run)
  File "googlecloudsdk/api_lib/source/git.py", line 273, in Clone
    self._RunCommand(cmd, dry_run)
  File "googlecloudsdk/api_lib/source/git.py", line 289, in _RunCommand
    subprocess.check_call(cmd)
  File "/usr/lib64/python2.6/subprocess.py", line 505, in check_call
    raise CalledProcessError(retcode, cmd)
[output truncated]

```

Original issue reported on code.google.com by `comco...@gmail.com` on 30 Jan 2016 at 10:24

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the report.

[gcloud init] calls [gcloud source repos clone] which in turn shells out to git.
In fact you can run [gcloud source repos clone] with --dry-run flag to see 
exactly what git command is called.

Even though clone part of gcloud init failed the command itself still succeeded.
Unfortunately the stack-trace in your report got truncated to determine what 
has happened when git command was run. Can you replicate the issue and attach 
output of
  gcloud info --show-log

```

Original comment by `che...@google.com` on 1 Feb 2016 at 3:01
- Changed state: **NeedsMoreInfo**
