### ISSUE TITLE
crash on gcloud auth login

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#511]
```
Issue running command [gcloud auth login].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "lib/googlecloudsdk/gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  File "lib/googlecloudsdk/calliope/cli.py", line 643, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "lib/googlecloudsdk/calliope/backend.py", line 1402, in Run
    resources = command_instance.Run(args)
  File "lib/googlecloudsdk/calliope/exceptions.py", line 110, in TryFunc
    return func(*args, **kwargs)
  File "lib/surface/auth/login.py", line 126, in Run
    creds = self.DoWebFlow(args.launch_browser)
  File "lib/surface/auth/login.py", line 191, in DoWebFlow
    return c_store.AcquireFromWebFlow(launch_browser=launch_browser)
  File "lib/googlecloudsdk/core/credentials/store.py", line 401, in AcquireFromWebFlow
    http=_Http())
  File "lib/googlecloudsdk/core/credentials/flow.py", line 170, in Run
    credential = flow.step2_exchange(code, http=http)
  File "./lib/third_party/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "./lib/third_party/oauth2client/client.py", line 1993, in step2_exchange
    headers=headers)
  File "./lib/third_party/httplib2/__init__.py", line 1609, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "./lib/third_party/httplib2/__init__.py", line 1351, in _request
[output truncated]

```

Original issue reported on code.google.com by `tamari...@gmail.com` on 30 Jan 2016 at 7:07

**Comment by GoogleCodeExporter** [comment]
```
Could you please attach the full stack trace?
```

Original comment by `dlor...@google.com` on 1 Feb 2016 at 4:37
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
The problem disappeared when I updated Python. Thanks for replying!
```

Original comment by `tamari...@gmail.com` on 1 Feb 2016 at 4:38

**Comment by GoogleCodeExporter** [comment]
```
Thanks for following up!
```

Original comment by `z...@google.com` on 18 Feb 2016 at 7:08
- Changed state: **Invalid**
