### ISSUE TITLE
cloud crashed while connecting to the compute instance

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#515]
```
What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "lib/googlecloudsdk/gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  File "lib/googlecloudsdk/calliope/cli.py", line 643, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "lib/googlecloudsdk/calliope/backend.py", line 1391, in Run
    last_group = context_filter(tool_context, Http, args)
  File "lib/googlecloudsdk/calliope/backend.py", line 752, in ContextFilter
    group.Filter(context, args)
  File "lib/surface/compute/__init__.py", line 65, in Filter
    _DoFilter(context, self.Http(), 'v1', args)
  File "lib/googlecloudsdk/calliope/base.py", line 295, in Http
    return self._http_func(auth=auth, creds=creds, **kwargs)
  File "lib/googlecloudsdk/calliope/backend.py", line 1386, in Http
    **kwargs)
  File "lib/googlecloudsdk/core/cli.py", line 139, in Http
    creds = c_store.Load()
  File "lib/googlecloudsdk/core/credentials/store.py", line 261, in Load
    Refresh(cred)
  File "lib/googlecloudsdk/core/credentials/store.py", line 279, in Refresh
    creds.refresh(http or _Http())
  File "./lib/third_party/oauth2client/client.py", line 597, in refresh
    self._refresh(http.request)
  File "./lib/third_party/oauth2client/client.py", line 780, in _refresh
    self._do_refresh_request(http_request)
  File "./lib/third_party/oauth2client/client.py", line 799, in _do_refresh_request
    self.token_uri, method='POST', body=body, headers=headers)
[output truncated]

```

Original issue reported on code.google.com by `nisgu...@gmail.com` on 2 Feb 2016 at 2:55

**Comment by GoogleCodeExporter** [comment]
```
Issues such as this are usually related to network problems.  Do you experience 
it consistently? Do you have any unusual network/firewall/proxy settings?

Please provide a full stack trace in order to help us fully diagnose.
```

Original comment by `z...@google.com` on 18 Feb 2016 at 7:05
- Changed state: **NeedsMoreInfo**
