### ISSUE TITLE
gcloud connectivity issue from gcloud sdk

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#517]
```
Issue running command [gcloud init].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "lib\googlecloudsdk\calliope\cli.py", line 609, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "lib\googlecloudsdk\calliope\backend.py", line 1228, in Run
    resources = command_instance.Run(args)
  File "lib\googlecloudsdk\surface\init.py", line 92, in Run
    self._PickDefaultRegionAndZone()
  File "lib\googlecloudsdk\surface\init.py", line 241, in _PickDefaultRegionAndZone
    project_info = self._RunCmd(['compute', 'project-info', 'describe'])
  File "lib\googlecloudsdk\surface\init.py", line 391, in _RunCmd
    result = self.cli.Execute(args)
  File "lib\googlecloudsdk\calliope\cli.py", line 609, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "lib\googlecloudsdk\calliope\backend.py", line 1218, in Run
    last_group = context_filter(tool_context, Http, args)
  File "lib\googlecloudsdk\calliope\backend.py", line 580, in ContextFilter
    group.Filter(context, args)
  File "lib\googlecloudsdk\surface\compute\__init__.py", line 53, in Filter
    _DoFilter(context, self.Http(), 'v1', args)
  File "lib\googlecloudsdk\calliope\base.py", line 283, in Http
    return self._http_func(auth=auth, creds=creds, **kwargs)
  File "lib\googlecloudsdk\calliope\backend.py", line 1213, in Http
    **kwargs)
  File "lib\googlecloudsdk\core\cli.py", line 127, in Http
    creds = c_store.Load()
[output truncated]

```

Original issue reported on code.google.com by `manish.o...@gmail.com` on 3 Feb 2016 at 8:32
- Merged into: #535

**Comment by GoogleCodeExporter** [comment]
Original comment by `che...@google.com` on 12 Feb 2016 at 2:34
- Changed state: **Duplicate**
