### ISSUE TITLE
gcloud preview app leads to Connection broken: IncompleteRead ProtocolError

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#518]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?
Run "sudo gcloud preview app deploy app.yaml --docker-build remote"

What is the expected output? What do you see instead?

Expected instance to run, encountered error message after npm install

Please provide any additional information below.

Site Packages: [Disabled]

Installation Root: [/Users/karl/google-cloud-sdk]
Installed Components:
  core: [2015.12.16]
  core-nix: [2015.11.24]
  gcloud: []
  gsutil-nix: [4.15]
  gsutil: [4.16]
  bq: [2.0.18]
  bq-nix: [2.0.18]
System PATH: 
[/Users/karl/google-cloud-sdk/bin:/usr/local/sbin:/Users/karl/.composer/vendor/b
in:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin]
Cloud SDK on PATH: [True]

Installation Properties: [/Users/karl/google-cloud-sdk/properties]
User Config Directory: [/Users/karl/.config/gcloud]
User Properties: [/Users/karl/.config/gcloud/properties]
Current Workspace: [None]
Workspace Config Directory: [None]
Workspace Properties: [None]

Account: [karl@cookadlib.com]
Project: [cookadlib-2016]

Current Properties:
  [core]
    project: [cookadlib-2016]
    account: [karl@cookadlib.com]
    disable_usage_reporting: [False]
  [app]
    promote_by_default: [true]
    suppress_change_warning: [true]
  [compute]
    region: [europe-west1-d]
    zone: [europe-west1-d]

Logs Directory: [/Users/karl/.config/gcloud/logs]
Last Log File: [/Users/karl/.config/gcloud/logs/2016.02.02/15.33.05.961191.log]


app.yaml contents:
api_version: 1
runtime: custom
vm: true
handlers:
- url: /.*
  script: server.js
  secure: optional
skip_files:
 - ^node_modules$


Dockerfile contents:
FROM node:latest

MAINTAINER Karl Podger <karl@cookadlib.com>

WORKDIR /tmp

ADD package.json package.json

ADD *.js ./

ADD *.json ./

ADD .* ./

ADD app app

RUN npm install

EXPOSE 8080

WORKDIR .

ENTRYPOINT ["node", "server.js"]

server.js contents:
'use strict';

var appengine = require('appengine');
var express = require('express');

var app = express();

app.use(appengine.middleware.base);

app.get('/', function(req, res) {
  res.status(200).send('Hello, world!');
});

var server = app.listen(process.env.PORT || 8080, function() {
  var host = this.address().address;
  var port = this.address().port;

  console.log('App listening at http://%s:%s', host, port);
});

Traceback (most recent call last):
  File "lib/googlecloudsdk/calliope/cli.py", line 609, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "lib/googlecloudsdk/calliope/backend.py", line 1228, in Run
    resources = command_instance.Run(args)
  File "lib/googlecloudsdk/surface/preview/app/deploy.py", line 256, in Run
    remote_build)
  File "lib/googlecloudsdk/api_lib/app/deploy_command_util.py", line 177, in BuildAndPushDockerImages
    info.file, docker_client, image_name)
  File "lib/googlecloudsdk/api_lib/app/deploy_command_util.py", line 248, in BuildAndPushDockerImage
    image.Build(docker_client)
  File "lib/googlecloudsdk/api_lib/app/docker_image.py", line 105, in Build
    for line in build_res:
  File "./lib/third_party/docker/docker/client.py", line 213, in _stream_helper
    data = reader.read(1)
  File "./lib/third_party/requests/packages/urllib3/response.py", line 231, in read
    raise ProtocolError('Connection broken: %r' % e, e)
ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', 
IncompleteRead(0 bytes read))

Installation information:

Google Cloud SDK [91.0.1]

Platform: [Mac OS X, x86_64]
Python Version: [2.7.11 (default, Dec  5 2015, 14:44:53)  [GCC 4.2.1 Compatible 
Apple LLVM 7.0.0 (clang-700.1.76)]]
Python Location: 
[/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/Resour
ces/Python.app/Contents/MacOS/Python]
[output truncated]

```

Original issue reported on code.google.com by `karl.pod...@primeordinal.com` on 3 Feb 2016 at 9:45
- Merged into: #549

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 18 Feb 2016 at 7:03
- Changed state: **Duplicate**
