### ISSUE TITLE
gcloud/gsutil failing with a "Server presented certificate that does not match host www.googleapis.com" error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#519]
```
Issue running command [gcloud init].
Running gcloud/gsutil fails with a "Server presented certificate that does not 
match host www.googleapis.com" error

What steps will reproduce the problem?
gcloud init
gsutil cp -Rn XXXX gs://bucketname/

What is the expected output? What do you see instead?
I expect my environment to be initialized or my file to be copied up to the 
Google cloud

Please provide any additional information below.
The gsutil cp command worked fine last night.

Traceback (most recent call last):
  File "lib/googlecloudsdk/gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  File "lib/googlecloudsdk/calliope/cli.py", line 643, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "lib/googlecloudsdk/calliope/backend.py", line 1402, in Run
    resources = command_instance.Run(args)
  File "lib/surface/init.py", line 107, in Run
    self._PickDefaultRegionAndZone()
  File "lib/surface/init.py", line 260, in _PickDefaultRegionAndZone
    project_info = self._RunCmd(['compute', 'project-info', 'describe'])
  File "lib/surface/init.py", line 427, in _RunCmd
    result = self.cli.Execute(args)
  File "lib/googlecloudsdk/calliope/cli.py", line 643, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "lib/googlecloudsdk/calliope/backend.py", line 1402, in Run
    resources = command_instance.Run(args)
  File "lib/googlecloudsdk/api_lib/compute/base_classes.py", line 750, in Run
    resources = list(self.ComputeDynamicProperties(args, resources))
  File "lib/googlecloudsdk/api_lib/compute/lister.py", line 52, in ProcessResults
    for resource in resources:
  File "lib/googlecloudsdk/api_lib/compute/lister.py", line 24, in _ConvertProtobufsToDicts
    for resource in resources:
  File "lib/googlecloudsdk/api_lib/compute/request_helper.py", line 146, in MakeRequests
    requests=requests, http=http, batch_url=batch_url)
[output truncated]

```

Original issue reported on code.google.com by `wcob...@us.westfield.com` on 3 Feb 2016 at 12:39

**Comment by GoogleCodeExporter** [comment]
```
While we should handle this error more nicely, it does indicate a real problem. 
We attempt to access www.googleapis.com, but our request is somehow being 
intercepted (perhaps by a captive portal). Are you able to directly access 
www.googleapis.com, using ex. `curl https://www.googleapis.com/` (this will 
give you an error page, but not an SSL-related error).
```

Original comment by `z...@google.com` on 18 Feb 2016 at 7:02
- Changed state: **NeedsMoreInfo**
