### ISSUE TITLE
Internal error when setting project

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#52]
```
What steps will reproduce the problem?
gcloud config set project <my-project-id>

Working on ubuntu VM.

What is the expected output? What do you see instead?
jonas25007@vbox-ub1:~$ gcloud config set project steel-spark-625
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 504, in run
  File "/home/jonas25007/google-cloud-sdk/./lib/googlecloudsdk/core/metrics.py", line 133, in __Run
  File "/home/jonas25007/google-cloud-sdk/./lib/googlecloudsdk/core/metrics.py", line 184, in __SendEvent
  File "/home/jonas25007/google-cloud-sdk/./lib/httplib2/__init__.py", line 1586, in request
  File "/home/jonas25007/google-cloud-sdk/./lib/httplib2/__init__.py", line 1333, in _request
  File "/home/jonas25007/google-cloud-sdk/./lib/httplib2/__init__.py", line 1257, in _conn_request
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'timeout'
jonas25007@vbox-ub1:~$ python --version
Python 2.7.3


What is the output of 'gcloud version'?
Google Cloud SDK 0.9.27

app-engine-python 1.9.6
app-engine-python-extras 1.9.6
bq 2.0.18
bq-nix 2.0.18
compute 2014.06.17
core 2014.06.17
core-nix 2014.06.17
dns 2014.04.30
gae-python 2014.05.06
gcutil 1.16.1
gcutil-nix 1.16.1
gsutil 4.3
gsutil-nix 4.3
sql 2014.06.17


Please provide any additional information below.


```

Original issue reported on code.google.com by `gilbert....@gmail.com` on 28 Jun 2014 at 7:08

**Comment by GoogleCodeExporter** [comment]
```
Upgrade your python version to solve your problem.

sudo apt-get upgrade

$ python --version
Python 2.7.6

damphat@my-ubuntu:~/my-project-id/default$ git pull
Already up-to-date.

```

Original comment by `damp...@gmail.com` on 30 Dec 2014 at 7:18

**Comment by GoogleCodeExporter** [comment]
```
Make sure to upgrade to Google Cloud SDK latest version, which is 0.9.76.
Please reopen if this is still an issue.

```

Original comment by `che...@google.com` on 8 Sep 2015 at 3:46
- Changed state: **Obsolete**
