### ISSUE TITLE
gcloud crashes

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#523]
```
Issue running command [gcloud compute instances create].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk/gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  File "googlecloudsdk/calliope/cli.py", line 646, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk/calliope/backend.py", line 1402, in Run
    resources = command_instance.Run(args)
  File "googlecloudsdk/api_lib/compute/base_classes.py", line 1064, in Run
    request_protobufs = self.CreateRequests(args)
  File "googlecloudsdk/surface/compute/instances/create.py", line 425, in CreateRequests
  File "googlecloudsdk/api_lib/compute/scope_prompter.py", line 315, in CreateZonalReferences
    prefix_filter=region_filter)
  File "googlecloudsdk/api_lib/compute/scope_prompter.py", line 289, in CreateScopedReferences
    prefix_filter=prefix_filter)
  File "googlecloudsdk/api_lib/compute/scope_prompter.py", line 149, in PromptForScope
    attribute, service, flag_names, prefix_filter))
  File "googlecloudsdk/api_lib/compute/scope_prompter.py", line 102, in FetchChoiceResources
    choices = [resource for resource in global_resources]
  File "googlecloudsdk/api_lib/compute/request_helper.py", line 138, in MakeRequests
    requests=requests, http=http, batch_url=batch_url, errors=errors):
  File "googlecloudsdk/api_lib/compute/request_helper.py", line 56, in _List
    batch_url=batch_url)
  File "googlecloudsdk/api_lib/compute/batch_helper.py", line 42, in MakeRequests
[output truncated]

```

Original issue reported on code.google.com by `tama...@google.com` on 7 Feb 2016 at 10:36

**Comment by GoogleCodeExporter** [comment]
```
Thanks for reporting this. Unfortunately, we aren't able to diagnose without 
more information. Can you please post the full stacktrace?
```

Original comment by `z...@google.com` on 18 Feb 2016 at 6:58
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
I am not sure what I can post more, but I just had another crash, here is the 
stack:

Issue running command [gcloud compute images list].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk/gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  [...]
    self._Execute(http)
  File "googlecloudsdk/third_party/apitools/base/py/batch.py", line 425, in _Execute
    response = http_wrapper.MakeRequest(http, request)
  File "googlecloudsdk/third_party/apitools/base/py/http_wrapper.py", line 332, in MakeRequest
    check_response_func=check_response_func)
  File "googlecloudsdk/third_party/apitools/base/py/http_wrapper.py", line 381, in _MakeRequestNoRetry
    redirections=redirections, connection_type=connection_type)
  File "googlecloudsdk/core/cli.py", line 330, in RequestWithErrHandling
    return orig_request(*args, **kwargs)
  File "oauth2client/client.py", line 562, in new_request
    redirections, connection_type)
  File "googlecloudsdk/core/cli.py", line 298, in RequestWithUserAgentAndTracing
    return orig_request(*modified_args, **kwargs)
  File "httplib2/__init__.py", line 1610, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "httplib2/__init__.py", line 1352, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "httplib2/__init__.py", line 1272, in _conn_request
    conn.connect()
  File "httplib2/__init__.py", line 928, in connect
    raise socket.error, msg
[output truncated]

```

Original comment by `tama...@google.com` on 22 Feb 2016 at 6:08

**Comment by GoogleCodeExporter** [comment]
```
When you run `gcloud feedback`, it should print out all of the truncated output 
to the terminal. You can also grab the log file in 
~/.config/gcloud/logs/[date]/[time].log. Either of those would be very helpful.
```

Original comment by `z...@google.com` on 22 Feb 2016 at 3:56
