### ISSUE TITLE
Not able to deploy the sample code on compute engine with mysql

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#524]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "lib/googlecloudsdk/gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  File "lib/googlecloudsdk/calliope/cli.py", line 643, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "lib/googlecloudsdk/calliope/backend.py", line 1402, in Run
    resources = command_instance.Run(args)
  File "lib/surface/preview/app/deploy.py", line 369, in Run
    config_cleanup)
  File "lib/googlecloudsdk/api_lib/app/deploy_command_util.py", line 204, in BuildAndPushDockerImages
    info.file, docker_client, image_name)
  File "lib/googlecloudsdk/api_lib/app/deploy_command_util.py", line 278, in BuildAndPushDockerImage
    image.Build(docker_client)
  File "lib/googlecloudsdk/api_lib/app/docker_image.py", line 110, in Build
    nocache=self._nocache, rm=self._rm, pull=False)
  File "./lib/third_party/docker/docker/api/build.py", line 49, in build
    context = utils.tar(path, exclude=exclude, dockerfile=dockerfile)
  File "./lib/third_party/docker/docker/utils/utils.py", line 86, in tar
    t.add(os.path.join(root, path), arcname=path, recursive=False)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tarfile.py", line 2015, in add
    with bltn_open(name, "rb") as f:
IOError: [Errno 13] Permission denied: '/Users/kartikdomadiya/.mysql_history'

Installation information:

Google Cloud SDK [94.0.0]

Platform: [Mac OS X, x86_64]
[output truncated]

```

Original issue reported on code.google.com by `kartik.d...@searce.com` on 7 Feb 2016 at 1:27

**Comment by GoogleCodeExporter** [comment]
```
Are you running `gcloud preview app deploy` in your home directory? You must 
have read access to all of the files in your current directory in order to 
deploy an application.

In general, you should create a directory for your application and put all its 
related files there. That's where you should run `gcloud preview app deploy` 
from.
```

Original comment by `z...@google.com` on 16 Feb 2016 at 11:12
- Changed state: **NeedsMoreInfo**
