### ISSUE TITLE
Error deploying Bookself app to Google Cloud Platform.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#527]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?
Deployment to Google Cloud Platform: gcloud preview app deploy.

What is the expected output? What do you see instead?
Expected output is successful deployment to the cloud platform. What I'm 
getting is Error 3: gcloud crashed in the Docker Build Output.

Please provide any additional information below.

====== [TRUNCATED MESSAGE] ======
WindowsError: [Error 3] The system cannot find the path specified: 'C:\\Users\\B
in\\Desktop\\nodejs-getting-started\\2-structured-data\\node_modules\\gcloud\\no
de_modules\\gce-images\\node_modules\\google-auto-auth\\node_modules\\google-aut
h-library\\node_modules\\gtoken\\node_modules\\google-p12-pem\\node_modules\\nod
e-forge\\flash\\PooledSocket.as'

Installation information:

Google Cloud SDK [94.0.0]

Platform: [Windows, x86_64]
Python Version: [2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD
64)]]
Python Location: [C:\python27_x64\python.exe]
Site Packages: [Disabled]

Installation Root: [C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk]
Installed Components:
  core: [2016.01.22]
  bq-win: [2.0.18]
  core-win: [2016.01.12]
  gcloud: []
  windows-ssh-tools: [2015.09.21]
  gsutil: [4.16]
  gsutil-win: [4.16]
  bq: [2.0.18]
System PATH: [C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\bi
n\sdk;C:\python27_x64\;C:\python27_x64\Scripts;C:\ProgramData\Oracle\Java\javapa
th;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\
;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\Win
dowsPowerShell\v1.0\;C:\Program Files (x86)\Acer\abFiles\;C:\Program Files\Intel
\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Manag
ement Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Eng
ine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Compo
nents\IPT;C:\Program Files\nodejs\;C:\Program Files (x86)\Heroku\bin;C:\Program
Files (x86)\git\cmd;C:\Program Files\MATLAB\R2015b\bin;C:\Program Files (x86)\Sk
ype\Phone\;C:\Program Files (x86)\MySQL\MySQL Fabric 1.5 ]
Cloud SDK on PATH: [False]

Installation Properties: [C:\Program Files (x86)\Google\Cloud SDK\google-cloud-s
dk\properties]
User Config Directory: [C:\Users\Bin\AppData\Roaming\gcloud]
User Properties: [C:\Users\Bin\AppData\Roaming\gcloud\properties]
Current Workspace: [None]
Workspace Config Directory: [None]
Workspace Properties: [None]

Account: [binxu.nyc@gmail.com]
Project: [nodejstest-1215]

Current Properties:
  [core]
    project: [nodejstest-1215]
    account: [binxu.nyc@gmail.com]
    disable_usage_reporting: [True]
  [app]
    suppress_change_warning: [true]

Logs Directory: [C:\Users\Bin\AppData\Roaming\gcloud\logs]
Last Log File: [C:\Users\Bin\AppData\Roaming\gcloud\logs\2016.02.08\13.55.38.396
000.log]

====== [END TRUNCATED MESSAGE] =======

Traceback (most recent call last):
  File "lib\googlecloudsdk\gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  File "lib\googlecloudsdk\calliope\cli.py", line 643, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "lib\googlecloudsdk\calliope\backend.py", line 1402, in Run
    resources = command_instance.Run(args)
  File "lib\surface\preview\app\deploy.py", line 369, in Run
    config_cleanup)
  File "lib\googlecloudsdk\api_lib\app\deploy_command_util.py", line 204, in BuildAndPushDockerImages
    info.file, docker_client, image_name)
  File "lib\googlecloudsdk\api_lib\app\deploy_command_util.py", line 278, in BuildAndPushDockerImage
    image.Build(docker_client)
  File "lib\googlecloudsdk\api_lib\app\docker_image.py", line 110, in Build
    nocache=self._nocache, rm=self._rm, pull=False)
  File "bin\..\./lib\third_party\docker\docker\api\build.py", line 49, in build
    context = utils.tar(path, exclude=exclude, dockerfile=dockerfile)
  File "bin\..\./lib\third_party\docker\docker\utils\utils.py", line 86, in tar
    t.add(os.path.join(root, path), arcname=path, recursive=False)
  File "C:\python27_x64\lib\tarfile.py", line 2000, in add
    tarinfo = self.gettarinfo(name, arcname)
  File "C:\python27_x64\lib\tarfile.py", line 1872, in gettarinfo
    statres = os.lstat(name)
[output truncated]

```

Original issue reported on code.google.com by `binxu....@gmail.com` on 8 Feb 2016 at 7:01
- Merged into: #496

**Comment by GoogleCodeExporter** [comment]
```
It appears as though you're running into the MAX_PATH limitation on Windows 
(<https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).asp
x>). We're looking into ways to work around this on our end. As a workaround, 
you can move your application into a folder with a shorter absolute name. 
Something like `C:\Users\Bin\n` should work.
```

Original comment by `z...@google.com` on 16 Feb 2016 at 11:11
- Changed state: **Duplicate**
