### ISSUE TITLE
ginit crashes

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#535]
```
Issue running command [gcloud init].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "lib\googlecloudsdk\gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  File "lib\googlecloudsdk\calliope\cli.py", line 646, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "lib\googlecloudsdk\calliope\backend.py", line 1402, in Run
    resources = command_instance.Run(args)
  File "lib\surface\init.py", line 107, in Run
    self._PickDefaultRegionAndZone()
  File "lib\surface\init.py", line 257, in _PickDefaultRegionAndZone
    project_info = self._RunCmd(['compute', 'project-info', 'describe'])
  File "lib\surface\init.py", line 424, in _RunCmd
    result = self.cli.Execute(args)
  File "lib\googlecloudsdk\calliope\cli.py", line 646, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "lib\googlecloudsdk\calliope\backend.py", line 1392, in Run
    last_group = context_filter(tool_context, Http, args)
  File "lib\googlecloudsdk\calliope\backend.py", line 753, in ContextFilter
    group.Filter(context, args)
  File "lib\surface\compute\__init__.py", line 65, in Filter
    _DoFilter(context, self.Http(), 'v1', args)
  File "lib\googlecloudsdk\calliope\base.py", line 397, in Http
    return self._http_func(auth=auth, creds=creds, **kwargs)
  File "lib\googlecloudsdk\calliope\backend.py", line 1387, in Http
    **kwargs)
  File "lib\googlecloudsdk\core\cli.py", line 139, in Http
    creds = c_store.Load()
[output trunca

```

Original issue reported on code.google.com by `faisalcl...@gmail.com` on 11 Feb 2016 at 11:38

**Comment by GoogleCodeExporter** [comment]
```
Thanks for reporting the issue.

During [gcloud init] did you have o type in project name or you were presented 
with a list to choose from?

Does the project you entered/selected in [gcloud init] have "Compute Engine 
APIs" enabled?
See 
https://console.cloud.google.com/apis/api/compute_component/overview?project=YOU
R_PROJECT_NAME

After this command fails can you attach content of log files, which you can 
locate with
  gcloud info --format='json(logs.last_logs)'
this will help debug this issue further.

```

Original comment by `che...@google.com` on 12 Feb 2016 at 2:33
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
Issue 495 has been merged into this issue.
```

Original comment by `che...@google.com` on 12 Feb 2016 at 2:33

**Comment by GoogleCodeExporter** [comment]
```
Issue 517 has been merged into this issue.
```

Original comment by `che...@google.com` on 12 Feb 2016 at 2:34
