### ISSUE TITLE
gcloud preview app deploy -- ERROR: (gcloud.preview.app.deploy) Unable to copy certificates.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#536]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Installation information:

Google Cloud SDK [95.0.0]

Platform: [Windows, x86_64]
Python Version: [2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit 
(AMD64)]]
Python Location: [C:\python27_x64\python.exe]
Site Packages: [Disabled]

Installation Root: [D:\mir\Google_SDK\google-cloud-sdk]
Installed Components:
  core: [2016.01.29]
  bq-win: [2.0.18]
  core-win: [2016.01.12]
  gcloud: []
  windows-ssh-tools: [2016.01.29]
  gsutil: [4.16]
  gsutil-win: [4.16]
  bq: [2.0.18]
System PATH: 
[D:\mir\Google_SDK\google-cloud-sdk\bin\..\bin\sdk;C:\python27_x64\;C:\python27_
x64\Scripts;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\S
ystem32\WindowsPowerShell\v1.0\;D:\mir\my_gittortise\bin;C:\Program 
Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft\Web 
Platform Installer\;D:\mir\my_pyth3;D:\mir\my_pyth3\Scripts;D:\mir\my_git\Git; 
D:\mir\my_git\Git\bin;D:\mir\Google_SDK\google-cloud-sdk\bin]
Cloud SDK on PATH: [True]

Installation Properties: [D:\mir\Google_SDK\google-cloud-sdk\properties]
User Config Directory: [C:\Users\FGMir\AppData\Roaming\gcloud]
User Properties: [C:\Users\FGMir\AppData\Roaming\gcloud\properties]
Current Workspace: [None]
Workspace Config Directory: [None]
Workspace Properties: [None]

Account: [faisalcloud.acc@gmail.com]
Project: [simpletest-1217]
[outpu

```

Original issue reported on code.google.com by `faisalcl...@gmail.com` on 11 Feb 2016 at 1:03

**Comment by GoogleCodeExporter** [comment]
```
Thanks for reporting this issue. It's a Windows-related problem that should be 
fixed in Cloud SDK 97.0.0, available now. Please comment if you're still 
experiencing this with the latest version.
```

Original comment by `z...@google.com` on 18 Feb 2016 at 6:25
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Still not working for me:

Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "lib\googlecloudsdk\gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  File "lib\googlecloudsdk\calliope\cli.py", line 646, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "lib\googlecloudsdk\calliope\backend.py", line 1394, in Run
    resources = command_instance.Run(args)
  File "lib\surface\preview\app\deploy.py", line 482, in Run
    config_cleanup)
  File "lib\googlecloudsdk\api_lib\app\deploy_command_util.py", line 199, in BuildAndPushDockerImages
    cli, version_id, remote, project) as docker_client:
  File "lib\googlecloudsdk\api_lib\app\images\docker_util.py", line 237, in __enter__
    kwargs = containers.KwargsFromEnv(self._vm.host, self._vm.cert_dir, True)
  File "lib\googlecloudsdk\api_lib\app\containers.py", line 100, in KwargsFromEnv
    assert_hostname=False)
  File "bin\..\lib\third_party\docker\docker\tls.py", line 46, in __init__
    'Path to a certificate and key files must be provided'
TLSParameterError: Path to a certificate and key files must be provided through 
the client_config param. TLS configurations should map the Docker CLI client 
configurations. See http://docs.docker.com/examples/https/ for API details.

Installation information:

Google Cloud SDK [97.0.0]

Platform: [Windows, x86_64]
Python Version: [2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit 
(Intel)]]
Python Location: [C:\python27\python.exe]
[output truncated]

```

Original comment by `jens.sch...@gmail.com` on 19 Feb 2016 at 10:45

**Comment by GoogleCodeExporter** [comment]
```
#2: You're experiencing a separate issue. See 
https://code.google.com/p/google-cloud-sdk/issues/detail?id=559
```

Original comment by `z...@google.com` on 19 Feb 2016 at 5:47

**Comment by GoogleCodeExporter** [comment]
```
Well the error I see in the console is the headline of this issue. But thanks 
for the link.
```

Original comment by `jens.sch...@gmail.com` on 19 Feb 2016 at 5:53
