### ISSUE TITLE
Managed VM deploy crash

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#537]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "lib/googlecloudsdk/gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  File "lib/googlecloudsdk/calliope/cli.py", line 646, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "lib/googlecloudsdk/calliope/backend.py", line 1402, in Run
    resources = command_instance.Run(args)
  File "lib/surface/preview/app/deploy.py", line 381, in Run
    config_cleanup)
  File "lib/googlecloudsdk/api_lib/app/deploy_command_util.py", line 193, in BuildAndPushDockerImages
    docker.UpdateDockerCredentials(registry_host)
  File "lib/googlecloudsdk/core/docker/docker.py", line 145, in UpdateDockerCredentials
    store.Refresh(cred)
  File "lib/googlecloudsdk/core/credentials/store.py", line 279, in Refresh
    creds.refresh(http or _Http())
  File "./lib/third_party/oauth2client/client.py", line 597, in refresh
    self._refresh(http.request)
  File "./lib/third_party/oauth2client/client.py", line 780, in _refresh
    self._do_refresh_request(http_request)
  File "./lib/third_party/oauth2client/client.py", line 799, in _do_refresh_request
    self.token_uri, method='POST', body=body, headers=headers)
  File "./lib/third_party/httplib2/__init__.py", line 1610, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "./lib/third_party/httplib2/__init__.py", line 1352, in _request
[output truncated]

```

Original issue reported on code.google.com by `elli...@tenthousandcoffees.com` on 11 Feb 2016 at 5:01

**Comment by GoogleCodeExporter** [comment]
```
Do you mind posting the remainder of the stack trace?

Is this issue still reproducible?
```

Original comment by `z...@google.com` on 18 Feb 2016 at 6:23
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
I reported this issue because I noticed terabytes of PD's on my gcloud
invoice that were allocated because of gcloud builder instances that were
not torn down properly. Since then I have not noticed the issue again. If I
do experience this issue again I will be sure to provide a complete stack
trace. Sorry about that.

-- 

*Elliott Garcea | Director of Engineering*

25 Brant Street, 2nd Floor

Toronto, ON M5V 2L9

*519-212-4847*

*Invite me for Coffee
<http://www.tenthousandcoffees.com/profile/elliott-garcea>*
```

Original comment by `elli...@tenthousandcoffees.com` on 18 Feb 2016 at 6:31

**Comment by GoogleCodeExporter** [comment]
```
Thanks. This is relatively difficult to diagnose without the full stacktrace, 
but related to a class of problems that we're actively working on.
```

Original comment by `z...@google.com` on 18 Feb 2016 at 8:19
- Changed state: **WontFix**
