### ISSUE TITLE
gcloud crash

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#539]
```
Issue running command [gcloud alpha source captures upload].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk/gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  File "googlecloudsdk/calliope/cli.py", line 646, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk/calliope/backend.py", line 1402, in Run
    resources = command_instance.Run(args)
  File "surface/source/captures/upload.py", line 84, in Run
    args.target_path)
  File "googlecloudsdk/api_lib/source/capture.py", line 266, in UploadCapture
    return self._PopulateCapture(capture, workspace, src_name, target_root)
  File "googlecloudsdk/api_lib/source/capture.py", line 291, in _PopulateCapture
    workspace, src_name, target_root)
  File "googlecloudsdk/api_lib/source/capture.py", line 182, in _AddSourceDirToWorkspace
    workspace.WriteFile(os.path.join(target_root, path), contents)
  File "googlecloudsdk/api_lib/source/source.py", line 429, in WriteFile
    self.FlushPendingActions(check_size_threshold=True)
  File "googlecloudsdk/api_lib/source/source.py", line 374, in FlushPendingActions
    self._client.projects_repos_workspaces.ModifyWorkspace(request))
  File "googlecloudsdk/third_party/apis/source/v1/source_v1_client.py", line 861, in ModifyWorkspace
    config, request, global_params=global_params)
  File "googlecloudsdk/third_party/apitools/base/py/base_api.py", line 706, in _RunMethod
    http, http_request, **opts)
File "googlecloudsdk/third_party/apitools/base/py/http_wrapper.py", line 332, 
in MakeRequest
    check_response_func=check_response_func)
  File "googlecloudsdk/third_party/apitools/base/py/http_wrapper.py", line 387, in _MakeRequestNoRetry
    check_response_func(response)
  File "googlecloudsdk/third_party/apitools/base/py/http_wrapper.py", line 217, in CheckResponse
    raise exceptions.BadStatusCodeError.FromResponse(response)
BadStatusCodeError: HttpError accessing 
<https://source.googleapis.com/v1/projects/dragongame-dev/repos/google-source-ca
ptures/workspaces/google%2F_capture%2F59FCC3E7368B110199C90A9B168DEAE82069147C:m
odifyWorkspace?alt=json>: response: <{'status': '504', 'alternate-protocol': 
'443:quic,p=1', 'content-length': '140', 'x-xss-protection': '1; mode=block', 
'x-content-type-options': 'nosniff', 'transfer-encoding': 'chunked', 'vary': 
'Origin, X-Origin, Referer', 'server': 'ESF', '-content-encoding': 'gzip', 
'cache-control': 'private', 'date': 'Thu, 11 Feb 2016 21:33:45 GMT', 
'x-frame-options': 'SAMEORIGIN', 'alt-svc': 'quic=":443"; ma=604800; 
v="30,29,28,27,26,25"', 'content-type': 'application/json; charset=UTF-8'}>, 
content <{
  "error": {
    "code": 504,
    "message": "Deadline expired before operation could complete.",
    "status": "DEADLINE_EXCEEDED"
  }
}
>

Installation information:

Google Cloud SDK [95.0.0]

Platform: [Mac OS X, x86_64]
Python Version: [2.7.9 (default, Dec 20 2014, 13:46:58)  [GCC 4.2.1 Compatible 
Apple LLVM 6.0 (clang-600.0.56)]]
Python Location: 
[/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/Resourc
es/Python.app/Contents/MacOS/Python]
Site Packages: [Disabled]

Installation Root: [/Users/cgoody/google-cloud-sdk]
Installed Components:
  core: [2016.01.29]
  app-engine-python: [1.9.31]
  core-nix: [2015.11.24]
  kubectl: []
  gcloud: []
  gsutil-nix: [4.15]
  beta: [2016.01.12]
  gsutil: [4.16]
  bq: [2.0.18]
  alpha: [2016.01.12]
  bq-nix: [2.0.18]
  kubectl-darwin-x86_64: [1.1.4]
System PATH: 
[/Users/cgoody/google-cloud-sdk/bin:/usr/local/sbin:/usr/local/bin:/usr/local/bi
n:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/bin:/Users/cgoody/bin:/Users/c
goody/gsutil:/Applications/Xcode.app/Contents/Developer/../Applications/Applicat
ion Loader.app/Contents/MacOS/itms/bin]
Cloud SDK on PATH: [True]

Installation Properties: [/Users/cgoody/google-cloud-sdk/properties]
User Config Directory: [/Users/cgoody/.config/gcloud]
User Properties: [/Users/cgoody/.config/gcloud/properties]
Current Workspace: [None]
Workspace Config Directory: [None]
Workspace Properties: [None]

Account: [cgoody@backflipstudios.com]
Project: [backflipstudios.com:backflip-gcp]

Current Properties:
  [core]
    project: [backflipstudios.com:backflip-gcp]
    account: [cgoody@backflipstudios.com]
    disable_usage_reporting: [True]
  [app]
    suppress_change_warning: [true]
  [compute]
    region: [asia-east1]
    zone: [asia-east1-a]

Logs Directory: [/Users/cgoody/.config/gcloud/logs]
Last Log File: 
[/Users/cgoody/.config/gcloud/logs/2016.02.11/14.32.44.312934.log]

```

Original issue reported on code.google.com by `cgo...@backflipstudios.com` on 11 Feb 2016 at 9:36

**Comment by GoogleCodeExporter** [comment]
```
This looks like a temporary network hiccup. Is it reproducible if you try again?
```

Original comment by `z...@google.com` on 18 Feb 2016 at 6:21
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
Hi,

This appeared to happen 100% of the time running the command.  We have a
few large files so I'm assuming that we just hit a timeout.
```

Original comment by `cgo...@backflipstudios.com` on 22 Feb 2016 at 10:12

**Comment by GoogleCodeExporter** [comment]
```
Makes sense. The backend team is aware of this issue. We're looking into 
identifying a root cause.
```

Original comment by `z...@google.com` on 22 Feb 2016 at 10:13
- Changed state: **Accepted**
