### ISSUE TITLE
"gcloud deployment-manager manifests describe" crashes on non ascii characters

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#541]
```
Issue running command [gcloud deployment].

What steps will reproduce the problem?
Ran describing a manifest on a deployment of a marketplace solution.
$ gcloud deployment-manager manifests describe manifest-1455236560043 
--deployment cui-edb-postgres-enterprise-1

What is the expected output? What do you see instead?

ERROR: gcloud crashed (UnicodeEncodeError): 'ascii' codec can't encode 
character u'\xae' in position 1211: ordinal not in range(128)



Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk/gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  File "googlecloudsdk/calliope/cli.py", line 643, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk/calliope/backend.py", line 1403, in Run
    display.Displayer(command_instance, args, resources).Display()
  File "googlecloudsdk/calliope/display.py", line 368, in Display
    self._command.Display(self._args, self._resources)
  File "surface/deployment_manager/manifests/describe.py", line 98, in Display
    out=log.out)
  File "googlecloudsdk/core/resource_printer.py", line 490, in Print
    formatter.PrintSingleRecord(_MakeSerializable(resources))
  File "googlecloudsdk/core/resource_printer.py", line 183, in PrintSingleRecord
    record = self._UpdateTypesForOutput(record)
  File "googlecloudsdk/core/resource_printer.py", line 155, in _UpdateTypesForOutput
    val[key] = self._UpdateTypesForOutput(val[key])
  File "googlecloudsdk/core/resource_printer.py", line 151, in _UpdateTypesForOutput
    val[i] = self._UpdateTypesForOutput(val[i])
  File "googlecloudsdk/core/resource_printer.py", line 155, in _UpdateTypesForOutput
    val[key] = self._UpdateTypesForOutput(val[key])
  File "googlecloudsdk/core/resource_printer.py", line 148, in _UpdateTypesForOutput
    return YamlPrinter._LiteralString(val)
[output truncated]

```

Original issue reported on code.google.com by `huyhu...@google.com` on 12 Feb 2016 at 12:41
- Merged into: #509

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 18 Feb 2016 at 6:20
- Changed state: **Duplicate**
