### ISSUE TITLE
Python encoding error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#542]
```
Issue running command [gcloud compute ssh].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk\gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  File "googlecloudsdk\calliope\cli.py", line 643, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk\calliope\backend.py", line 1402, in Run
    resources = command_instance.Run(args)
  File "surface\compute\ssh.py", line 142, in Run
    ssh_args.append(ssh_utils.UserHost(user, external_ip_address))
  File "googlecloudsdk\api_lib\compute\ssh_utils.py", line 75, in UserHost
    return user + '@' + host
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf3 in position 5: ordinal 
not in range(128)

Installation information:

Google Cloud SDK [94.0.0]

Platform: [Windows, x86_64]
Python Version: [2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit 
(AMD64)]]
Python Location: [C:\python27_x64\python.exe]
Site Packages: [Disabled]

Installation Root: [C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk]
Installed Components:
  core: [2016.01.22]
  bq-win: [2.0.18]
  core-win: [2016.01.12]
  gcloud: []
  windows-ssh-tools: [2015.09.21]
  gsutil: [4.16]
  gsutil-win: [4.16]
  bq: [2.0.18]
[output truncated]

```

Original issue reported on code.google.com by `kristofe...@gmail.com` on 12 Feb 2016 at 10:47
- Merged into: #477

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 12 Feb 2016 at 11:33
- Changed state: **Duplicate**
