### ISSUE TITLE
glcoud crash issue

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#544]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk/gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  File "googlecloudsdk/calliope/cli.py", line 646, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk/calliope/backend.py", line 1402, in Run
    resources = command_instance.Run(args)
  File "surface/preview/app/deploy.py", line 300, in Run
    config_cleanup = configurator.GenerateConfigs()
AttributeError: 'NoneType' object has no attribute 'GenerateConfigs'

Installation information:

Google Cloud SDK [96.0.0]

Platform: [Mac OS X, x86_64]
Python Version: [2.7.10 (default, Oct 23 2015, 19:19:21)  [GCC 4.2.1 Compatible 
Apple LLVM 7.0.0 (clang-700.0.59.5)]]
Python Location: [/usr/bin/python]
Site Packages: [Disabled]

Installation Root: [/Users/Steve/Dev/gcloud/google-cloud-sdk]
Installed Components:
  core: [2016.02.05]
  core-nix: [2016.02.05]
  gcloud: []
  gsutil-nix: [4.15]
  gsutil: [4.16]
  bq: [2.0.18]
  bq-nix: [2.0.18]
[output truncated]

```

Original issue reported on code.google.com by `etienne....@gmail.com` on 14 Feb 2016 at 4:27

**Comment by GoogleCodeExporter** [comment]
```
Thanks for reporting this! This message indicates that we were unable to 
automatically detect what type of app you were deploying. As a workaround, 
please create an app.yaml file for your application manually.
```

Original comment by `z...@google.com` on 18 Feb 2016 at 5:55
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
This particular issue should be fixed in Cloud SDK 99.0.0, which is not yet 
released.
```

Original comment by `z...@google.com` on 18 Feb 2016 at 8:11
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
Issue 593 has been merged into this issue.
```

Original comment by `z...@google.com` on 25 Feb 2016 at 9:39

**Comment by GoogleCodeExporter** [comment]
```
Issue 616 has been merged into this issue.
```

Original comment by `z...@google.com` on 2 Mar 2016 at 2:46

**Comment by GoogleCodeExporter** [comment]
```
99.0.0 is out now. Please re-open if you're still experiencing this with 99.0.0.
```

Original comment by `z...@google.com` on 4 Mar 2016 at 6:07
- Changed state: **Fixed**
