### ISSUE TITLE
gcloud alpha ml --help crashes

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#545]
```
What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk/gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  [...]
  File "googlecloudsdk/calliope/backend.py", line 322, in _get_values
    return super(ArgumentParser, self)._get_values(action, arg_strings)
  File "third_party/argparse/__init__.py", line 2229, in _get_values
    self._check_value(action, value[0])
  File "googlecloudsdk/calliope/backend.py", line 180, in _check_value
    if is_subparser and action.IsValidChoice(value):
  File "googlecloudsdk/calliope/backend.py", line 364, in IsValidChoice
    return self._calliope_command.IsValidSubElement(choice)
  File "googlecloudsdk/calliope/backend.py", line 1243, in IsValidSubElement
    return bool(self.LoadSubElement(name))
  File "googlecloudsdk/calliope/backend.py", line 1281, in LoadSubElement
    self._config_hooks, parent_group=self, allow_empty=allow_empty)
  File "googlecloudsdk/calliope/backend.py", line 1098, in __init__
    self._GetModuleFromPath(module_dir, module_path, path, construction_id),
  File "googlecloudsdk/calliope/backend.py", line 1016, in _GetModuleFromPath
    name_to_give, os.path.join(module_dir, *module_path))
  File "googlecloudsdk/core/util/pkg_resources.py", line 108, in GetModuleFromPath
    module = imp.load_module(name_to_give, f, file_path, items)
  File "surface/ml/__init__.py", line 82, in <module>
    resources.ClientDef(
CommandLoadFailure: Problem loading gcloud.alpha.ml: 'module' object has no 
attribute 'ClientDef'.
[output truncated]

```

Original issue reported on code.google.com by `bryn...@spotify.com` on 15 Feb 2016 at 11:37
- Merged into: #543

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 16 Feb 2016 at 11:01
- Changed state: **Duplicate**
