### ISSUE TITLE
I am trying to create a node js application for Atlassian Connect Plugin

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#549]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk/gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  [...]
  File "surface/preview/app/deploy.py", line 381, in Run
    config_cleanup)
  File "googlecloudsdk/api_lib/app/deploy_command_util.py", line 210, in BuildAndPushDockerImages
    info.file, docker_client, image_name)
  File "googlecloudsdk/api_lib/app/deploy_command_util.py", line 284, in BuildAndPushDockerImage
    image.Build(docker_client)
  File "googlecloudsdk/api_lib/app/docker_image.py", line 110, in Build
    nocache=self._nocache, rm=self._rm, pull=False)
  File "third_party/docker/docker/api/build.py", line 97, in build
    timeout=timeout,
  File "third_party/docker/docker/client.py", line 107, in _post
    return self.post(url, **self._set_request_timeout(kwargs))
  File "third_party/requests/sessions.py", line 507, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "third_party/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "third_party/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "third_party/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))

[output truncated]

```

Original issue reported on code.google.com by `vikashku...@gmail.com` on 17 Feb 2016 at 4:31

**Comment by GoogleCodeExporter** [comment]
```
"Connection reset by peer" indicates a network hiccup, usually temporary.

Is this issue reproducible?
```

Original comment by `z...@google.com` on 18 Feb 2016 at 6:12
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
This is the plugin I cloned from here 
https://bitbucket.org/atlassianlabs/connect-jira-activity/src

And did some require changes in the respective files. You can try deploying 
this on google cloud and you should see the same error.

Regards,
Vikash Kumar
```

Original comment by `vikashku...@gmail.com` on 18 Feb 2016 at 6:26

**Comment by GoogleCodeExporter** [comment]
```
Issue 518 has been merged into this issue.
```

Original comment by `z...@google.com` on 18 Feb 2016 at 7:03
