### ISSUE TITLE
ArchLinux, gcloud deployment-manager deployments list

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#550]
```
Issue running command [gcloud deployment].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk/gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  [...]
  File "googlecloudsdk/third_party/apitools/base/py/base_api.py", line 586, in __ProcessHttpResponse
    raise exceptions.HttpError.FromResponse(http_response)
HttpError: HttpError accessing 
<https://www.googleapis.com/deploymentmanager/v2/projects/wirelesssimulator/glob
al/deployments?alt=json&maxResults=500>: response: <{'status': '403', 
'alternate-protocol': '443:quic,p=1', 'content-length': '568', 
'x-xss-protection': '1; mode=block', 'x-content-type-options': 'nosniff', 
'transfer-encoding': 'chunked', 'expires': 'Wed, 17 Feb 2016 05:25:01 GMT', 
'vary': 'Origin, X-Origin', 'server': 'GSE', '-content-encoding': 'gzip', 
'cache-control': 'private, max-age=0', 'date': 'Wed, 17 Feb 2016 05:25:01 GMT', 
'x-frame-options': 'SAMEORIGIN', 'alt-svc': 'quic=":443"; ma=2592000; 
v="30,29,28,27,26,25"', 'content-type': 'application/json; charset=UTF-8'}>, 
content <{
 "error": {
  "errors": [
   {
    "domain": "usageLimits",
    "reason": "accessNotConfigured",
    "message": "Access Not Configured. The API (Google Cloud Deployment Manager API) is not enabled for your project. Please use the Google Developers Console to update your configuration.",
[output truncated]

```

Original issue reported on code.google.com by `ssendilk...@gmail.com` on 17 Feb 2016 at 5:26

**Comment by GoogleCodeExporter** [comment]
```
Thanks for reporting this. It indicates that you have not enabled the Google 
Cloud Deployment Manager API for your project. Please go to 
https://console.developers.google.com and search for and enable it under "API 
Manager" 

(We are working on a way of enabling this automatically, but for now do not 
have the ability.)
```

Original comment by `z...@google.com` on 18 Feb 2016 at 5:53
- Changed state: **WorkingAsIntended**
