### ISSUE TITLE
[gcloud dns record] 'NoneType' object is not iterable` error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#551]
```
Issue running command [gcloud dns record].

What steps will reproduce the problem?
gcloud dns record-sets transaction remove -z example-zone --name 
*.dev.example.com. --ttl 21600 --type A 1.2.3.4

What is the expected output? What do you see instead?
Expected to see a message stating that the record set has been removed. But got 
`ERROR: gcloud crashed (TypeError): 'NoneType' object is not iterable` message

Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk/gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  File "googlecloudsdk/calliope/cli.py", line 646, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk/calliope/backend.py", line 1402, in Run
    resources = command_instance.Run(args)
  File "googlecloudsdk/api_lib/dns/util.py", line 58, in CatchHTTPErrorRaiseHTTPException
    return func(*args, **kwargs)
  File "surface/dns/record_sets/transaction/remove.py", line 64, in Run
    change = trans_util.ChangeFromYamlFile(trans_file)
  File "googlecloudsdk/api_lib/dns/transaction_util.py", line 74, in ChangeFromYamlFile
    change.additions = _RecordSetsFromDictionaries(change_dict['additions'])
  File "googlecloudsdk/api_lib/dns/transaction_util.py", line 51, in _RecordSetsFromDictionaries
    for record_set_dict in record_set_dictionaries:
TypeError: 'NoneType' object is not iterable

Installation information:

Google Cloud SDK [96.0.0]

Platform: [Mac OS X, x86_64]
Python Version: [2.7.11 (default, Dec 26 2015, 17:47:53)  [GCC 4.2.1 Compatible 
Apple LLVM 7.0.2 (clang-700.1.81)]]
Python Location: 
[/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/Resour
ces/Python.app/Contents/MacOS/Python]
Site Packages: [Disabled]

Installation Root: 
[/opt/homebrew-cask/Caskroom/google-cloud-sdk/latest/google-cloud-sdk]
Installed Components:
[output truncated]

```

Original issue reported on code.google.com by `dhilipsiva` on 17 Feb 2016 at 12:49

**Comment by GoogleCodeExporter** [comment]
```
This message indicates corruption in your transaction.yaml file. Please abort 
the transaction and start again.

We'll look into making a better message.
```

Original comment by `z...@google.com` on 18 Feb 2016 at 3:35
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
This issue will result in a better error starting in the 99.0.0 release of the 
Cloud SDK.
```

Original comment by `z...@google.com` on 18 Feb 2016 at 9:51
- Changed state: **Started**
