### ISSUE TITLE
gsutil ImportError: No module named gce

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#552]
```
What steps will reproduce the problem?

Installing gsutil with pip stopped working on 2016-02-16 after pip package 
oauth2client 2.0 was published.

https://pypi.python.org/pypi/oauth2client/2.0.0


What is the expected output? What do you see instead?

Traceback (most recent call last):
  File "/usr/bin/gsutil", line 9, in <module>
    load_entry_point('gsutil==4.16', 'console_scripts', 'gsutil')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 568, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2720, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2380, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2386, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/gslib/__main__.py", line 53, in <module>
    from gslib import wildcard_iterator
  File "/usr/lib/python2.7/site-packages/gslib/wildcard_iterator.py", line 37, in <module>
    from gslib.translation_helper import GenerationFromUrlAndString
  File "/usr/lib/python2.7/site-packages/gslib/translation_helper.py", line 25, in <module>
    from apitools.base.py import encoding
  File "/usr/lib/python2.7/site-packages/apitools/base/py/__init__.py", line 20, in <module>
    from apitools.base.py.base_api import *
  File "/usr/lib/python2.7/site-packages/apitools/base/py/base_api.py", line 33, in <module>
    from apitools.base.py import credentials_lib
  File "/usr/lib/python2.7/site-packages/apitools/base/py/credentials_lib.py", line 28, in <module>
    import oauth2client.gce
ImportError: No module named gce


What is the output of 'gcloud info'?


Please provide any additional information below.

Could fix it by:

$ pip uninstall oauth2client
$ pip install oauth2client==1.5.2




```

Original issue reported on code.google.com by `camil.bl...@gmail.com` on 17 Feb 2016 at 12:58

**Comment by GoogleCodeExporter** [comment]
```
Thanks for reporting this! gsutil issues are tracked here: 
https://github.com/GoogleCloudPlatform/gsutil/issues

In fact, this issue has been filed: 
https://github.com/GoogleCloudPlatform/gsutil/issues/330

Please track it there.
```

Original comment by `z...@google.com` on 18 Feb 2016 at 3:44
- Changed state: **Invalid**
