### ISSUE TITLE
WindowsError: [Error 32] The process cannot access the file because it is being used by another process

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#554]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?
Following the node.js bookshelf starter app on step 2 using the datastore
Have set - gcloud config set app/use_cloud_build True


What is the expected output? What do you see instead?
Can't deploy
Expected to have app provisioned instead get the error...

Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk\gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  File "googlecloudsdk\calliope\cli.py", line 646, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk\calliope\backend.py", line 1402, in Run
    resources = command_instance.Run(args)
  File "surface\preview\app\deploy.py", line 381, in Run
    config_cleanup)
  File "googlecloudsdk\api_lib\app\deploy_command_util.py", line 189, in BuildAndPushDockerImages
    code_bucket, cloudbuild_client, http)
  File "googlecloudsdk\api_lib\app\deploy_command_util.py", line 236, in _BuildImagesWithCloudBuild
    cloud_build.UploadSource(image.dockerfile_dir, source_gcs_uri)
  File "googlecloudsdk\api_lib\app\cloud_build.py", line 100, in UploadSource
    shutil.rmtree(temp_dir)
  File "C:\Program Files (x86)\Python27\lib\shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "C:\Program Files (x86)\Python27\lib\shutil.py", line 250, in rmtree
    os.remove(fullname)
WindowsError: [Error 32] The process cannot access the file because it is being 
used by another process: 
'c:\\users\\bran1\\appdata\\local\\temp\\tmp0jk7bl\\src.tgz'

Installation information:

Google Cloud SDK [96.0.0]

Platform: [Windows, x86_64]
Python Version: [2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC 
v.1500 32 bit (Intel)]]
[output truncated]

```

Original issue reported on code.google.com by `bful...@ledavont.com` on 17 Feb 2016 at 5:21

**Comment by GoogleCodeExporter** [comment]
```
The message here means that some other process is trying to access the source 
files as you're uploading them. Is this reproducible?
```

Original comment by `z...@google.com` on 18 Feb 2016 at 3:46
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
Yes, it was reproducible by following the steps outlined here:
https://cloud.google.com/nodejs/getting-started/using-cloud-datastore

Specifically, the step about deploying the app to gcloud.

$ gcloud preview app deploy


I tried multiple times. I tried logging off and then retrying. I even tried
restarting the system and then retrying. None of which affected the result
or the error.
```

Original comment by `bful...@ledavont.com` on 19 Feb 2016 at 12:52

**Comment by GoogleCodeExporter** [comment]
```
Is there any chance that you have antivirus software or something similar that 
would be scanning your disk? The files that Windows cannot delete are temporary 
files in a directory only gcloud should know about.
```

Original comment by `z...@google.com` on 19 Feb 2016 at 5:51

**Comment by GoogleCodeExporter** [comment]
```
Issue 596 has been merged into this issue.
```

Original comment by `z...@google.com` on 28 Feb 2016 at 10:51

**Comment by GoogleCodeExporter** [comment]
```
You marked as duplicate and did not provide a resolution.
I still cannot upload. How ever I uploaded once (first time) after few days I 
got this error.
```

Original comment by `induwara...@gmail.com` on 29 Feb 2016 at 4:29

**Comment by GoogleCodeExporter** [comment]
```
Having the same issue

C:\nodejs-getting-started\2-structured-data>gcloud preview app deploy
You are about to deploy the following modules:
 - nodejs-books/default (from [C:\nodejs-getting-started\2-structured-data\app.yaml])
     Deployed URL: [https://nodejs-books.appspot.com]

Do you want to continue (Y/n)?  Y

Beginning deployment...

Verifying that Managed VMs are enabled and ready.
Building and pushing image for module [default]
ERROR: gcloud crashed (WindowsError): [Error 32] The process cannot access the 
file because it is being used by another process: 
'c:\\users\\jamesw~1\\appdata\\local\\temp\\tmpxrsalt\\src.tgz'

If you would like to report this issue, please run the following command:
  gcloud feedback

C:\nodejs-getting-started\2-structured-data>
```

Original comment by `jamesw...@amuzedesign.com` on 2 Mar 2016 at 7:27

**Comment by GoogleCodeExporter** [comment]
```
We have a fix for this, which should go out in the to-be-released Cloud SDK 
100.0.0 release.
```

Original comment by `z...@google.com` on 2 Mar 2016 at 10:02
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
Cloud SDK 100.0.0 is out–please let us know if you're still experiencing this.
```

Original comment by `z...@google.com` on 9 Mar 2016 at 7:22
- Changed state: **Fixed**
