### ISSUE TITLE
Crash on Deploying Bookshelf App Certification Error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#555]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "lib\googlecloudsdk\gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  File "lib\googlecloudsdk\calliope\cli.py", line 646, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "lib\googlecloudsdk\calliope\backend.py", line 1394, in Run
    resources = command_instance.Run(args)
  File "lib\surface\preview\app\deploy.py", line 482, in Run
    config_cleanup)
  File "lib\googlecloudsdk\api_lib\app\deploy_command_util.py", line 199, in BuildAndPushDockerImages
    cli, version_id, remote, project) as docker_client:
  File "lib\googlecloudsdk\api_lib\app\images\docker_util.py", line 237, in __enter__
    kwargs = containers.KwargsFromEnv(self._vm.host, self._vm.cert_dir, True)
  File "lib\googlecloudsdk\api_lib\app\containers.py", line 100, in KwargsFromEnv
    assert_hostname=False)
  File "bin\..\lib\third_party\docker\docker\tls.py", line 46, in __init__
    'Path to a certificate and key files must be provided'
TLSParameterError: Path to a certificate and key files must be provided through 
the client_config param. TLS configurations should map the Docker CLI client 
configurations. See http://docs.docker.com/examples/https/ for API details.

Installation information:

Google Cloud SDK [97.0.0]

Platform: [Windows, x86_64]
Python Version: [2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit 
(AMD64)]]
Python Location: [C:\python27_x64\python.exe]
[output truncated]

```

Original issue reported on code.google.com by `noah.hen...@gmail.com` on 17 Feb 2016 at 8:26

**Comment by GoogleCodeExporter** [comment]
```
Issue 556 has been merged into this issue.
```

Original comment by `z...@google.com` on 18 Feb 2016 at 3:44

**Comment by GoogleCodeExporter** [comment]
```
Can you try running:

    $ gcloud config set app/use_cloud_build true

and then trying again as a workaround?
```

Original comment by `z...@google.com` on 18 Feb 2016 at 3:45
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
Thank you for your help! I tried with this command. Unfortunately it still 
won't work. I can start the app on my local machine and even the DB-Connection 
works fine. I already created a new Project on Google Cloud Platform and run 
the tutorial again, got still an error:

Beginning deployment...
If this is your first deployment, this may take a while...done.

Verifying that Managed VMs are enabled and ready.
Building and pushing image for module [default]
Started cloud build [16443994-794a-4798-881d-4bceb15fb1e0].
To see logs in the Cloud Console: 
https://console.developers.google.com/logs?project=gbook
shelf&service=cloudbuild.googleapis.com&key1=16443994-794a-4798-881d-4bceb15fb1e
0
---------------------------------- REMOTE BUILD OUTPUT 
-----------------------------------

starting build "16443994-794a-4798-881d-4bceb15fb1e0"

FETCHSOURCE
Fetching storage object: 
gs://staging.gbookshelf.appspot.com/gbookshelf.default.20160218t1
73734
Copying 
gs://staging.gbookshelf.appspot.com/gbookshelf.default.20160218t173734...
Downloading file:///tmp/source-archive.tgz:                      11.77 
MiB/11.77 MiB
FETCHBUILDER
BUILD
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64
Sending build context to Docker daemon 50.18 kB
Step 1 : FROM gcr.io/google_appengine/nodejs
 ---> 9b761a98c145
Step 2 : COPY . /app/
 ---> 470096c37d35
Removing intermediate container 0f07d102b5e9
Step 3 : RUN npm install --unsafe-perm ||   ((if [ -f npm-debug.log ]; then     
  cat npm-
debug.log;     fi) && false)
 ---> Running in 5b8d43546ba5

> kerberos@0.0.18 install /app/node_modules/kerberos
> (node-gyp rebuild) || (exit 0)
make: Entering directory '/app/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
  CXX(target) Release/obj.target/kerberos/lib/worker.o
  CC(target) Release/obj.target/kerberos/lib/kerberosgss.o
←[91m../lib/kerberosgss.c:36:0: warning: ignoring #pragma clang diagnostic 
[-Wunknown-prag
mas]
 #pragma clang diagnostic push
 ^
←[0m←[91m../lib/kerberosgss.c:37:0: warning: ignoring #pragma clang 
diagnostic [-Wunknown-
pragmas]
 #pragma clang diagnostic ignored "-Wdeprecated-declarations"
 ^
←[0m←[91m../lib/kerberosgss.c: In function 'authenticate_gss_client_wrap':
←[0m←[91m../lib/kerberosgss.c:362:19: warning: variable 'server_conf_flags' 
set but not us
ed [-Wunused-but-set-variable]
   char buf[4096], server_conf_flags;
                   ^
←[0m←[91m../lib/kerberosgss.c: At top level:
←[0m←[91m../lib/kerberosgss.c:930:0: warning: ignoring #pragma clang 
diagnostic [-Wunknown
-pragmas]
 #pragma clang diagnostic pop
 ^
←[0m  CC(target) Release/obj.target/kerberos/lib/base64.o
  CXX(target) Release/obj.target/kerberos/lib/kerberos_context.o
  SOLINK_MODULE(target) Release/obj.target/kerberos.node
  COPY Release/kerberos.node
make: Leaving directory '/app/node_modules/kerberos/build'

> sse4_crc32@4.1.1 install 
/app/node_modules/gcloud/node_modules/hash-stream-validation/no
de_modules/fast-crc32c/node_modules/sse4_crc32
> node-gyp rebuild

make: Entering directory 
'/app/node_modules/gcloud/node_modules/hash-stream-validation/nod
e_modules/fast-crc32c/node_modules/sse4_crc32/build'
  CXX(target) Release/obj.target/crc32c_sse42/src/crc32c_sse42.o
  AR(target) Release/obj.target/crc32c_sse42.a
  COPY Release/crc32c_sse42.a
  CXX(target) Release/obj.target/sse4_crc32/src/crc32c.o
  SOLINK_MODULE(target) Release/obj.target/sse4_crc32.node
  COPY Release/sse4_crc32.node
make: Leaving directory 
'/app/node_modules/gcloud/node_modules/hash-stream-validation/node
_modules/fast-crc32c/node_modules/sse4_crc32/build'
body-parser@1.15.0 node_modules/body-parser
Ôö£ÔöÇÔöÇ content-type@1.0.1
Ôö£ÔöÇÔöÇ bytes@2.2.0
Ôö£ÔöÇÔöÇ depd@1.1.0
Ôö£ÔöÇÔöÇ qs@6.1.0
Ôö£ÔöÇÔöÇ on-finished@2.3.0 (ee-first@1.1.1)
Ôö£ÔöÇÔöÇ raw-body@2.1.5 (unpipe@1.0.0)
Ôö£ÔöÇÔöÇ http-errors@1.4.0 (statuses@1.2.1, inherits@2.0.1)
Ôö£ÔöÇÔöÇ iconv-lite@0.4.13
Ôö£ÔöÇÔöÇ debug@2.2.0 (ms@0.7.1)
ÔööÔöÇÔöÇ type-is@1.6.11 (media-typer@0.3.0, mime-types@2.1.10)

express@4.13.4 node_modules/express
Ôö£ÔöÇÔöÇ escape-html@1.0.3
Ôö£ÔöÇÔöÇ array-flatten@1.1.1
Ôö£ÔöÇÔöÇ cookie-signature@1.0.6
Ôö£ÔöÇÔöÇ utils-merge@1.0.0
Ôö£ÔöÇÔöÇ content-type@1.0.1
Ôö£ÔöÇÔöÇ merge-descriptors@1.0.1
Ôö£ÔöÇÔöÇ vary@1.0.1
Ôö£ÔöÇÔöÇ methods@1.1.2
Ôö£ÔöÇÔöÇ content-disposition@0.5.1
Ôö£ÔöÇÔöÇ etag@1.7.0
Ôö£ÔöÇÔöÇ cookie@0.1.5
Ôö£ÔöÇÔöÇ range-parser@1.0.3
Ôö£ÔöÇÔöÇ fresh@0.3.0
Ôö£ÔöÇÔöÇ parseurl@1.3.1
Ôö£ÔöÇÔöÇ path-to-regexp@0.1.7
Ôö£ÔöÇÔöÇ serve-static@1.10.2
Ôö£ÔöÇÔöÇ depd@1.1.0
Ôö£ÔöÇÔöÇ qs@4.0.0
Ôö£ÔöÇÔöÇ on-finished@2.3.0 (ee-first@1.1.1)
Ôö£ÔöÇÔöÇ finalhandler@0.4.1 (unpipe@1.0.0)
Ôö£ÔöÇÔöÇ debug@2.2.0 (ms@0.7.1)
Ôö£ÔöÇÔöÇ proxy-addr@1.0.10 (forwarded@0.1.0, ipaddr.js@1.0.5)
Ôö£ÔöÇÔöÇ send@0.13.1 (destroy@1.0.4, statuses@1.2.1, ms@0.7.1, 
mime@1.3.4, http-errors@1.
3.1)
Ôö£ÔöÇÔöÇ type-is@1.6.11 (media-typer@0.3.0, mime-types@2.1.10)
ÔööÔöÇÔöÇ accepts@1.2.13 (negotiator@0.5.3, mime-types@2.1.10)

mysql@2.10.2 node_modules/mysql
Ôö£ÔöÇÔöÇ bignumber.js@2.1.4
ÔööÔöÇÔöÇ readable-stream@1.1.13 (inherits@2.0.1, 
string_decoder@0.10.31, isarray@0.0.1, c
ore-util-is@1.0.2)

kerberos@0.0.18 node_modules/kerberos
ÔööÔöÇÔöÇ nan@2.0.9

prompt@0.2.14 node_modules/prompt
Ôö£ÔöÇÔöÇ revalidator@0.1.8
Ôö£ÔöÇÔöÇ pkginfo@0.3.1
Ôö£ÔöÇÔöÇ read@1.0.7 (mute-stream@0.0.6)
Ôö£ÔöÇÔöÇ winston@0.8.3 (cycle@1.0.3, async@0.2.10, stack-trace@0.0.9, 
eyes@0.1.8, isstrea
m@0.1.2, colors@0.6.2)
ÔööÔöÇÔöÇ utile@0.2.1 (async@0.2.10, deep-equal@1.0.1, ncp@0.4.2, 
i@0.3.4, mkdirp@0.5.1, r
imraf@2.5.2)

mongodb@2.1.7 node_modules/mongodb
Ôö£ÔöÇÔöÇ es6-promise@3.0.2
Ôö£ÔöÇÔöÇ readable-stream@1.0.31 (string_decoder@0.10.31, 
isarray@0.0.1, inherits@2.0.1, c
ore-util-is@1.0.2)
ÔööÔöÇÔöÇ mongodb-core@1.3.1 (bson@0.4.21, require_optional@1.0.0)

jade@1.11.0 node_modules/jade
Ôö£ÔöÇÔöÇ commander@2.6.0
Ôö£ÔöÇÔöÇ character-parser@1.2.1
Ôö£ÔöÇÔöÇ void-elements@2.0.1
Ôö£ÔöÇÔöÇ mkdirp@0.5.1 (minimist@0.0.8)
Ôö£ÔöÇÔöÇ jstransformer@0.0.2 (is-promise@2.1.0, promise@6.1.0)
Ôö£ÔöÇÔöÇ constantinople@3.0.2 (acorn@2.7.0)
Ôö£ÔöÇÔöÇ with@4.0.3 (acorn@1.2.2, acorn-globals@1.0.9)
Ôö£ÔöÇÔöÇ clean-css@3.4.9 (commander@2.8.1, source-map@0.4.4)
Ôö£ÔöÇÔöÇ transformers@2.1.0 (promise@2.0.0, css@1.0.8, 
uglify-js@2.2.5)
ÔööÔöÇÔöÇ uglify-js@2.6.1 (async@0.2.10, uglify-to-browserify@1.0.2, 
source-map@0.5.3, yar
gs@3.10.0)

gcloud@0.27.0 node_modules/gcloud
Ôö£ÔöÇÔöÇ propprop@0.3.0
Ôö£ÔöÇÔöÇ prop-assign@1.0.0
Ôö£ÔöÇÔöÇ string-format-obj@1.0.1
Ôö£ÔöÇÔöÇ arrify@1.0.1
Ôö£ÔöÇÔöÇ methmeth@1.1.0
Ôö£ÔöÇÔöÇ is@3.1.0
Ôö£ÔöÇÔöÇ async@1.5.2
Ôö£ÔöÇÔöÇ extend@3.0.0
Ôö£ÔöÇÔöÇ dns-zonefile@0.1.10
Ôö£ÔöÇÔöÇ modelo@4.2.0
Ôö£ÔöÇÔöÇ mime-types@2.1.10 (mime-db@1.22.0)
Ôö£ÔöÇÔöÇ create-error-class@2.0.1 (capture-stack-trace@1.0.0, 
inherits@2.0.1)
Ôö£ÔöÇÔöÇ once@1.3.3 (wrappy@1.0.1)
Ôö£ÔöÇÔöÇ stream-events@1.0.1 (stubs@1.1.2)
Ôö£ÔöÇÔöÇ split-array-stream@1.0.0 (is-stream-ended@0.1.0)
Ôö£ÔöÇÔöÇ retry-request@1.2.3 (stream-cache@0.0.2)
Ôö£ÔöÇÔöÇ pumpify@1.3.3 (pump@1.0.1)
Ôö£ÔöÇÔöÇ duplexify@3.4.2 (end-of-stream@1.0.0, readable-stream@2.0.5)
Ôö£ÔöÇÔöÇ concat-stream@1.5.1 (inherits@2.0.1, typedarray@0.0.6, 
readable-stream@2.0.5)
Ôö£ÔöÇÔöÇ through2@2.0.1 (xtend@4.0.1, readable-stream@2.0.5)
Ôö£ÔöÇÔöÇ JSONStream@1.0.7 (through@2.3.8, jsonparse@1.2.0)
Ôö£ÔöÇÔöÇ gcs-resumable-upload@0.3.0 (buffer-equal@0.0.1, 
configstore@1.4.0)
Ôö£ÔöÇÔöÇ hash-stream-validation@0.1.3 (fast-crc32c@1.0.1)
Ôö£ÔöÇÔöÇ request@2.69.0 (aws-sign2@0.6.0, forever-agent@0.6.1, 
tunnel-agent@0.4.2, oauth-
sign@0.8.1, form-data@1.0.0-rc3, is-typedarray@1.0.0, caseless@0.11.0, 
stringstream@0.0.5,
 isstream@0.1.2, json-stringify-safe@5.0.1, tough-cookie@2.2.1, node-uuid@1.4.7, qs@6.0.2,
 combined-stream@1.0.5, aws4@1.2.1, bl@1.0.3, hawk@3.1.3, http-signature@1.1.1, har-valida
tor@2.0.6)
Ôö£ÔöÇÔöÇ google-auto-auth@0.2.4 (object-assign@3.0.0, 
google-auth-library@0.9.7)
Ôö£ÔöÇÔöÇ gce-images@0.2.3 (object-assign@3.0.0, got@4.2.0, 
google-auto-auth@0.1.1)
ÔööÔöÇÔöÇ protobufjs@4.1.3 (ascli@1.0.0, glob@5.0.15, yargs@3.32.0, 
bytebuffer@4.1.0)

lodash@4.5.0 node_modules/lodash
 ---> 935ed906bc6b
Removing intermediate container 5b8d43546ba5
Step 4 : RUN /usr/local/bin/install_node '>=0.12.7'
 ---> Running in 4d99d7d4c002
 ---> 7a7bb404d7c9
Removing intermediate container 4d99d7d4c002
Step 5 : CMD npm start
 ---> Running in e1f007f37115
 ---> fcfabaaa843e
Removing intermediate container e1f007f37115
Successfully built fcfabaaa843e
PUSH
The push refers to a repository 
[appengine.gcr.io/gcloud/gbookshelf.default.20160218t17373
4] (len: 1)
Sending image list
Pushing repository appengine.gcr.io/gcloud/gbookshelf.default.20160218t173734 
(1 tags)
Image 4bfc20f0ed66 already pushed, skipping
Image 503fd1aca23d already pushed, skipping
Image 8b9bf88f2892 already pushed, skipping
Image 3bc7cdb36864 already pushed, skipping
Image 096d9403d234 already pushed, skipping
Image cbdf4c2dcc2f already pushed, skipping
Image ed3573c4b7cf already pushed, skipping
Image ed81708239a2 already pushed, skipping
Image de0c46ffaa53 already pushed, skipping
Image b3302394c696 already pushed, skipping
Image 48cd0a3de336 already pushed, skipping
Image 2b4a07b4db94 already pushed, skipping
Image 857ba32536c8 already pushed, skipping
Image 305e0e8232d2 already pushed, skipping
Image 9b761a98c145 already pushed, skipping
470096c37d35: Pushing
470096c37d35: Image successfully pushed
935ed906bc6b: Pushing
935ed906bc6b: Image successfully pushed
7a7bb404d7c9: Pushing
7a7bb404d7c9: Image successfully pushed
fcfabaaa843e: Pushing
fcfabaaa843e: Image successfully pushed
Pushing tag for rev [fcfabaaa843e] on 
{https://appengine.gcr.io/v1/repositories/gcloud/gbo
okshelf.default.20160218t173734/tags/latest}
DONE
--------------------------------------------------------------------------------
----------


Updating module [default]...failed.
ERROR: (gcloud.preview.app.deploy) Error Response: [13] Managed VMs can not be 
hosted in t
he application's region. (e~)
```

Original comment by `noah.hen...@gmail.com` on 18 Feb 2016 at 4:45

**Comment by GoogleCodeExporter** [comment]
```
Are you in Europe, or is your application's region Europe?

Managed VMs are not currently available in Europe.
```

Original comment by `z...@google.com` on 18 Feb 2016 at 5:05

**Comment by GoogleCodeExporter** [comment]
```
Yay, finally it works!!! That was the problem! Yes i'm in Europe and I kind of 
overread the point, that the project needs to be hosted in the US...

Thank you very much for your fast and effective help!

Keep up your good work and Have a nice day! :-)
```

Original comment by `noah.hen...@gmail.com` on 18 Feb 2016 at 5:25

**Comment by GoogleCodeExporter** [comment]
```
Glad we were able to figure it out, and we hope you use Managed VMs if we do 
launch them in Europe–I know we would like to.
```

Original comment by `z...@google.com` on 18 Feb 2016 at 5:47
- Changed state: **WorkingAsIntended**
