### ISSUE TITLE
Cannot deploy managed vm

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#556]
```
Issue running command [gcloud preview app deploy].

Traceback (most recent call last):
  File "lib\googlecloudsdk\gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  File "lib\googlecloudsdk\calliope\cli.py", line 646, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "lib\googlecloudsdk\calliope\backend.py", line 1394, in Run
    resources = command_instance.Run(args)
  File "lib\surface\preview\app\deploy.py", line 482, in Run
    config_cleanup)
  File "lib\googlecloudsdk\api_lib\app\deploy_command_util.py", line 199, in BuildAndPushDockerImages
    cli, version_id, remote, project) as docker_client:
  File "lib\googlecloudsdk\api_lib\app\images\docker_util.py", line 237, in __enter__
    kwargs = containers.KwargsFromEnv(self._vm.host, self._vm.cert_dir, True)
  File "lib\googlecloudsdk\api_lib\app\containers.py", line 100, in KwargsFromEnv
    assert_hostname=False)
  File "bin\..\lib\third_party\docker\docker\tls.py", line 46, in __init__
    'Path to a certificate and key files must be provided'
TLSParameterError: Path to a certificate and key files must be provided through 
the client_config param. TLS configurations should map the Docker CLI client 
configurations. See http://docs.docker.com/examples/https/ for API details.

Installation information:

Google Cloud SDK [97.0.0]

Platform: [Windows, x86_64]
Python Version: [2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC 
v.1500 32 bit (Intel)]]
[output truncated]

```

Original issue reported on code.google.com by `Stas.Sok...@synesis.ru` on 18 Feb 2016 at 10:16
- Merged into: #555

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 18 Feb 2016 at 3:44
- Changed state: **Duplicate**
