### ISSUE TITLE
gcloud crashed (SSLHandshakeError): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#557]
```
Issue running command [gcloud init].

What steps will reproduce the problem?

Running on Windows 7

Install static gcloud sdk google-cloud-sdk-97.0.0-windows-x86_64
Install python 2.7.11 python-2.7.11.amd64
Open command prompt
c:\google-cloud-sdk\bin>gcloud.cmd init

Welcome! This command will take you through the configuration of gcloud.

Settings from your current configuration [default] are:
Your active configuration is: [default]

[core]
disable_usage_reporting = True

Pick configuration to use:
 [1] Re-initialize this configuration [default] with new settings
 [2] Create a new configuration
Please enter your numeric choice:  1

Your current configuration has been set to: [default]

To continue, you must log in. Would you like to log in (Y/n)?  Y

Your browser has been opened to visit:

    https://accounts.google.com/o/oauth2/auth?redirect_uri=http%3A%2F%2Flocalhost%3A8085%2F&prompt=select_account&response_type=code&client_id=3
2555940559.apps.googleusercontent.com&scope=https%3A%2F%2Fwww.googleapis.com%2Fa
uth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fc
loud-platform+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fappengine.admin+https%3A
%2F%2Fwww.googleapis.com%2Fauth%2Fcompute&access_type=offline

#-------------------------------------------------------------------------
#You are now authenticated with the Google Cloud SDK! displayed in Browser
#-------------------------------------------------------------------------

You can use [gcloud config] to change more gcloud settings.

Your active configuration is: [default]

[core]
disable_usage_reporting = True
ERROR: gcloud crashed (SSLHandshakeError): [SSL: CERTIFICATE_VERIFY_FAILED] 
certificate verify failed (_ssl.c:590)

If you would like to report this issue, please run the following command:
  gcloud feedback


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "lib\googlecloudsdk\gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  [...]
  File "lib\surface\auth\login.py", line 193, in DoWebFlow
    return c_store.AcquireFromWebFlow(launch_browser=launch_browser)
  File "lib\googlecloudsdk\core\credentials\store.py", line 401, in AcquireFromWebFlow
    http=_Http())
  File "lib\googlecloudsdk\core\credentials\flow.py", line 170, in Run
    credential = flow.step2_exchange(code, http=http)
  File "bin\..\lib\third_party\oauth2client\util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "bin\..\lib\third_party\oauth2client\client.py", line 1993, in step2_exchange
    headers=headers)
  File "bin\..\lib\third_party\httplib2\__init__.py", line 1610, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "bin\..\lib\third_party\httplib2\__init__.py", line 1352, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "bin\..\lib\third_party\httplib2\__init__.py", line 1272, in _conn_request
    conn.connect()
  File "bin\..\lib\third_party\httplib2\__init__.py", line 1059, in connect
    raise SSLHandshakeError(e)
SSLHandshakeError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed 
(_ssl.c:590)

[output truncated]

```

Original issue reported on code.google.com by `sm...@allstate.com` on 18 Feb 2016 at 1:12

**Comment by GoogleCodeExporter** [comment]
```
SSL verification errors can happen due to a number of reasons:
* General network issues
* A real SSL issue (there could be a captive portal in between you and Google)
* A Python version/system libraries with SSL issues (2.7.11 seems to work for 
most users, but you can try different minor versions, like 2.7.10 or 2.7.9).

Can you verify that none of these are the cause?
```

Original comment by `z...@google.com` on 18 Feb 2016 at 3:43
- Changed state: **NeedsMoreInfo**
