### ISSUE TITLE
gcloud always crashing 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#558]
```
What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "lib\googlecloudsdk\gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  [...]
  File "lib\googlecloudsdk\core\cli.py", line 139, in Http
    creds = c_store.Load()
  File "lib\googlecloudsdk\core\credentials\store.py", line 261, in Load
    Refresh(cred)
  File "lib\googlecloudsdk\core\credentials\store.py", line 279, in Refresh
    creds.refresh(http or _Http())
  File "bin\..\lib\third_party\oauth2client\client.py", line 597, in refresh
    self._refresh(http.request)
  File "bin\..\lib\third_party\oauth2client\client.py", line 780, in _refresh
    self._do_refresh_request(http_request)
  File "bin\..\lib\third_party\oauth2client\client.py", line 799, in _do_refresh_request
    self.token_uri, method='POST', body=body, headers=headers)
  File "bin\..\lib\third_party\httplib2\__init__.py", line 1610, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "bin\..\lib\third_party\httplib2\__init__.py", line 1352, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "bin\..\lib\third_party\httplib2\__init__.py", line 1308, in _conn_request
    response = conn.getresponse()
  File "D:\programFiles\Python27\lib\httplib.py", line 1013, in getresponse
    raise ResponseNotReady()
ResponseNotReady

[output truncated]

```

Original issue reported on code.google.com by `slamdunq...@gmail.com` on 18 Feb 2016 at 1:30
- Merged into: #14

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 18 Feb 2016 at 2:23
- Changed state: **Duplicate**
