### ISSUE TITLE
TLSParameterError when running gcloud preview app deploy

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#559]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?
Pushing the test app to asia-east1-a

What is the expected output? What do you see instead?


Please provide any additional information below.
Link provided to http://docs.docker.com/examples/https/ results in a 404

Traceback (most recent call last):
  File "lib\googlecloudsdk\gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  File "lib\googlecloudsdk\calliope\cli.py", line 646, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "lib\googlecloudsdk\calliope\backend.py", line 1394, in Run
    resources = command_instance.Run(args)
  File "lib\surface\preview\app\deploy.py", line 482, in Run
    config_cleanup)
  File "lib\googlecloudsdk\api_lib\app\deploy_command_util.py", line 199, in BuildAndPushDockerImages
    cli, version_id, remote, project) as docker_client:
  File "lib\googlecloudsdk\api_lib\app\images\docker_util.py", line 237, in __enter__
    kwargs = containers.KwargsFromEnv(self._vm.host, self._vm.cert_dir, True)
  File "lib\googlecloudsdk\api_lib\app\containers.py", line 100, in KwargsFromEnv
    assert_hostname=False)
  File "bin\..\lib\third_party\docker\docker\tls.py", line 46, in __init__
    'Path to a certificate and key files must be provided'
TLSParameterError: Path to a certificate and key files must be provided through 
the client_config param. TLS configurations should map the Docker CLI client 
configurations. See http://docs.docker.com/examples/https/ for API details.

Installation information:

Google Cloud SDK [97.0.0]

Platform: [Windows, x86_64]
Python Version: [2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit 
(AMD64)]]
Python Location: [C:\python27\python.exe]
[output truncated]

```

Original issue reported on code.google.com by `AlexFran...@gmail.com` on 19 Feb 2016 at 6:20

**Comment by GoogleCodeExporter** [comment]
```
This should be a transient issue. Please try again.

If that still does not work, to work around please run

    $ gcloud config set app/use_cloud_build true

and attempt to deploy again.

We're looking into fixing it.
```

Original comment by `z...@google.com` on 19 Feb 2016 at 5:48
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
Issue 563 has been merged into this issue.
```

Original comment by `z...@google.com` on 22 Feb 2016 at 2:39

**Comment by GoogleCodeExporter** [comment]
```
Issue 561 has been merged into this issue.
```

Original comment by `z...@google.com` on 22 Feb 2016 at 2:39

**Comment by GoogleCodeExporter** [comment]
```
Issue 564 has been merged into this issue.
```

Original comment by `z...@google.com` on 22 Feb 2016 at 2:39

**Comment by GoogleCodeExporter** [comment]
```
Issue 565 has been merged into this issue.
```

Original comment by `z...@google.com` on 22 Feb 2016 at 2:40

**Comment by GoogleCodeExporter** [comment]
```
Issue 567 has been merged into this issue.
```

Original comment by `z...@google.com` on 22 Feb 2016 at 2:40

**Comment by GoogleCodeExporter** [comment]
```
We're investigating this issue.
```

Original comment by `z...@google.com` on 22 Feb 2016 at 2:45

**Comment by GoogleCodeExporter** [comment]
```
Issue 570 has been merged into this issue.
```

Original comment by `z...@google.com` on 22 Feb 2016 at 3:56

**Comment by GoogleCodeExporter** [comment]
```
Issue 571 has been merged into this issue.
```

Original comment by `z...@google.com` on 22 Feb 2016 at 9:29

**Comment by GoogleCodeExporter** [comment]
```
Issue 574 has been merged into this issue.
```

Original comment by `z...@google.com` on 23 Feb 2016 at 12:11

**Comment by GoogleCodeExporter** [comment]
```
Issue 579 has been merged into this issue.
```

Original comment by `z...@google.com` on 24 Feb 2016 at 3:22

**Comment by GoogleCodeExporter** [comment]
```
Issue 581 has been merged into this issue.
```

Original comment by `z...@google.com` on 24 Feb 2016 at 6:05

**Comment by GoogleCodeExporter** [comment]
```
Issue 584 has been merged into this issue.
```

Original comment by `z...@google.com` on 25 Feb 2016 at 1:56

**Comment by GoogleCodeExporter** [comment]
```
Issue 583 has been merged into this issue.
```

Original comment by `z...@google.com` on 25 Feb 2016 at 1:58

**Comment by GoogleCodeExporter** [comment]
```
The workaround fixed this issue for me. Thanks.
```

Original comment by `latch...@gmail.com` on 25 Feb 2016 at 8:10

**Comment by GoogleCodeExporter** [comment]
```
Issue 590 has been merged into this issue.
```

Original comment by `z...@google.com` on 25 Feb 2016 at 9:09

**Comment by GoogleCodeExporter** [comment]
```
Issue 591 has been merged into this issue.
```

Original comment by `z...@google.com` on 25 Feb 2016 at 9:19

**Comment by GoogleCodeExporter** [comment]
```
Issue 594 has been merged into this issue.
```

Original comment by `z...@google.com` on 26 Feb 2016 at 12:47

**Comment by GoogleCodeExporter** [comment]
```
Issue 595 has been merged into this issue.
```

Original comment by `z...@google.com` on 26 Feb 2016 at 10:00

**Comment by GoogleCodeExporter** [comment]
```
Issue 601 has been merged into this issue.
```

Original comment by `z...@google.com` on 28 Feb 2016 at 10:50

**Comment by GoogleCodeExporter** [comment]
```
Issue 598 has been merged into this issue.
```

Original comment by `z...@google.com` on 28 Feb 2016 at 10:50

**Comment by GoogleCodeExporter** [comment]
```
Issue 599 has been merged into this issue.
```

Original comment by `z...@google.com` on 28 Feb 2016 at 10:50

**Comment by GoogleCodeExporter** [comment]
```
Issue 597 has been merged into this issue.
```

Original comment by `z...@google.com` on 28 Feb 2016 at 10:51

**Comment by GoogleCodeExporter** [comment]
```
Issue 602 has been merged into this issue.
```

Original comment by `z...@google.com` on 28 Feb 2016 at 10:52

**Comment by GoogleCodeExporter** [comment]
```
Issue 604 has been merged into this issue.
```

Original comment by `che...@google.com` on 29 Feb 2016 at 1:57

**Comment by GoogleCodeExporter** [comment]
```
Issue 603 has been merged into this issue.
```

Original comment by `che...@google.com` on 29 Feb 2016 at 1:57

**Comment by GoogleCodeExporter** [comment]
```
Issue 611 has been merged into this issue.
```

Original comment by `che...@google.com` on 2 Mar 2016 at 1:59

**Comment by GoogleCodeExporter** [comment]
```
Issue 613 has been merged into this issue.
```

Original comment by `che...@google.com` on 2 Mar 2016 at 2:00

**Comment by GoogleCodeExporter** [comment]
```
Issue 614 has been merged into this issue.
```

Original comment by `che...@google.com` on 2 Mar 2016 at 2:00

**Comment by GoogleCodeExporter** [comment]
```
Issue 623 has been merged into this issue.
```

Original comment by `z...@google.com` on 4 Mar 2016 at 4:31

**Comment by GoogleCodeExporter** [comment]
```
We believe that release 99.0.0 contains a fix for this. Do you mind upgrading 
and trying again?
```

Original comment by `z...@google.com` on 4 Mar 2016 at 4:31

**Comment by GoogleCodeExporter** [comment]
```
How do I reverse the workaround? I'm not sure what the value was originally.
```

Original comment by `latch...@gmail.com` on 4 Mar 2016 at 5:38

**Comment by GoogleCodeExporter** [comment]
```
to reverse: gcloud config set app/use_cloud_build false
```

Original comment by `matthew....@gmail.com` on 4 Mar 2016 at 5:42

**Comment by GoogleCodeExporter** [comment]
```
You can also run `gcloud config unset app/use_cloud_build`, so that if we 
toggle the default behavior you'll pick that up.
```

Original comment by `z...@google.com` on 4 Mar 2016 at 5:59

**Comment by GoogleCodeExporter** [comment]
```
Setting to false built just fine with 99. Thanks.
```

Original comment by `latch...@gmail.com` on 4 Mar 2016 at 6:04

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 4 Mar 2016 at 6:05
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Issue 627 has been merged into this issue.
```

Original comment by `vil...@google.com` on 5 Mar 2016 at 2:18

**Comment by GoogleCodeExporter** [comment]
```
Issue 630 has been merged into this issue.
```

Original comment by `z...@google.com` on 7 Mar 2016 at 5:03

**Comment by GoogleCodeExporter** [comment]
```
Issue 644 has been merged into this issue.
```

Original comment by `z...@google.com` on 12 Mar 2016 at 10:27
