### ISSUE TITLE
Error running gcloud preview app deploy

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#561]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?

I'm follow this https://cloud.google.com/nodejs/getting-started/hello-world
at 'gcloud preview app deploy' I got a error

What is the expected output? What do you see instead?

I expected the app running on gcloud

Instead I see this error:

-----------
Beginning deployment...
If this is your first deployment, this may take a while...done.

Verifying that Managed VMs are enabled and ready.
Provisioning remote build service.
Copying certificates for secure access. You may be prompted to create an SSH 
keypair.
ERROR: gcloud crashed (TLSParameterError): Path to a certificate and key files 
must be provided through the client_config param. TLS configurations should map 
the Docker CLI client configurations. See 
http://docs.docker.com/examples/https/ for API details.
---------------

Please provide any additional information below.

The nodejs project is running fine, but I can't deploy to gcloud.


Traceback (most recent call last):
  File "lib\googlecloudsdk\gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  File "lib\googlecloudsdk\calliope\cli.py", line 646, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "lib\googlecloudsdk\calliope\backend.py", line 1394, in Run
    resources = command_instance.Run(args)
  File "lib\surface\preview\app\deploy.py", line 482, in Run
    config_cleanup)
  File "lib\googlecloudsdk\api_lib\app\deploy_command_util.py", line 199, in BuildAndPushDockerImages
    cli, version_id, remote, project) as docker_client:
  File "lib\googlecloudsdk\api_lib\app\images\docker_util.py", line 237, in __enter__
    kwargs = containers.KwargsFromEnv(self._vm.host, self._vm.cert_dir, True)
  File "lib\googlecloudsdk\api_lib\app\containers.py", line 100, in KwargsFromEnv
    assert_hostname=False)
  File "bin\..\lib\third_party\docker\docker\tls.py", line 46, in __init__
    'Path to a certificate and key files must be provided'
TLSParameterError: Path to a certificate and key files must be provided through 
the client_config param. TLS configurations should map the Docker CLI client 
configurations. See http://docs.docker.com/examples/https/ for API details.

Installation information:

Google Cloud SDK [97.0.0]

Platform: [Windows, x86_64]
Python Version: [2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit 
(AMD64)]]
Python Location: [C:\python27_x64\python.exe]
[output truncated]

```

Original issue reported on code.google.com by `jose.raphael.marques` on 19 Feb 2016 at 8:26
- Merged into: #559

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 22 Feb 2016 at 2:39
- Changed state: **Duplicate**
