### ISSUE TITLE
gcloud crashed (error): [Errno 61] Connection refused

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#562]
```
Issue running command [gcloud init].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk/gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  [...]
  File "googlecloudsdk/calliope/exceptions.py", line 110, in TryFunc
    return func(*args, **kwargs)
  File "surface/auth/login.py", line 128, in Run
    creds = self.DoWebFlow(args.launch_browser)
  File "surface/auth/login.py", line 193, in DoWebFlow
    return c_store.AcquireFromWebFlow(launch_browser=launch_browser)
  File "googlecloudsdk/core/credentials/store.py", line 401, in AcquireFromWebFlow
    http=_Http())
  File "googlecloudsdk/core/credentials/flow.py", line 170, in Run
    credential = flow.step2_exchange(code, http=http)
  File "third_party/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "third_party/oauth2client/client.py", line 1993, in step2_exchange
    headers=headers)
  File "third_party/httplib2/__init__.py", line 1610, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "third_party/httplib2/__init__.py", line 1352, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "third_party/httplib2/__init__.py", line 1272, in _conn_request
    conn.connect()
  File "third_party/httplib2/__init__.py", line 1075, in connect
    raise socket.error, msg
[output truncated]

```

Original issue reported on code.google.com by `yuan...@gmail.com` on 20 Feb 2016 at 6:03

**Comment by GoogleCodeExporter** [comment]
```
This message usually indicates a temporary connection hiccup. Does the issue 
persist when you try the command again?

Do you have any unusual network/firewall/proxy settings?
```

Original comment by `z...@google.com` on 22 Feb 2016 at 2:57
- Changed state: **NeedsMoreInfo**
