### ISSUE TITLE
GCloud managed vm Java example broken by missing certificate paths

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#565]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?
following the managed_vm helloworld instructions at:
https://cloud.google.com/appengine/docs/managed-vms/java/hello-world

What is the expected output? What do you see instead?
I expected to deploy the demo and run it
Instead I am getting docker certificate related errors

log:
[INFO] Running C:\python27_x64\python.exe -S C:\Program Files\Google\Cloud 
SDK\google-cloud-sdk\lib\gcloud.py --quiet preview app deploy 
c:\_projects\rtc\dev\_store\java-docs-samples\managed_vms\helloworld\target\appe
ngine-staging/app.yaml --promote
[INFO] You are about to deploy the following modules:
[INFO]  - xxxx/default (from 
[c:\_projects\rtc\dev\_store\java-docs-samples\managed_vms\helloworld\target\app
engine-staging\app.yaml])
[INFO]      Deployed URL: [https://xxx.appspot.com]
[INFO]
[INFO] Beginning deployment...
[INFO]
[INFO] Verifying that Managed VMs are enabled and ready.
[INFO] Provisioning remote build service.
[INFO] Copying certificates for secure access. You may be prompted to create an 
SSH keypair.
[INFO] ERROR: gcloud crashed (TLSParameterError): Path to a certificate and key 
files must be provided through the client_config param. TLS configurations 
should map the Docker CLI client configurations. See 
http://docs.docker.com/examples/https/ for API details.



Please provide any additional information below.
From what I can discover, the gcloud deploy seems to be expecting environment 
variables that were originally created by boot2docker:  
DOCKER_HOST, DOCKER_CERT_PATH, DOCKER_TLS_VERIFY
But these are no longer created by the Docker-Toolbox.
And the documentation link in the error message is broken.

Traceback (most recent call last):
  File "googlecloudsdk\gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  File "googlecloudsdk\calliope\cli.py", line 646, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk\calliope\backend.py", line 1394, in Run
    resources = command_instance.Run(args)
  File "surface\preview\app\deploy.py", line 482, in Run
    config_cleanup)
  File "googlecloudsdk\api_lib\app\deploy_command_util.py", line 199, in BuildAndPushDockerImages
    cli, version_id, remote, project) as docker_client:
  File "googlecloudsdk\api_lib\app\images\docker_util.py", line 237, in __enter__
    kwargs = containers.KwargsFromEnv(self._vm.host, self._vm.cert_dir, True)
  File "googlecloudsdk\api_lib\app\containers.py", line 100, in KwargsFromEnv
    assert_hostname=False)
  File "third_party\docker\docker\tls.py", line 46, in __init__
    'Path to a certificate and key files must be provided'
TLSParameterError: Path to a certificate and key files must be provided through 
the client_config param. TLS configurations should map the Docker CLI client 
configurations. See http://docs.docker.com/examples/https/ for API details.

Installation information:

Google Cloud SDK [97.0.0]

Platform: [Windows, x86_64]
Python Version: [2.7.6 (default, Nov 10 2013, 19:24:24) [MSC v.1500 64 bit 
(AMD64)]]
Python Location: [C:\python27_x64\python.exe]
Site Packages: [Disabled]

[output truncated]

```

Original issue reported on code.google.com by `rillingw...@bizpay.co.uk` on 21 Feb 2016 at 12:37
- Merged into: #559

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 22 Feb 2016 at 2:40
- Changed state: **Duplicate**
