### ISSUE TITLE
Crash while updating module -- nodejs

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#566]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk/gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  [...]
  File "googlecloudsdk/api_lib/app/util.py", line 370, in Send
    response = self._server.Send(*args, **kwargs)
  File "googlecloudsdk/third_party/appengine/tools/appengine_rpc_httplib2.py", line 230, in Send
    url, method=method, body=payload, headers=headers)
  File "third_party/oauth2client/client.py", line 540, in new_request
    self._refresh(request_orig)
  File "third_party/oauth2client/client.py", line 768, in _refresh
    self._do_refresh_request(http_request)
  File "third_party/oauth2client/client.py", line 799, in _do_refresh_request
    self.token_uri, method='POST', body=body, headers=headers)
  File "third_party/httplib2/__init__.py", line 1610, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "third_party/httplib2/__init__.py", line 1352, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "third_party/httplib2/__init__.py", line 1308, in _conn_request
    response = conn.getresponse()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1119, in getresponse
    raise ResponseNotReady()
ResponseNotReady

[output truncated]

```

Original issue reported on code.google.com by `mostafa....@ibtikar.net.sa` on 21 Feb 2016 at 2:51

**Comment by GoogleCodeExporter** [comment]
```
ResponseNotReady usually indicates a temporary connection hiccup. Does the 
issue persist when you try the command again?

Do you have any unusual network/firewall/proxy settings?
```

Original comment by `z...@google.com` on 22 Feb 2016 at 2:44
- Changed state: **NeedsMoreInfo**
