### ISSUE TITLE
error with gcloud preview app deploy, Path to a certificate and key files must be provided' TLSParameterError

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#567]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?

    just running gcloud preview app deploy. I tried adding --docker-build=remote but same result.

What is the expected output? What do you see instead?

Deployment to an appengine managed VM

Please provide any additional information below.

It's the first time I try to deploy a managed VM. Before it was the standard 
appengine.
I found the command on 
https://cloud.google.com/appengine/docs/managed-vms/python/hello-world


Traceback (most recent call last):
  File "googlecloudsdk/gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  File "googlecloudsdk/calliope/cli.py", line 646, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk/calliope/backend.py", line 1394, in Run
    resources = command_instance.Run(args)
  File "surface/preview/app/deploy.py", line 482, in Run
    config_cleanup)
  File "googlecloudsdk/api_lib/app/deploy_command_util.py", line 199, in BuildAndPushDockerImages
    cli, version_id, remote, project) as docker_client:
  File "googlecloudsdk/api_lib/app/images/docker_util.py", line 237, in __enter__
    kwargs = containers.KwargsFromEnv(self._vm.host, self._vm.cert_dir, True)
  File "googlecloudsdk/api_lib/app/containers.py", line 100, in KwargsFromEnv
    assert_hostname=False)
  File "third_party/docker/docker/tls.py", line 46, in __init__
    'Path to a certificate and key files must be provided'
TLSParameterError: Path to a certificate and key files must be provided through 
the client_config param. TLS configurations should map the Docker CLI client 
configurations. See http://docs.docker.com/examples/https/ for API details.

Installation information:

Google Cloud SDK [97.0.0]

Platform: [Linux, x86_64]
Python Version: [2.7.6 (default, Mar 22 2014, 22:59:56)  [GCC 4.8.2]]
Python Location: [/usr/bin/python2]
Site Packages: [Disabled]

Installation Root: [/home/nico/projects/gator/gator/lib/google-cloud-sdk]
Installed Components:
  core: [2016.02.11]
  core-nix: [2016.02.05]
  gcloud: []
  gsutil-nix: [4.15]
  beta: [2016.01.12]
  gsutil: [4.16]
  bq: [2.0.18]
  gcd-emulator: [v1beta3-1.0.0]
  bq-nix: [2.0.18]
System PATH: 
[/home/nico/projects/gator/gator/lib/google-cloud-sdk/bin:/usr/local/sbin:/usr/l
ocal/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/go
/bin:/home/nico/dev/go_workspace/bin::/home/nico/apps/android-studio/bin:/home/n
ico/dev/apache-maven/apache-maven-3.2.3/bin:/home/nico/dev/python_appengine/goog
le_appengine:/home/nico/dev/phantomjs/phantomjs/bin]
Cloud SDK on PATH: [True]

Installation Properties: 
[/home/nico/projects/gator/gator/lib/google-cloud-sdk/properties]
User Config Directory: [/home/nico/.config/gcloud]
User Properties: [/home/nico/.config/gcloud/properties]
Current Workspace: [None]
Workspace Config Directory: [None]
Workspace Properties: [None]

Account: [gator.gae@gmail.com]
Project: [gator-01]

Current Properties:
  [core]
    project: [gator-01]
    account: [gator.gae@gmail.com]
    disable_usage_reporting: [True]
  [app]
    suppress_change_warning: [true]
  [compute]
    region: [us-central1]
    zone: [us-central1-f]

Logs Directory: [/home/nico/.config/gcloud/logs]
Last Log File: [/home/nico/.config/gcloud/logs/2016.02.21/16.59.31.551985.log]

```

Original issue reported on code.google.com by `lecri...@gmail.com` on 21 Feb 2016 at 4:13
- Merged into: #559

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 22 Feb 2016 at 2:40
- Changed state: **Duplicate**
