### ISSUE TITLE
gcloud init crashed

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#568]
```
Issue running command [gcloud init].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "lib\googlecloudsdk\gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  File "lib\googlecloudsdk\calliope\cli.py", line 646, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "lib\googlecloudsdk\calliope\backend.py", line 1394, in Run
    resources = command_instance.Run(args)
  File "lib\googlecloudsdk\surface\init.py", line 97, in Run
    self.cli.Execute(['config', 'list'])
  File "lib\googlecloudsdk\calliope\cli.py", line 621, in Execute
    args = self.__parser.parse_args(args)
  File "lib\googlecloudsdk\calliope\backend.py", line 92, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "lib\googlecloudsdk\calliope\backend.py", line 83, in parse_known_args
    args, argv = super(ArgumentParser, self).parse_known_args(args, namespace)
  File "bin\..\lib\third_party\argparse\__init__.py", line 1735, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "bin\..\lib\third_party\argparse\__init__.py", line 1944, in _parse_known_args
    stop_index = consume_positionals(start_index)
  File "bin\..\lib\third_party\argparse\__init__.py", line 1900, in consume_positionals
    take_action(action, args)
  File "bin\..\lib\third_party\argparse\__init__.py", line 1809, in take_action
    action(self, namespace, argument_values, option_string)
[output truncated]

```

Original issue reported on code.google.com by `internetboy0823` on 22 Feb 2016 at 11:55

**Comment by GoogleCodeExporter** [comment]
```
Thanks for reporting the issue.

Can you tell us what version you are using, by running [gcloud info] and copy 
pasting its output here.
```

Original comment by `che...@google.com` on 22 Feb 2016 at 1:17
- Changed state: **NeedsMoreInfo**
