### ISSUE TITLE
How to login>?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#569]
```
Issue running command [gcloud auth login].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk\gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  File "googlecloudsdk\calliope\cli.py", line 646, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk\calliope\backend.py", line 1394, in Run
    resources = command_instance.Run(args)
  File "googlecloudsdk\calliope\exceptions.py", line 110, in TryFunc
    return func(*args, **kwargs)
  File "surface\auth\login.py", line 140, in Run
    c_store.Store(creds, account)
  File "googlecloudsdk\core\credentials\store.py", line 309, in Store
    _GetLegacyGen(account, creds).WriteTemplate()
  File "googlecloudsdk\core\credentials\store.py", line 314, in _GetLegacyGen
    multistore_path=config.Paths().LegacyCredentialsMultistorePath(account),
  File "googlecloudsdk\core\config.py", line 639, in LegacyCredentialsMultistorePath
    return os.path.join(self.LegacyCredentialsDir(account), 'multistore.json')
  File "googlecloudsdk\core\config.py", line 628, in LegacyCredentialsDir
    return os.path.join(self.global_config_dir, 'legacy_credentials', account)
  File "C:\python27\lib\ntpath.py", line 85, in join
    result_path = result_path + p_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb5 in position 7: ordinal 
not in range(128)

Installation information:

Google Cloud SDK [97.0.0]

Platform: [Windows, x86_64]
[output truncated]

```

Original issue reported on code.google.com by `gemihanm...@gmail.com` on 22 Feb 2016 at 3:31
- Merged into: #502

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 22 Feb 2016 at 3:49
- Changed state: **Duplicate**
