### ISSUE TITLE
Can´t seem to access list of servers

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#575]
```
Issue running command [gcloud init].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "calliope/cli.py", line 609, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "calliope/backend.py", line 1218, in Run
    last_group = context_filter(tool_context, Http, args)
  File "calliope/backend.py", line 580, in ContextFilter
    group.Filter(context, args)
  File "surface/projects/__init__.py", line 25, in Filter
    http=self.Http())
  File "calliope/base.py", line 283, in Http
    return self._http_func(auth=auth, creds=creds, **kwargs)
  File "calliope/backend.py", line 1213, in Http
    **kwargs)
  File "core/cli.py", line 127, in Http
    creds = c_store.Load()
  File "core/credentials/store.py", line 249, in Load
    Refresh(cred)
  File "core/credentials/store.py", line 269, in Refresh
    raise RefreshError(e)
RefreshError: Unable to find the server at accounts.google.com

Installation information:

Google Cloud SDK [90.0.0]

Platform: [Linux, x86_64]
Python Version: [2.7.9 (default, Apr  2 2015, 15:33:21)  [GCC 4.9.2]]
Python Location: [/usr/bin/python2]
Site Packages: [Disabled]

Installation Root: [/home/user/google-cloud-sdk]
Installed Components:
  core: [2015.12.07]
  core-nix: [2015.11.24]
  gcloud: []
  gsutil-nix: [4.15]
  beta: [2015.10.08]
  gsutil: [4.16]
  bq: [2.0.18]
  bq-nix: [2.0.18]
[output truncated]

```

Original issue reported on code.google.com by `ralph.a....@gmail.com` on 23 Feb 2016 at 3:08

**Comment by GoogleCodeExporter** [comment]
```
This error "Unable to find the server at accounts.google.com" is suspect. Where 
are you running this command (ex. locally, on a Google Compute Engine VM, etc.)?

It seems as though your machine is unable to resolve the hostname 
accounts.google.com through DNS, which points to unusual network settings on 
your machine.
```

Original comment by `z...@google.com` on 23 Feb 2016 at 12:42
- Changed state: **NeedsMoreInfo**
