### ISSUE TITLE
gcloud crashed (UnicodeEncodeError) - ascii codec can't encode character \u25aa

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#585]
```
Issue running command [gcloud topic configurations].

What steps will reproduce the problem?
Fresh Fedora 23 install, install Google Cloud SDK, auth w/ a user account from 
Google Apps, gcloud config set project, finally issue: "gcloud topic 
configurations"... crash!


What is the expected output? What do you see instead?
No crash, view topics


Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk/gcloud_main.py", line 171, in main
    gcloud_cli.Execute()
  [...]
  File "third_party/argparse/__init__.py", line 1735, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "third_party/argparse/__init__.py", line 1941, in _parse_known_args
    start_index = consume_optional(start_index)
  File "third_party/argparse/__init__.py", line 1881, in consume_optional
    take_action(action, args, option_string)
  File "third_party/argparse/__init__.py", line 1809, in take_action
    action(self, namespace, argument_values, option_string)
  File "googlecloudsdk/calliope/actions.py", line 402, in __call__
    title=title)
  File "googlecloudsdk/core/document_renderers/render_document.py", line 714, in RenderDocument
    _MarkdownConverter(style_renderer, fin=fin or sys.stdin, notes=notes).Run()
  File "googlecloudsdk/core/document_renderers/render_document.py", line 682, in Run
    i = detect_and_convert(i)
  File "googlecloudsdk/core/document_renderers/render_document.py", line 580, in _ConvertBulletList
    self._renderer.List(self._depth)
  File "googlecloudsdk/core/document_renderers/text_renderer.py", line 194, in List
    self._bullet[(level - 1) % len(self._bullet)])
UnicodeEncodeError: 'ascii' codec can't encode character u'\u25aa' in position 
6: ordinal not in range(128)

[output truncated]

```

Original issue reported on code.google.com by `gabr...@e-radical.ro` on 25 Feb 2016 at 10:53

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the report. You can workaround by:
LC_ALL=C gcloud topic configurations
```

Original comment by `gsfow...@google.com` on 25 Feb 2016 at 11:30
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the report. You can workaround by:
LC_ALL=C gcloud topic configurations
```

Original comment by `gsfow...@google.com` on 25 Feb 2016 at 11:30

**Comment by GoogleCodeExporter** [comment]
```
Workaround confirmed!
[Though I have another system (upgraded from F22, upgraded gcloud from earlier 
versions) that works without issues!]

Regards,
```

Original comment by `gabr...@e-radical.ro` on 26 Feb 2016 at 6:54

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the confirmation.

It makes sense that an earlier version worked. We are trying to wring out all 
of the codec bugs and a refactor to unicode bullets for rendering help docs on 
the fly introduced a new code path.

The fix will be in release 99.0.0 next week.
```

Original comment by `gsfow...@google.com` on 26 Feb 2016 at 12:26

**Comment by GoogleCodeExporter** [comment]
```
Issue 608 has been merged into this issue.
```

Original comment by `gsfow...@google.com` on 1 Mar 2016 at 4:47

**Comment by GoogleCodeExporter** [comment]
```
99.0.0 is out now.
```

Original comment by `z...@google.com` on 4 Mar 2016 at 6:06
- Changed state: **Fixed**
