### ISSUE TITLE
gcloud preview app deploy

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#587]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk\gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  [...]
  File "googlecloudsdk\api_lib\app\images\docker_util.py", line 170, in CopyCerts
    _REMOTE_CERT_FORMAT.format(name=self._name), self.cert_dir])
  File "googlecloudsdk\calliope\cli.py", line 646, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk\calliope\backend.py", line 1394, in Run
    resources = command_instance.Run(args)
  File "surface\compute\copy_files.py", line 129, in Run
    self.ActuallyRun(args, scp_args, user, instance)
  File "googlecloudsdk\api_lib\compute\ssh_utils.py", line 735, in ActuallyRun
    self.WaitUntilSSHable(user, GetExternalIPAddress(instance))
  File "googlecloudsdk\api_lib\compute\ssh_utils.py", line 614, in WaitUntilSSHable
    retval = subprocess.call(ssh_args_for_polling)
  File "C:\python27\lib\subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\python27\lib\subprocess.py", line 913, in _execute_child
    args = list2cmdline(args)
  File "C:\python27\lib\subprocess.py", line 644, in list2cmdline
    return ''.join(result)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcf in position 0: ordinal 
not in range(128)

[output truncated]

```

Original issue reported on code.google.com by `tank7...@gmail.com` on 25 Feb 2016 at 4:18

**Comment by GoogleCodeExporter** [comment]
```
Do any of these contain any non-ascii characters?
- username
- home directory
- gcloud installation directory
```

Original comment by `gsfow...@google.com` on 11 Mar 2016 at 12:40
- Changed state: **NeedsMoreInfo**
