### ISSUE TITLE
"gcloud beta iam service-accounts delete" crashes if you don't provide a fully qualified email address

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#588]
```
Issue running command [gcloud beta iam service].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk/gcloud_main.py", line 171, in main
    gcloud_cli.Execute()
  File "googlecloudsdk/calliope/cli.py", line 646, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk/calliope/backend.py", line 1394, in Run
    resources = command_instance.Run(args)
  File "googlecloudsdk/api_lib/iam/utils.py", line 165, in wrapper
    return func(*args, **kwargs)
  File "googlecloudsdk/api_lib/iam/utils.py", line 136, in wrapper
    return func(*args, **kwargs)
  File "surface/iam/service_accounts/delete.py", line 44, in Run
    self.SetAddress(args.account)
  File "googlecloudsdk/api_lib/iam/base_classes.py", line 86, in SetAddress
    address))
ValueError: IAM address must be an email, given [test-annount]

Installation information:

Google Cloud SDK [98.0.0]

Platform: [Linux, x86_64]
Python Version: [2.7.6 (default, Jun 22 2015, 17:58:13)  [GCC 4.8.2]]
Python Location: [/usr/bin/python2]
Site Packages: [Disabled]

Installation Root: [/usr/local/google/home/kennaway/google-cloud-sdk]
Installed Components:
  kubectl: []
  core-nix: [2016.02.05]
  core: [2016.02.22]
  gcloud: []
  gsutil-nix: [4.15]
  beta: [2016.01.12]
  gsutil: [4.16]
  bq: [2.0.18]
  alpha: [2016.01.12]
  kubectl-linux-x86_64: [1.1.7]
  bq-nix: [2.0.18]
[output truncated]

```

Original issue reported on code.google.com by `kenna...@google.com` on 25 Feb 2016 at 5:22

**Comment by GoogleCodeExporter** [comment]
```
Can you post the exact gcloud command line that produced the problem? Thanks
```

Original comment by `gsfow...@google.com` on 11 Mar 2016 at 12:44
- Changed state: **NeedsMoreInfo**
