### ISSUE TITLE
gcloud dataproc - fails on non-ascii character response 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#589]
```
Issue running command [gcloud dataproc operations describe].

What steps will reproduce the problem?
Within project, google.com:pm-hackathon
gcloud dataproc operations describe bc6f9c32-1b1c-4aeb-8392-86d4feb30e26


What is the expected output? What do you see instead?
CRASH!

Please provide any additional information below.


Traceback (most recent call last):
  File "gcloud_main.py", line 171, in main
    gcloud_cli.Execute()
  File "calliope/cli.py", line 646, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "calliope/backend.py", line 1394, in Run
    resources = command_instance.Run(args)
  File "api_lib/dataproc/util.py", line 76, in CatchHTTPErrorRaiseHTTPException
    msg = FormatHttpError(error)
  File "api_lib/dataproc/util.py", line 46, in FormatHttpError
    return str(error)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 
2531-2533: ordinal not in range(128)

Installation information:

Google Cloud SDK [98.0.0]

Platform: [Mac OS X, x86_64]
Python Version: [2.7.10 (default, Oct 23 2015, 18:05:06)  [GCC 4.2.1 Compatible 
Apple LLVM 7.0.0 (clang-700.0.59.5)]]
Python Location: [/workspace/pm-hackathon/bin/python2]
Site Packages: [Enabled]

Installation Root: [/Users/taim/google-cloud-sdk]
Installed Components:
  core: [2016.02.22]
  core-nix: [2016.02.05]
  gcloud: []
  gsutil-nix: [4.15]
  gsutil: [4.16]
  bq: [2.0.18]
  bq-nix: [2.0.18]
System PATH: 
[/workspace/pm-hackathon/bin:/Users/taim/google-cloud-sdk/bin:/usr/local/git/cur
rent/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin]
Cloud SDK on PATH: [True]

Installation Properties: [/Users/taim/google-cloud-sdk/properties]
[output truncated]

```

Original issue reported on code.google.com by `t...@google.com` on 25 Feb 2016 at 6:59

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the report. We have an internal issue tracking this.
```

Original comment by `gsfow...@google.com` on 11 Mar 2016 at 12:48
- Changed state: **Accepted**
