### ISSUE TITLE
check this out

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#593]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk\gcloud_main.py", line 171, in main
    gcloud_cli.Execute()
  File "googlecloudsdk\calliope\cli.py", line 646, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk\calliope\backend.py", line 1394, in Run
    resources = command_instance.Run(args)
  File "surface\preview\app\deploy.py", line 404, in Run
    config_cleanup = configurator.GenerateConfigs()
AttributeError: 'NoneType' object has no attribute 'GenerateConfigs'

Installation information:

Google Cloud SDK [98.0.0]

Platform: [Windows, x86_64]
Python Version: [2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit 
(Intel)]]
Python Location: [C:\Users\chu\AppData\Local\Google\Cloud 
SDK\google-cloud-sdk\platform\bundledpython\python.exe]
Site Packages: [Disabled]

Installation Root: [C:\Users\chu\AppData\Local\Google\Cloud 
SDK\google-cloud-sdk]
Installed Components:
  bundled-python: [2.7.10]
  bq-win: [2.0.18]
  core: [2016.02.22]
  core-win: [2016.02.05]
  gcloud: []
  windows-ssh-tools: [2016.02.22]
  gsutil: [4.16]
  bq: [2.0.18]
  gsutil-win: [4.16]
[output truncated]

```

Original issue reported on code.google.com by `lambton...@gmail.com` on 25 Feb 2016 at 9:37
- Merged into: #544

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 25 Feb 2016 at 9:39
- Changed state: **Duplicate**
