### ISSUE TITLE
App deploy issue

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#595]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?

Changed some code and ran 'gcloud preview app deploy'

What is the expected output? What do you see instead?

Expected it to deploy my code like normal.  Instead it errors out with 
'Beginning deployment...
If this is your first deployment, this may take a while...done.

Verifying that Managed VMs are enabled and ready.
Provisioning remote build service.
Copying certificates for secure access. You may be prompted to create an SSH 
keypair.
ERROR: gcloud crashed (TLSParameterError): Path to a certificate and key files 
must be provided through the client_config param. TLS configurations should map 
the Docker CLI client configurations. See 
http://docs.docker.com/examples/https/ for API details.
'


Please provide any additional information below.

I was able to hit deploy again the first time it happened, but now it appears 
to be happening every time.


Traceback (most recent call last):
  File "googlecloudsdk/gcloud_main.py", line 171, in main
    gcloud_cli.Execute()
  File "googlecloudsdk/calliope/cli.py", line 646, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk/calliope/backend.py", line 1394, in Run
    resources = command_instance.Run(args)
  File "surface/preview/app/deploy.py", line 483, in Run
    config_cleanup)
  File "googlecloudsdk/api_lib/app/deploy_command_util.py", line 200, in BuildAndPushDockerImages
    cli, version_id, remote, project) as docker_client:
  File "googlecloudsdk/api_lib/app/images/docker_util.py", line 237, in __enter__
    kwargs = containers.KwargsFromEnv(self._vm.host, self._vm.cert_dir, True)
  File "googlecloudsdk/api_lib/app/containers.py", line 100, in KwargsFromEnv
    assert_hostname=False)
  File "third_party/docker/docker/tls.py", line 46, in __init__
    'Path to a certificate and key files must be provided'
TLSParameterError: Path to a certificate and key files must be provided through 
the client_config param. TLS configurations should map the Docker CLI client 
configurations. See http://docs.docker.com/examples/https/ for API details.

Installation information:

Google Cloud SDK [98.0.0]

Platform: [Mac OS X, x86_64]
Python Version: [2.7.10 (default, Oct 23 2015, 18:05:06)  [GCC 4.2.1 Compatible 
Apple LLVM 7.0.0 (clang-700.0.59.5)]]
Python Location: [/usr/bin/python]
Site Packages: [Disabled]

[output truncated]

```

Original issue reported on code.google.com by `dds1...@gmail.com` on 26 Feb 2016 at 9:59
- Merged into: #559

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 26 Feb 2016 at 10:00
- Changed state: **Duplicate**
