### ISSUE TITLE
Cannot upload the app to gcloud

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#596]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk\gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  File "googlecloudsdk\calliope\cli.py", line 646, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk\calliope\backend.py", line 1394, in Run
    resources = command_instance.Run(args)
  File "surface\preview\app\deploy.py", line 482, in Run
    config_cleanup)
  File "googlecloudsdk\api_lib\app\deploy_command_util.py", line 189, in BuildAndPushDockerImages
    code_bucket, cloudbuild_client, http)
  File "googlecloudsdk\api_lib\app\deploy_command_util.py", line 236, in _BuildImagesWithCloudBuild
    cloud_build.UploadSource(image.dockerfile_dir, source_gcs_uri)
  File "googlecloudsdk\api_lib\app\cloud_build.py", line 100, in UploadSource
    shutil.rmtree(temp_dir)
  File "C:\python27\lib\shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "C:\python27\lib\shutil.py", line 250, in rmtree
    os.remove(fullname)
WindowsError: [Error 32] The process cannot access the file because it is being 
used by another process: 
'c:\\users\\supun\\appdata\\local\\temp\\tmp21j8wi\\src.tgz'

Installation information:

Google Cloud SDK [97.0.0]

Platform: [Windows, x86_64]
Python Version: [2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit 
(AMD64)]]
Python Location: [C:\python27\python.exe]
[output truncated]

```

Original issue reported on code.google.com by `induwara...@gmail.com` on 27 Feb 2016 at 6:57
- Merged into: #554

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 28 Feb 2016 at 10:51
- Changed state: **Duplicate**
