### ISSUE TITLE
Cannot install google-cloud-sdk on Ubuntu 14.04

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#60]
```
What steps will reproduce the problem?
1. Upgrade Ubuntu from 12.04 to 14.04
2. Run the install script as instructed here 
https://developers.google.com/cloud/sdk/

What is the expected output? What do you see instead?
- Expected result: gcloud tool should be installed
- Actual result: "SSLError: The read operation timed out"

What is the output of 'gcloud version'?
- NONE

Please provide any additional information below.

Here is the stack trace:

Installing: gcloud app Python Extensions ... Traceback (most recent call last):
  File "/usr/lib/google/google-cloud-sdk/bin/bootstrapping/install.py", line 367, in <module>
    main()
  File "/usr/lib/google/google-cloud-sdk/bin/bootstrapping/install.py", line 346, in main
    pargs.additional_components)
  File "/usr/lib/google/google-cloud-sdk/bin/bootstrapping/install.py", line 309, in Install
    components = InstallComponents(to_install)
  File "/usr/lib/google/google-cloud-sdk/bin/bootstrapping/install.py", line 331, in InstallComponents
    components.update(component_ids=component_ids, allow_no_backup=True)
  File "/usr/lib/google/google-cloud-sdk/bin/bootstrapping/../../lib/googlecloudsdk/calliope/frontend.py", line 235, in __call__
    post_run_hooks=None, kwargs=kwargs)
  File "/usr/lib/google/google-cloud-sdk/bin/bootstrapping/../../lib/googlecloudsdk/calliope/frontend.py", line 274, in _Execute
    pre_run_hooks=pre_run_hooks, post_run_hooks=post_run_hooks)
  File "/usr/lib/google/google-cloud-sdk/bin/bootstrapping/../../lib/googlecloudsdk/calliope/backend.py", line 878, in Run
    result = command_instance.Run(args)
  File "/usr/lib/google/google-cloud-sdk/lib/googlecloudsdk/gcloud/sdktools/components/update.py", line 65, in Run
    args.component_ids, allow_no_backup=args.allow_no_backup)
  File "/usr/lib/google/google-cloud-sdk/bin/bootstrapping/../../lib/googlecloudsdk/core/updater/update_manager.py", line 457, in Update
    self._InstallFunction(staging_state, diff))
  File "/usr/lib/google/google-cloud-sdk/bin/bootstrapping/../../lib/googlecloudsdk/core/updater/update_manager.py", line 372, in _UpdateAndPrint
    action_func(component.id)
  File "/usr/lib/google/google-cloud-sdk/bin/bootstrapping/../../lib/googlecloudsdk/core/updater/update_manager.py", line 378, in Inner
    return install_state.Install(diff.latest, component_id)
  File "/usr/lib/google/google-cloud-sdk/bin/bootstrapping/../../lib/googlecloudsdk/core/updater/local_state.py", line 80, in _TryFunc
    return func(*args, **kwargs)
  File "/usr/lib/google/google-cloud-sdk/bin/bootstrapping/../../lib/googlecloudsdk/core/updater/local_state.py", line 418, in Install
    files = self._GetInstaller(snapshot).Install(component_id)
  File "/usr/lib/google/google-cloud-sdk/bin/bootstrapping/../../lib/googlecloudsdk/core/updater/installers.py", line 109, in Install
    return self._InstallTar(component)
  File "/usr/lib/google/google-cloud-sdk/bin/bootstrapping/../../lib/googlecloudsdk/core/updater/installers.py", line 144, in _InstallTar
    url, self.__download_directory, self.__sdk_root)
  File "/usr/lib/google/google-cloud-sdk/bin/bootstrapping/../../lib/googlecloudsdk/core/updater/installers.py", line 176, in DownloadAndExtractTar
    shutil.copyfileobj(req, fp)
  File "/usr/lib/python2.7/shutil.py", line 49, in copyfileobj
    buf = fsrc.read(length)
  File "/usr/lib/python2.7/socket.py", line 380, in read
    data = self._sock.recv(left)
  File "/usr/lib/python2.7/httplib.py", line 567, in read
    s = self.fp.read(amt)
  File "/usr/lib/python2.7/socket.py", line 380, in read
    data = self._sock.recv(left)
  File "/usr/lib/python2.7/ssl.py", line 341, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 260, in read
    return self._sslobj.read(len)
ssl.SSLError: The read operation timed out

```

Original issue reported on code.google.com by `giakhanh...@gmail.com` on 20 Jul 2014 at 6:13

**Comment by GoogleCodeExporter** [comment]
```
I moved the extracted folder to my home directory and it worked just fine. 
Thanks!
```

Original comment by `giakhanh...@gmail.com` on 20 Jul 2014 at 6:31

**Comment by GoogleCodeExporter** [comment]
```
What do you mean to the extracted folder?
```

Original comment by `chuck.go...@gmail.com` on 31 Jul 2014 at 7:32

**Comment by GoogleCodeExporter** [comment]
```
Hi chuck,
I downloaded the zip package and extracted the content to a folder. That's all. 
It was just a permission stupid mistake I could have avoided.
```

Original comment by `giakhanh...@gmail.com` on 31 Jul 2014 at 10:40

**Comment by GoogleCodeExporter** [comment]
```
I encountered the same problem :(
```

Original comment by `sreejith...@gmail.com` on 9 Aug 2014 at 7:37

**Comment by GoogleCodeExporter** [comment]
```
Looks like we might have a break on the newest version of Ubuntu. Could you 
take a look and see what's going on?
```

Original comment by `rdayal@google.com` on 11 Aug 2014 at 2:19

**Comment by GoogleCodeExporter** [comment]
```
@sreejith You may want to copy the downloaded package to your home directory, 
extract and execute the installation script from there. That is exactly what I 
do. Could be a quick fix your you.
```

Original comment by `giakhanh...@gmail.com` on 11 Aug 2014 at 2:45

**Comment by GoogleCodeExporter** [comment]
```
I'm having the same problem after upgrading to latest ubuntu this morning. I 
suspect it might be a ssl issue. 
```

Original comment by `samkiller@gmail.com` on 9 Nov 2014 at 6:56

**Comment by GoogleCodeExporter** [comment]
Original comment by `rdayal@google.com` on 9 Nov 2014 at 7:02

**Comment by GoogleCodeExporter** [comment]
```
sorry .. doesn't seem to be an ssl mistake. Rather a permission one.
So first tried to get the sdk install via curl, and failed miserably ... Then 
did it via sudo curl ..... and worked fine.
But after trying to log via gcloud auth login, I ran into some other errors. 
*There seemed to be an error with permission at ~/.config/gcloud/gce file. I 
did a chown on the file ... and suddenly it worked.
```

Original comment by `samkiller@gmail.com` on 9 Nov 2014 at 7:06

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
Original comment by `rdayal@google.com` on 11 Feb 2015 at 3:23

**Comment by GoogleCodeExporter** [comment]
```
Please re-open if you're still experiencing this. I've installed gcloud on 
Ubuntu 14.04 and it's worked like a charm.
```

Original comment by `z...@google.com` on 27 Aug 2015 at 11:03
- Changed state: **Obsolete**
