### ISSUE TITLE
ERROR: gcloud crashed (DockerException): Error while fetching server API version: ('Connection aborted.', error(61, 'Connection refused'))

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#606]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?
Deploying a Node app using the app.yaml from the Hello World examples, e.g.:
# [START runtime]
runtime: nodejs
vm: true
# [END runtime]

# Temporary setting to keep gcloud from uploading node_modules
skip_files:
 - ^node_modules$

What is the expected output? What do you see instead?
I would expect it to deploy successfully.  

Initial output:

Daniels-MacBook-Pro:support dallen$ gcloud preview app deploy
You are about to deploy the following modules:
 - my-project/default (from [/Users/dallen/dev/support/app.yaml])
     Deployed URL: [https://my-project.appspot.com]

Do you want to continue (Y/n)?  Y

Beginning deployment...
If this is your first deployment, this may take a while...done.

Verifying that Managed VMs are enabled and ready.
Provisioning remote build service.
Copying certificates for secure access. You may be prompted to create an SSH 
keypair.
ERROR: gcloud crashed (DockerException): Error while fetching server API 
version: ('Connection aborted.', error(61, 'Connection refused'))



Below is the additional truncated information:

Platform: [Mac OS X, x86_64]
Python Version: [2.7.10 (default, Oct 23 2015, 18:05:06)  [GCC 4.2.1 Compatible 
Apple LLVM 7.0.0 (clang-700.0.59.5)]]
Python Location: [/usr/bin/python]
Site Packages: [Disabled]

Installation Root: [/Users/dallen/dev/google-cloud-sdk]
Installed Components:
  core: [2016.02.22]
  core-nix: [2016.02.05]
  gcloud: []
  gsutil-nix: [4.15]
  gsutil: [4.16]
  bq: [2.0.18]
  bq-nix: [2.0.18]
System PATH: 
[/Users/dallen/dev/google-cloud-sdk/bin:/Users/dallen/dev/apache-maven-3.3.9/bin
:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/dallen/dev/appengine-java-s
dk-1.9.18/bin/:/data/db]
Cloud SDK on PATH: [True]

Installation Properties: [/Users/dallen/dev/google-cloud-sdk/properties]
User Config Directory: [/Users/dallen/.config/gcloud]
User Properties: [/Users/dallen/.config/gcloud/properties]
Current Workspace: [None]
Workspace Config Directory: [None]
Workspace Properties: [None]

Account: [my account - removed for privacy]
Project: [my project - removed for privacy]

Current Properties:
  [core]
    project: [my project - removed for privacy]
    account: [my account - removed for privacy]
    disable_usage_reporting: [False]
  [app]
    suppress_change_warning: [true]

Logs Directory: [/Users/dallen/.config/gcloud/logs]
Last Log File: 
[/Users/dallen/.config/gcloud/logs/2016.02.29/15.55.38.798965.log]
Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk/gcloud_main.py", line 171, in main
    gcloud_cli.Execute()
  File "googlecloudsdk/calliope/cli.py", line 646, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk/calliope/backend.py", line 1394, in Run
    resources = command_instance.Run(args)
  File "surface/preview/app/deploy.py", line 483, in Run
    config_cleanup)
  File "googlecloudsdk/api_lib/app/deploy_command_util.py", line 200, in BuildAndPushDockerImages
    cli, version_id, remote, project) as docker_client:
  File "googlecloudsdk/api_lib/app/images/docker_util.py", line 243, in __enter__
    return containers.NewDockerClient(local=(not self._remote), **kwargs)
  File "googlecloudsdk/api_lib/app/containers.py", line 139, in NewDockerClient
    client = NewDockerClientNoCheck(**kwargs)
  File "googlecloudsdk/api_lib/app/containers.py", line 122, in NewDockerClientNoCheck
    return docker.Client(**kwargs)
  File "third_party/docker/docker/client.py", line 77, in __init__
    self._version = self._retrieve_server_version()
  File "third_party/docker/docker/client.py", line 97, in _retrieve_server_version
    'Error while fetching server API version: {0}'.format(e)
DockerException: Error while fetching server API version: ('Connection 
aborted.', error(61, 'Connection refused'))

Installation information:

Google Cloud SDK [98.0.0]

[output truncated]

```

Original issue reported on code.google.com by `daniel-a...@vetconnectplus.com` on 29 Feb 2016 at 9:03
- Merged into: #469

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 29 Feb 2016 at 9:06
- Changed state: **Duplicate**
