### ISSUE TITLE
Crash running topic configurations

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#607]
```
Issue running command [gcloud topic configurations].

What steps will reproduce the problem?
Run the command on Goobuntu

What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk/gcloud_main.py", line 171, in main
    gcloud_cli.Execute()
  [...]
  File "third_party/argparse/__init__.py", line 1735, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "third_party/argparse/__init__.py", line 1941, in _parse_known_args
    start_index = consume_optional(start_index)
  File "third_party/argparse/__init__.py", line 1881, in consume_optional
    take_action(action, args, option_string)
  File "third_party/argparse/__init__.py", line 1809, in take_action
    action(self, namespace, argument_values, option_string)
  File "googlecloudsdk/calliope/actions.py", line 402, in __call__
    title=title)
  File "googlecloudsdk/core/document_renderers/render_document.py", line 714, in RenderDocument
    _MarkdownConverter(style_renderer, fin=fin or sys.stdin, notes=notes).Run()
  File "googlecloudsdk/core/document_renderers/render_document.py", line 682, in Run
    i = detect_and_convert(i)
  File "googlecloudsdk/core/document_renderers/render_document.py", line 580, in _ConvertBulletList
    self._renderer.List(self._depth)
  File "googlecloudsdk/core/document_renderers/text_renderer.py", line 194, in List
    self._bullet[(level - 1) % len(self._bullet)])
UnicodeEncodeError: 'ascii' codec can't encode character u'\u25aa' in position 
6: ordinal not in range(128)

[output truncated]

```

Original issue reported on code.google.com by `shan...@google.com` on 29 Feb 2016 at 11:28

**Comment by GoogleCodeExporter** [comment]
```
This has been fixed in next release.
```

Original comment by `che...@google.com` on 1 Mar 2016 at 2:30
- Changed state: **Fixed**
