### ISSUE TITLE
Can not deploy MVM app

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#610]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk/gcloud_main.py", line 171, in main
    gcloud_cli.Execute()
  [...]
  File "googlecloudsdk/api_lib/app/cloud_build.py", line 170, in ExecuteCloudBuild
    retry_callback=log_tailer.Poll)
  File "googlecloudsdk/api_lib/app/api/operations.py", line 61, in WaitForOperation
    retry_callback)
  File "googlecloudsdk/api_lib/app/api/operations.py", line 94, in _PollUntilDone
    retry_callback()
  File "googlecloudsdk/api_lib/app/cloud_storage.py", line 218, in Poll
    raise api_exceptions.HttpError(res, body, self.url)
HttpError: HttpError accessing 
<https://www.googleapis.com/storage/v1/b/staging.strydweb.appspot.com/o/log-f524
a4be-b28a-4bd3-ad67-2815d2db2708.txt?alt=media>: response: <{'status': '500', 
'alternate-protocol': '443:quic,p=1', 'content-length': '13', 'cache-control': 
'private, max-age=0', 'expires': 'Tue, 01 Mar 2016 22:03:22 GMT', 'vary': 
'Origin, X-Origin', 'server': 'UploadServer', 'x-guploader-uploadid': 
'AEnB2UpQ7HgMCkdt9WAFRXgvTpj-dEU23K3TJbWLvwEnCoQbycrJ-qYX9PUO1U6E8EvFanMDmP58Aho
chog9nKX_wbBhZoGrhQ', 'date': 'Tue, 01 Mar 2016 22:03:22 GMT', 'alt-svc': 
'quic=":443"; ma=2592000; v="30,29,28,27,26,25"', 'content-type': 'text/html; 
charset=UTF-8'}>, content <Backend Error>

[output truncated]

```

Original issue reported on code.google.com by `k...@stryd.com` on 1 Mar 2016 at 10:05

**Comment by GoogleCodeExporter** [comment]
```
Thanks for reporting this. Is this reproducible? The 500 error here should be 
temporary.
```

Original comment by `z...@google.com` on 1 Mar 2016 at 11:40
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
It appeared twice when I was trying to deploy to the same version which is live 
in production. If I don't specify that version, then everything is fine.

Can't produce it now.
```

Original comment by `k...@stryd.com` on 2 Mar 2016 at 12:17

**Comment by GoogleCodeExporter** [comment]
```
I think this was a temporary service hiccup. If you ever see it again, let us 
know and we'll investigate further.
```

Original comment by `z...@google.com` on 2 Mar 2016 at 3:11
- Changed state: **Invalid**
