### ISSUE TITLE
Path to a certificate and key files must be provided

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#614]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?

I am using Ubuntu 14.04 behind a proxy.

Download & install go language
Download & install google cloud sdk
Download & install go appengine sdk

go get -u -d 
github.com/GoogleCloudPlatform/golang-samples/docs/managed_vms/helloworld
cd 
$GOPATH/src/github.com/GoogleCloudPlatform/golang-samples/docs/managed_vms/hello
world
go get google.golang.org/appengine/cmd/aedeploy
aedeploy gcloud preview app deploy app.yaml --promote

What is the expected output? What do you see instead?

Regular deployment on appengine using managed VM. Instead, crash.

Please provide any additional information below.

Traceback (most recent call last):
  File "lib/google-cloud-sdk/lib/googlecloudsdk/gcloud_main.py", line 171, in main
    gcloud_cli.Execute()
  File "lib/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 646, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "lib/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 1394, in Run
    resources = command_instance.Run(args)
  File "lib/google-cloud-sdk/lib/surface/preview/app/deploy.py", line 483, in Run
    config_cleanup)
  File "lib/google-cloud-sdk/lib/googlecloudsdk/api_lib/app/deploy_command_util.py", line 200, in BuildAndPushDockerImages
    cli, version_id, remote, project) as docker_client:
  File "lib/google-cloud-sdk/lib/googlecloudsdk/api_lib/app/images/docker_util.py", line 237, in __enter__
    kwargs = containers.KwargsFromEnv(self._vm.host, self._vm.cert_dir, True)
  File "lib/google-cloud-sdk/lib/googlecloudsdk/api_lib/app/containers.py", line 100, in KwargsFromEnv
    assert_hostname=False)
  File "bin/../lib/google-cloud-sdk/lib/third_party/docker/docker/tls.py", line 46, in __init__
    'Path to a certificate and key files must be provided'
TLSParameterError: Path to a certificate and key files must be provided through 
the client_config param. TLS configurations should map the Docker CLI client 
configurations. See http://docs.docker.com/examples/https/ for API details.

Installation information:

Google Cloud SDK [98.0.0]
Ubuntu 14.04

[output truncated]

```

Original issue reported on code.google.com by `cuihtlau...@gmail.com` on 2 Mar 2016 at 10:44
- Merged into: #559

**Comment by GoogleCodeExporter** [comment]
Original comment by `che...@google.com` on 2 Mar 2016 at 2:00
- Changed state: **Duplicate**
