### ISSUE TITLE
ERROR: gcloud crashed (ConnectionError): ('Connection aborted.', error(104, 'Connection reset by peer'))

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#615]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?
Beginning teardown of remote build environment (this may take a few seconds)
ERROR: gcloud crashed (ConnectionError): ('Connection aborted.', error(104, 
'Connection reset by peer'))



What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "lib/google-cloud-sdk/lib/googlecloudsdk/gcloud_main.py", line 171, in main
    gcloud_cli.Execute()
  [...]
  File "lib/google-cloud-sdk/lib/googlecloudsdk/api_lib/app/deploy_command_util.py", line 285, in BuildAndPushDockerImage
    image.Build(docker_client)
  File "lib/google-cloud-sdk/lib/googlecloudsdk/api_lib/app/docker_image.py", line 110, in Build
    nocache=self._nocache, rm=self._rm, pull=False)
  File "bin/../lib/google-cloud-sdk/lib/third_party/docker/docker/api/build.py", line 97, in build
    timeout=timeout,
  File "bin/../lib/google-cloud-sdk/lib/third_party/docker/docker/client.py", line 107, in _post
    return self.post(url, **self._set_request_timeout(kwargs))
  File "bin/../lib/google-cloud-sdk/lib/third_party/requests/sessions.py", line 507, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "bin/../lib/google-cloud-sdk/lib/third_party/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "bin/../lib/google-cloud-sdk/lib/third_party/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "bin/../lib/google-cloud-sdk/lib/third_party/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
[output truncated]

```

Original issue reported on code.google.com by `amiash...@gmail.com` on 2 Mar 2016 at 11:44
- Merged into: #297

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 2 Mar 2016 at 2:34
- Changed state: **Duplicate**
