### ISSUE TITLE
COuld not deploy my application

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#616]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk/gcloud_main.py", line 171, in main
    gcloud_cli.Execute()
  File "googlecloudsdk/calliope/cli.py", line 646, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk/calliope/backend.py", line 1394, in Run
    resources = command_instance.Run(args)
  File "surface/preview/app/deploy.py", line 404, in Run
    config_cleanup = configurator.GenerateConfigs()
AttributeError: 'NoneType' object has no attribute 'GenerateConfigs'

Installation information:

Google Cloud SDK [98.0.0]

Platform: [Mac OS X, x86_64]
Python Version: [2.7.10 (default, Oct 23 2015, 18:05:06)  [GCC 4.2.1 Compatible 
Apple LLVM 7.0.0 (clang-700.0.59.5)]]
Python Location: [/usr/bin/python]
Site Packages: [Disabled]

Installation Root: [/Users/lorenamorao/google-cloud-sdk]
Installed Components:
  core: [2016.02.22]
  core-nix: [2016.02.05]
  gcloud: []
  gsutil-nix: [4.15]
  gsutil: [4.16]
  bq: [2.0.18]
  bq-nix: [2.0.18]
[output truncated]

```

Original issue reported on code.google.com by `epae...@gmail.com` on 2 Mar 2016 at 2:45
- Merged into: #544

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 2 Mar 2016 at 2:46
- Changed state: **Duplicate**
