### ISSUE TITLE
after login in browser and shows "You are now authenticated with the Google Cloud SDK!", the gcloud crashed in my terminal

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#618]
```
Issue running command [gcloud auth login].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk/gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  [...]
  File "third_party/httplib2/__init__.py", line 1352, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "third_party/httplib2/__init__.py", line 1272, in _conn_request
    conn.connect()
  File "third_party/httplib2/__init__.py", line 1047, in connect
    'host %s: %s' % (hostname, cert), hostname, cert)
CertificateHostnameMismatch: Server presented certificate that does not match 
host accounts.google.com: {'notAfter': 'May 17 00:00:00 2016 GMT', 
'subjectAltName': (('DNS', '*.orkut.com'), ('DNS', '*.a.orkut.gmodules.com'), 
('DNS', '*.demo.orkut.com'), ('DNS', '*.orkut.co.in'), ('DNS', 
'*.orkut.com.br'), ('DNS', '*.orkut.gmodules.com'), ('DNS', 
'*.staging.orkut.com'), ('DNS', '*.www.orkut.com'), ('DNS', 'orkut.co.in'), 
('DNS', 'orkut.com'), ('DNS', 'orkut.com.br')), 'subject': ((('countryName', 
u'US'),), (('stateOrProvinceName', u'California'),), (('localityName', 
u'Mountain View'),), (('organizationName', u'Google Inc'),), (('commonName', 
u'*.orkut.com'),))}

[output truncated]

```

Original issue reported on code.google.com by `lsy20090605` on 3 Mar 2016 at 7:51

**Comment by GoogleCodeExporter** [comment]
```
Thanks for reporting the issue.

By any chance you are on guest wifi network? Does the issue remains if you 
retry the command?

```

Original comment by `che...@google.com` on 3 Mar 2016 at 2:34
- Changed state: **NeedsMoreInfo**
