### ISSUE TITLE
gcloud crashed (ServerNotFoundError)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#619]
```
Issue running command [gcloud auth login].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  [...]
  File "core\credentials\store.py", line 445, in AcquireFromWebFlow
    http=_Http())
  File "core\credentials\flow.py", line 170, in Run
    credential = flow.step2_exchange(code, http=http)
  File "C:\Program Files\Google\Cloud SDK\bin\..\lib\third_party\oauth2client\util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Program Files\Google\Cloud SDK\bin\..\lib\third_party\oauth2client\client.py", line 2000, in step2_exchange
    headers=headers)
  File "C:\Program Files\Google\Cloud SDK\bin\..\lib\third_party\httplib2\__init__.py", line 1610, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "C:\Program Files\Google\Cloud SDK\bin\..\lib\third_party\httplib2\__init__.py", line 1352, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "C:\Program Files\Google\Cloud SDK\bin\..\lib\third_party\httplib2\__init__.py", line 1278, in _conn_request
    raise ServerNotFoundError("Unable to find the server at %s" % conn.host)
ServerNotFoundError: Unable to find the server at accounts.google.com

[output truncated]

```

Original issue reported on code.google.com by `tateishi...@gmail.com` on 3 Mar 2016 at 9:29

**Comment by GoogleCodeExporter** [comment]
```
Thanks for reporting the issue.

By any chance you are behind some firewall/proxy? If so, have you tried setting 
http_proxy/https_proxy environment variables. You can also set gcloud settings 
to configure proxy parameters: 
https://cloud.google.com/sdk/gcloud/reference/config/set
```

Original comment by `che...@google.com` on 3 Mar 2016 at 2:44
- Changed state: **NeedsMoreInfo**
