### ISSUE TITLE
glcoud docker push fails (possible proxy issue perhaps) ?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#620]
```
Issue running command [gcloud docker].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk/gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  [...]
  File "surface/docker.py", line 111, in Run
    docker.UpdateDockerCredentials(server)
  File "googlecloudsdk/core/docker/docker.py", line 145, in UpdateDockerCredentials
    store.Refresh(cred)
  File "googlecloudsdk/core/credentials/store.py", line 304, in Refresh
    creds.refresh(http or _Http())
  File "third_party/oauth2client/client.py", line 604, in refresh
    self._refresh(http.request)
  File "third_party/oauth2client/client.py", line 787, in _refresh
    self._do_refresh_request(http_request)
  File "third_party/oauth2client/client.py", line 806, in _do_refresh_request
    self.token_uri, method='POST', body=body, headers=headers)
  File "third_party/httplib2/__init__.py", line 1610, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "third_party/httplib2/__init__.py", line 1352, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "third_party/httplib2/__init__.py", line 1308, in _conn_request
    response = conn.getresponse()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1033, in getresponse
    raise ResponseNotReady()
ResponseNotReady

[output truncated]

```

Original issue reported on code.google.com by `nick.sca...@gmail.com` on 3 Mar 2016 at 8:40

**Comment by GoogleCodeExporter** [comment]
```
Thank you for your feedback. To help us investigate this further, can you 
please provide the following:

- Complete stack trace
- Output of gcloud info

Note: Please redact any personal information before sharing the information.
```

Original comment by `vil...@google.com` on 4 Mar 2016 at 8:40
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
Also, have you tried re-running the command? Does the problem persist?

Additionally, are you behind a proxy? If so, what kind?
```

Original comment by `vil...@google.com` on 5 Mar 2016 at 2:53

**Comment by GoogleCodeExporter** [comment]
```
Definitely seems like a proxy issue. I had both http_proxy & https_proxy
set properly (uppercase too) as the normal gcloud commands work. When off
proxy gcloud docker push worked fine.
```

Original comment by `nick.sca...@gmail.com` on 5 Mar 2016 at 3:58

**Comment by GoogleCodeExporter** [comment]
```
Can you share what you had http_proxy & https_proxy set to?

Did `gcloud docker push` fail every time you re-ran the command?
```

Original comment by `vil...@google.com` on 6 Mar 2016 at 2:05

**Comment by GoogleCodeExporter** [comment]
```
It was your normal http proxy:

http_proxy=http://<user>:<pass>@proxy.example.com:<port>

I can try it again on Monday. Yes it failed every time, just seemed to hang
there.
```

Original comment by `nick.sca...@gmail.com` on 6 Mar 2016 at 2:32

**Comment by GoogleCodeExporter** [comment]
```
Strange, that should work. We use httplib2, which should be able to handle the 
proxy definition  as shown here: 
https://github.com/jcgregorio/httplib2/blob/master/python2/httplib2/__init__.py#
L828 .

You are using a socks proxy, right?
```

Original comment by `vil...@google.com` on 6 Mar 2016 at 10:16

**Comment by GoogleCodeExporter** [comment]
```
You can close this. Networking issue on our side.
```

Original comment by `nick.sca...@gmail.com` on 7 Mar 2016 at 6:56

**Comment by GoogleCodeExporter** [comment]
```
Thanks for clarifying.
```

Original comment by `vil...@google.com` on 8 Mar 2016 at 4:34
- Changed state: **WorkingAsIntended**
