### ISSUE TITLE
help please

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#621]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk/gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  File "googlecloudsdk/calliope/cli.py", line 652, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk/calliope/backend.py", line 1394, in Run
    resources = command_instance.Run(args)
  File "surface/preview/app/deploy.py", line 494, in Run
    config_cleanup)
  File "googlecloudsdk/api_lib/app/deploy_command_util.py", line 200, in BuildAndPushDockerImages
    cli, version_id, remote, project) as docker_client:
  File "googlecloudsdk/api_lib/app/images/docker_util.py", line 254, in __enter__
    return containers.NewDockerClient(local=(not self._remote), **kwargs)
  File "googlecloudsdk/api_lib/app/containers.py", line 150, in NewDockerClient
    client = NewDockerClientNoCheck(**kwargs)
  File "googlecloudsdk/api_lib/app/containers.py", line 133, in NewDockerClientNoCheck
    return docker.Client(**kwargs)
  File "third_party/docker/docker/client.py", line 77, in __init__
    self._version = self._retrieve_server_version()
  File "third_party/docker/docker/client.py", line 97, in _retrieve_server_version
    'Error while fetching server API version: {0}'.format(e)
DockerException: Error while fetching server API version: [SSL: 
CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

Installation information:

Google Cloud SDK [99.0.0]

[output truncated]

```

Original issue reported on code.google.com by `moltedi...@gmail.com` on 3 Mar 2016 at 9:46
- Merged into: #476

**Comment by GoogleCodeExporter** [comment]
```
Thank you for your feedback. To help us investigate this further, can you 
please provide the following:

- Complete stack trace
- Complete output of gcloud info

Note: Please redact any personal information before sharing the information.
```

Original comment by `vil...@google.com` on 4 Mar 2016 at 8:41
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
Hi this is te gcloud info output:

====================================================

Google Cloud SDK [99.0.0]

Platform: [Linux, x86_64]
Python Version: [2.7.10 (default, Oct 14 2015, 16:09:02)  [GCC 5.2.1 20151010]]
Python Location: [/usr/bin/python2]
Site Packages: [Disabled]

Installation Root: [/home/diego/google-cloud-sdk]
Installed Components:
  core: [2016.02.26]
  core-nix: [2016.02.05]
  gcloud: []
  gsutil-nix: [4.15]
  gsutil: [4.17]
  bq: [2.0.18]
  bq-nix: [2.0.18]
System PATH: 
[/home/diego/google-cloud-sdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/
bin:/sbin:/bin:/usr/games:/usr/local/games]
Cloud SDK on PATH: [True]

Installation Properties: [/home/diego/google-cloud-sdk/properties]
User Config Directory: [/home/diego/.config/gcloud]
User Properties: [/home/diego/.config/gcloud/properties]

Account: [moltediego@gmail.com]
Project: [testjs-1240]

Current Properties:
  [core]
    project: [testjs-1240]
    account: [moltediego@gmail.com]
    disable_usage_reporting: [False]
  [app]
    suppress_change_warning: [true]

Logs Directory: [/home/diego/.config/gcloud/logs]
Last Log File: [/home/diego/.config/gcloud/logs/2016.03.04/15.06.46.709437.log]

====================================================

```

Original comment by `moltedi...@gmail.com` on 4 Mar 2016 at 9:09

**Comment by GoogleCodeExporter** [comment]
```
Issue 622 has been merged into this issue.
```

Original comment by `vil...@google.com` on 5 Mar 2016 at 2:21

**Comment by GoogleCodeExporter** [comment]
Original comment by `vil...@google.com` on 5 Mar 2016 at 2:26
- Changed state: **Duplicate**

**Comment by GoogleCodeExporter** [comment]
```
Can you please follow the advice in 
https://code.google.com/p/google-cloud-sdk/issues/detail?id=476 and confirm 
whether it resolves your problem? Thank you.
```

Original comment by `vil...@google.com` on 6 Mar 2016 at 1:10

**Comment by GoogleCodeExporter** [comment]
```
The problem has been fixed.

Changed the adapter from NAT to BRIDGE in the network configuration of my VM.

Thank you for the support.

Best Regards,
Diego
```

Original comment by `moltedi...@gmail.com` on 7 Mar 2016 at 3:11

**Comment by GoogleCodeExporter** [comment]
```
You are welcome. Thank you for letting us know about your resolution.
```

Original comment by `vil...@google.com` on 7 Mar 2016 at 3:33
