### ISSUE TITLE
deploying to GAE (MVM) failed

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#622]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk/gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  File "googlecloudsdk/calliope/cli.py", line 652, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk/calliope/backend.py", line 1394, in Run
    resources = command_instance.Run(args)
  File "surface/preview/app/deploy.py", line 494, in Run
    config_cleanup)
  File "googlecloudsdk/api_lib/app/deploy_command_util.py", line 200, in BuildAndPushDockerImages
    cli, version_id, remote, project) as docker_client:
  File "googlecloudsdk/api_lib/app/images/docker_util.py", line 254, in __enter__
    return containers.NewDockerClient(local=(not self._remote), **kwargs)
  File "googlecloudsdk/api_lib/app/containers.py", line 150, in NewDockerClient
    client = NewDockerClientNoCheck(**kwargs)
  File "googlecloudsdk/api_lib/app/containers.py", line 133, in NewDockerClientNoCheck
    return docker.Client(**kwargs)
  File "third_party/docker/docker/client.py", line 77, in __init__
    self._version = self._retrieve_server_version()
  File "third_party/docker/docker/client.py", line 97, in _retrieve_server_version
    'Error while fetching server API version: {0}'.format(e)
DockerException: Error while fetching server API version: [SSL: 
CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

Installation information:

Google Cloud SDK [99.0.0]

[output truncated]

```

Original issue reported on code.google.com by `and...@ionicsecurity.com` on 4 Mar 2016 at 5:13
- Merged into: #476

**Comment by GoogleCodeExporter** [comment]
```
Thank you for your feedback. To help us investigate this further, can you 
please provide the following:

- Complete stack trace
- Output of gcloud info

Note: Please redact any personal information before sharing the information.
```

Original comment by `vil...@google.com` on 4 Mar 2016 at 8:42
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
Original comment by `vil...@google.com` on 5 Mar 2016 at 2:21
- Changed state: **Duplicate**

**Comment by GoogleCodeExporter** [comment]
Original comment by `vil...@google.com` on 5 Mar 2016 at 2:26

**Comment by GoogleCodeExporter** [comment]
```
Please try the resolution described in duplicate issue.
```

Original comment by `vil...@google.com` on 5 Mar 2016 at 2:28
