### ISSUE TITLE
I can't deploy a managed VM due to some cert error (I've never passed/specified certs)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#623]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk/gcloud_main.py", line 171, in main
    gcloud_cli.Execute()
  File "googlecloudsdk/calliope/cli.py", line 646, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk/calliope/backend.py", line 1394, in Run
    resources = command_instance.Run(args)
  File "surface/preview/app/deploy.py", line 483, in Run
    config_cleanup)
  File "googlecloudsdk/api_lib/app/deploy_command_util.py", line 200, in BuildAndPushDockerImages
    cli, version_id, remote, project) as docker_client:
  File "googlecloudsdk/api_lib/app/images/docker_util.py", line 237, in __enter__
    kwargs = containers.KwargsFromEnv(self._vm.host, self._vm.cert_dir, True)
  File "googlecloudsdk/api_lib/app/containers.py", line 100, in KwargsFromEnv
    assert_hostname=False)
  File "third_party/docker/docker/tls.py", line 46, in __init__
    'Path to a certificate and key files must be provided'
TLSParameterError: Path to a certificate and key files must be provided through 
the client_config param. TLS configurations should map the Docker CLI client 
configurations. See http://docs.docker.com/examples/https/ for API details.

Installation information:

Google Cloud SDK [98.0.0]

Platform: [Mac OS X, x86_64]
Python Version: [2.7.10 (default, Sep 23 2015, 04:34:21)  [GCC 4.2.1 Compatible 
Apple LLVM 7.0.0 (clang-700.0.72)]]
[output truncated]

```

Original issue reported on code.google.com by `matthew....@gmail.com` on 4 Mar 2016 at 2:25
- Merged into: #559

**Comment by GoogleCodeExporter** [comment]
```
I believe we fixed this in a release that went out yesterday. Can you try 
running:

gcloud components update

and deploying again?
```

Original comment by `dlor...@google.com` on 4 Mar 2016 at 3:27

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 4 Mar 2016 at 4:31
- Changed state: **Duplicate**
