### ISSUE TITLE
invoice vm

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#624]
```
Issue running command [gcloud compute ssh].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "lib/googlecloudsdk/calliope/cli.py", line 609, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "lib/googlecloudsdk/calliope/backend.py", line 1228, in Run
    resources = command_instance.Run(args)
  File "lib/googlecloudsdk/surface/compute/ssh.py", line 113, in Run
    external_ip_address = self.GetInstanceExternalIpAddress(instance_ref)
  File "lib/googlecloudsdk/api_lib/compute/ssh_utils.py", line 448, in GetInstanceExternalIpAddress
    custom_get_requests=None))
  File "lib/googlecloudsdk/api_lib/compute/request_helper.py", line 134, in MakeRequests
    requests=requests, http=http, batch_url=batch_url)
  File "lib/googlecloudsdk/api_lib/compute/batch_helper.py", line 30, in MakeRequests
    responses = batch.Execute(http)
  File "lib/googlecloudsdk/third_party/apitools/base/py/batch.py", line 189, in Execute
    http.request.credentials.refresh(http)
  File "./lib/third_party/oauth2client/client.py", line 597, in refresh
    self._refresh(http.request)
  File "./lib/third_party/oauth2client/client.py", line 780, in _refresh
    self._do_refresh_request(http_request)
  File "./lib/third_party/oauth2client/client.py", line 833, in _do_refresh_request
    raise AccessTokenRefreshError(error_msg)
AccessTokenRefreshError: invalid_grant

Installation information:

Google Cloud SDK [91.0.1]

Platform: [Linux, x86_64]
[output truncated]

```

Original issue reported on code.google.com by `edwin.s...@easytaxi.com.pe` on 4 Mar 2016 at 4:51

**Comment by GoogleCodeExporter** [comment]
```
Thank you for your feedback.

Can you please retry this after running `gcloud auth login`?

If it still does not work, please provide the following:

- Full stack trace.
- Complete `gcloud info` output.

Please remove any personal info before sharing.
```

Original comment by `vil...@google.com` on 4 Mar 2016 at 8:53
- Changed state: **NeedsMoreInfo**
