### ISSUE TITLE
unable to submit gcloud dataproc pyspark job

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#625]
```
Issue running command [gcloud beta dataproc jobs submit pyspark].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  File "calliope/cli.py", line 646, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "calliope/backend.py", line 1402, in Run
    resources = command_instance.Run(args)
  File "api_lib/dataproc/base_classes.py", line 71, in Run
    self.ValidateAndStageFiles()
  File "api_lib/dataproc/base_classes.py", line 143, in ValidateAndStageFiles
    storage_helpers.Upload(self.files_to_stage, self._staging_dir)
  File "api_lib/dataproc/storage_helpers.py", line 100, in Upload
    exit_code = _RunGsutilCommand('cp', args)
  File "api_lib/dataproc/storage_helpers.py", line 88, in _RunGsutilCommand
    return execution_utils.Exec(gsutil_cmd, no_exit=True, env=env)
  File "core/execution_utils.py", line 252, in Exec
    p = subprocess.Popen(args, env=env, **extra_popen_kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Installation information:

Google Cloud SDK [96.0.0]

Platform: [Linux, x86_64]
Python Version: [2.7.9 (default, Apr  2 2015, 15:33:21)  [GCC 4.9.2]]
Python Location: [/home/mohamed/Envs/feedcrm/bin/python2]
Site Packages: [Enabled]

[output truncated]

```

Original issue reported on code.google.com by `moha...@weborama.com` on 4 Mar 2016 at 5:12

**Comment by GoogleCodeExporter** [comment]
```
Thank you for your feedback. To help us investigate this further, can you 
please provide the following:

- Complete stack trace
- Complete output of gcloud info

Note: Please redact any personal information before sharing the information.
```

Original comment by `vil...@google.com` on 4 Mar 2016 at 8:54
- Changed state: **NeedsMoreInfo**
