### ISSUE TITLE
Issue deploying to glcoud, internet permissions don't allow me to access the mime\build file

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#634]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "lib\googlecloudsdk\gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  [...]
  File "lib\googlecloudsdk\api_lib\app\deploy_command_util.py", line 211, in BuildAndPushDockerImages
    info.file, docker_client, image_name)
  File "lib\googlecloudsdk\api_lib\app\deploy_command_util.py", line 285, in BuildAndPushDockerImage
    image.Build(docker_client)
  File "lib\googlecloudsdk\api_lib\app\docker_image.py", line 110, in Build
    nocache=self._nocache, rm=self._rm, pull=False)
  File "bin\..\lib\third_party\docker\docker\api\build.py", line 49, in build
    context = utils.tar(path, exclude=exclude, dockerfile=dockerfile)
  File "bin\..\lib\third_party\docker\docker\utils\utils.py", line 86, in tar
    t.add(os.path.join(root, path), arcname=path, recursive=False)
  File "platform\bundledpython\lib\tarfile.py", line 2000, in add
    tarinfo = self.gettarinfo(name, arcname)
  File "platform\bundledpython\lib\tarfile.py", line 1872, in gettarinfo
    statres = os.lstat(name)
WindowsError: [Error 3] The system cannot find the path specified: 
'C:\\Users\\Daniel\\Desktop\\nodejs-getting-started-master\\nodejs-getting-start
ed-master\\2-structured-data\\node_modules\\gcloud\\node_modules\\gce-images\\no
de_modules\\google-auto-auth\\node_modules\\google-auth-library\\node_modules\\g
token\\node_modules\\mime\\build\\build.js'

[output truncated]

```

Original issue reported on code.google.com by `daniel.c...@gmail.com` on 8 Mar 2016 at 4:51
- Merged into: #496

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 8 Mar 2016 at 5:00
- Changed state: **Duplicate**
