### ISSUE TITLE
Crashing while deploying my app with Node.js

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#637]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "lib\googlecloudsdk\gcloud_main.py", line 171, in main
    gcloud_cli.Execute()
  File "lib\googlecloudsdk\calliope\cli.py", line 646, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "lib\googlecloudsdk\calliope\backend.py", line 1394, in Run
    resources = command_instance.Run(args)
  File "lib\surface\preview\app\deploy.py", line 483, in Run
    config_cleanup)
  File "lib\googlecloudsdk\api_lib\app\deploy_command_util.py", line 200, in BuildAndPushDockerImages
    cli, version_id, remote, project) as docker_client:
  File "lib\googlecloudsdk\api_lib\app\images\docker_util.py", line 243, in __enter__
    return containers.NewDockerClient(local=(not self._remote), **kwargs)
  File "lib\googlecloudsdk\api_lib\app\containers.py", line 139, in NewDockerClient
    client = NewDockerClientNoCheck(**kwargs)
  File "lib\googlecloudsdk\api_lib\app\containers.py", line 122, in NewDockerClientNoCheck
    return docker.Client(**kwargs)
  File "bin\..\lib\third_party\docker\docker\client.py", line 77, in __init__
    self._version = self._retrieve_server_version()
  File "bin\..\lib\third_party\docker\docker\client.py", line 97, in _retrieve_server_version
    'Error while fetching server API version: {0}'.format(e)
DockerException: Error while fetching server API version: [SSL: 
CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

[output truncated]

```

Original issue reported on code.google.com by `Wendy4U2...@gmail.com` on 9 Mar 2016 at 7:24
- Merged into: #476

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 9 Mar 2016 at 7:25
- Changed state: **Duplicate**
