### ISSUE TITLE
[Errno 61] Connection refused

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#639]
```
Issue running command [gcloud init].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk/gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  [...]
  File "googlecloudsdk/calliope/backend.py", line 1387, in Http
    **kwargs)
  File "googlecloudsdk/core/cli.py", line 139, in Http
    creds = c_store.Load()
  File "googlecloudsdk/core/credentials/store.py", line 261, in Load
    Refresh(cred)
  File "googlecloudsdk/core/credentials/store.py", line 279, in Refresh
    creds.refresh(http or _Http())
  File "third_party/oauth2client/client.py", line 597, in refresh
    self._refresh(http.request)
  File "third_party/oauth2client/client.py", line 780, in _refresh
    self._do_refresh_request(http_request)
  File "third_party/oauth2client/client.py", line 799, in _do_refresh_request
    self.token_uri, method='POST', body=body, headers=headers)
  File "third_party/httplib2/__init__.py", line 1610, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "third_party/httplib2/__init__.py", line 1352, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "third_party/httplib2/__init__.py", line 1272, in _conn_request
    conn.connect()
  File "third_party/httplib2/__init__.py", line 1075, in connect
    raise socket.error, msg
error: [Errno 61] Connection refused

[output truncated]

```

Original issue reported on code.google.com by `675091...@qq.com` on 10 Mar 2016 at 1:50

**Comment by GoogleCodeExporter** [comment]
```
Thanks for providing feedback.

So that we can investigate this further, can you please provide:

- The full stacktrace (from log file).
- The full output of `gcloud info` (after removing personal info).

```

Original comment by `vil...@google.com` on 11 Mar 2016 at 12:19
- Changed state: **NeedsMoreInfo**
