### ISSUE TITLE
gcloud preview app deploy

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#641]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?
gcloud preview app deploy

What is the expected output? What do you see instead?
launch the app. been trying this for days. this feels like its the closest ive 
come

Please provide any additional information below.


Traceback (most recent call last):
  File "lib\googlecloudsdk\gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  [...]
  File "lib\googlecloudsdk\api_lib\app\deploy_command_util.py", line 211, in BuildAndPushDockerImages
    info.file, docker_client, image_name)
  File "lib\googlecloudsdk\api_lib\app\deploy_command_util.py", line 285, in BuildAndPushDockerImage
    image.Build(docker_client)
  File "lib\googlecloudsdk\api_lib\app\docker_image.py", line 110, in Build
    nocache=self._nocache, rm=self._rm, pull=False)
  File "bin\..\lib\third_party\docker\docker\api\build.py", line 49, in build
    context = utils.tar(path, exclude=exclude, dockerfile=dockerfile)
  File "bin\..\lib\third_party\docker\docker\utils\utils.py", line 86, in tar
    t.add(os.path.join(root, path), arcname=path, recursive=False)
  File "platform\bundledpython\lib\tarfile.py", line 2000, in add
    tarinfo = self.gettarinfo(name, arcname)
  File "platform\bundledpython\lib\tarfile.py", line 1872, in gettarinfo
    statres = os.lstat(name)
WindowsError: [Error 3] The system cannot find the path specified: 
'C:\\Users\\David\\Documents\\notes_spring_semester_2016\\NotesFromSpring2016\\n
otes-from-4th-semester\\UNIV-2016\\chip-works2\\node_modules\\gcloud\\node_modul
es\\gce-images\\node_modules\\google-auto-auth\\node_modules\\google-auth-librar
y\\node_modules\\jws\\lib\\data-stream.js'

[output truncated]

```

Original issue reported on code.google.com by `daxaxel...@gmail.com` on 11 Mar 2016 at 3:21
- Merged into: #496

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 11 Mar 2016 at 1:35
- Changed state: **Duplicate**
