### ISSUE TITLE
install.sh does not work

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#69]
```
What steps will reproduce the problem?
>install.sh

What is the expected output? What do you see instead?
cheng-chuntu@unknownf81edfe56f2a:/tmp/google-cloud-sdk$ ./install.sh 
Welcome to the Google Cloud SDK!
Traceback (most recent call last):
  File "/tmp/google-cloud-sdk/bin/bootstrapping/install.py", line 8, in <module>
    import bootstrapping
  File "/private/tmp/google-cloud-sdk/bin/bootstrapping/bootstrapping.py", line 18, in <module>
    from googlecloudsdk.core import config
  File "/private/tmp/google-cloud-sdk/bin/bootstrapping/../../lib/googlecloudsdk/core/config.py", line 235, in <module>
    INSTALLATION_CONFIG = InstallationConfig.Load()
  File "/private/tmp/google-cloud-sdk/bin/bootstrapping/../../lib/googlecloudsdk/core/config.py", line 207, in Load
    return InstallationConfig(**data)
TypeError: __init__() keywords must be strings


What is the output of 'gcloud info'?
gcloud not able to intall

Please provide any additional information below.
I'm using macbook pro, GNU bash, version 3.2.48(1)-release 
(x86_64-apple-darwin10.0)
Python 2.6.1


```

Original issue reported on code.google.com by `u9012063` on 18 Sep 2014 at 4:33

**Comment by GoogleCodeExporter** [comment]
```
We only support Python 2.7 right now, but we are working to make things Python 
2.6 compatible. We'll track this issue, but for now, you'll need to move to 
Python 2.7.
```

Original comment by `rdayal@google.com` on 10 Nov 2014 at 4:39
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
I'm getting a different install error using python 3.5. I also have python 2.7 
installed, but it's not the default, and it would be very inconvenient for me 
to make it default. I (and probably a lot of other people) need a way to 
specify which python installation to use without re-implementing virtualenv by 
hand.
```

Original comment by `chris.sn...@gmail.com` on 12 Feb 2016 at 10:22

**Comment by GoogleCodeExporter** [comment]
```
You can set the environment variable CLOUDSDK_PYTHON=/path/to/python2.7.
```

Original comment by `z...@google.com` on 12 Feb 2016 at 11:05
