### ISSUE TITLE
sane standard packaging please (unable to install via pip to virtualenv)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#7]
```
What steps will reproduce the problem?

google cloud sdk cannot be installed via pip.

What is the expected output?

- older gcutil & gsutil could be installed via pip

pip install 
https://google-compute-engine-tools.googlecode.com/files/gcutil-1.10.0.tar.gz

## What do you see instead?

Downloading/unpacking 
https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.zip
  Downloading google-cloud-sdk.zip (351kB): 351kB downloaded
  Running setup.py egg_info for package from https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.zip
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
    IOError: [Errno 2] No such file or directory: '/var/folders/tj/175z0y850xv6hqmgzfwqjyx00000gp/T/pip-vzQ6uZ-build/setup.py'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

IOError: [Errno 2] No such file or directory: 
'/var/folders/tj/175z0y850xv6hqmgzfwqjyx00000gp/T/pip-vzQ6uZ-build/setup.py'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in 
/var/folders/tj/175z0y850xv6hqmgzfwqjyx00000gp/T/pip-vzQ6uZ-build
Storing complete log in /Users/dch/.pip/pip.log




## What version of the product are you using? On what operating system?

- current SDK, OSX, system python & virtualenvs.

## Please provide any additional information below.


by using pip, we have:

- a standard way to upgrade and install python packages, whether in virtualenv 
or not.

by using pip, I can successfully run other tools like ansible, which *are* 
installed via pip, in a virtualenv, or separately. it's really awkward to have 
to use a separate terminal & python setup to run gcutil commands, when the 
active project work is in a virtualenv with terminal.

If google *doesn't* want to support venv & pip, then some possible workarounds 
are:

- provide a wrapper gcutil script that de-activates an active virtualenv for 
the execution of gcutil (which otherwise doesn't work inside the virtualenv)
- provide equivalent tools in go that have no pip/python dependency at all

```

Original issue reported on code.google.com by `d...@jsonified.com` on 4 Dec 2013 at 9:06

**Comment by GoogleCodeExporter** [comment]
```
This is on our TODO list already. I'll update this issue when we have something 
ready for you.
```

Original comment by `jasm...@google.com` on 4 Dec 2013 at 2:52
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
Original comment by `markp...@google.com` on 26 Dec 2013 at 5:35
- Added labels: **Type-Enhancement**
- Removed labels: **Type-Defect**

**Comment by GoogleCodeExporter** [comment]
```
bump, any progress? I'm forced now to upgrade and it's a complete pythonic 
pigsty. I need a separate terminal for all gc* related work, compared to the 
active project.
```

Original comment by `d...@jsonified.com` on 12 Mar 2014 at 12:41

**Comment by GoogleCodeExporter** [comment]
```
It's unlikely that we'll ever offer a "pip install google-cloud-sdk" or 
something similar. The Google Cloud SDK is not a python library or tool, it's a 
set of command-line tools that happen to be mostly implemented in python. Java 
and go are also well-represented.

We do have better virtualenv support, though. You should be able to use the 
Cloud SDK from within a virtualenv with no trouble now.

I'm marking this as fixed, due to the virtualenv support. If you still have 
concerns, feel free to reopen the issue.


```

Original comment by `jasm...@google.com` on 16 Apr 2014 at 5:24
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
I’m happy with proper virtualenv support — thanks! This is actually the 
most important part.

On 16. April 2014 at 19:24:36, google-cloud-sdk@googlecode.com 
(google-cloud-sdk@googlecode.com) wrote:
```

Original comment by `d...@jsonified.com` on 16 Apr 2014 at 5:27
