### ISSUE TITLE
Add armv6l as a Platform (aka Raspberry Pi)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#76]
```
pi@raspberrypi ~/google-cloud-sdk/lib/googlecloudsdk $ gcloud info
Traceback (most recent call last):
  File "/home/pi/google-cloud-sdk/./lib/googlecloudsdk/gcloud/gcloud.py", line 153, in <module>
    main()
  File "/home/pi/google-cloud-sdk/./lib/googlecloudsdk/gcloud/gcloud.py", line 149, in main
    _cli.Execute()
  File "/home/pi/google-cloud-sdk/./lib/googlecloudsdk/calliope/cli.py", line 431, in Execute
    post_run_hooks=self.__post_run_hooks, kwargs=kwargs)
  File "/home/pi/google-cloud-sdk/./lib/googlecloudsdk/calliope/frontend.py", line 274, in _Execute
    pre_run_hooks=pre_run_hooks, post_run_hooks=post_run_hooks)
  File "/home/pi/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 885, in Run
    output_formatter(result)
  File "/home/pi/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 870, in OutputFormatter
    command_instance.Display(args, obj)
  File "/home/pi/google-cloud-sdk/lib/googlecloudsdk/gcloud/sdktools/root/info.py", line 32, in Display
    log.Print(info)
  File "/home/pi/google-cloud-sdk/./lib/googlecloudsdk/core/log.py", line 432, in Print
    out.Print(*msg)
  File "/home/pi/google-cloud-sdk/./lib/googlecloudsdk/core/log.py", line 112, in Print
    message = ' '.join([str(m) for m in msg])
  File "/home/pi/google-cloud-sdk/lib/googlecloudsdk/gcloud/sdktools/root/info.py", line 52, in __str__
    out.write(str(self.basic) + '\n')
  File "/home/pi/google-cloud-sdk/lib/googlecloudsdk/gcloud/sdktools/root/info.py", line 80, in __str__
    arch=self.architecture.name,
AttributeError: 'NoneType' object has no attribute 'name'


Sample code to fix:
googlecloudsdk/core/util/platforms.py

class Architecture(object):
  """An enum representing the system architecture you are running on."""
  _ARCHITECTURE_SYSTEM_TUPLE = collections.namedtuple('ArchitectureTuple',
                                                      ['id', 'name'])
  x86 = _ARCHITECTURE_SYSTEM_TUPLE('x86', 'x86')
  x86_64 = _ARCHITECTURE_SYSTEM_TUPLE('x86_64', 'x86_64')
  ppc = _ARCHITECTURE_SYSTEM_TUPLE('PPC', 'PPC')
  raspi = _ARCHITECTURE_SYSTEM_TUPLE('armv6l', 'armv6l')
  _ALL = [x86, x86_64, ppc, raspi]
  _MACHINE_TO_ARCHITECTURE = {'AMD64': x86_64, 'x86_64': x86_64,
                              'i386': x86, 'i686': x86, 'x86': x86,
                              'Power Macintosh': ppc, 'armv6l': raspi}

```

Original issue reported on code.google.com by `Paul.M.B...@gmail.com` on 1 Oct 2014 at 7:30

**Comment by GoogleCodeExporter** [comment]
```
Aren't you working on this?
```

Original comment by `rdayal@google.com` on 10 Nov 2014 at 4:33
- Changed state: **Accepted**
