### ISSUE TITLE
recent yum update has broken gcloud compute instances list

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#79]
```
What steps will reproduce the problem?
1. gcloud compute instances list

What is the expected output? What do you see instead?
A list of project instances.

Traceback (most recent call last):
  File "/root/google-cloud-sdk/./lib/googlecloudsdk/gcloud/gcloud.py", line 153, in <module>
    main()
  File "/root/google-cloud-sdk/./lib/googlecloudsdk/gcloud/gcloud.py", line 149, in main
    _cli.Execute()
  File "/root/google-cloud-sdk/./lib/googlecloudsdk/calliope/cli.py", line 431, in Execute
    post_run_hooks=self.__post_run_hooks, kwargs=kwargs)
  File "/root/google-cloud-sdk/./lib/googlecloudsdk/calliope/frontend.py", line 274, in _Execute
    pre_run_hooks=pre_run_hooks, post_run_hooks=post_run_hooks)
  File "/root/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 860, in Run
    last_group = context_filter(tool_context, config, args)
  File "/root/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 276, in ContextFilter
    group.Filter(context, args)
  File "/root/google-cloud-sdk/lib/googlecloudsdk/compute/subcommands/__init__.py", line 51, in Filter
    context['resources'] = resources.REGISTRY.CloneAndSwitchAPIs(v1_compute)
  File "/root/google-cloud-sdk/./lib/googlecloudsdk/core/resources.py", line 429, in CloneAndSwitchAPIs
    reg = self._Clone()
  File "/root/google-cloud-sdk/./lib/googlecloudsdk/core/resources.py", line 345, in _Clone
    return copy.deepcopy(self)
  File "/usr/lib64/python2.6/copy.py", line 189, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib64/python2.6/copy.py", line 338, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib64/python2.6/copy.py", line 162, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.6/copy.py", line 255, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python2.6/copy.py", line 162, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.6/copy.py", line 255, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python2.6/copy.py", line 162, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.6/copy.py", line 255, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python2.6/copy.py", line 162, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.6/copy.py", line 255, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python2.6/copy.py", line 162, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.6/copy.py", line 255, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python2.6/copy.py", line 162, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.6/copy.py", line 255, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python2.6/copy.py", line 162, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.6/copy.py", line 255, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python2.6/copy.py", line 162, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.6/copy.py", line 255, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python2.6/copy.py", line 162, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.6/copy.py", line 255, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python2.6/copy.py", line 189, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib64/python2.6/copy.py", line 338, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib64/python2.6/copy.py", line 162, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.6/copy.py", line 255, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python2.6/copy.py", line 189, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib64/python2.6/copy.py", line 338, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib64/python2.6/copy.py", line 162, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.6/copy.py", line 255, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python2.6/copy.py", line 162, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.6/copy.py", line 255, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python2.6/copy.py", line 189, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib64/python2.6/copy.py", line 329, in _reconstruct
    y.append(item)
  File "/root/google-cloud-sdk/./lib/protorpc/messages.py", line 1087, in append
    self.__field.validate_element(value)
AttributeError: 'FieldList' object has no attribute '_FieldList__field'

What is the output of 'gcloud info'?
Google Cloud SDK [0.9.33]

Platform: [Linux, x86_64]
Python Version: [2.6.6 (r266:84292, Jan 22 2014, 09:42:36)  [GCC 4.4.7 20120313 
(Red Hat 4.4.7-4)]]
Site Packages: [Disabled]

Installation Root: [/root/google-cloud-sdk]
Installed Components:
  core: [2014.09.30]
  core-nix: [2014.09.30]
  gcutil: [1.16.5]
  gsutil-nix: [4.6]
  gsutil: [4.6]
  bq: [2.0.18]
  dns: [2014.09.02]
  sql: [2014.09.30]
  compute: [2014.09.30]
  gcutil-nix: [1.16.5]
  bq-nix: [2.0.18]
System PATH: 
[/root/google-cloud-sdk/bin:/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/root/
bin]
Cloud SDK on PATH: [True]

Installation Properties: [/root/google-cloud-sdk/properties]
User Config Directory: [/root/.config/gcloud]
User Properties: [/root/.config/gcloud/properties]
Current Workspace: [None]
Workspace Config Directory: [None]
Workspace Properties: [None]

Account: [xxxxxxxx@mydomain.com]
Project: [myproject-gce]

Current Properties:
  [core]
    project: [myproject-gce]
    account: [xxxxxxxx@mydomain.com]
    disable_usage_reporting: [True]
    user_output_enabled: [True]

Logs Directory: [/root/.config/gcloud/logs]
Last Log File: [/root/.config/gcloud/logs/2014.10.13/19.41.51.649815.log]

Please provide any additional information below.

The prior yum update included a couple of python packages:
    Dep-Install python-libcloud-0.14.1-1.el6.noarch             @epel
    Updated     python-zmq-2.2.0.1-1.el6.x86_64                 @epel
    Update                 14.3.1-1.el6.x86_64                  @epel


```

Original issue reported on code.google.com by `brett.sp...@gmail.com` on 13 Oct 2014 at 7:48

**Comment by GoogleCodeExporter** [comment]
```
I got it figured out.  Google cloud sdk now requires python 2.7.  I nice 
message indicating that is indeed the problem would be nice.
```

Original comment by `brett.sp...@gmail.com` on 14 Oct 2014 at 8:43

**Comment by GoogleCodeExporter** [comment]
Original comment by `rdayal@google.com` on 14 Oct 2014 at 11:09

**Comment by GoogleCodeExporter** [comment]
```
Will having python 2.7 be a hard requirement going forward, or will 
compatibility with 2.6 remain (or meant to be improved)?

(Looking at this, I'm not quite sure, even though the bug was specific to 
gcutil - 
https://code.google.com/p/google-cloud-sdk/issues/detail?id=15&can=1&q=2.6)


```

Original comment by `moo...@gmail.com` on 14 Oct 2014 at 11:34

**Comment by GoogleCodeExporter** [comment]
```
We're aiming to improve Python 2.6 compatibility.
```

Original comment by `rdayal@google.com` on 14 Oct 2014 at 11:35

**Comment by GoogleCodeExporter** [comment]
```
Hey, guys, the work around I used is similar to what was done in the link 
above.  I installed python 2.7 on my centOS 6.5 instance in GCE and set 
CLOUDSDK_PYTHON=python2.7 variable in my scripts that use gcloud commands.  
This seems to be working for the time being.
```

Original comment by `brett.sp...@gmail.com` on 15 Oct 2014 at 12:07

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the confirmation for Python 2.6 compatibility. :)

It ultimately just saves me from having to install 2.7 in CentOS 6.x and just 
being able to use 2.6 that comes stock with it.
```

Original comment by `moo...@gmail.com` on 15 Oct 2014 at 1:00

**Comment by GoogleCodeExporter** [comment]
```
FYI, this bug can possibly be closed now, as doing a "gcloud compute instances 
list" is working fine now with the latest version of the SDK (seems it was 
fixed a few releases back).  It's at least working fine on my end, still with 
CentOS 6.5 and Python 2.6.6.
```

Original comment by `moo...@gmail.com` on 5 Nov 2014 at 10:21

**Comment by GoogleCodeExporter** [comment]
Original comment by `rdayal@google.com` on 10 Nov 2014 at 4:23
- Changed state: **Fixed**
