### ISSUE TITLE
gcloud fails

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#9]
```
kapil@realms-slice:~$ gcloud 
Traceback (most recent call last):
  File "/home/kapil/projects/cloud/google-cloud-sdk/bin/../lib/google/cloud/sdk/gcloud/gcloud.py", line 39, in <module>
    from google.cloud.sdk.core import cli
  File "/home/kapil/projects/cloud/google-cloud-sdk/bin/../lib/google/cloud/sdk/core/cli.py", line 7, in <module>
    import httplib2
  File "/home/kapil/projects/cloud/google-cloud-sdk/bin/../lib/httplib2/__init__.py", line 1, in <module>
    from __future__ import generators
ImportError: No module named __future__


```

Original issue reported on code.google.com by `kapilt@gmail.com` on 4 Dec 2013 at 2:33
- Merged into: #8

**Comment by GoogleCodeExporter** [comment]
```
ubuntu 13.10 . python 2.7.5
```

Original comment by `kapilt@gmail.com` on 4 Dec 2013 at 2:34

**Comment by GoogleCodeExporter** [comment]
Original comment by `markp...@google.com` on 4 Dec 2013 at 7:25
- Changed state: **Duplicate**

**Comment by GoogleCodeExporter** [comment]
Original comment by `markp...@google.com` on 4 Dec 2013 at 7:25
