### ISSUE TITLE
gcloud compute copy-files traceback is verbose and very hard going

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prototipando/google-cloud-sdk#90]
```
What steps will reproduce the problem?

$ gcloud compute copy-files ~/Downloads/test.rft  instance-1:~/usr/local/ 
--zone "us-central1-a" --project "thermal-scene-750"

What is the expected output? 

Something useful more specific

What do you see instead?

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
seebe@instance-1:~$ gcloud compute copy-files ~/Downloads/test.rft 
 instance-1:~/usr/local/ --zone "us-central1-a" --project "thermal-scene-750"
Traceback (most recent call last):
  File "/usr/local/bin/../share/google/google-cloud-sdk/./lib/googlecloudsdk/gcloud/gcloud.py", line 153, in <module>
    main()
  File "/usr/local/bin/../share/google/google-cloud-sdk/./lib/googlecloudsdk/gcloud/gcloud.py", line 149, in main
    _cli.Execute()
  File "/usr/local/bin/../share/google/google-cloud-sdk/./lib/googlecloudsdk/calliope/cli.py", line 381, in Execute
    post_run_hooks=self.__post_run_hooks, kwargs=kwargs)
  File "/usr/local/bin/../share/google/google-cloud-sdk/./lib/googlecloudsdk/calliope/frontend.py", line 274, in _Execute
    pre_run_hooks=pre_run_hooks, post_run_hooks=post_run_hooks)
  File "/usr/local/bin/../share/google/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 887, in Run
    result = command_instance.Run(args)
  File "/usr/local/share/google/google-cloud-sdk/lib/googlecloudsdk/compute/subcommands/copy_files.py", line 102, in Run
    instance_ref = self.CreateZonalReference(instances.pop(), args.zone)
  File "/usr/local/bin/../share/google/google-cloud-sdk/./lib/googlecloudsdk/compute/lib/scope_prompter.py", line 150, in CreateZonalReference
    [resource_name], zone_arg, resource_type, flag_name, region_filter)[0]
  File "/usr/local/bin/../share/google/google-cloud-sdk/./lib/googlecloudsdk/compute/lib/scope_prompter.py", line 145, in CreateZonalReferences
    prefix_filter=region_filter)
  File "/usr/local/bin/../share/google/google-cloud-sdk/./lib/googlecloudsdk/compute/lib/scope_prompter.py", line 108, in CreateScopedReferences
    resolve=False)
  File "/usr/local/bin/../share/google/google-cloud-sdk/./lib/googlecloudsdk/core/resources.py", line 669, in Parse
    return self.ParseCollectionPath(collection, line, params or {}, resolve)
  File "/usr/local/bin/../share/google/google-cloud-sdk/./lib/googlecloudsdk/core/resources.py", line 559, in ParseCollectionPath
    collection_path, kwargs, resolve)
  File "/usr/local/bin/../share/google/google-cloud-sdk/./lib/googlecloudsdk/core/resources.py", line 192, in ParseCollectionPath
    setattr(request, param, field)
  File "/usr/local/bin/../share/google/google-cloud-sdk/./lib/protorpc/messages.py", line 926, in __setattr__
    object.__setattr__(self, name, value)
  File "/usr/local/bin/../share/google/google-cloud-sdk/./lib/protorpc/messages.py", line 1232, in __set__
    self.validate(value)
  File "/usr/local/bin/../share/google/google-cloud-sdk/./lib/protorpc/messages.py", line 1321, in validate
    self.__validate(value, self.validate_element)
  File "/usr/local/bin/../share/google/google-cloud-sdk/./lib/protorpc/messages.py", line 1287, in __validate
    validate_element(value)
  File "/usr/local/bin/../share/google/google-cloud-sdk/./lib/protorpc/messages.py", line 1452, in validate_element
    raise validation_error
protorpc.messages.ValidationError: Field instance encountered non-ASCII string 
 instance-1: 'ascii' codec can't decode byte 0xc2 in position 0: ordinal not 
in range(128)
seebe@instance-1:~$ 


What is the output of 'gcloud info'?

Google Cloud SDK [0.9.35]

Platform: [Linux, x86_64]
Python Version: [2.7.3 (default, Mar 13 2014, 11:03:55)  [GCC 4.7.2]]
Site Packages: [Disabled]

Installation Root: [/usr/local/share/google/google-cloud-sdk]
Installed Components:
  core: [2014.11.03]
  core-nix: [2014.10.20]
  compute: [2014.10.30]
  gsutil-nix: [4.6]
  gsutil: [4.6]
  bq: [2.0.18]
  dns: [2014.10.30]
  sql: [2014.10.30]
  gcutil: [1.16.5]
  gcutil-nix: [1.16.5]
  bq-nix: [2.0.18]
System PATH: [/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games]
Cloud SDK on PATH: [False]

Installation Properties: [/usr/local/share/google/google-cloud-sdk/properties]
User Config Directory: [/home/seebe/.config/gcloud]
User Properties: [/home/seebe/.config/gcloud/properties]
Current Workspace: [None]
Workspace Config Directory: [None]
Workspace Properties: [None]

Account: [clive.boulton@gmail.com]
Project: [thermal-scene-750]

Current Properties:
  [core]
    project: [thermal-scene-750]
    account: [clive.boulton@gmail.com]
    user_output_enabled: [True]

Logs Directory: [/home/seebe/.config/gcloud/logs]
Last Log File: [/home/seebe/.config/gcloud/logs/2014.11.09/23.06.16.661125.log]

Please provide any additional information below.

All I am trying do is copy a file to my GCP project. I have the top devops from 
Eucalyptus stumped. Please PLEASE make gcloud complete more user friendly. 
Clive 2x CS/EE degrees.  

```

Original issue reported on code.google.com by `clive.bo...@gmail.com` on 9 Nov 2014 at 11:14

**Comment by GoogleCodeExporter** [comment]
```
Please ask doco folks to provide working examples.  The example fed back makes 
no sense.

usage: gcloud compute copy-files  [[USER@]INSTANCE:]SRC [[[USER@]INSTANCE:]SRC 
...]  [[USER@]INSTANCE:]DEST [optional flags]
ERROR: (gcloud.compute.copy-files) too few arguments
seebe@instance-1:~$ gcloud compute copy-files 
~/Downloads/test.rft instance-1:~/usr/local/ --zone "us-central1-a" --project 
"thermal-scene-750"
usage: gcloud compute copy-files  [[USER@]INSTANCE:]SRC [[[USER@]INSTANCE:]SRC 
...]  [[USER@]INSTANCE:]DEST [optional flags]
ERROR: (gcloud.compute.copy-files) too few arguments
seebe@instance-1:~$ gcloud compute copy-files seebe@ 
~/Downloads/test.rft seebe@instance-1:~/usr/local/ --zone "us-central1-a" 
--project "thermal-scene-750"
ERROR: (gcloud.compute.copy-files) All sources must be remote files when the 
destination is local.
seebe@instance-1:~$ gcloud compute copy-files 
seebe@:~/Downloads/test.rft seebe@instance-1:~/usr/local/ --zone 
"us-central1-a" --project "thermal-scene-750"
usage: gcloud compute copy-files  [[USER@]INSTANCE:]SRC [[[USER@]INSTANCE:]SRC 
...]  [[USER@]INSTANCE:]DEST [optional flags]
ERROR: (gcloud.compute.copy-files) too few arguments
seebe@instance-1:~$ 

```

Original comment by `clive.bo...@gmail.com` on 9 Nov 2014 at 11:47

**Comment by GoogleCodeExporter** [comment]
```
Thank you for filing this feedback. We will work to make the documentation 
clearer.
```

Original comment by `kpro...@google.com` on 11 Nov 2014 at 6:52

**Comment by GoogleCodeExporter** [comment]
```
Thank you team on gcloud compute. Examples for doco will make copy easy.
```

Original comment by `clive.bo...@gmail.com` on 11 Nov 2014 at 7:30

**Comment by GoogleCodeExporter** [comment]
```
Hi Clive,  I'm surprised you're getting a stack trace.  I haven't been able to 
reproduce this.  It looks like gcloud is getting an non-ascii character from 
some where.  Did you copy and paste the command invocation?  What do you get if 
you run 
  $ echo "LANG=$LANG   LANGUAGE=$LANGUAGE   LC_ALL=$LC_ALL   LC_TYPE=$LC_CTYPE"
```

Original comment by `jeffvaughan@google.com` on 12 Nov 2014 at 7:53

**Comment by GoogleCodeExporter** [comment]
```
Closing this issue pending further feedback.
```

Original comment by `vil...@google.com` on 25 Nov 2014 at 6:24
- Changed state: **WorkingAsIntended**

**Comment by GoogleCodeExporter** [comment]
```
sorry for delay. I switched machines. 

seebe@instance-1:~$ echo "LANG=$LANG   LANGUAGE=$LANGUAGE   LC_ALL=$LC_ALL   
LC_TYPE=$LC_CTYPE"
LANG=en_US.UTF-8   LANGUAGE=   LC_ALL=   LC_TYPE=
seebe@instance-1:~$ 
```

Original comment by `clive.bo...@gmail.com` on 26 Nov 2014 at 2:26
